Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2019-02, with the labels that each got.

#1647 boinc: kill slow-mo
  extra-scientific/boinc/autobuild/patches/0001-client-cs_platform-do-not-support-32-bit-on-x64.patch
  extra-scientific/boinc/spec
Labels: in progress, to-stable

#1683 cpprestsdk: update to 2.10.10
  extra-devel/cpprestsdk/spec
Labels: in progress, upgrade

#1682 mono: update to 5.18.0.268
  extra-mono/mono/autobuild/prepare
  extra-mono/mono/spec
Labels: discussion-needed, in progress, upgrade
