Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2019-03, with the labels that each got.

#1685 pgadmin: update to 4.2
  extra-database/pgadmin/autobuild/prepare
  extra-database/pgadmin/spec
Labels: in progress, upgrade

#1687 shadowsocks-libev: update to 3.2.4
  extra-network/shadowsocks-libev/spec
Labels: in progress, to-stable, upgrade

#1691 typescript: update to 3.3.3333
  extra-js/typescript/spec
Labels: in progress, upgrade

#1692 gulp: update to 4.0.0
  extra-js/gulp/spec
Labels: in progress, upgrade

#1693 coffeescript: update to 2.3.2
  extra-js/coffeescript/autobuild/build
  extra-js/coffeescript/spec
Labels: in progress, upgrade

#1694 sudo: update to 1.8.27
  extra-security/sudo/spec
Labels: in progress, upgrade

#1707 tar: update to 1.32
  base-utils/tar/spec
Labels: in progress, upgrade

#1708 powershell: refactor build script
  extra-shells/powershell/autobuild/build
  extra-shells/powershell/autobuild/defines
  extra-shells/powershell/autobuild/patches/0001-add-aosc-to-support-list.patch
  extra-shells/powershell/autobuild/prepare
  extra-shells/powershell/spec
Labels: enhancement, in progress

#1709 powershell: set nostatic to no again
  extra-shells/powershell/autobuild/build
  extra-shells/powershell/autobuild/defines
  extra-shells/powershell/spec
Labels: bug, in progress

#1710 nano: update to 3.2
  base-editors/nano/spec
Labels: in progress, upgrade

#1714 vscode: expected update to 1.32.1
  extra-editors/vscode/spec
Labels: expected-update, in progress, upgrade

#1715 gptfdisk: update to 1.0.4
  base-admin/gptfdisk/spec
Labels: in progress, upgrade

#1733 vscode: expected update to 1.32.3
  extra-editors/vscode/spec
Labels: expected update, in progress, upgrade

#1737 trojan: update to 1.10.1
  extra-network/trojan/spec
Labels: Ready

#1742 mono: update to 5.18.1.0
  extra-mono/mono/spec
Labels: in progress, upgrade

#1754 python-3: update to 3.6.8
  base-python/python-3/spec
Labels: in progress, security, to-stable, upgrade

#1755 python-3: update to 3.7.3, remove patch (#1663)
  base-python/python-3/autobuild/patches/CVE-2019-5010.patch
  base-python/python-3/spec
Labels: in progress, security, to-testing, upgrade

#1757 mono: building from release pkg needs no autogen
  extra-mono/mono/autobuild/defines
  extra-mono/mono/autobuild/prepare
Labels: enhancement, in progress

#1758 mono: remove patch, see below
  extra-mono/mono/autobuild/patches/mono-4.6.1-aarch64.patch
Labels: enhancement, in progress, to-testing
