Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2019-04, with the labels that each got.

#1765 trojan: update to 1.11.0
  extra-network/trojan/spec
Labels: Ready

#1787 audacity: update to 2.3.1
  extra-creativity/audacity/spec
Labels: Ready, to-testing, upgrade

#1789 darktable: update to 2.6.2
  extra-creativity/darktable/spec
Labels: Ready, to-testing, upgrade

#1794 Add .editorconfig.
  .editorconfig
Labels: discussion-needed, enhancement, in progress
