Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2019-05, with the labels that each got.

#1832 trojan: update to 1.12.2
  extra-network/trojan/spec
Labels: Ready, to-stable, upgrade, upgrade-exception

#1824 nano: update to 4.2
  base-editors/nano/spec
Labels: Ready, to-testing, upgrade

#1834 Revert "nano: update to 4.2"
  base-editors/nano/spec
Labels: in progress

#1831 ccache: update to latest stable + changed d/l source
  extra-devel/ccache/spec
Labels: to-testing, upgrade, upstream-moved
