Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-07, with the labels that each got.

#3228 xrdp: do not ship (!) private keys with the package
  extra-network/xrdp/autobuild/beyond
  extra-network/xrdp/autobuild/conffiles
  extra-network/xrdp/autobuild/overrides/etc/xrdp/cert.pem
  extra-network/xrdp/autobuild/overrides/etc/xrdp/key.pem
  extra-network/xrdp/autobuild/overrides/etc/xrdp/openssl.conf
  extra-network/xrdp/autobuild/overrides/etc/xrdp/rsakeys.ini
  extra-network/xrdp/autobuild/postinst
  extra-network/xrdp/spec
Labels: 0day, security

#3233 ciel: update to 3.0.5
  extra-devel/ciel/spec
Labels: upgrade

#3219 systemd: update to 248.3
  extra-admin/systemd/autobuild/defines
  extra-admin/systemd/autobuild/patches/0002-basic-add-make_mount_point_inode-helper.patch
  extra-admin/systemd/autobuild/patches/0003-core-add-systemctl-and-DBUS-method-to-bind-mount-new.patch
  extra-admin/systemd/spec
Labels: upgrade

#3231 bitwarden-cli: update to 1.17.0
  extra-js/bitwarden-cli/autobuild/patches/0001-bitwarden-fix-webpack-bundling.patch
  extra-js/bitwarden-cli/spec
Labels: upgrade

#3234 ciel: update to 3.0.7
  extra-devel/ciel/spec
Labels: upgrade

#3242 autobuild3: update to 1.6.12
  extra-devel/autobuild3/spec
Labels: bug, upgrade

#3243 atm: "update" to 0.3.1~alpha.1
  extra-admin/atm/spec
Labels: bug, upgrade

#3246 autobuild3: update to 1.6.13
  extra-devel/autobuild3/spec
Labels: bug, upgrade

#3257 nodejs: update to 14.17.3
  extra-js/nodejs/spec
Labels: security, upgrade

#3252 systemd: backport hwdb resolution override for Pinebook Pro patch
  extra-admin/systemd/autobuild/patches/0002-hwdb-add-resolution-override-for-Pinebook-Pro-touchpad.patch
  extra-admin/systemd/spec
Labels: enhancement

#3259 telegram-desktop: backport file dialog/global menu fixes
  extra-web/telegram-desktop/autobuild/patches/1001-backport-file-dialog-global-menu-fix.patch
  extra-web/telegram-desktop/spec
Labels: bug

#3263 mesa: Rework to fix FTBFS
  extra-libs/mesa/autobuild/beyond
  extra-libs/mesa/spec
Labels: rework

#3264 vscode: update to 1.58.0
  extra-editors/vscode/autobuild/prepare
  extra-editors/vscode/spec
Labels: upgrade

#3274 iosevka-fonts: update to 7.2.8
  extra-fonts/iosevka-fonts/spec
Labels: upgrade

#3273 sarasa-gothic-fonts: update to 0.32.10
  extra-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#3271 lxgwwenkai-font: update to 1.001
  extra-fonts/lxgwwenkai-font/spec
Labels: upgrade

#3270 vscode: update to 1.58.1
  extra-editors/vscode/spec
Labels: upgrade

#3268 bat: update to 0.18.2
  extra-utils/bat/spec
Labels: upgrade

#3265 you-get: update to 0.4.1536
  extra-multimedia/you-get/spec
Labels: upgrade

#3279 vscode: update to 1.58.2
  extra-editors/vscode/spec
Labels: upgrade

#3232 vaultwarden: new, 1.22.1
  extra-security/vaultwarden/autobuild/beyond
  extra-security/vaultwarden/autobuild/defines
  extra-security/vaultwarden/autobuild/overrides/usr/lib/systemd/system/vaultwarden.service
  extra-security/vaultwarden/autobuild/prepare
  extra-security/vaultwarden/spec
Labels: new-package

#3277 code-server: update to 3.11.0
  extra-utils/code-server/autobuild/build
  extra-utils/code-server/autobuild/defines
  extra-utils/code-server/autobuild/prepare
  extra-utils/code-server/spec
Labels: upgrade

#3285 firefox: update to 90.0
  extra-web/firefox/spec
Labels: 0day, security, upgrade

#3290 osu-lazer: update to 2021.720.0
  extra-games/osu-lazer/spec
Labels: upgrade

#3287 flameshot: update to 0.10.0
  extra-utils/flameshot/spec
Labels: upgrade

#3294 nnn: update to 4.2
  extra-utils/nnn/spec
Labels: upgrade

#3309 flameshot: update to 0.10.1
  extra-utils/flameshot/spec
Labels: upgrade

#3308 vaultwarden: update to 1.22.2
  extra-security/vaultwarden/spec
Labels: upgrade

#3311 shadowsocks-rust: update to 1.11.2
  extra-network/shadowsocks-rust/spec
Labels: upgrade

#3317 Pillow: upgrade to 8.3.1, install headers
  extra-python/pillow/autobuild/beyond
  extra-python/pillow/spec
Labels: enhancement, upgrade

#3316 CUPS Filters: upgrade to 1.28.9
  extra-libs/cups-filters/autobuild/defines
  extra-libs/cups-filters/spec
Labels: bug, upgrade

#3310 wine: update to 6.13
  extra-emulation/wine/autobuild/patches/0001-Revert-winegcc-Support-Wl-foo-.-style-linker-options.patch
  extra-emulation/wine/spec
Labels: upgrade

#3319 nodejs: update to 14.17.4
  extra-js/nodejs/spec
Labels: security, upgrade
