Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-04, with the labels that each got.

#2942 dracut: update to 053
  extra-kernel/dracut/autobuild/overrides/usr/bin/update-initramfs
  extra-kernel/dracut/spec
Labels: upgrade

#2937 vscode: update to 1.55.0
  extra-editors/vscode/spec
Labels: upgrade

#2939 rclone: update to 1.55.0
  extra-web/rclone/spec
Labels: upgrade

#2936 curl: update to 7.76.0
  extra-web/curl/spec
Labels: security, upgrade

#2955 mpv: update to 0.33.1
  extra-multimedia/mpv/spec
Labels: upgrade

#2959 osu-lazer: update to 2021.407.1
  extra-games/osu-lazer/spec
Labels: upgrade

#2964 intel-graphics-compiler: update to 1.0.6812
  extra-devel/intel-graphics-compiler/autobuild/defines
  extra-devel/intel-graphics-compiler/autobuild/patches/0002-use-cmake-chaining.patch
  extra-devel/intel-graphics-compiler/autobuild/patches/0004-fix-build-with-llvm-11.patch
  extra-devel/intel-graphics-compiler/spec
Labels: ready, upgrade

#2969 shadowsocks-rust: update to 1.10.5
  extra-network/shadowsocks-rust/spec
Labels: upgrade

#2967 vscode: update to 1.55.1
  extra-editors/vscode/autobuild/defines
  extra-editors/vscode/spec
Labels: upgrade

#2968 fish: update to 3.2.2
  extra-shells/fish/spec
Labels: upgrade

#2963 adobe-source-han-sans: update to 2.003
  extra-fonts/adobe-source-han-sans/spec
Labels: upgrade

#2966 v2ray: update to 4.37.2
  extra-network/v2ray/spec
Labels: upgrade

#2965 sessiond: new, 0.4.0
  extra-admin/sessiond/autobuild/beyond
  extra-admin/sessiond/autobuild/defines
  extra-admin/sessiond/spec
Labels: new-package

#2981 xorg-server: update to 1.20.11; fix #2980
  extra-x11/xorg-server/spec
Labels: priority, security, upgrade

#2983 v2ray: update to 4.37.3
  extra-network/v2ray/spec
Labels: upgrade

#2984 clash: update to 1.5.0
  extra-network/clash/spec
Labels: upgrade

#2993 mesa{,+32}: update to 21.0.2 and change some options
  extra-libs/mesa/autobuild/defines
  extra-libs/mesa/spec
  extra-optenv32/mesa+32/autobuild/build
  extra-optenv32/mesa+32/spec
Labels: upgrade

#2988 nodejs: update to 14.16.1
  extra-js/nodejs/spec
Labels: priority, security, upgrade

#2996 linux-firmware: update to newest git and refactor build script
  extra-kernel/linux-firmware/01-nonfree/build
  extra-kernel/linux-firmware/01-nonfree/free-list
  extra-kernel/linux-firmware/spec
Labels: upgrade

#3001 xorg-server: revert don't force 96dpi patch
  extra-x11/xorg-server/autobuild/patches/0006-don-t-force-96dpi.patch
  extra-x11/xorg-server/spec
Labels: bug

#2998 youtube-dl: update to 2021.04.17
  extra-multimedia/youtube-dl/spec
Labels: upgrade

#2987 vscode: update to 1.55.2
  extra-editors/vscode/spec
Labels: security, upgrade

#3004 shadowsocks-rust: update to 1.10.8
  extra-network/shadowsocks-rust/spec
Labels: upgrade

#3005 bitwarden-cli: new, 1.15.1
  extra-js/bitwarden-cli/autobuild/build
  extra-js/bitwarden-cli/autobuild/defines
  extra-js/bitwarden-cli/autobuild/patches/0001-bitwarden-fix-webpack-bundling.patch
  extra-js/bitwarden-cli/spec
Labels: new-package

#2986 baidupcs-go: update to 3.7.9
  extra-web/baidupcs-go/spec
Labels: upgrade

#3022 ykdl: update to 1.7.0+git20210410
  extra-multimedia/ykdl/spec
Labels: upgrade

#3023 kitty: update to 0.20.1
  extra-utils/kitty/spec
Labels: upgrade

#3033 sarasa-gothic-fonts: update to 0.31.0
  extra-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#3029 adobe-source-han-sans: update to 2.004
  extra-fonts/adobe-source-han-sans/spec
Labels: upgrade
