Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-09, with the labels that each got.

#3409 openssl: security update to 1.1.1l
  base-libs/openssl/spec
Labels: upgrade, security

#3410 openssl+1.0: security update to 1.0.2u
  extra-libs/openssl+1.0/spec
Labels: upgrade, security

#3405 nodejs: security update to 14.17.6
  extra-js/nodejs/spec
Labels: upgrade, security

#3415 systemd-boot-friend: update to 0.9.2
  extra-admin/systemd-boot-friend/spec
Labels: upgrade

#3412 telegram-desktop: update to 3.0.0
  extra-web/telegram-desktop/autobuild/patches/0001-Fix-missing-include.patch
  extra-web/telegram-desktop/autobuild/patches/0004-fix-build-on-gcc10-cpp17.patch
  extra-web/telegram-desktop/autobuild/patches/0004-fix-platform-integration-in-kde.patch
  extra-web/telegram-desktop/autobuild/patches/1001-backport-file-dialog-global-menu-fix.patch
  extra-web/telegram-desktop/spec
Labels: upgrade

#3396 i2pd-2.39.0-rework
  extra-web/i2pd/autobuild/overrides/usr/lib/tmpfiles.d/i2pd.conf
  extra-web/i2pd/autobuild/patch
  extra-web/i2pd/autobuild/patches/0001-Arch-Linux-tweak-i2pd-default-config.patch
  extra-web/i2pd/autobuild/patches/0002-Arch-Linux-i2pd-do-not-override-config.patch
  extra-web/i2pd/autobuild/patches/0003-Arch-Linux-i2pd-tunnels-d-readme.patch
  extra-web/i2pd/autobuild/patches/0004-Drop-atomic-check.patch
Labels: rework

#3430 linux-kernel-retro: build jme as a module
  extra-kernel/linux-kernel-retro/autobuild/i486/config
  extra-kernel/linux-kernel-retro/spec
Labels: enhancement, retro

#3426 telegram-desktop: update to 3.0.1
  extra-web/telegram-desktop/spec
Labels: upgrade

#3433 meowdict: update to 0.6.7
  extra-i18n/meowdict/spec
Labels: upgrade

#3434 util-base: add ripgrep
  extra-bases/util-base/autobuild/defines
  extra-bases/util-base/spec
Labels: enhancement

#3431 vscode: update to 1.60.0
  extra-editors/vscode/spec
Labels: upgrade

#3435 apt-gen-list: update to 0.5.0
  extra-admin/apt-gen-list/spec
Labels: upgrade

#3437 systemd-boot-friend: update to 0.9.3
  extra-admin/systemd-boot-friend/spec
Labels: upgrade

#3440 fanwunming: update to 1.007
  extra-fonts/fanwunming/spec
Labels: upgrade

#3443 firefox: update to 92.0
  extra-web/firefox/spec
Labels: upgrade, security

#3446 scrcpy: update to 1.19
  extra-android/scrcpy/spec
Labels: upgrade

#3442 pytz-2021.1-rework
  extra-security/volatility/autobuild/beyond
Labels: rework

#3458 systemd-boot-friend: update to 0.9.4
  extra-admin/systemd-boot-friend/spec
Labels: upgrade

#3455 fcitx5-pinyin-moegirl: upgrade to 20210914
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#3449 wine: update to 6.17
  extra-emulation/wine/spec
Labels: upgrade

#3459 lightcord: update to 0.1.9
  extra-web/lightcord/spec
Labels: upgrade

#3466 unar: rebuild for GNUStep Base 1.28
  extra-utils/unar/spec
Labels: abi-break

#3465 unnamed-sdvx-clone: add patches...
  extra-games/unnamed-sdvx-clone/autobuild/patches/0002-separate-user-and-system-folders.patch
  extra-games/unnamed-sdvx-clone/spec
Labels: bug, rework, lgtm

#3475 gtk-doc: fix saved triplet in pkg-config path
  extra-doc/gtk-doc/autobuild/prepare
  extra-doc/gtk-doc/spec
Labels: bug, lgtm

#3470 vscode: update to 1.60.2
  extra-editors/vscode/spec
Labels: lgtm

#3468 telegram-desktop: update to 3.1.0
  extra-web/telegram-desktop/spec
Labels: upgrade, lgtm

#3477 autobuild3: update to 1.6.30
  extra-devel/autobuild3/spec
Labels: bug, enhancement, upgrade, lgtm
