Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-11, with the labels that each got.

#3642 [ci] showmethekey: new, 1.5.0
  extra-utils/showmethekey/autobuild/defines
  extra-utils/showmethekey/spec
Labels: new-package, lgtm

#3646 mitmproxy: update to 7.0.4
  extra-network/mitmproxy/autobuild/patches/0001-allow-zstandard-0.15.patch
  extra-network/mitmproxy/spec
Labels: upgrade, lgtm

#3648 lightcord: drop, upstream unmaintained/abandoned
  extra-web/lightcord/autobuild/build
  extra-web/lightcord/autobuild/defines
  extra-web/lightcord/autobuild/patches/0002-fix-desktop-exec-path.patch
  extra-web/lightcord/autobuild/prepare
  extra-web/lightcord/spec
Labels: lgtm, drop-package, unmaintained

#3647 rustc: use bundled libgit2
  extra-rust/rustc/autobuild/prepare
  extra-rust/rustc/spec
Labels: bug, lgtm

#3635 nodejs: update to 16.13.0
  extra-js/nodejs/autobuild/defines
  extra-js/nodejs/spec
Labels: upgrade, lgtm

#3654 osu-lazer: update to 2021.1113.0
  extra-games/osu-lazer/spec
Labels: upgrade, lgtm

#3641 fortunes-zh: better build script
  extra-games/fortunes-zh/autobuild/beyond
  extra-games/fortunes-zh/autobuild/defines
  extra-games/fortunes-zh/autobuild/patches/0001-bugfix-fix-path.patch
  extra-games/fortunes-zh/autobuild/patches/0001-fix-fortunes-zh-path.patch
  extra-games/fortunes-zh/spec
Labels: rework, lgtm

#3657 shadowsocks-rust: update to 1.12.1
  extra-network/shadowsocks-rust/spec
Labels: upgrade, lgtm

#3660 fcitx5-pinyin-moegirl: update to 20211116
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#3656 vscode: update to 1.62.2
  extra-editors/vscode/spec
Labels: upgrade, lgtm

#3666 oolite: bump rel, rebuild for gnustep-base
  extra-games/oolite/spec
Labels: abi-break, lgtm

#3667 systemd-boot-friend: update to 0.11.0
  extra-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm

#3671 zerotier-one: update to 1.8.3
  extra-network/zerotier-one/spec
Labels: upgrade, lgtm

#3663 vscode: update to 1.62.3
  extra-editors/vscode/spec
Labels: upgrade, lgtm

#3672 wine: update to 6.22
  extra-emulation/wine/spec
Labels: upgrade, lgtm

#3674 starship: new, 1.0.0
  extra-utils/starship/autobuild/beyond
  extra-utils/starship/autobuild/defines
  extra-utils/starship/spec
Labels: new-package, lgtm

#3678 transmission: fix sysusers and tmpfiles file install
  extra-web/transmission/autobuild/overrides/usr/lib/sysusers.d/transmission.conf
  extra-web/transmission/autobuild/overrides/usr/lib/tmpfiles.d/transmission.conf
Labels: lgtm
