Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-12, with the labels that each got.

#3686 macchina: update to 5.0.5
  extra-utils/macchina/spec
Labels: upgrade, lgtm

#3690 yubioath-desktop: update to 5.1.0
  extra-security/yubioath-desktop/autobuild/beyond
  extra-security/yubioath-desktop/spec
Labels: upgrade, lgtm

#3689 libvirt: adjust dep list
  extra-emulation/libvirt/autobuild/defines
  extra-emulation/libvirt/spec
Labels: enhancement, lgtm

#3699 osu-lazer: update to 2021.1211.0
  extra-games/osu-lazer/spec
Labels: upgrade, lgtm

#3695 Jellyfin: new, 10.7.7
  extra-multimedia/jellyfin/autobuild/build
  extra-multimedia/jellyfin/autobuild/defines
  extra-multimedia/jellyfin/autobuild/overrides/etc/jellyfin.env
  extra-multimedia/jellyfin/autobuild/overrides/usr/bin/jellyfin
  extra-multimedia/jellyfin/autobuild/overrides/usr/lib/systemd/system/jellyfin.service
  extra-multimedia/jellyfin/autobuild/overrides/usr/lib/sysusers.d/jellyfin.conf
  extra-multimedia/jellyfin/autobuild/overrides/usr/lib/tmpfiles.d/jellyfin.conf
  extra-multimedia/jellyfin/autobuild/postinst
  extra-multimedia/jellyfin/spec
Labels: new-package, lgtm

#3680 chiron-sans-hk: new, 2.045
  extra-fonts/chiron-sans-hk/autobuild/build
  extra-fonts/chiron-sans-hk/autobuild/defines
  extra-fonts/chiron-sans-hk/spec
Labels: new-package, lgtm

#3703 fcitx5-pinyin-moegirl: update to 20211214
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#3711 ncdu: update to 1.16
  extra-utils/ncdu/spec
Labels: upgrade, lgtm

#3681 i2pd: update to 2.40.0
  extra-web/i2pd/spec
Labels: upgrade, lgtm

#3720 jemalloc: upgrade to 5.2.1, set page size to max possible for arm64
  extra-libs/jemalloc/autobuild/defines
  extra-libs/jemalloc/spec
Labels: enhancement, upgrade, lgtm
