Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-03, with the labels that each got.

#2893 webkit2gtk: update to 2.30.6
  extra-libs/webkit2gtk/spec
Labels: priority, security, upgrade

#2898 pyside2: update to 5.15.1
  extra-libs/pyside2/autobuild/defines
  extra-libs/pyside2/spec
Labels: upgrade

#2907 iosevka-fonts: update to 5.0.9
  extra-fonts/iosevka-fonts/spec
Labels: upgrade

#2906 baidupcs-go: update to 3.7.8
  extra-web/baidupcs-go/spec
Labels: upgrade

#2909 shadowsocks-rust: update to 1.10.1
  extra-network/shadowsocks-rust/autobuild/defines
  extra-network/shadowsocks-rust/autobuild/patches/0001-enable-cross-language-lto.patch
  extra-network/shadowsocks-rust/autobuild/prepare
  extra-network/shadowsocks-rust/spec
Labels: upgrade

#2908 telegram-desktop: update to 2.7.1
  extra-web/telegram-desktop/spec
Labels: upgrade

#2916 iosevka-fonts: update to 5.1.0
  extra-fonts/iosevka-fonts/spec
Labels: upgrade

#2910 nix-user-chroot: update to 1.2.1
  extra-utils/nix-user-chroot/spec
Labels: upgrade

#2912 shadowsocks-rust: update to 1.10.2
  extra-network/shadowsocks-rust/spec
Labels: upgrade

#2911 v2ray: update to 4.36.0
  extra-network/v2ray/spec
Labels: upgrade

#2914 sarasa-gothic-fonts: update to 0.18.9
  extra-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#2888 zfs: update to 2.0.4
  extra-kernel/zfs/autobuild/postinst
  extra-kernel/zfs/spec
Labels: upgrade

#2917 wine: update to 6.5
  extra-emulation/wine/spec
Labels: upgrade

#2918 apt: update to 2.2.2
  extra-admin/apt/spec
Labels: upgrade

#2921 iosevka-fonts: update to 5.1.1
  extra-fonts/iosevka-fonts/spec
Labels: upgrade

#2920 sarasa-gothic-fonts: update to 0.20.0
  extra-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#2797 ffmpeg: Massage loongson2f support for Retro
  extra-multimedia/ffmpeg/autobuild/build
  extra-multimedia/ffmpeg/autobuild/loongson2f/prepare
  extra-multimedia/ffmpeg/autobuild/patches/0001-avcodec-mips-loongson-refine-process-of-setting-bloc.patch
  extra-multimedia/ffmpeg/autobuild/patches/0002-avutil-mips-Avoid-instruction-exception-caused-by-gs.patch
  extra-multimedia/ffmpeg/autobuild/patches/0003-avutil-mips-refine-msa-macros-CLIP_.patch
  extra-multimedia/ffmpeg/autobuild/patches/0004-avcodec-mips-Fix-a-warnning-of-indentation-not-refle.patch
  extra-multimedia/ffmpeg/autobuild/patches/0005-avutil-mips-refactor-msa-SLDI_Bn_0-and-SLDI_Bn-macro.patch
  extra-multimedia/ffmpeg/autobuild/patches/0006-avcodec-mips-Fixed-four-warnings-in-vc1dsp.patch
  extra-multimedia/ffmpeg/autobuild/patches/0007-avcodec-mips-msa-optimizations-for-vc1dsp.patch
  extra-multimedia/ffmpeg/autobuild/patches/0008-lavc-mips-simplify-the-switch-code.patch
  extra-multimedia/ffmpeg/autobuild/patches/0009-avcodec-aacdec-fix-compilation-under-soft-float-MIPS.patch
  extra-multimedia/ffmpeg/autobuild/patches/0010-avcodec-mips-fix-get_cabac_inline_mips-function-name.patch
  extra-multimedia/ffmpeg/autobuild/patches/0011-avcodec-mips-fix-type-mismatch-in-h264dsp_msa.c.patch
  extra-multimedia/ffmpeg/autobuild/patches/0012-ffbuild-Refine-MIPS-handling.patch
  extra-multimedia/ffmpeg/autobuild/patches/0013-libavutils-Add-parse_r-helper-for-MIPS.patch
  extra-multimedia/ffmpeg/autobuild/patches/0014-libavutil-Detect-MMI-and-MSA-flags-for-MIPS.patch
  extra-multimedia/ffmpeg/autobuild/patches/0015-libavcodec-Enable-runtime-detection-for-MIPS-MMI-MSA.patch
  extra-multimedia/ffmpeg/autobuild/patches/0016-libavcodec-MIPS-MMI-Fix-type-mismatches.patch
  extra-multimedia/ffmpeg/autobuild/patches/0017-libavcodec-MIPS-MMI-Move-sp-out-of-the-clobber-list.patch
  extra-multimedia/ffmpeg/autobuild/patches/0018-avcodec-mips-Fix-register-constraint-error-reported-.patch
  extra-multimedia/ffmpeg/autobuild/patches/0019-avcodec-mips-cabac-Fix-a-bug-in-get_cabac_inline_mip.patch
  extra-multimedia/ffmpeg/autobuild/patches/0020-avcodec-mips-Fix-segfault-in-imdct36_mips_float.patch
  extra-multimedia/ffmpeg/autobuild/patches/0021-avcodec-mips-loongson-Fixed-mmi-optimization.patch
  extra-multimedia/ffmpeg/autobuild/patches/0022-avcodec-mips-Add-switch-for-MADD-instruction.patch
  extra-multimedia/ffmpeg/autobuild/patches/0023-avutil-mips-Use-MMI_-L-S-QC1-macro-in-SAVE-RECOVER-_.patch
  extra-multimedia/ffmpeg/autobuild/patches/0024-avutil-mips-Extract-load-store-with-shift-C1-pair-ma.patch
  extra-multimedia/ffmpeg/autobuild/patches/0025-avcodec-mips-Use-MMI-marcos-to-replace-Loongson3-ins.patch
  extra-multimedia/ffmpeg/autobuild/patches/0026-avutil-mips-Use-at-as-MMI-macro-temporary-register.patch
Labels: retro

#2930 zoom: drop due to prohibitive terms of service
  extra-web/zoom/autobuild/build
  extra-web/zoom/autobuild/defines
  extra-web/zoom/autobuild/overrides/usr/share/applications/Zoom.desktop
  extra-web/zoom/autobuild/overrides/usr/share/doc/zoom/changelog.gz
  extra-web/zoom/autobuild/overrides/usr/share/mime/packages/zoom.xml
  extra-web/zoom/autobuild/overrides/usr/share/pixmaps/Zoom.png
  extra-web/zoom/autobuild/overrides/usr/share/pixmaps/application-x-zoom.png
  extra-web/zoom/spec
Labels: Ready

#2913 rime-cantonese: update to 20210325
  extra-i18n/rime-cantonese/autobuild/defines
  extra-i18n/rime-cantonese/spec
Labels: upgrade

#2932 youtube-dl: update to 2021.03.31
  extra-multimedia/youtube-dl/spec
Labels: upgrade

#2933 sarasa-gothic-fonts: update to 0.20.1
  extra-fonts/sarasa-gothic-fonts/spec
Labels: upgrade
