Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-08, with the labels that each got.

#3342 peek: new, 1.5.1
  extra-graphics/peek/autobuild/defines
  extra-graphics/peek/spec
Labels: new-package

#3347 ciel: update to 3.0.11
  extra-devel/ciel/spec
Labels: upgrade, priority

#3339 qemu: utilize binfmt-misc flags to prevent copying qemu-user-static bin
  extra-emulation/qemu/02-static-aarch64/overrides/etc/binfmt.d/qemu-aarch64.conf
  extra-emulation/qemu/03-static-alpha/overrides/etc/binfmt.d/qemu-alpha.conf
  extra-emulation/qemu/04-static-arm/overrides/etc/binfmt.d/qemu-arm.conf
  extra-emulation/qemu/05-static-armeb/overrides/etc/binfmt.d/qemu-armeb.conf
  extra-emulation/qemu/06-static-cris/overrides/etc/binfmt.d/qemu-cris.conf
  extra-emulation/qemu/07-static-i386/overrides/etc/binfmt.d/qemu-i386.conf
  extra-emulation/qemu/08-static-m68k/overrides/etc/binfmt.d/qemu-m68k.conf
  extra-emulation/qemu/09-static-microblaze/overrides/etc/binfmt.d/qemu-microblaze.conf
  extra-emulation/qemu/11-static-mips/overrides/etc/binfmt.d/qemu-mips.conf
  extra-emulation/qemu/14-static-mipsel/overrides/etc/binfmt.d/qemu-mipsel.conf
  extra-emulation/qemu/18-static-ppc/overrides/etc/binfmt.d/qemu-ppc.conf
  extra-emulation/qemu/19-static-ppc64/overrides/etc/binfmt.d/qemu-ppc64.conf
  extra-emulation/qemu/22-static-s390x/overrides/etc/binfmt.d/qemu-s390x.conf
  extra-emulation/qemu/23-static-sh4/overrides/etc/binfmt.d/qemu-sh4.conf
  extra-emulation/qemu/24-static-sh4eb/overrides/etc/binfmt.d/qemu-sh4eb.conf
  extra-emulation/qemu/25-static-sparc/overrides/etc/binfmt.d/qemu-sparc.conf
  extra-emulation/qemu/26-static-sparc32plus/overrides/etc/binfmt.d/qemu-sparc32plus.conf
  extra-emulation/qemu/27-static-sparc64/overrides/etc/binfmt.d/qemu-sparc64.conf
  extra-emulation/qemu/29-static-x86_64/overrides/etc/binfmt.d/qemu-x86_64.conf
  extra-emulation/qemu/30-static-riscv64/overrides/etc/binfmt.d/qemu-riscv64.conf
  extra-emulation/qemu/spec
Labels: enhancement

#3354 acbs: update to 20210816
  extra-devel/acbs/spec
Labels: upgrade

#3282 boinctui: fix manpage location
  extra-scientific/boinctui/autobuild/beyond
  extra-scientific/boinctui/spec
Labels: bug

#3350 tesseract: update to 4.1.1
  extra-utils/tesseract/spec
Labels: upgrade

#3356 docbook-xsl: base catalog file on the one shipped in docbook-dtd
  extra-doc/docbook-xsl/autobuild/defines
  extra-doc/docbook-xsl/autobuild/postinst
  extra-doc/docbook-xsl/spec
Labels: bug

#3341 crow-translate: new, 2.8.4
  extra-i18n/crow-translate/autobuild/defines
  extra-i18n/crow-translate/spec
Labels: new-package

#3362 sqlite: update to 3.36.0
  base-database/sqlite/spec
Labels: upgrade

#3363 aosc-os-repository-data: update to 20210819
  extra-misc/aosc-os-repository-data/spec
Labels: upgrade

#3364 aosc-os-repository-data: fix shell script syntax
  extra-misc/aosc-os-repository-data/spec
Labels: bug

#3366 you-get: update to 0.4.1545
  extra-multimedia/you-get/spec
Labels: upgrade

#3372 autobuild3: update to 1.6.23
  extra-devel/autobuild3/spec
Labels: bug, upgrade

#3377 typing: update to 3.10.0.0, rework
  extra-python/m2crypto/spec
Labels: rework

#3376 ykdl: update to 1.8.1~a2
  extra-multimedia/ykdl/spec
Labels: enhancement, upgrade

#3380 i2pd: update to 2.39.0
  extra-web/i2pd/spec
Labels: upgrade

#3382 aria2: update to 1.36.0
  extra-web/aria2/spec
Labels: upgrade

#3390 libbsd: add loongarch64 patch
  extra-libs/libbsd/autobuild/patches/0001-port-loongarch64-recognition.patch.loongarch64
Labels: new-port

#3402 ytdl-gui: update to 3.0
  extra-web/ytdl-gui/spec
Labels: upgrade
