Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-10, with the labels that each got.

#3483 telegram-desktop: update to 3.1.1
  extra-web/telegram-desktop/spec
Labels: upgrade, lgtm

#3481 nnn: update to 4.3
  extra-utils/nnn/spec
Labels: upgrade, lgtm

#3482 deno: update to 1.14.2
  extra-js/deno/spec
Labels: upgrade, lgtm

#3479 yarn: update to 1.22.15
  extra-js/yarn/spec
Labels: upgrade, lgtm

#3485 glew: fix QA errors when building
  extra-libs/glew/autobuild/build
  extra-libs/glew/spec
Labels: lgtm

#3486 README: unify spelling
  README.md
Labels: enhancement

#3493 workflows: add new workflow for building packages
  .github/workflows/build_on_request.yml
Labels: enhancement

#3495 workflows: use script to allocate a PTY for acbs
  .github/workflows/build_on_request.yml
Labels: bug

#3496 workflows: use script as a command
  .github/workflows/build_on_request.yml
Labels: bug

#3497 workflows: checkout PR instead of stable
  .github/workflows/build_on_request.yml
Labels: bug

#3498 workflows: install GitHub CLI in container
  .github/workflows/build_on_request.yml
Labels: bug

#3499 workflows: use absolute path on linking
  .github/workflows/build_on_request.yml
Labels: bug

#3500 workflows: use POSIX shell syntax
  .github/workflows/build_on_request.yml
Labels: bug

#3501 workflows: run installation in repo
  .github/workflows/build_on_request.yml
Labels: bug

#3484 lxgwwenkai-font: update to 1.100
  extra-fonts/lxgwwenkai-font/spec
Labels: upgrade, lgtm

#3502 workflows: fix gh tool
  .github/workflows/build_on_request.yml
Labels: bug

#3488 meowdict: update to 0.8.1
  extra-i18n/meowdict/spec
Labels: upgrade, lgtm

#3487 nodejs: update to 14.18.0
  extra-js/nodejs/spec
Labels: upgrade, lgtm

#3506 workflows: enable building on issue comments
  .github/workflows/build_on_request.yml
Labels: enhancement

#3507 workflows: update the container before building
  .github/workflows/build_on_request.yml
Labels: bug

#3508 workflows: use Fastly CDN instead of repo
  .github/workflows/build_on_request.yml
Labels: bug

#3510 workflows: use debs as archive name
  .github/workflows/build_on_request.yml
Labels: enhancement

#3511 workflows: allow building multiple packages
  .github/workflows/build_on_request.yml
Labels: bug, enhancement

#3513 workflows: check for lgtm label on PR
  .github/workflows/lgtm.yml
Labels: enhancement

#3514 workflows-lgtm: fix typo
  .github/workflows/lgtm.yml
Labels: bug

#3515 workflows-lgtm: fix escaping
  .github/workflows/lgtm.yml
Labels: bug

#3516 workflows: check names instead of [object Object]
  .github/workflows/lgtm.yml
Labels: bug

#3517 workflows: run lgtm in more situations
  .github/workflows/lgtm.yml
Labels: bug

#3519 workflows: update status in comments
  .github/workflows/build_on_request.yml
Labels: enhancement, lgtm

#3509 suitesparse: manually specify a make target to prevent running demo
  extra-libs/suitesparse/autobuild/build
  extra-libs/suitesparse/spec
Labels: lgtm

#3522 eigen-3: noarchize
  extra-devel/eigen-3/autobuild/defines
  extra-devel/eigen-3/spec
Labels: lgtm

#3521 workflows-lgtm: optimize triggers
  .github/workflows/lgtm.yml
Labels: bug

#3523 workflows-build: update matrix limitation docs
  .github/workflows/README.md
Labels: enhancement, lgtm

#3529 workflows: use buildkit daily container
  .github/workflows/Dockerfile
  .github/workflows/build_on_request.yml
  .github/workflows/buildkit-daily.yml
Labels: bug, enhancement, lgtm

#3504 Update libatomic_ops to v7.6.12
  base-libs/libatomic-ops/spec
Labels: lgtm

#3505 gc: update to 8.0.6
  base-libs/gc/spec
Labels: lgtm

#3532 workflows-container: use apt-get instead of apt
  .github/workflows/buildkit-daily.yml
Labels: enhancement

#3533 workflows-container: improve OCI labels
  .github/workflows/buildkit-daily.yml
Labels: enhancement

#3632 nvidia: manually create symlink for libglxserver_nvidia.so
  extra-x11/nvidia/autobuild/build
  extra-x11/nvidia/spec
Labels: bug, priority, rework, lgtm
