Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-06, with the labels that each got.

#3128 you-get: update to 0.4.1527
  extra-multimedia/you-get/spec
Labels: upgrade

#3127 nnn: update to 4.1
  extra-utils/nnn/spec
Labels: upgrade

#3126 meowdict: update to 0.6.1
  extra-i18n/meowdict/autobuild/defines
  extra-i18n/meowdict/spec
Labels: upgrade

#3129 diff-so-fancy: update to 1.4.1
  extra-utils/diff-so-fancy/spec
Labels: upgrade

#3130 baidupcs-go: update to 3.8.0
  extra-web/baidupcs-go/spec
Labels: upgrade

#3133 QEMU: Upgrade to 6.0.0, enable LTO
  extra-emulation/qemu/01-shared/build
  extra-emulation/qemu/spec
Labels: enhancement, upgrade

#3149 aoscdk-rs: new, 0+git20210605
  extra-admin/aoscdk-rs/autobuild/beyond
  extra-admin/aoscdk-rs/autobuild/defines
  extra-admin/aoscdk-rs/spec
Labels: new-package

#3155 aiohttp: update to 3.7.4.post0
  extra-python/aiohttp/spec
Labels: security, upgrade

#3157 shadowsocks-rust: update to 1.11.1
  extra-network/shadowsocks-rust/autobuild/beyond
  extra-network/shadowsocks-rust/autobuild/defines
  extra-network/shadowsocks-rust/spec
Labels: upgrade

#3151 linux-kernel-retro: enable CONFIG_TUN
  extra-kernel/linux-kernel-retro/autobuild/i486/config
Labels: retro

#3162 vscode: update to 1.57.0
  extra-editors/vscode/spec
Labels: upgrade

#3171 deno: update to 1.11.0
  extra-js/deno/spec
Labels: upgrade

#3174 aoscdk-rs: update to 0.2.0
  extra-admin/aoscdk-rs/spec
Labels: upgrade

#3175 aoscbootstrap: update to 0.1.10
  extra-utils/aoscbootstrap/spec
Labels: upgrade

#3181 squashfs-tools: fix bindir
  extra-admin/squashfs-tools/autobuild/build
  extra-admin/squashfs-tools/spec
Labels: bug

#3180 iio-sensor-proxy: update to 3.1
  extra-utils/iio-sensor-proxy/autobuild/autobuild/0001-light-Support-sensors-using-raw-values-as-well.patch
  extra-utils/iio-sensor-proxy/autobuild/defines
  extra-utils/iio-sensor-proxy/autobuild/definest
  extra-utils/iio-sensor-proxy/spec
Labels: upgrade

#3186 redis: update to 6.2.4; fix #3146
  extra-database/redis/spec
Labels: security, upgrade

#3184 nodejs: update to 14.17.1
  extra-js/nodejs/spec
Labels: upgrade

#3187 yubioath-desktop: update to 5.0.5
  extra-security/yubioath-desktop/spec
Labels: upgrade

#3189 vivaldi: update to 4.0.2312.27
  extra-web/vivaldi/spec
Labels: 0day, security, upgrade

#3191 fcitx5-pinyin-moegirl: update to 20210614
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#3193 meowdict: update to 0.6.3
  extra-i18n/meowdict/autobuild/defines
  extra-i18n/meowdict/spec
Labels: upgrade

#3188 vscode: update to 1.57.1
  extra-editors/vscode/spec
Labels: upgrade

#3192 hugo: update to 0.84.0
  extra-web/hugo/spec
Labels: upgrade

#3179 cpio: (Fedora patch) revert CVE-2015-1197 to fix dracut
  base-utils/cpio/autobuild/defines
  base-utils/cpio/autobuild/patches/0002-Fedora-cpio-2.13-revert-CVE-2015-1197-fix.patch
  base-utils/cpio/spec
Labels: bug

#3201 postgresql: update to 13.3
  extra-database/postgresql/autobuild/beyond
  extra-database/postgresql/autobuild/postgresql-check-db-dir.in
  extra-database/postgresql/autobuild/prepare
  extra-database/postgresql/spec
Labels: security, upgrade

#3199 iosevka-fonts: update to 7.1.1
  extra-fonts/iosevka-fonts/spec
Labels: upgrade

#3205 pushpkg: update to 0+20210622
  extra-devel/pushpkg/autobuild/defines
  extra-devel/pushpkg/spec
Labels: upgrade

#3206 v2ray: update to 4.41.0
  extra-network/v2ray/spec
Labels: upgrade

#3209 ipt2socks: fix QA error 321
  extra-network/ipt2socks/autobuild/defines
  extra-network/ipt2socks/autobuild/patches/0002-ipt2socks-no-strip.patch
  extra-network/ipt2socks/spec
Labels: has-fix

#3211 lxgwwenkai-font: update to 0.334
  extra-fonts/lxgwwenkai-font/spec
Labels: upgrade

#3217 postgresql: enable JIT and use Python 3
  extra-database/postgresql/autobuild/defines
  extra-database/postgresql/spec
Labels: enhancement

#3216 dbus: fix permission for dbus-daemon-launch-helper
  extra-admin/dbus/autobuild/beyond
  extra-admin/dbus/spec
Labels: bug

#3221 lightcord: update to 0.1.7
  extra-web/lightcord/spec
Labels: upgrade

#3222 sddm: clean up scripts with fixed gid and uid
  extra-displaymanagers/sddm/autobuild/beyond
  extra-displaymanagers/sddm/autobuild/postinst
  extra-displaymanagers/sddm/spec
Labels: upgrade
