Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2021-05, with the labels that each got.

#3028 telegram-desktop: update to 2.7.4
  extra-web/telegram-desktop/spec
Labels: upgrade

#3030 netease-cloud-music-gtk: update to 1.2.2
  extra-multimedia/netease-cloud-music-gtk/autobuild/defines
  extra-multimedia/netease-cloud-music-gtk/spec
Labels: upgrade

#3031 v2ray: update to 4.38.1
  extra-network/v2ray/spec
Labels: upgrade

#3032 rclone: update to 1.55.1
  extra-web/rclone/spec
Labels: upgrade

#3034 samba: fix gnome-control-center install
  extra-network/samba/autobuild/defines
  extra-network/samba/spec
Labels: bug

#3041 nix-user-chroot: update to 1.2.2
  extra-utils/nix-user-chroot/spec
Labels: upgrade

#3046 scipy: update to 1.6.3
  extra-python/scipy/spec
Labels: upgrade

#3050 systemd-boot-friend: update to 0.6.0
  extra-admin/systemd-boot-friend/spec
Labels: upgrade

#3053 lxgwwenkai-font: new, 0.312
  extra-fonts/lxgwwenkai-font/autobuild/build
  extra-fonts/lxgwwenkai-font/autobuild/defines
  extra-fonts/lxgwwenkai-font/spec
Labels: new-package

#3052 vscode: update to 1.56.0
  extra-editors/vscode/spec
Labels: upgrade

#2951 xray: new, 1.4.2
  extra-network/xray/autobuild/build
  extra-network/xray/autobuild/defines
  extra-network/xray/autobuild/overrides/usr/lib/systemd/system/xray.service
  extra-network/xray/autobuild/overrides/usr/lib/systemd/system/xray@.service
  extra-network/xray/spec
Labels: new-package

#3042 iosevka-fonts: update to 6.1.2
  extra-fonts/iosevka-fonts/spec
Labels: upgrade

#3074 groovy: mark as noarch
  extra-java/groovy/autobuild/defines
  extra-java/groovy/spec
Labels: enhancement

#2848 syncthing: update to 1.14.0
  extra-network/syncthing/spec
Labels: upgrade

#3056 spamassassin: security update to 3.4.6
  extra-network/spamassassin/autobuild/build
  extra-network/spamassassin/autobuild/patch
  extra-network/spamassassin/autobuild/postinst
  extra-network/spamassassin/spec
Labels: security, upgrade

#3065 firefox: update to 88.0.1
  extra-web/firefox/spec
Labels: security, upgrade

#3078 openjfx: strip symbols for amd64
  extra-java/openjfx/autobuild/build
Labels: bug

#3082 bat: update to 0.18.1
  extra-utils/bat/spec
Labels: upgrade

#3083 cbindgen: disable LTO on loongson3
  extra-rust/cbindgen/autobuild/defines
Labels: bug, has-fix

#3097 nodejs: update to 14.17.0
  extra-js/nodejs/spec
Labels: upgrade

#3096 bitwarden-cli: update to 1.16.0
  extra-js/bitwarden-cli/autobuild/build
  extra-js/bitwarden-cli/autobuild/patches/0001-bitwarden-fix-webpack-bundling.patch
  extra-js/bitwarden-cli/spec
Labels: upgrade

#3101 youtube-dl: update to 2021.05.16
  extra-multimedia/youtube-dl/spec
Labels: upgrade

#3098 i2pd: update to 2.38.0
  extra-web/i2pd/autobuild/defines
  extra-web/i2pd/spec
Labels: upgrade

#3109 aoscbootstrap: update to 0.1.6
  extra-utils/aoscbootstrap/spec
Labels: upgrade

#3111 meowdict: new, 0.3.0
  extra-i18n/meowdict/autobuild/defines
  extra-i18n/meowdict/spec
Labels: new-package
