Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-10, with the labels that each got.

#4226 x11-ssh-askpass: install binaries to /usr/libexec
  extra-utils/x11-ssh-askpass/autobuild/defines
  extra-utils/x11-ssh-askpass/autobuild/overrides/etc/profile.d/x11-ssh-askpass.sh
  extra-utils/x11-ssh-askpass/spec
Labels: enhancement, lgtm

#4224 fcitx5-pinyin-moegirl: update to 20220925
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#4229 libcryptui: add missing BUILDDEP gtk-doc
  extra-libs/libcryptui/autobuild/defines
Labels: rework, lgtm

#4231 gnome-user-share: fix FTBFS by backporting a patch
  extra-gnome/gnome-user-share/autobuild/patches/0001-build-fix-build-with-meson-0.61.patch
  extra-gnome/gnome-user-share/spec
Labels: lgtm

#4232 celt-0.5: fix FTBFS by disabling RECONF
  extra-multimedia/celt-0.5/autobuild/defines
  extra-multimedia/celt-0.5/spec
Labels: FTBFS, lgtm

#4233 spice-protocol: noarchize
  extra-network/spice-protocol/autobuild/defines
  extra-network/spice-protocol/spec
Labels: enhancement, FTBFS, lgtm

#4235 libva-nvidia-driver: add missing dependency gstreamer
  extra-libs/libva-nvidia-driver/autobuild/defines
  extra-libs/libva-nvidia-driver/spec
Labels: rework, lgtm

#4241 libdmapsharing: add missing BUILDDEPs
  extra-libs/libdmapsharing/autobuild/defines
  extra-libs/libdmapsharing/spec
Labels: enhancement, FTBFS, lgtm

#4247 gegl-0.4: adapt for new babl and riscv64
  extra-libs/gegl-0.4/autobuild/defines
  extra-libs/gegl-0.4/autobuild/patches/0001-gegl-sampler-nearest-fix-typo-in-babl_process.patch
  extra-libs/gegl-0.4/autobuild/patches/0003-nuke-stray-NULL-parameter-from-babl_process.patch
  extra-libs/gegl-0.4/spec
Labels: new-port, lgtm

#4216 fail2ban: new, 0.11.2+git20220917
  extra-security/fail2ban/autobuild/beyond
  extra-security/fail2ban/autobuild/defines
  extra-security/fail2ban/autobuild/overrides/etc/fail2ban/jail.d/sshd.local
  extra-security/fail2ban/autobuild/patches/0001-fix-fail2ban-run-in-systemd.patch
  extra-security/fail2ban/spec
Labels: new-package, lgtm

#4252 libunity: import a patch from Fedora to fix FTBFS
  extra-libs/libunity/autobuild/patches/0002-Fedora-libunity-7.1.4-vala-053.patch
  extra-libs/libunity/spec
Labels: bug, FTBFS, lgtm

#4254 gnome-software: adapt for riscv64 by masking valgrind
  extra-gnome/gnome-software/autobuild/defines
Labels: enhancement, FTBFS, new-port, lgtm

#4255 polymc: use "AOSC MC" Microsoft MSA Client ID
  extra-games/polymc/autobuild/build
  extra-games/polymc/spec
Labels: bug, lgtm

#4056 openjdk: add riscv64 support
  extra-java/openjdk/autobuild/defines
  extra-java/openjdk/autobuild/prepare
  extra-java/openjdk/spec
Labels: new-port, lgtm

#4256 s-tui: update to 1.1.3
  extra-utils/s-tui/spec
Labels: upgrade, lgtm

#4258 aoscdk-rs: update to 0.5.1
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#4261 zellij: update to 0.31.4
  extra-utils/zellij/spec
Labels: upgrade, lgtm

#4264 discord: update to 0.0.21
  extra-web/discord/spec
Labels: upgrade, lgtm

#4093 rsync: upgrade to 3.2.5~pre1 fixing CVE-2022-29154
  extra-network/rsync/spec
Labels: upgrade, security, aosa-pending, has-fix, lgtm

#4263 osu-lazer: update to 2022.1008.2
  extra-games/osu-lazer/spec
Labels: upgrade, lgtm

#4257 bear: update to 3.0.20
  extra-devel/bear/spec
Labels: upgrade, lgtm

#4268 osu-lazer: update to 2022.1022.0
  extra-games/osu-lazer/spec
Labels: upgrade, lgtm

#4271 uboot-tools: update to 2022.10
  extra-utils/uboot-tools/autobuild/build
  extra-utils/uboot-tools/autobuild/defines
  extra-utils/uboot-tools/spec
Labels: upgrade, FTBFS, lgtm

#4269 prismlauncher: new, 5.0
  extra-games/prismlauncher/autobuild/defines
  extra-games/prismlauncher/spec
Labels: new-package, lgtm

#4266 linux-kernel-lemote: update to 5.4.219
  extra-kernel/linux+kernel+lemote/autobuild/defines
  extra-kernel/linux+kernel+lemote/spec
  extra-kernel/linux-kernel-lemote/autobuild/config
  extra-kernel/linux-kernel-lemote/autobuild/defines
  extra-kernel/linux-kernel-lemote/spec
Labels: lgtm

#4275 gdb: enable all targets and languages
  extra-devel/gdb/autobuild/defines
  extra-devel/gdb/spec
Labels: enhancement, lgtm

#4276 libffi: disable LTO
  base-libs/libffi/autobuild/defines
  base-libs/libffi/spec
Labels: enhancement, lgtm
