Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-04, with the labels that each got.

#3876 vscode: update to 1.65.2
  extra-editors/vscode/spec
Labels: upgrade, lgtm

#3898 bitwarden-cli: drop
  extra-js/bitwarden-cli/autobuild/build
  extra-js/bitwarden-cli/autobuild/defines
  extra-js/bitwarden-cli/autobuild/patches/0001-bitwarden-fix-webpack-bundling.patch
  extra-js/bitwarden-cli/spec
Labels: lgtm

#3900 lxgwwenkai-font: update to 1.233.2
  extra-fonts/lxgwwenkai-font/autobuild/build
  extra-fonts/lxgwwenkai-font/spec
Labels: upgrade, lgtm

#3931 libarchive: security update to 3.6.1
  extra-libs/libarchive/spec
Labels: security, lgtm, tested

#3919 nbd: security update to 3.24
  extra-network/nbd/spec
Labels: upgrade, security, lgtm, tested

#3932 fcitx5-pinyin-moegirl: update to 20220414
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#3939 wezterm: update to 20220408-101518-b908e2dd
  extra-utils/wezterm/autobuild/patches/0002-config-do-not-check-update.patch
  extra-utils/wezterm/spec
Labels: upgrade, lgtm

#3943 aosc-os-repository-data: update to v20220429
  extra-misc/aosc-os-repository-data/spec
Labels: lgtm
