Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-01, with the labels that each got.

#3731 fd: fix usability for 16k page size devices
  extra-utils/fd/autobuild/defines
  extra-utils/fd/spec
Labels: bug, abi-break, lgtm

#3629 [ci] libslirp: security update to 4.6.1; #3628
  extra-libs/libslirp/spec
Labels: upgrade, security, priority, lgtm

#3752 fcitx5-pinyin-moegirl: update to 20220114
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#3754 aosc-logos: set 'icenowy' as current
  extra-misc/aosc-logos/autobuild/overrides/usr/bin/aosc-logo
  extra-misc/aosc-logos/spec
Labels: upgrade, lgtm

#3755 xorg-server: disable libunwind on arm64 due to segfaults
  extra-x11/xorg-server/autobuild/defines
  extra-x11/xorg-server/spec
Labels: bug, rework, lgtm

#3756 aosc-aaa: reset console color at each end-of-line in the postinst logo
  core-misc/aosc-aaa/autobuild/postinst
  core-misc/aosc-aaa/spec
Labels: bug, rework, lgtm

#3761 systemd-boot-friend: update to 0.13.0
  extra-admin/systemd-boot-friend/autobuild/overrides/etc/systemd-boot-friend.conf
  extra-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm

#3762 kde-base: drop kcm-fcitx Recommends
  extra-bases/kde-base/autobuild/defines
  extra-bases/kde-base/spec
Labels: enhancement, upgrade, lgtm

#3764 aoscbootstrap: update to 0.2.0
  extra-utils/aoscbootstrap/spec
Labels: upgrade, lgtm

#3765 hplip: fix cups daemon service name org.cups.cupsd => cups
  extra-doc/hplip/autobuild/postinst
  extra-doc/hplip/spec
Labels: bug, lgtm

#3766 codec-base: drop GStreamer 0.10 codecs from dep
  extra-bases/codec-base/autobuild/defines
  extra-bases/codec-base/spec
Labels: enhancement, lgtm

#3767 discord: add a configurable launcher script
  extra-web/discord/autobuild/build
  extra-web/discord/autobuild/overrides/etc/discord-launcher.conf
  extra-web/discord/autobuild/overrides/usr/bin/discord
  extra-web/discord/spec
Labels: bug, enhancement, lgtm

#3772 systemd-boot-friend: update to 0.16.0
  extra-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm

#3774 polkit: fix PwnKit vulnerability (CVE-2021-4034); #3773
  extra-admin/polkit/autobuild/patches/0001-pkexec-local-privilege-escalation-CVE-2021-4034.patch
  extra-admin/polkit/spec
Labels: security, 0day, lgtm

#3775 Google Chrome 97.0.4692.99
  extra-web/google-chrome/spec
Labels: upgrade, lgtm

#3778 polkit: mark SUID for /usr/bin/pkexec
  extra-admin/polkit/autobuild/beyond
  extra-admin/polkit/spec
Labels: bug, lgtm

#3779 glib: drop sysprof dep
  base-libs/glib/autobuild/defines
  base-libs/glib/spec
Labels: enhancement, lgtm
