Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-07, with the labels that each got.

#4052 shadow: (fix #4045) chmod /etc/shadow to 0000 in postinst
  base-admin/shadow/autobuild/postinst
  base-admin/shadow/spec
Labels: security, priority, 0day, lgtm

#4038 icalingua++: fix extract path
  extra-web/icalingua++/autobuild/build
  extra-web/icalingua++/spec
Labels: bug, has-fix, lgtm

#4057 xkeyboard-config: update to 2.36
  extra-x11/xkeyboard-config/autobuild/beyond
  extra-x11/xkeyboard-config/autobuild/defines
  extra-x11/xkeyboard-config/spec
Labels: upgrade, lgtm

#4070 git: security update to 2.37.1; #4069
  extra-vcs/git/spec
Labels: upgrade, security, lgtm

#4078 flameshot: update to 12.1.0
  extra-utils/flameshot/spec
Labels: upgrade, lgtm

#4081 pushpkg: update to 0+git20220722
  extra-devel/pushpkg/spec
Labels: upgrade, lgtm

#4080 bluez: upgrade to 5.64, bring back old utilities
  extra-libs/bluez/autobuild/beyond
  extra-libs/bluez/autobuild/defines
  extra-libs/bluez/spec
Labels: enhancement, upgrade, lgtm

#4083 osu-lazer: update to 2022.723.0
  extra-games/osu-lazer/spec
Labels: upgrade, lgtm

#4049 zerotier-one: update to 1.10.1
  extra-network/zerotier-one/autobuild/build
  extra-network/zerotier-one/autobuild/defines
  extra-network/zerotier-one/autobuild/patches/0001-clang-support-for-lto.patch
  extra-network/zerotier-one/spec
Labels: upgrade, lgtm
