Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-06, with the labels that each got.

#4006 qemu: update to 7.0.0
  extra-emulation/qemu/01-shared/build
  extra-emulation/qemu/01-shared/overrides/usr/lib/systemd/system/qemu-ga-virtio@.service
  extra-emulation/qemu/spec
Labels: enhancement, upgrade, lgtm

#4005 gdb: update to 12.1 and enable more features
  extra-devel/gdb/autobuild/beyond
  extra-devel/gdb/autobuild/defines
  extra-devel/gdb/autobuild/patches/0001-Fix-broken-configure-tests-compromised-by-LTO.patch
  extra-devel/gdb/spec
Labels: enhancement, upgrade, lgtm

#4023 polymc: update to 1.3.1
  extra-games/polymc/spec
Labels: upgrade, lgtm

#4024 discord: update to 0.0.18
  extra-web/discord/spec
Labels: upgrade, lgtm

#4027 linux-firmware: update to 20220610
  extra-kernel/linux-firmware/01-nonfree/build
  extra-kernel/linux-firmware/01-nonfree/patches/0001-Fedora-Add-support-for-compressing-firmware-in-copy-firmware.patch
  extra-kernel/linux-firmware/02-free/build
  extra-kernel/linux-firmware/spec
Labels: upgrade, lgtm

#4033 kwallet: add patches for org.freedesktop.secrets support
  extra-kde/kwallet/autobuild/defines
  extra-kde/kwallet/autobuild/patches/0001-Introduce-Secret-Service-API.patch
  extra-kde/kwallet/autobuild/patches/0002-Do-not-create-EntryLocation-with-empty-key.patch
  extra-kde/kwallet/autobuild/patches/0003-Do-not-try-to-rename-label-twice-in-entryRenamed.patch
  extra-kde/kwallet/spec
Labels: enhancement, lgtm

#4035 plasma-default-settings: update to 0+git20220620
  extra-misc/plasma-default-settings/spec
Labels: enhancement, lgtm

#4001 icalingua++: new, 2.6.3
  extra-web/icalingua++/autobuild/build
  extra-web/icalingua++/autobuild/defines
  extra-web/icalingua++/spec
Labels: new-package, lgtm

#4019 ghidra: update to 10.1.4
  extra-devel/ghidra/autobuild/build
  extra-devel/ghidra/autobuild/defines
  extra-devel/ghidra/autobuild/patches/0001-fix-build-arm64.patch
  extra-devel/ghidra/spec
Labels: upgrade, lgtm

#3964 hplip: update to 3.22.4
  extra-doc/hplip/autobuild/conffiles
  extra-doc/hplip/autobuild/defines
  extra-doc/hplip/autobuild/patches/0003-Fedora-hplip-ui-optional.patch
  extra-doc/hplip/autobuild/patches/0012-Fedora-hplip-logdir.patch
  extra-doc/hplip/autobuild/patches/0023-Fedora-hplip-sourceoption.patch
  extra-doc/hplip/autobuild/patches/0032-Fedora-hplip-keyserver.patch
  extra-doc/hplip/autobuild/patches/0034-Fedora-0025-Remove-all-ImageProcessor-functionality-which-is-clo.patch
  extra-doc/hplip/autobuild/patches/0037-Fedora-hplip-missing-links.patch
  extra-doc/hplip/autobuild/patches/0045-Fedora-hplip-missing-drivers.patch
  extra-doc/hplip/autobuild/patches/0054-Fedora-hplip-check-userperms.patch
  extra-doc/hplip/autobuild/patches/0054-Fedora-hplip-thread-isalive-removed.patch
  extra-doc/hplip/autobuild/patches/0055-Fedora-hplip-fab-import.patch
  extra-doc/hplip/autobuild/patches/0055-Fedora-hplip-timeb-removed.patch
  extra-doc/hplip/autobuild/patches/0056-Fedora-hplip-hpsetup-noscanjets.patch
  extra-doc/hplip/autobuild/patches/0057-Fedora-hplip-hpfirmware-timeout.patch
  extra-doc/hplip/autobuild/patches/0058-Fedora-hplip-gpgdir-perms.patch
  extra-doc/hplip/autobuild/patches/0059-Fedora-hplip-plugin-udevissues.patch
  extra-doc/hplip/autobuild/patches/0060-Fedora-hplip-osname-mismatch.patch
  extra-doc/hplip/autobuild/patches/1000-add-AOSC-OS-to-sudo-caller.patch
  extra-doc/hplip/spec
Labels: bug, enhancement, upgrade, lgtm

#4040 flameshot: update to 12.0.0
  extra-utils/flameshot/spec
Labels: upgrade, lgtm

#4041 libdrm: update to 2.4.111
  extra-libs/libdrm/autobuild/defines
  extra-libs/libdrm/spec
Labels: upgrade, lgtm

#4044 systemd-boot-friend: update to 0.24.0
  extra-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm
