Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-08, with the labels that each got.

#4089 polymc: update to 1.4.1
  extra-games/polymc/spec
Labels: upgrade, lgtm

#4090 rustc: fix outdated patch from retro
  extra-rust/rustc/autobuild/patches/0003-add-i486-unknown-linux-gnu-compiler-target.patch
  extra-rust/rustc/autobuild/prepare
Labels: bug, lgtm

#4076 git: enable PCRE2 JIT on RISC-V
  extra-vcs/git/autobuild/build
Labels: FTBFS, rework, lgtm

#4101 ttf-misaki: assign perm 644 to files
  extra-fonts/ttf-misaki/autobuild/build
  extra-fonts/ttf-misaki/spec
Labels: rework, lgtm

#4099 yt-dlp: update to 2022.08.08
  extra-multimedia/yt-dlp/spec
Labels: upgrade, lgtm

#4087 apt-gen-list: update to 0.6.7
  extra-admin/apt-gen-list/spec
Labels: upgrade, has-fix, lgtm

#4104 discord: update to 0.0.19
  extra-web/discord/spec
Labels: upgrade, lgtm

#4100 aoscdk-rs: update to 0.4.12
  extra-admin/aoscdk-rs/autobuild/defines
  extra-admin/aoscdk-rs/autobuild/patches/0001-disks-fix-new_partition_table-in-ppc64-el.patch
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#4109 ntfs-3g: retarget currently 404ed source files to aosc-repacks
  extra-libs/ntfs-3g/spec
Labels: lgtm, 404

#4108 xf86-input-wacom: update to 1.1.0 and drop beyond hack
  extra-x11/xf86-input-wacom/autobuild/beyond
  extra-x11/xf86-input-wacom/spec
Labels: upgrade, lgtm

#4111 libstoragemgmt: disable Valgrind on riscv64
  extra-libs/libstoragemgmt/autobuild/defines
Labels: new-port, lgtm

#4115 apt-gen-list: update to 0.6.8
  extra-admin/apt-gen-list/spec
Labels: upgrade, lgtm

#4118 fuse-3: disable building examples
  extra-libs/fuse-3/02-fuse-3/defines
  extra-libs/fuse-3/spec
Labels: FTBFS, lgtm

#4119 libgtop: add missing builddep gnome-common
  extra-libs/libgtop/autobuild/defines
  extra-libs/libgtop/spec
Labels: FTBFS, lgtm

#4120 libunique3: explicitly enable gtk-doc and introspection
  extra-libs/libunique3/autobuild/defines
  extra-libs/libunique3/spec
Labels: enhancement, FTBFS, lgtm

#4121 nodejs: update to 16.16.0
  extra-js/nodejs/spec
Labels: upgrade, lgtm

#4122 exempi: fix FTBFS because of GCC 11
  extra-libs/exempi/autobuild/patches/0001-gentoo-exempi-2.4.5-gcc11.patch
  extra-libs/exempi/spec
Labels: FTBFS, lgtm

#4123 vte-gtk3: noarchize
  extra-libs/vte-gtk3/autobuild/defines
  extra-libs/vte-gtk3/spec
Labels: lgtm

#4124 systemd-boot-friend: remove the empty `BOOTARG` in ...
  extra-admin/systemd-boot-friend/autobuild/amd64/overrides/etc/systemd-boot-friend.conf
  extra-admin/systemd-boot-friend/autobuild/arm64/overrides/etc/systemd-boot-friend.conf
  extra-admin/systemd-boot-friend/spec
Labels: bug, lgtm

#4128 libpeas: use lua instead of luajit on riscv64
  extra-libs/libpeas/autobuild/defines
Labels: enhancement, lgtm

#4129 autobuild3: update to 1.6.59
  extra-devel/autobuild3/spec
Labels: upgrade, lgtm

#4131 llvm: partially revert change from retro sync
  base-devel/llvm/01-runtime/defines
Labels: bug, lgtm

#4113 virtualbox: upgrade to 6.1.36
  extra-emulation/virtualbox/01-host/patches/0000-disable-update-check.patch
  extra-emulation/virtualbox/01-host/patches/0002-fix-build-with-python-3.10.patch
  extra-emulation/virtualbox/01-host/patches/0003-fix-pyunicode-problem.patch
  extra-emulation/virtualbox/01-host/patches/0015-Arch-Linux-vboxr0-clags.patch
  extra-emulation/virtualbox/spec
Labels: upgrade, lgtm

#4132 nvidia: upgrade to 515.65.01
  extra-x11/nvidia/spec
Labels: upgrade, lgtm

#4133 cheese: fix FTBFS by backporting a patch
  extra-gnome/cheese/autobuild/patches/0002-meson-avoid-positional-arguments-in-merge_file.patch
  extra-gnome/cheese/spec
Labels: FTBFS, lgtm

#4114 okular: rebuild for poppler update
  extra-kde/okular/spec
Labels: bug, rework, lgtm

#4134 libquvi-scripts: noarchize
  extra-libs/libquvi-scripts/autobuild/defines
  extra-libs/libquvi-scripts/spec
Labels: enhancement, lgtm

#4135 uhttpmock: drop beyond hack
  extra-libs/uhttpmock/autobuild/beyond
  extra-libs/uhttpmock/spec
Labels: FTBFS, lgtm

#4137 libquvi: fix FTBFS by importing a patch from Gentoo
  extra-libs/libquvi/autobuild/patches/0001-gentoo-autoconf-2.70.patch
  extra-libs/libquvi/spec
Labels: FTBFS, ready, lgtm

#4141 gvfs: fix FTBFS by backporting a patch
  extra-libs/gvfs/autobuild/patches/0001-build-remove-incorrect-i18n-merge-file-argument.patch
  extra-libs/gvfs/spec
Labels: FTBFS, lgtm

#4139 libtommath: disable LTO
  extra-libs/libtommath/autobuild/defines
  extra-libs/libtommath/spec
Labels: enhancement, lgtm

#4142 clit: inject CFLAGS to Makefiles
  extra-utils/clit/autobuild/patch
  extra-utils/clit/spec
Labels: enhancement, FTBFS, lgtm

#4143 kwin: drop dependency kwayland-server
  extra-kde/kwin/autobuild/defines
  extra-kde/kwin/spec
Labels: enhancement, dependencies, lgtm

#4146 nautilus: fix FTBFS by backporting a patch
  extra-gnome/nautilus/autobuild/patches/0001-build-remove-incorrect-i18n-merge-file-argument.patch
  extra-gnome/nautilus/spec
Labels: FTBFS, lgtm

#4145 kwin: add some missing dependencies
  extra-kde/kwin/autobuild/defines
  extra-kde/kwin/spec
Labels: enhancement, FTBFS, lgtm

#4147 autobuild3: update to 1.6.60
  extra-devel/autobuild3/spec
Labels: bug, upgrade, lgtm

#4148 gstreamer-0-10: fix a macro definition incompatible w/ GCC11
  extra-multimedia/gstreamer-0-10/autobuild/patch
  extra-multimedia/gstreamer-0-10/autobuild/patches/0001-fix-for-gcc11.patch
  extra-multimedia/gstreamer-0-10/spec
Labels: bug, lgtm

#4150 enblend-enfuse: fix FTBFS by explicitly specify C++14
  extra-creativity/enblend-enfuse/autobuild/prepare
  extra-creativity/enblend-enfuse/spec
Labels: FTBFS, lgtm

#4151 libgpod: add missing builddep gtk-doc
  extra-libs/libgpod/autobuild/defines
  extra-libs/libgpod/spec
Labels: dependencies, lgtm

#4153 pahole: revert to 1.22 from 1.24
  extra-utils/pahole/autobuild/defines
  extra-utils/pahole/spec
Labels: lgtm, downgrade

#4154 maruku: noarchize
  extra-doc/maruku/autobuild/defines
  extra-doc/maruku/spec
Labels: enhancement, lgtm

#4156 sass: noarchize
  extra-devel/sass/autobuild/defines
  extra-devel/sass/spec
Labels: enhancement, lgtm

#4157 cmake: backport an upstream patch to fix FindOpenMP on riscv64
  extra-devel/cmake/autobuild/patches/0001-find-openmp-from-system-paths.patch
  extra-devel/cmake/spec
Labels: enhancement, new-port, lgtm

#4160 xarchiver: disable RECONF
  extra-utils/xarchiver/autobuild/defines
  extra-utils/xarchiver/spec
Labels: FTBFS, lgtm

#4161 keybinder-3.0: add missing builddep gtk-doc and gobject-introspection
  extra-libs/keybinder-3.0/autobuild/defines
Labels: FTBFS, lgtm

#4163 cppcheck: update to 2.8
  extra-devel/cppcheck/spec
Labels: upgrade, lgtm

#4166 farstream: add builddep gtk-doc
  extra-network/farstream/autobuild/defines
  extra-network/farstream/spec
Labels: FTBFS, lgtm

#4167 chisel: new, 1.7.7
  extra-network/chisel/autobuild/build
  extra-network/chisel/autobuild/defines
  extra-network/chisel/spec
Labels: new-package, lgtm
