Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-05, with the labels that each got.

#3944 telegram-desktop: update to 3.7.3
  extra-web/telegram-desktop/autobuild/patches/0008-seek-for-Wayland-protocols-definitions-in-a-system-wide.patch
  extra-web/telegram-desktop/autobuild/patches/0009-waylandProtocols-for-qt5.patch
  extra-web/telegram-desktop/autobuild/patches/0010-Remove-Qt6-function-call.patch
  extra-web/telegram-desktop/spec
Labels: upgrade, lgtm

#3947 wine: update to 7.7
  extra-emulation/wine/spec
Labels: upgrade, lgtm

#3948 aoscdk-rs: update to 0.4.3
  extra-admin/aoscdk-rs/autobuild/patches/0001-fix-nix::libc-import.patch
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#3946 zellij: update to 0.29.1
  extra-utils/zellij/spec
Labels: upgrade, lgtm

#3955 aoscbootstrap: update to 0.2.1
  extra-utils/aoscbootstrap/spec
Labels: upgrade, lgtm

#3956 plasma-default-settings: update to 0+git20220508
  extra-misc/plasma-default-settings/spec
Labels: lgtm

#3957 aoscdk-rs: update to 0.4.7
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#3960 apt-gen-list: update to 0.6.5
  extra-admin/apt-gen-list/spec
Labels: upgrade, lgtm

#3941 Git: update to 2.36.0
  extra-vcs/git/spec
Labels: upgrade, security, lgtm, tested

#3965 autobuild3: update to 1.6.51
  extra-devel/autobuild3/spec
Labels: upgrade, lgtm, tested

#3967 winetricks: upgrade to 20220411
  extra-emulation/winetricks/autobuild/patches/0001-AOSC-disable-version-check.patch
  extra-emulation/winetricks/spec
Labels: upgrade, lgtm

#3961 curl{,+32}: Security upgrade to 7.83.1
  extra-optenv32/curl+32/spec
  extra-web/curl/spec
Labels: upgrade, security, 0day, lgtm

#3978 polymc: update to 1.2.2
  extra-games/polymc/spec
Labels: upgrade, lgtm

#3986 polymc: update to 1.3.0
  extra-games/polymc/spec
Labels: upgrade, lgtm

#3975 solaar: update to 1.1.3
  extra-utils/solaar/autobuild/defines
  extra-utils/solaar/spec
Labels: upgrade, lgtm

#3970 colord-kde: new, 0.5.0
  extra-kde/colord-kde/autobuild/defines
  extra-kde/colord-kde/autobuild/patches/0001-description-remove-broken-calibration-button.patch
  extra-kde/colord-kde/spec
Labels: new-package, lgtm

#4002 yt-dlp: update to 2022.05.18
  extra-multimedia/yt-dlp/spec
Labels: upgrade, lgtm

#4004 atm: update to 0.5.4
  extra-admin/atm/spec
Labels: upgrade, lgtm
