Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-09, with the labels that each got.

#4172 minicom: update to 2.8
  extra-utils/minicom/autobuild/defines
  extra-utils/minicom/spec
Labels: upgrade, FTBFS, lgtm

#4174 aoscdk-rs: update to 0.4.13
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#4155 icalingua++: update to 2.6.8
  extra-web/icalingua++/spec
Labels: upgrade, lgtm

#4178 rinutils: noarchize
  extra-libs/rinutils/autobuild/defines
  extra-libs/rinutils/spec
Labels: enhancement, lgtm

#4179 okteta: import a patch from Fedora to fix FTBFS
  extra-kde/okteta/autobuild/patches/0001-fedora-okteta-gcc11.patch
  extra-kde/okteta/spec
Labels: FTBFS, lgtm

#4180 tl-expected: noarchize and disable test
  extra-libs/tl-expected/autobuild/defines
  extra-libs/tl-expected/spec
Labels: enhancement, FTBFS, lgtm

#4181 microsoft-gsl: noarchize
  extra-libs/microsoft-gsl/autobuild/defines
  extra-libs/microsoft-gsl/spec
Labels: enhancement, lgtm

#4162 Update libatomic_ops to v7.6.14
  base-libs/libatomic-ops/spec
Labels: upgrade, lgtm

#4188 autobuild3: update to 1.6.62
  extra-devel/autobuild3/spec
Labels: upgrade, lgtm, tested

#4171 miniserve: update to 0.20.0
  extra-web/miniserve/spec
Labels: upgrade, lgtm

#4170 bandwhich: new, 0.20.0
  extra-network/bandwhich/autobuild/defines
  extra-network/bandwhich/spec
Labels: new-package, lgtm

#4186 wireless-regdb: upgrade to 2022.08.12, install regulatory.db
  extra-network/wireless-regdb/autobuild/build
  extra-network/wireless-regdb/spec
Labels: upgrade, lgtm

#4192 autobuild3: update to 1.6.64
  extra-devel/autobuild3/spec
Labels: bug, upgrade, lgtm

#4189 weston: update to 10.0.2
  extra-x11/weston/autobuild/defines
  extra-x11/weston/spec
Labels: upgrade, lgtm

#4193 gstreamer: adapt for riscv64
  extra-multimedia/gstreamer/autobuild/defines
Labels: FTBFS, lgtm

#4194 showmethekey: update to 1.7.3
  extra-utils/showmethekey/autobuild/defines
  extra-utils/showmethekey/spec
Labels: upgrade, lgtm

#4196 discord: update to 0.0.20
  extra-web/discord/spec
Labels: upgrade, lgtm

#4197 gstreamer: fix up for adapting for riscv64
  extra-multimedia/gstreamer/autobuild/defines
Labels: rework, lgtm

#4200 plymouth: disable gtk-3/X11 preview support
  extra-kernel/plymouth/autobuild/defines
  extra-kernel/plymouth/spec
Labels: rework, lgtm

#4201 gstreamer: disable rust binding on riscv64 now
  extra-multimedia/gstreamer/autobuild/defines
Labels: FTBFS, lgtm

#4202 boot-base: adjust standard features
  extra-bases/boot-base/autobuild/defines
  extra-bases/boot-base/spec
Labels: enhancement, lgtm

#4204 shadow: comment ERASECHAR in /etc/login.defs, fix backspace in KMSCON
  base-admin/shadow/autobuild/overrides/etc/login.defs
  base-admin/shadow/spec
Labels: bug, lgtm, tested

#4207 file-roller: add libhandy dep
  extra-gnome/file-roller/autobuild/defines
  extra-gnome/file-roller/spec
Labels: dependencies, lgtm

#4210 autobuild3: upgrade to 1.6.65
  extra-devel/autobuild3/spec
Labels: bug, upgrade, priority, lgtm

#4213 rofi: update to 1.7.5
  extra-utils/rofi/spec
Labels: upgrade, lgtm

#4209 networkmanager: fix dns issue
  extra-network/networkmanager/autobuild/defines
  extra-network/networkmanager/spec
Labels: lgtm

#4214 polymc: update to 1.4.2
  extra-games/polymc/spec
Labels: upgrade, lgtm

#4218 geoclue2: enable demo-agent
  extra-libs/geoclue2/autobuild/defines
  extra-libs/geoclue2/spec
Labels: rework, lgtm

#4217 bandwhich: update defines
  extra-network/bandwhich/autobuild/defines
  extra-network/bandwhich/spec
Labels: FTBFS, rework, lgtm

#4220 osu-lazer: update to 2022.923.1
  extra-games/osu-lazer/spec
Labels: upgrade, lgtm
