Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-11, with the labels that each got.

#4288 ncbi-blast: update to 2.13.0
  extra-scientific/ncbi-blast+/autobuild/defines
  extra-scientific/ncbi-blast+/autobuild/patches/0001-feature-enable-debug.patch
  extra-scientific/ncbi-blast+/spec
Labels: upgrade, lgtm

#4286 igv: update to 2.15.1
  extra-scientific/igv/autobuild/build
  extra-scientific/igv/autobuild/conffiles
  extra-scientific/igv/autobuild/overrides/usr/bin/igv
  extra-scientific/igv/spec
Labels: upgrade, lgtm

#4291 multipathd: upgrade to 0.9.1, fix library dlopen path
  extra-admin/multipath-tools/autobuild/prepare
  extra-admin/multipath-tools/spec
Labels: bug, upgrade, lgtm

#4296 qemu: add patch bringing virt board support for MIPS
  extra-emulation/qemu/01-shared/patches/0004-DRAFT-flygoat-MIPS-add-virt-board-support.patch
  extra-emulation/qemu/01-shared/patches/0005-upsttream-add-load_image_to_fw_cfg-to-definitions.patch
  extra-emulation/qemu/spec
Labels: enhancement, new-port, lgtm

#4287 picom: update to 10
  extra-x11/picom/spec
Labels: upgrade, lgtm

#4300 wimlib: update to 1.13.6
  extra-utils/wimlib/autobuild/defines
  extra-utils/wimlib/spec
Labels: upgrade, lgtm

#4316 lutris: update to 0.5.11
  extra-games/lutris/autobuild/defines
  extra-games/lutris/autobuild/patches/0001-AOSC-OS-adaption.patch
  extra-games/lutris/spec
Labels: enhancement, upgrade, lgtm

#4315 sunxi-tools: update to newest git
  extra-devel/sunxi-tools/autobuild/build
  extra-devel/sunxi-tools/autobuild/defines
  extra-devel/sunxi-tools/spec
Labels: lgtm

#4318 ciel: update to 3.1.3
  extra-devel/ciel/spec
Labels: bug, upgrade, has-fix, lgtm

#4320 openfpgaloader: update to 0.9.1
  extra-electronics/openfpgaloader/autobuild/defines
  extra-electronics/openfpgaloader/spec
Labels: upgrade, lgtm

#4321 libxml2: rework python2/3 bindings
  base-libs/libxml2/autobuild/beyond
  base-libs/libxml2/autobuild/defines
  base-libs/libxml2/spec
Labels: rework, lgtm

#4302 samtools: update to 1.16.1
  extra-scientific/htslib/autobuild/patches/0001-fix-so-permission.patch
  extra-scientific/htslib/spec
  extra-scientific/samtools/spec
Labels: upgrade, lgtm
