Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-12, with the labels that each got.

#4325 qemu: add static edition of loongarch64-linux-user w/ binfmt
  extra-emulation/qemu/02-static-aarch64/qemu-aarch64.conf
  extra-emulation/qemu/30-static-riscv64/qemu-riscv64.conf
  extra-emulation/qemu/33-static-loongarch64/build
  extra-emulation/qemu/33-static-loongarch64/defines
  extra-emulation/qemu/33-static-loongarch64/qemu-loongarch64.conf
  extra-emulation/qemu/99-static-meta/defines
  extra-emulation/qemu/spec
Labels: enhancement, new-port, lgtm

#4331 zerotier-one: update to 1.10.2
  extra-network/zerotier-one/spec
Labels: upgrade, lgtm

#4332 discord: update to 0.0.22
  extra-web/discord/spec
Labels: upgrade, lgtm

#4303 bread-dog: new, 0.1.0
  extra-utils/bread-dog/autobuild/defines
  extra-utils/bread-dog/spec
Labels: new-package, lgtm

#4339 prismlauncher: update to 6.0
  extra-games/prismlauncher/spec
Labels: upgrade, lgtm

#4340 mcfly: revert init mcfly from /etc/profile
  extra-utils/mcfly/autobuild/beyond
  extra-utils/mcfly/autobuild/postinst
  extra-utils/mcfly/spec
Labels: enhancement, lgtm

#4350 Community Wallpapers 2022.08.5
  extra-wallpaper/aosc-community-wallpapers/spec
Labels: upgrade, lgtm

#4353 v2ray: update to 5.1.0
  extra-network/v2ray/autobuild/build
  extra-network/v2ray/spec
Labels: upgrade, lgtm

#4354 aoscbootstrap: update to 0.2.6
  extra-utils/aoscbootstrap/spec
Labels: bug, upgrade, has-fix, priority, lgtm
