Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-02, with the labels that each got.

#3780 wine: update to 7.1
  extra-emulation/wine/spec
Labels: upgrade, lgtm

#3796 systemd-boot-friend: update to 0.17.0
  extra-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm

#3782 fd: update to 8.3.2
  extra-utils/fd/spec
Labels: upgrade, lgtm

#3784 util-base: add fd
  extra-bases/util-base/autobuild/defines
  extra-bases/util-base/spec
Labels: enhancement, lgtm

#3786 bat: update to 0.19.0
  extra-utils/bat/spec
Labels: upgrade, lgtm

#3787 vaultwarden: update to 1.24.0
  extra-security/vaultwarden/autobuild/defines
  extra-security/vaultwarden/spec
Labels: upgrade, lgtm

#3788 adobe-source-han-serif: update to 2.001
  extra-fonts/adobe-source-han-serif/spec
Labels: upgrade, lgtm

#3789 proxychains-ng: update to 4.16
  extra-network/proxychains-ng/spec
Labels: upgrade, lgtm

#3790 zola: update to 0.15.3
  extra-web/zola/spec
Labels: upgrade, lgtm

#3804 gdal: ftbfs rework
  extra-gis/gdal/autobuild/beyond
  extra-gis/gdal/autobuild/build
  extra-gis/gdal/autobuild/defines
  extra-gis/gdal/autobuild/patches/0002-fix-ftbfs-by-unsupported-2to3-set.patch
  extra-gis/gdal/autobuild/prepare
  extra-gis/gdal/spec
Labels: rework, lgtm

#3805 aoscdk-rs: update to 0.3.5
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#3791 yt-dlp: update to 2022.01.21
  extra-multimedia/yt-dlp/spec
Labels: upgrade, lgtm

#3795 alacritty: update to 0.10.0
  extra-utils/alacritty/spec
Labels: upgrade, lgtm

#3810 systemd-boot-friend: update to 0.18.0
  extra-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm

#3785 dolphin-emu: update to 5.0+git20211101
  extra-games/dolphin-emu/spec
Labels: upgrade, lgtm

#3814 autobuild: update to 1.6.47
  extra-devel/autobuild3/spec
Labels: upgrade, lgtm

#3811 inkscape: update to 1.1.2
  extra-creativity/inkscape/spec
Labels: upgrade, lgtm

#3832 ciel: disable LTO and do not use clang on RISC-V 64
  extra-devel/ciel/autobuild/defines
Labels: new-port, lgtm

#3824 vscode: update to 1.64.2
  extra-editors/vscode/spec
Labels: upgrade, lgtm

#3831 linux-kernel: add a generic kernel that supports mainlined boards (HFUs)
  extra-kernel/linux-kernel/autobuild/build
  extra-kernel/linux-kernel/autobuild/riscv64/config
Labels: new-port, lgtm

#3827 shadowsocks-rust: update to 1.13.2
  extra-network/shadowsocks-rust/spec
Labels: upgrade, lgtm

#3830 nbd: update to 3.23 and fix PKGSEC QA problem
  extra-network/nbd/autobuild/defines
  extra-network/nbd/spec
Labels: upgrade, lgtm

#3835 discord: update to 0.0.17
  extra-web/discord/spec
Labels: upgrade, lgtm

#3834 p7zip: fix ftbfs
  extra-utils/p7zip/autobuild/build
  extra-utils/p7zip/autobuild/patches/15-fix-gcc11-build.patch
  extra-utils/p7zip/autobuild/patches/series
  extra-utils/p7zip/spec
Labels: bug, FTBFS, lgtm

#3828 wine: update to 7.2
  extra-emulation/wine/spec
Labels: upgrade, lgtm

#3836 fcitx5-pinyin-moegirl: update to 20220218
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#3837 meta: add riscv64 to PR template
  .github/PULL_REQUEST_TEMPLATE
Labels: new-port, lgtm

#3839 gnu-efi: update to 3.0.14
  extra-devel/gnu-efi/autobuild/build
  extra-devel/gnu-efi/autobuild/defines
  extra-devel/gnu-efi/spec
Labels: upgrade, new-port, lgtm

#3845 zellij: new, 0.25.0
  extra-utils/zellij/autobuild/beyond
  extra-utils/zellij/autobuild/defines
  extra-utils/zellij/spec
Labels: new-package, lgtm

#3847 starship: add postinst, remove PKGSUG
  extra-utils/starship/autobuild/defines
  extra-utils/starship/autobuild/postinst
  extra-utils/starship/spec
Labels: enhancement, rework, lgtm

#3848 bsc: new, 2022.01
  extra-electronics/bsc/autobuild/build
  extra-electronics/bsc/autobuild/defines
  extra-electronics/bsc/autobuild/prepare
  extra-electronics/bsc/spec
Labels: new-package, lgtm

#3853 aosc-os-presets-base: fix FTBFS
  extra-misc/aosc-os-presets-base/autobuild/defines
Labels: FTBFS, lgtm

#3855 go: support riscv64
  extra-go/go/autobuild/build
  extra-go/go/autobuild/defines
Labels: new-port, lgtm

#3854 linux-kernel: update to 5.16.11
  extra-kernel/linux-kernel/autobuild/amd64/config
  extra-kernel/linux-kernel/autobuild/arm64/config
  extra-kernel/linux-kernel/autobuild/defines
  extra-kernel/linux-kernel/autobuild/loongson3/config
  extra-kernel/linux-kernel/autobuild/ppc64el/config
  extra-kernel/linux-kernel/autobuild/riscv64/config
  extra-kernel/linux-kernel/spec
Labels: upgrade, lgtm

#3856 linux+kernel: bump to 5.16.11
  extra-kernel/linux+kernel/autobuild/defines
  extra-kernel/linux+kernel/spec
Labels: upgrade, rework, lgtm

#3857 expat: update to 2.4.6
  base-libs/expat/spec
Labels: security, lgtm

#3833 bear: update to 3.0.18
  extra-devel/bear/spec
Labels: upgrade, lgtm
