Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2022-03, with the labels that each got.

#3842 i2pd: update to 2.41.0
  extra-web/i2pd/spec
Labels: upgrade, lgtm

#3871 fcitx5-pinyin-moegirl: update to 20220314
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#3875 pushpkg: update to 0+git20220319
  extra-devel/pushpkg/spec
Labels: upgrade, lgtm

#3874 xxhash: update to 0.8.1
  extra-libs/xxhash/spec
Labels: upgrade, lgtm

#3885 zotero: update to 6.0.3
  extra-productivity/zotero/spec
Labels: upgrade, lgtm

#3886 dog: rebuild for rust update
  extra-network/dog/spec
Labels: rework, lgtm

#3890 kde-base: fix dependencies
  extra-bases/kde-base/autobuild/defines
  extra-bases/kde-base/spec
Labels: bug, rework, lgtm

#3893 rbw: new, 1.4.3
  extra-security/rbw/autobuild/beyond
  extra-security/rbw/autobuild/defines
  extra-security/rbw/autobuild/patches/0001-use-native-tls-to-fix-build-in-power-and-loongson.patch
  extra-security/rbw/spec
Labels: lgtm

#3892 yt-dlp: update to 2022.03.08.1
  extra-multimedia/yt-dlp/spec
Labels: upgrade, lgtm
