Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-10, with the labels that each got.

#4750 linux-kernel-lts: (mips64r6el) refresh config to make build pass
  runtime-kernel/linux-kernel-lts/autobuild/mips64r6el/config
Labels: rework

#4752 discord: update to 0.0.31
  app-web/discord/spec
Labels: upgrade

#4755 ciel: rebuild for OpenSSL 3.1.1 (rework)
  app-devel/ciel/spec
Labels: rework

#4757 openssl: drop nvidia, cuda from PKGBREAK
  runtime-cryptography/openssl/autobuild/defines
  runtime-cryptography/openssl/spec
Labels: rework

#4753 yt-dlp: update to 2023.09.24
  app-multimedia/yt-dlp/spec
Labels: upgrade

#4760 openssl: remove powershell from PKGBREAK list
  runtime-cryptography/openssl/autobuild/defines
  runtime-cryptography/openssl/spec
Labels: rework

#4756 aoscbootstrap: update to 0.3.1
  app-utils/aoscbootstrap/spec
Labels: upgrade

#4763 telegram-desktop: add patch to revert hidpi handling behavior
  app-web/telegram-desktop/autobuild/patches/1001-revert-hidpi-handling.patch
  app-web/telegram-desktop/spec
Labels: enhancement, has-fix

#4761 oma: update to 1.0.8
  app-admin/oma/spec
Labels: upgrade

#4769 fcitx5-pinyin-moegirl: upgrade to 20231014
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#4773 editor-base: adjust dependencies
  meta-bases/editor-base/autobuild/defines
  meta-bases/editor-base/spec
Labels: dependencies

#4770 feishin: update to 0.4.1
  app-multimedia/feishin/spec
Labels: upgrade

#4775 wpmeta: new, 0.1.0
  app-utils/wpmeta/autobuild/defines
  app-utils/wpmeta/spec
Labels: new-package

#4778 linux-kernel: (mips64r6el) update config for 6.4.11
  runtime-kernel/linux-kernel/autobuild/mips64r6el/config
Labels: rework, cip-pilot

#4781 discord: update to 0.0.32
  app-web/discord/spec
Labels: upgrade

#4768 texlive: ship shared libraries
  app-doc/texlive/autobuild/build
  app-doc/texlive/spec
Labels: enhancement

#4782 fend: update to 1.3.0
  app-utils/fend/autobuild/patches/0001-Fix-ppc64el-and-loongson3-fend-console.patch
  app-utils/fend/spec
Labels: upgrade

#4780 dua: new, 2.20.1
  app-utils/dua/autobuild/defines
  app-utils/dua/spec
Labels: new-package

#4779 Template Update 20231016
  .github/PULL_REQUEST_TEMPLATE
Labels: enhancement, rfc, meta

#4785 oma: update to 1.1.6
  app-admin/oma/spec
Labels: upgrade

#4783 autobuild3: update to 1.7
  app-devel/autobuild3/spec
Labels: upgrade

#4796 serf: (Gentoo patches) fix compatibility with OpenSSL 3
  runtime-web/serf/autobuild/patches/0001-Gentoo-serf-1.3.9-openssl-3-errgetfunc.patch
  runtime-web/serf/autobuild/patches/0002-Gentoo-serf-1.3.9-openssl-3-bio-ctrl.patch
  runtime-web/serf/spec
Labels: abi-break, has-fix, priority

#4792 bash-startup: update to 0.5.2.2
  runtime-data/bash-startup/spec
Labels: upgrade, has-fix

#4791 dpkg: update to 1.21.22
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-loongarch64-recognition.patch.loongarch64
  app-admin/dpkg/spec
Labels: upgrade, new-port
