Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-02, with the labels that each got.

#4395 zellij: update to 0.34.4
  extra-utils/zellij/spec
Labels: upgrade, lgtm

#4398 aoscdk-rs: update to 0.5.4
  extra-admin/aoscdk-rs/spec
Labels: upgrade, has-fix, lgtm

#4400 MIPS64r6el Bring Up Rework (2)
  base-admin/dpkg/01-update-alternatives/build
  base-admin/dpkg/spec
Labels: has-fix, rework, lgtm

#4404 yt-dlp: update to 2023.01.06
  extra-multimedia/yt-dlp/spec
Labels: upgrade, lgtm

#4410 mesa: disable LTO to prevent artifact with LLVM 15 + AMDGPU
  extra-libs/mesa/autobuild/defines
  extra-libs/mesa/spec
Labels: bug, has-fix, priority, lgtm, tested, hardware-support

#4397 v2raya: new, 2.0.1
  extra-network/v2raya/autobuild/beyond
  extra-network/v2raya/autobuild/build
  extra-network/v2raya/autobuild/conffiles
  extra-network/v2raya/autobuild/defines
  extra-network/v2raya/autobuild/overrides/etc/default/v2raya
  extra-network/v2raya/autobuild/overrides/usr/lib/systemd/system/v2raya.service
  extra-network/v2raya/autobuild/overrides/usr/lib/systemd/user/v2raya-lite.service
  extra-network/v2raya/spec
Labels: new-package, lgtm

#4414 Revert "nano: drop, orphaned"
  base-editors/nano/autobuild/alternatives
  base-editors/nano/autobuild/beyond
  base-editors/nano/autobuild/defines
  base-editors/nano/autobuild/overrides/etc/nanorc
  base-editors/nano/spec
Labels: has-fix, priority, lgtm

#4417 MIPS64r6el Bring Up Rework (4)
  base-devel/llvm/01-runtime/defines
Labels: rework, new-port, lgtm, cip-pilot

#4420 discord: update to 0.0.25
  extra-web/discord/autobuild/build
  extra-web/discord/spec
Labels: upgrade, lgtm

#4421 fcitx5-pinyin-moegirl: update to 20230214
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#4424 kernel-tools: update to 6.0.2
  extra-kernel/kernel-tools/spec
Labels: bug, upgrade, lgtm

#4430 pushpkg: update to 0+git20230220
  extra-devel/pushpkg/autobuild/build
  extra-devel/pushpkg/spec
Labels: upgrade, lgtm

#4425 systemd-boot-friend: update to 0.25.0
  extra-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm

#4431 bcache-tools: fix typo `Bcachefs` => `Bcache`
  extra-admin/bcache-tools/autobuild/defines
  extra-admin/bcache-tools/spec
Labels: bug, lgtm

#4402 fish: update to 3.6.0
  extra-shells/fish/spec
Labels: upgrade, lgtm

#4439 thermald: update to 2.5.2
  extra-admin/thermald/spec
Labels: upgrade, has-fix, lgtm, hardware-support

#4429 aoscdk-rs: update to 0.5.5
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#4385 dpkg: update to 1.21.18
  base-admin/dpkg/01-update-alternatives/defines
  base-admin/dpkg/02-dpkg/defines
  base-admin/dpkg/spec
Labels: upgrade, lgtm

#4432 yt-dlp: update to 2023.02.17
  extra-multimedia/yt-dlp/spec
Labels: upgrade, lgtm

#4428 v2ray: update to 5.3.0
  extra-network/v2ray/spec
Labels: upgrade, lgtm

#4440 prismlauncher: update to 6.3
  extra-games/prismlauncher/spec
Labels: upgrade, lgtm

#4008 systemd-usb-gadget: new, newest git
  extra-admin/systemd-usb-gadget/autobuild/build
  extra-admin/systemd-usb-gadget/autobuild/defines
  extra-admin/systemd-usb-gadget/spec
Labels: new-package, lgtm

#4212 grub: backport a patch to fix riscv64 build
  extra-admin/grub/autobuild/patches/0225-RISC-V-adjust-march-flags-for-binutils-2.28.patch
  extra-admin/grub/spec
Labels: FTBFS, lgtm

#4322 memtester: update to 4.5.1 and adapt to ABTYPE=self
  extra-benchmarks/memtester/autobuild/beyond
  extra-benchmarks/memtester/autobuild/build
  extra-benchmarks/memtester/autobuild/defines
  extra-benchmarks/memtester/spec
Labels: enhancement, upgrade, lgtm

#4427 zerotier-one: update to 1.10.3
  extra-network/zerotier-one/spec
Labels: upgrade, lgtm
