Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-11, with the labels that each got.

#4803 feishin: update to 0.5.1
  app-multimedia/feishin/spec
Labels: upgrade

#4810 gtk-3: migrate to Meson
  desktop-gnome/gtk-3/autobuild/defines
  desktop-gnome/gtk-3/spec
Labels: bug, has-fix

#4812 bash-startup: update to 0.5.2.4
  runtime-data/bash-startup/spec
Labels: upgrade

#4808 nvidia: upgrade to 545.29.02 - prepare for kernel 6.6
  runtime-display/nvidia/autobuild/build
  runtime-display/nvidia/autobuild/build-optenv32
  runtime-display/nvidia/spec
Labels: upgrade

#4815 discord: update to 0.0.34
  app-web/discord/spec
Labels: upgrade

#4813 nvidia: fix checksum for arm64
  runtime-display/nvidia/spec
Labels: rework

#4818 telegram-desktop: update to 4.11.6
  app-web/telegram-desktop/autobuild/patches/0004-core_settings-use-system-window-decoration-by-defaul.patch
  app-web/telegram-desktop/autobuild/patches/1000-tdesktop-fix-build-qt5.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#4819 fcitx5-pinyin-moegirl: update to 20231114
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#4822 discord: update to 0.0.35
  app-web/discord/spec
Labels: upgrade

#4825 lychee: new, 0.13.0
  app-web/lychee/autobuild/defines
  app-web/lychee/spec
Labels: new-package

#4830 hyperfine: new, 1.18.0
  app-devel/hyperfine/autobuild/defines
  app-devel/hyperfine/spec
Labels: new-package

#4829 gitoxide: update to 0.31.1
  app-vcs/gitoxide/spec
Labels: upgrade

#4828 pushpkg: fix competion
  app-devel/pushpkg/autobuild/build
  app-devel/pushpkg/spec
Labels: bug, has-fix

#4832 upx: update to 4.2.1
  app-devel/upx/autobuild/build
  app-devel/upx/autobuild/defines
  app-devel/upx/autobuild/prepare
  app-devel/upx/spec
Labels: upgrade

#4833 oma: update to 1.1.8
  app-admin/oma/spec
Labels: upgrade

#4837 telegram-desktop: update to 4.11.8
  app-web/telegram-desktop/spec
Labels: upgrade

#4840 openvpn: update to 2.5.2
  app-network/openvpn/spec
Labels: upgrade

#4843 discord: update to 0.0.36
  app-web/discord/spec
Labels: upgrade

#4841 cryptography: update to 40.0.0
  lang-python/cryptography/autobuild/defines
  lang-python/cryptography/spec
Labels: upgrade

#4842 ripgrep: update to 14.0.3
  app-utils/ripgrep/autobuild/beyond
  app-utils/ripgrep/autobuild/patches/0001-allow-lower-rustc-version-compile.patch
  app-utils/ripgrep/autobuild/patches/0001-enable-lto.patch
  app-utils/ripgrep/spec
Labels: upgrade

#4845 pushpkg: update to 0+git20231129
  app-devel/pushpkg/autobuild/build
  app-devel/pushpkg/spec
Labels: upgrade
