Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-08, with the labels that each got.

#4645 ouch: new, 0.4.1
  app-utils/ouch/autobuild/defines
  app-utils/ouch/spec
Labels: new-package

#4642 htop: update to 3.2.2 and backport a fix for offline CPU display
  app-admin/htop/autobuild/patches/0001-BACKPORT-Remove-LXC-special-handling-for-the-CPU-count.patch
  app-admin/htop/spec
Labels: bug, has-fix

#4647 oma: new, 1.0.1
  app-admin/oma/autobuild/beyond
  app-admin/oma/autobuild/defines
  app-admin/oma/spec
Labels: new-package

#4648 squashfs-tools-ng: new, 1.2.0
  app-admin/squashfs-tools-ng/autobuild/defines
  app-admin/squashfs-tools-ng/spec
Labels: new-package

#4650 rbw: update to 1.8.3
  app-utils/rbw/spec
Labels: upgrade

#4649 oma, update to 1.0.3
  app-admin/oma/spec
Labels: upgrade, has-fix

#4655 pydantic: disable ABSPLITDBG for !amd64
  lang-python/pydantic/autobuild/defines
Labels: rework

#4654 oma: update to 1.0.4
  app-admin/oma/spec
Labels: upgrade, has-fix

#4656 virtualbox: upgrade to 7.0.10
  app-virtualization/virtualbox/spec
Labels: upgrade

#4659 jetbrains-mono: new, 2.304
  desktop-fonts/jetbrains-mono/autobuild/build
  desktop-fonts/jetbrains-mono/autobuild/defines
  desktop-fonts/jetbrains-mono/spec
Labels: new-package

#4658 yt-dlp: update to 2023.07.06
  app-multimedia/yt-dlp/spec
Labels: upgrade

#4660 virtualbox: fix kernel modules on 6.4.10
  app-virtualization/virtualbox/01-host/patches/0011-kernel-6-4-10-include-gso-h.patch
  app-virtualization/virtualbox/01-host/postinst.in
  app-virtualization/virtualbox/01-host/prepare
  app-virtualization/virtualbox/01-host/prerm
  app-virtualization/virtualbox/01-host/prerm.in
  app-virtualization/virtualbox/spec
Labels: has-fix

#4664 blender: rework building on arm64/amd64
  app-creativity/blender/autobuild/defines
  app-creativity/blender/autobuild/patches/0001-cmake-fix-embree-linking.patch
  app-creativity/blender/autobuild/patches/0001-cmake-link-against-embree-avx512.patch
  app-creativity/blender/spec
Labels: bug, ftbfs, rework

#4668 fcitx5-pinyin-moegirl: update to 20230814
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#4670 jetbrains-mono: fix CHKUPDATE
  desktop-fonts/jetbrains-mono/spec
Labels: rework

#4673 fail2ban: update to 1.0.2
  app-admin/fail2ban/autobuild/defines
  app-admin/fail2ban/autobuild/overrides/etc/fail2ban/paths-aosc.conf
  app-admin/fail2ban/autobuild/patches/0002-use-aosc-paths.patch
  app-admin/fail2ban/autobuild/prepare
  app-admin/fail2ban/spec
Labels: upgrade

#4672 python-systemd: update to 235
  lang-python/python-systemd/spec
Labels: upgrade

#4678 oma: update to 1.0.7
  app-admin/oma/spec
Labels: upgrade

#4675 lldpd: new, 1.0.17
  app-network/lldpd/autobuild/defines
  app-network/lldpd/autobuild/postinst
  app-network/lldpd/spec
Labels: new-package

#4680 taskwarrior: new, 2.6.2
  app-productivity/taskwarrior/autobuild/defines
  app-productivity/taskwarrior/spec
Labels: new-package

#4682 acpica-unix: update to 20230628
  app-devel/acpica-unix/spec
Labels: upgrade

#4677 edid-decode: new, 0.1+git20230804
  app-utils/edid-decode/autobuild/build
  app-utils/edid-decode/autobuild/defines
  app-utils/edid-decode/spec
Labels: new-package

#4684 hw-probe: new, 1.6.5
  app-utils/hw-probe/autobuild/build
  app-utils/hw-probe/autobuild/defines
  app-utils/hw-probe/spec
Labels: new-package

#4688 aoscdk-rs: update to 0.9.5
  app-admin/aoscdk-rs/spec
Labels: upgrade

#4689 gitoxide: update to 0.29.0
  app-vcs/gitoxide/spec
Labels: upgrade

#4685 binutils: update to 2.41
  core-devel/binutils/autobuild/patches/0001-MIPS-default-output-as-r6-when-default-target-as-r6.patch
  core-devel/binutils/autobuild/patches/1001-Debian-gold-mips.patch.loongson
  core-devel/binutils/autobuild/patches/1002-Debian-mips64-default-n64.patch.loongson
  core-devel/binutils/autobuild/patches/1002-Debian-mips64-default-n64.patch.loongson2f
  core-devel/binutils/autobuild/patches/1002-Debian-mips64-default-n64.patch.loongson3
  core-devel/binutils/spec
Labels: upgrade

#4692 feishin: new, 0.3.0
  app-multimedia/feishin/autobuild/amd64/build
  app-multimedia/feishin/autobuild/build
  app-multimedia/feishin/autobuild/defines
Labels: new-package

#4674 less: update to version 643
  app-utils/less/autobuild/defines
  app-utils/less/autobuild/prepare
  app-utils/less/spec
Labels: upgrade
