Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-09, with the labels that each got.

#4697 discord: update to 0.0.29
  app-web/discord/spec
Labels: upgrade

#4696 prismlauncher: update to 7.2
  app-games/prismlauncher/spec
Labels: upgrade

#4690 zotero: update to 6.0.26
  app-productivity/zotero/spec
Labels: upgrade

#4704 aosc-logos: update to 11, add jinkela and koshki logos
  runtime-data/aosc-logos/autobuild/overrides/usr/bin/aosc-logo
  runtime-data/aosc-logos/autobuild/overrides/usr/share/aosc-logos/jinkela
  runtime-data/aosc-logos/autobuild/overrides/usr/share/aosc-logos/koshki
  runtime-data/aosc-logos/spec
Labels: upgrade

#4716 mosh: update to 1.4.0
  app-network/mosh/autobuild/beyond
  app-network/mosh/autobuild/defines
  app-network/mosh/spec
Labels: upgrade

#4717 ciel: add squashfs-tools dep
  app-devel/ciel/autobuild/defines
  app-devel/ciel/spec
Labels: has-fix, dependencies

#4719 fcitx5-pinyin-moegirl: update to 20230914
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#4722 bash-config: update to 0.5.1
  runtime-data/bash-startup/spec
Labels: upgrade

#4723 aosc-os-repository-data: update to 20230828
  runtime-data/aosc-os-repository-data/spec
Labels: upgrade

#4727 autobuild3: update to 1.6.104
  app-devel/autobuild3/spec
Labels: upgrade

#4731 mcfly: fix postinst instruction for fish
  app-utils/mcfly/autobuild/postinst
  app-utils/mcfly/spec
Labels: rework

#4724 qbittorrent: add nox build recipe
  app-web/qbittorrent/01-gui/defines
  app-web/qbittorrent/01-gui/patches/0001-Disable-strip-during-build-time.patch
  app-web/qbittorrent/01-gui/prepare
  app-web/qbittorrent/02-nox/defines
  app-web/qbittorrent/02-nox/prepare
  app-web/qbittorrent/spec
Labels: enhancement

#4736 snapper: update to 0.10.6
  app-admin/snapper/autobuild/defines
  app-admin/snapper/spec
Labels: upgrade

#4741 dunst: update to 1.9.2
  app-utils/dunst/spec
Labels: upgrade

#4742 feishin: update to 0.4.0
  app-multimedia/feishin/autobuild/build
  app-multimedia/feishin/spec
Labels: upgrade

#4740 Go 1.21 Rework
  lang-golang/go/autobuild/build
  lang-golang/go/autobuild/build.stage2
  lang-golang/go/spec
Labels: rework

#4743 racket: update to 8.10
  lang-lisp/racket/autobuild/defines
  lang-lisp/racket/spec
Labels: upgrade
