Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-01, with the labels that each got.

#4355 prismlauncher: update to 6.1
  extra-games/prismlauncher/spec
Labels: upgrade, lgtm

#4359 perl-net-ssleay: rebuild for Perl 5.36
  extra-perl/perl-net-ssleay/spec
Labels: abi-break, lgtm

#4358 wezterm: use --distro-defaults flag to disable self check update
  extra-utils/wezterm/autobuild/defines
  extra-utils/wezterm/spec
Labels: enhancement, has-fix, lgtm

#4363 discord: update to 0.0.23
  extra-web/discord/autobuild/build
  extra-web/discord/spec
Labels: upgrade, lgtm

#4364 dbus-deviation: add sphinx as build dependency
  extra-python/dbus-deviation/autobuild/defines
  extra-python/dbus-deviation/spec
Labels: rework, lgtm

#4367 discord: update to 0.0.24
  extra-web/discord/autobuild/build
  extra-web/discord/spec
Labels: upgrade, lgtm

#4368 fcitx5-pinyin-moegirl: update to 20230114
  extra-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#4366 reptyr: update to 0.9.0
  extra-utils/reptyr/spec
Labels: upgrade, lgtm

#4377 gnome-calculator: add libadwaita dep
  extra-gnome/gnome-calculator/autobuild/defines
  extra-gnome/gnome-calculator/spec
Labels: bug, dependencies, lgtm

#4381 vscode: update to 1.74.3
  extra-editors/vscode/autobuild/overrides/usr/bin/vscode
  extra-editors/vscode/autobuild/overrides/usr/share/applications/vscode-url-handler.desktop
  extra-editors/vscode/autobuild/overrides/usr/share/applications/vscode.desktop
  extra-editors/vscode/autobuild/overrides/usr/share/bash-completion/completions/vscode
  extra-editors/vscode/autobuild/overrides/usr/share/zsh/vendor-completions/_vscode
  extra-editors/vscode/autobuild/postinst.in
  extra-editors/vscode/autobuild/prepare
  extra-editors/vscode/autobuild/prerm
  extra-editors/vscode/spec
Labels: upgrade, lgtm

#4375 git: security update to 2.39.1
  extra-vcs/git/spec
Labels: upgrade, security, lgtm

#4374 httpd: security update to 2.4.55
  extra-web/httpd/spec
Labels: upgrade, security, lgtm

#4380 helix: update to 22.12
  extra-editors/helix/spec
Labels: upgrade, lgtm

#4389 aoscdk-rs: update to 0.5.3
  extra-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#4387 nnn: update to 4.7
  extra-utils/nnn/spec
Labels: upgrade, lgtm

#4396 clash-premium: update to 2023.01.29
  extra-network/clash-premium/autobuild/defines
  extra-network/clash-premium/spec
Labels: upgrade, new-port, lgtm, tested
