Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-04, with the labels that each got.

#4475 discord: update to 0.0.26
  app-web/discord/autobuild/build
  app-web/discord/spec
Labels: upgrade, lgtm

#4479 sddm: tmpfiles: disable auto cleanup for /var/lib/sddm
  desktop-displaymanagers/sddm/autobuild/overrides/usr/lib/tmpfiles.d/sddm.conf
  desktop-displaymanagers/sddm/spec
Labels: bug, has-fix, lgtm

#4481 typst: new, 23.03.28
  app-doc/typst/autobuild/defines
  app-doc/typst/spec
Labels: new-package, lgtm

#4480 aoscbootstrap: update to 0.2.9
  app-utils/aoscbootstrap/spec
Labels: upgrade, lgtm

#4469 rbw: update to 1.7.0
  app-utils/rbw/autobuild/defines
  app-utils/rbw/autobuild/patches/0001-use-native-tls-to-fix-build-in-power-and-loongson.patch
  app-utils/rbw/spec
Labels: upgrade, lgtm

#4464 libratbag: update to 0.17
  runtime-devices/libratbag/spec
Labels: upgrade, lgtm

#4489 systemd-boot-friend: update to 0.25.2
  app-admin/systemd-boot-friend/spec
Labels: upgrade, lgtm

#4498 systemd: enable hibernation support, disable in sleep.conf by default
  app-admin/systemd/autobuild/defines
  app-admin/systemd/autobuild/patches/0003-sleep-conf-disable-hibernation-by-default.patch
  app-admin/systemd/spec
Labels: enhancement, lgtm

#4495 etckeeper: new, 1.18.20
  app-admin/etckeeper/autobuild/build
  app-admin/etckeeper/autobuild/defines
  app-admin/etckeeper/autobuild/postinst
  app-admin/etckeeper/spec
Labels: new-package, lgtm

#4502 fwupd: (amd64, arm64) drop more invalid options
  app-admin/fwupd/autobuild/defines
Labels: FTBFS, rework, lgtm

#4494 lsof: update to 4.98.0
  app-utils/lsof/autobuild/beyond
  app-utils/lsof/autobuild/build
  app-utils/lsof/autobuild/defines
  app-utils/lsof/spec
Labels: upgrade, lgtm

#4493 parted: fix an issue where partition maps could not be edited
  app-admin/parted/autobuild/defines
  app-admin/parted/autobuild/patches/0001-Fedora-0001-maint-post-release-administrivia.patch
  app-admin/parted/autobuild/patches/0002-Fedora-0002-parted-add-type-command.patch
  app-admin/parted/autobuild/patches/0003-Fedora-0003-libparted-add-swap-flag-for-DASD-label.patch
  app-admin/parted/autobuild/patches/0004-Fedora-0004-parted-Reset-the-filesystem-type-when-changing-the-i.patch
  app-admin/parted/autobuild/patches/0005-Fedora-0005-tests-t3200-type-change-now-passes.patch
  app-admin/parted/autobuild/patches/0006-Fedora-0006-libparted-Fix-check-for-availability-of-_type_id-fun.patch
  app-admin/parted/autobuild/patches/0007-Fedora-0007-parted-Simplify-code-for-json-output.patch
  app-admin/parted/autobuild/patches/0008-Fedora-0008-disk.in.h-Remove-use-of-enums-with-define.patch
  app-admin/parted/autobuild/patches/0009-Fedora-0009-libparted-Fix-handling-of-gpt-partition-types.patch
  app-admin/parted/autobuild/patches/0010-Fedora-0010-tests-Add-a-libparted-test-for-ped_partition_set_sys.patch
  app-admin/parted/autobuild/patches/0011-Fedora-0011-libparted-Fix-handling-of-msdos-partition-types.patch
  app-admin/parted/autobuild/patches/0012-Fedora-0012-tests-Add-a-libparted-test-for-ped_partition_set_sys.patch
  app-admin/parted/autobuild/patches/0013-Fedora-0013-show-GPT-UUIDs-in-JSON-output.patch
  app-admin/parted/autobuild/patches/0014-Fedora-0014-gpt-Add-no_automount-partition-flag.patch
  app-admin/parted/autobuild/patches/0015-Fedora-0015-tests-XFS-requires-a-minimum-size-of-300M.patch
  app-admin/parted/autobuild/patches/0016-Fedora-0016-libparted-Fix-problem-with-creating-1s-partitions.patch
  app-admin/parted/autobuild/patches/0017-Fedora-0017-tests-Fixing-libparted-test-framework-usage.patch
  app-admin/parted/autobuild/patches/0018-Fedora-0018-filesys-Check-for-null-from-close_fn.patch
  app-admin/parted/autobuild/patches/0019-Fedora-0019-libparted-Fix-potential-NULL-dereference-in-ped_disk.patch
  app-admin/parted/autobuild/patches/0020-Fedora-0020-strlist-Handle-realloc-error-in-wchar_to_str.patch
  app-admin/parted/autobuild/patches/0021-Fedora-0021-ui-Add-checks-for-prompt-being-NULL.patch
  app-admin/parted/autobuild/patches/0022-Fedora-0022-tests-Fix-formatting-and-snprintf-warnings-in-tests.patch
  app-admin/parted/autobuild/patches/0023-Fedora-0023-parted-Fix-ending-sector-location-when-using-kibi-IE.patch
  app-admin/parted/spec
Labels: bug, has-fix, lgtm, tested

#4492 gparted: update to 1.5.0
  app-admin/gparted/autobuild/patch
  app-admin/gparted/spec
Labels: upgrade, lgtm

#4504 fcitx5-pinyin-moegirl: update to 20230414
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#4508 mpd: enable pipewire support
  app-multimedia/mpd/autobuild/defines
  app-multimedia/mpd/spec
Labels: enhancement, lgtm

#4513 dnsmasq: Update to 2.89; Fix CVE-2023-28450
  app-network/dnsmasq/autobuild/patches/0001-Upstream-Git-CVE-2023-28450.patch
  app-network/dnsmasq/spec
Labels: upgrade, security, lgtm

#4505 openvpn: update to 2.5.1
  app-network/openvpn/spec
Labels: upgrade, lgtm

#4520 discord: update to 0.0.27
  app-web/discord/spec
Labels: upgrade, lgtm

#4523 aoscdk-rs: update to 0.6.0
  app-admin/aoscdk-rs/spec
Labels: upgrade, lgtm

#4524 powerpc-utils: drop unused snap utility
  app-admin/powerpc-utils/autobuild/beyond
  app-admin/powerpc-utils/spec
Labels: rework, lgtm, file-conflict

#4526 libdispatch: (AUR patch) disable -Werror
  runtime-common/libdispatch/autobuild/patches/0001-AUR-remove-werror.patch
  runtime-common/libdispatch/spec
Labels: FTBFS, has-fix, lgtm

#4528 cryptography: (loongson3) fix build
  lang-python/cryptography/autobuild/defines
Labels: FTBFS, has-fix, lgtm

#4529 minetest: (riscv64) use lua (no luajit support)
  app-games/minetest/autobuild/defines
Labels: FTBFS, has-fix, lgtm

#4531 hook-uname: register mips64r6el
  app-devel/hook-uname/autobuild/build
  app-devel/hook-uname/spec
Labels: enhancement, new-port, lgtm

#4521 treevsrepo: new, 0.3.3
  app-devel/treevsrepo/autobuild/defines
  app-devel/treevsrepo/spec
Labels: new-package, lgtm
