Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-05, with the labels that each got.

#4535 meta: add build order template to PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
Labels: lgtm, workflow

#4536 topgrade: add new package
  app-admin/topgrade/autobuild/defines
  app-admin/topgrade/autobuild/patches/0001-disable-firmware-and-apt-updates.patch
  app-admin/topgrade/spec
Labels: new-package, lgtm

#4539 mpv: restore .desktop, add dependencies
  app-multimedia/mpv/autobuild/build
  app-multimedia/mpv/autobuild/defines
  app-multimedia/mpv/spec
Labels: enhancement, lgtm

#4544 autobuild3: add config dep
  app-devel/autobuild3/autobuild/defines
  app-devel/autobuild3/spec
Labels: dependencies, rework, lgtm

#4551 pipewire: update to 0.3.71
  app-multimedia/pipewire/spec
Labels: upgrade, lgtm

#4552 fcitx5-pinyin-moegirl: upgrade to 20230514
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade, lgtm

#4554 dracut: only hide Plymouth splash upon media check failure
  app-admin/dracut/autobuild/patches/0001-dmsquash-live-Do-not-hide-splash-unless-media-check-fails.patch
  app-admin/dracut/spec
Labels: enhancement, lgtm

#4556 lxdm: fix dependencies
  desktop-lxde/lxdm/autobuild/defines
  desktop-lxde/lxdm/autobuild/overrides/usr/lib/systemd/system/lxdm.service
  desktop-lxde/lxdm/spec
Labels: dependencies, lgtm

#4550 kcm-wacomtablet: rebuild to fix sover mismatch
  desktop-kde/kcm-wacomtablet/spec
Labels: bug, abi-break
