Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-07, with the labels that each got.

#4604 aoscdk-rs: update to 0.8.3
  app-admin/aoscdk-rs/spec
Labels: upgrade

#4598 rsync: fix runtime AVX2 detection
  app-network/rsync/autobuild/patches/0001-rsync-fix-runtime-avx2-detection.patch
  app-network/rsync/spec
Labels: bug, hardware-support

#4615 libkscreen: backport a patch to fix KScreenLocker crash on Wayland
  desktop-kde/libkscreen/autobuild/patches/0001-BACKPORT-libdpms-wayland-Do-not-create-dpms-interfaces-for-placeholder-QScreens.patch
  desktop-kde/libkscreen/spec
Labels: bug, enhancement, has-fix

#4614 kwin: backport a patch to fix Wayland touch screen issue
  desktop-kde/kwin/autobuild/patches/0001-BACKPORT-input-Make-sure-input-backends-are-initialised-when-the-workspace-is-set-up.patch
  desktop-kde/kwin/spec
Labels: enhancement, has-fix

#4619 aoscdk-rs: update to 0.9.0
  app-admin/aoscdk-rs/spec
Labels: upgrade

#4624 discord: update to 0.0.28
  app-web/discord/spec
Labels: upgrade

#4590 vscode: update to 1.79.2
  app-editors/vscode/spec
Labels: upgrade

#4606 opensans: new, 0+git20210927
  desktop-fonts/opensans/autobuild/build
  desktop-fonts/opensans/autobuild/defines
  desktop-fonts/opensans/spec
Labels: new-package

#4586 owntone: new, 28.6
  app-multimedia/owntone/autobuild/beyond
  app-multimedia/owntone/autobuild/conffiles
  app-multimedia/owntone/autobuild/defines
  app-multimedia/owntone/autobuild/overrides/usr/lib/sysusers.d/owntone.conf
  app-multimedia/owntone/autobuild/overrides/usr/lib/tmpfiles.d/owntone.conf
  app-multimedia/owntone/autobuild/postinst
  app-multimedia/owntone/spec
Labels: new-package

#4630 Hwdata rework 20230715
  runtime-data/hwdata/spec
Labels: rework

#4620 plasma-mobile: disable qtfeedback
  desktop-kde/plasma-mobile/autobuild/patches/0001-BACKPORT-Disable-QtFeedback.patch
  desktop-kde/plasma-mobile/spec
Labels: enhancement, has-fix

#4638 fcitx5-pinyin-moegirl: update to 20230714
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#4641 kernel-build-common: header install dir should include local name
  app-devel/kernel-build-common/autobuild/ab3/build
  app-devel/kernel-build-common/autobuild/ab3/build-common/ext-hdr
  app-devel/kernel-build-common/spec
Labels: enhancement
