Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2023-12, with the labels that each got.

#4849 libfreeaptx: fix CHKUPDATE in spec
  runtime-multimedia/libfreeaptx/spec
Labels: has-fix

#4850 aosc-findupdate: update to 0.3.1
  app-utils/aosc-findupdate/spec
Labels: upgrade

#4851 treevsrepo: update to 0.3.4
  app-devel/treevsrepo/spec
Labels: upgrade

#4852 strace: update to 6.5
  app-devel/strace/spec
Labels: upgrade

#4853 pyelftools: update to 0.30
  lang-python/pyelftools/spec
Labels: upgrade

#4824 libicns: new, 0.8.1
  runtime-imaging/libicns/autobuild/defines
  runtime-imaging/libicns/spec
Labels: new-package

#4855 cmake: update to 3.26.3
  app-devel/cmake/autobuild/patches/0001-find-openmp-from-system-paths.patch
  app-devel/cmake/spec
Labels: upgrade

#4859 toposort: update to 1.8
  lang-python/toposort/spec
Labels: upgrade

#4857 fcitx5-mozc: fix CHKUPDATE
  app-i18n/fcitx5-mozc/spec
Labels: has-fix

#4861 hatch-vcs: fix dependencies
  lang-python/hatch-vcs/autobuild/defines
  lang-python/hatch-vcs/spec
Labels: dependencies

#4863 setuptools-scm: fix dependencies
  lang-python/setuptools-scm/autobuild/defines
  lang-python/setuptools-scm/spec
Labels: dependencies

#4867 inxi: update to 3.3.31+2
  app-utils/inxi/spec
Labels: upgrade

#4868 superslicer: update to 2.5.59.3
  app-creativity/superslicer/spec
Labels: upgrade

#4869 clash: (no-build) use aosc-repacks; upstream tarball gone
  app-network/clash/spec
Labels: upstream-moved, has-fix

#4860 libffi: update to 3.4.4
  runtime-common/libffi/spec
Labels: upgrade

#4870 isodate: update to 0.6.1
  lang-python/isodate/spec
Labels: upgrade

#4871 swaylock: fix CHKUPDATE
  app-utils/swaylock/spec
Labels: has-fix

#4872 kramdown: fix CHKUPDATE
  lang-ruby/kramdown/spec
Labels: has-fix

#4874 i3: update to 4.23
  desktop-wm/i3/spec
Labels: upgrade

#4877 evolution: fix mail content height issue with new WebKitGTK+
  desktop-gnome/evolution/autobuild/patches/0001-I-2001-Mail-Update-preview-s-iframe-height-to-match-.patch
  desktop-gnome/evolution/spec
Labels: has-fix

#4882 libidn: update to 1.41
  runtime-network/libidn/spec
Labels: upgrade

#4879 oma: update to 1.2.0
  app-admin/oma/spec
Labels: upgrade

#4880 discord: update to 0.0.37
  app-web/discord/spec
Labels: upgrade

#4884 nano: update to 7.2
  app-editors/nano/spec
Labels: upgrade

#4883 yazi: new, 0.1.5
  app-utils/yazi/autobuild/beyond
  app-utils/yazi/autobuild/defines
  app-utils/yazi/autobuild/patches/0001-fix-compile.patch
  app-utils/yazi/spec
Labels: help-wanted, new-package

#4887 oma: update to 1.2.4
  app-admin/oma/spec
Labels: upgrade

#4888 hwdata: update to 0.377
  runtime-data/hwdata/spec
Labels: upgrade

#4890 ed: update to 1.19
  app-editors/ed/spec
Labels: upgrade

#4894 rustc-demangle: fix for loongson3
  runtime-common/rustc-demangle/autobuild/defines
Labels: rework

#4895 autobuild3: update to 1.8.2
  app-devel/autobuild3/spec
Labels: upgrade

#4896 aosc-os-repository-data: update to 20231211
  runtime-data/aosc-os-repository-data/spec
Labels: upgrade

#4893 binwalk: update to 2.3.4
  app-devel/binwalk/spec
Labels: upgrade

#4897 ecpdap: fix for loongson3
  app-electronics/ecpdap/autobuild/defines
Labels: ftbfs, has-fix

#4898 gifski: re-enable LTO for riscv64
  app-imaging/gifski/autobuild/defines
  app-imaging/gifski/spec
Labels: has-fix

#4905 discord: update to 0.0.38
  app-web/discord/spec
Labels: upgrade

#4902 gitui: fix for loongson3
  app-utils/gitui/autobuild/defines
Labels: has-fix

#4907 tokei: fix for loongson3
  app-devel/tokei/autobuild/defines
Labels: has-fix

#4909 oma: re-enable LTO for riscv64
  app-admin/oma/autobuild/defines
  app-admin/oma/spec
Labels: has-fix

#4910 openvpn: update to 2.5.3
  app-network/openvpn/spec
Labels: upgrade

#4914 mimalloc: new package
  runtime-common/mimalloc/autobuild/defines
  runtime-common/mimalloc/spec
Labels: new-package

#4913 qpageview: fix CHKUPDATE
  lang-python/qpageview/spec
Labels: has-fix

#4912 rttopo: new, 1.1.0
  runtime-gis/rttopo/autobuild/defines
  runtime-gis/rttopo/spec
Labels: new-package

#4911 rime-schema-manager: fix for loongson3
  app-i18n/rime-schema-manager/autobuild/defines
Labels: has-fix

#4916 mimalloc: various improvements
  runtime-common/mimalloc/autobuild/defines
  runtime-common/mimalloc/spec
Labels: enhancement, has-fix

#4847 aoscdk-rs: update to 0.10.0
  app-admin/aoscdk-rs/autobuild/patches/0001-fix-ppc64el-build.patch
  app-admin/aoscdk-rs/spec
Labels: upgrade

#4920 prjoxide: fix for loongson3
  app-electronics/prjoxide/autobuild/defines
Labels: has-fix

#4921 fd: fix for loongson3
  app-utils/fd/autobuild/defines
Labels: has-fix

#4923 nomino: fix for loongson3
  app-utils/nomino/autobuild/defines
Labels: has-fix

#4925 mcfly: fix for loongson3
  app-utils/mcfly/autobuild/defines
Labels: has-fix

#4924 treevsrepo: update to 0.4.0
  app-devel/treevsrepo/spec
Labels: upgrade

#4931 acbs: update to 20231217.4
  app-devel/acbs/spec
Labels: upgrade

#4932 autobuild3: update to 1.8.3
  app-devel/autobuild3/spec
Labels: upgrade

#4933 linux-kernel-retro: (i486) enable CONFIG_SATA_SIL
  runtime-kernel/linux-kernel-retro/autobuild/i486/config
Labels: retro, hardware-support

#4927 oma: update to 1.2.6
  app-admin/oma/spec
Labels: upgrade

#4935 MIPS64 R6 Survey 20231214 Rework
  runtime-multimedia/liblo/autobuild/patches/0000-configure-ac-fix-werror-detection.patch
  runtime-multimedia/liblo/autobuild/prepare
Labels: has-fix, rework, cip-pilot

#4944 discord: update to 0.0.39
  app-web/discord/spec
Labels: upgrade

#4948 fd: update to 8.7.1
  app-utils/fd/spec
Labels: upgrade

#4942 gifski: fix for loongson3
  app-imaging/gifski/autobuild/defines
Labels: has-fix

#4950 soundtouch+32: fix missing CHKSUMS
  runtime-optenv32/soundtouch+32/spec
Labels: has-fix

#4952 smpeg+32: fix SRCS & BUILDDEP
  runtime-optenv32/smpeg+32/autobuild/defines
  runtime-optenv32/smpeg+32/spec
Labels: optenv, has-fix

#4955 serd: update to 0.32.0
  runtime-common/serd/spec
Labels: upgrade, cip-pilot

#4953 shadowsocks-libev: add cap_net_admin to ss-redir in postinst
  app-network/shadowsocks-libev/autobuild/postinst
  app-network/shadowsocks-libev/spec
Labels: has-fix

#4941 aoscdk-rs: update to 0.11.1
  app-admin/aoscdk-rs/spec
Labels: upgrade

#4957 miniserve: fix for loongson3
  app-web/miniserve/autobuild/defines
Labels: has-fix

#4964 chore: remove trailing whitespaces found in .github
  .github/ISSUE_TEMPLATE/security-vulnerabilities-report.yml
  .github/PULL_REQUEST_TEMPLATE
  .github/workflows/build-packages.yml
Labels: meta

#4962 mkvtoolnix: bump REL for rebuild
  app-multimedia/mkvtoolnix/spec
Labels: has-fix, dependencies, cip-pilot

#4972 sdl-ttf+32: build fixes
  runtime-optenv32/sdl-ttf+32/autobuild/build
  runtime-optenv32/sdl-ttf+32/autobuild/defines
Labels: has-fix

#4963 libnvme: fix pkgbreak
  runtime-devices/libnvme/autobuild/defines
  runtime-devices/libnvme/spec
Labels: has-fix, cip-pilot

#4977 clutter: fix ftbfs
  desktop-gnome/clutter/autobuild/defines
Labels: ftbfs, has-fix

#4960 babl: fix ftbfs for mips64r6el
  runtime-imaging/babl/autobuild/defines
Labels: ftbfs, cip-pilot

#4934 oma: fix 1.2.6 version bump
  app-admin/oma/spec
Labels: has-fix

#4938 aarty: new, 0.4.9
  app-utils/aarty/autobuild/defines
  app-utils/aarty/autobuild/prepare
  app-utils/aarty/spec
Labels: new-package

#4961 gitoxide: update to 0.32.0
  app-vcs/gitoxide/spec
Labels: upgrade

#4971 yt-dlp: update to 2023.11.16
  app-multimedia/yt-dlp/spec
Labels: upgrade

#4946 ast-grep: update to 0.15.1
  app-devel/ast-grep/spec
Labels: upgrade

#4985 zellij: update to 0.39.2
  app-utils/zellij/spec
Labels: upgrade

#4987 ghidra: update to 11.0
  app-devel/ghidra/spec
Labels: upgrade

#4991 cython: create cython3 symlink
  lang-python/cython/autobuild/beyond
Labels: enhancement

#4993 cython: rework spec to bump REL
  lang-python/cython/spec
Labels: rework

#4992 fd: update to 9.0.0
  app-utils/fd/spec
Labels: upgrade

#4995 superslicer: update to 2.5.59.4
  app-creativity/superslicer/spec
Labels: upgrade

#4998 openocd: update to 0.12.0
  app-devel/openocd/spec
Labels: upgrade

#4994 cython: sanitize symlinks and bump rel
  lang-python/cython/autobuild/beyond
  lang-python/cython/spec
Labels: rework

#5003 QEMU: update to 8.2.0
  app-virtualization/qemu/01-shared/beyond
  app-virtualization/qemu/01-shared/build
  app-virtualization/qemu/01-shared/defines
  app-virtualization/qemu/01-shared/patch
  app-virtualization/qemu/01-shared/patches/0001-linux-headers-Synchronize-linux-headers-from-linux-v.patch.system-only
  app-virtualization/qemu/01-shared/patches/0001-linux-user-correctly-pack-target_epoll_event-for-i38.patch
  app-virtualization/qemu/01-shared/patches/0002-emulate-loongson-for-mips3-mips64r2.patch
  app-virtualization/qemu/01-shared/patches/0002-target-loongarch-Define-some-kvm_arch-interfaces.patch.system-only
  app-virtualization/qemu/01-shared/patches/0003-target-loongarch-Supplement-vcpu-env-initial-when-vc.patch.system-only
  app-virtualization/qemu/01-shared/patches/0004-target-loongarch-Implement-kvm-get-set-registers.patch.system-only
  app-virtualization/qemu/01-shared/patches/0005-target-loongarch-Implement-kvm_arch_init-function.patch.system-only
  app-virtualization/qemu/01-shared/patches/0006-target-loongarch-Implement-kvm_arch_init_vcpu.patch.system-only
  app-virtualization/qemu/01-shared/patches/0007-target-loongarch-Implement-kvm_arch_handle_exit.patch.system-only
  app-virtualization/qemu/01-shared/patches/0008-target-loongarch-Implement-set-vcpu-intr-for-kvm.patch.system-only
  app-virtualization/qemu/01-shared/patches/0009-target-loongarch-Add-loongarch-kvm-into-meson-build.patch.system-only
  app-virtualization/qemu/01-shared/patches/0010-Add-LSX-LASX-support.patch.system-only
  app-virtualization/qemu/01-shared/patches/1002-hw-misc-Add-MIPS-Trickbox-device.patch
  app-virtualization/qemu/01-shared/patches/1003-hw-mips-Add-MIPS-virt-board.patch
  app-virtualization/qemu/01-shared/patches/1004-DRAFT-target-mips-Properly-set-C0_CMGCRBase-after-CP.patch
  app-virtualization/qemu/01-shared/patches/1005-HACK-target-mips-Enable-MTTCG.patch
  app-virtualization/qemu/01-shared/patches/9999-build-most-modules-statically-hack.patch.user-only
  app-virtualization/qemu/01-shared/prepare
  app-virtualization/qemu/spec
Labels: upgrade

#5011 Autobuild3: update to 1.8.6
  app-devel/autobuild3/spec
Labels: upgrade

#5012 aoscbootstrap: update to 0.3.3
  app-utils/aoscbootstrap/spec
Labels: upgrade

#5013 bash-startup (Bash basic configuration): update to 0.6.5
  runtime-data/bash-startup/spec
Labels: upgrade

#5015 ACBS (AutoBuild CI Build System): update to 20231225
  app-devel/acbs/spec
Labels: upgrade

#5004 jemalloc: update to 5.3.0
  runtime-common/jemalloc/spec
Labels: upgrade

#5023 aoscdk-rs: update to 0.11.2
  app-admin/aoscdk-rs/spec
Labels: upgrade

#5040 cln: fix build on loongarch64
  runtime-common/cln/autobuild/patches/0001-LoongArchLinux-cln-la64.patch.loongarch64
Labels: has-fix, new-port

#5014 ciel: update to 3.2.1
  app-devel/ciel/spec
Labels: upgrade

#5010 librsvg: update to 2.56.1
  runtime-imaging/librsvg/autobuild/defines
  runtime-imaging/librsvg/spec
Labels: upgrade

#5043 latx (Loongson Architecture Translator for x86): new, 1.4.3+emukit20231027
  app-emulation/latx/autobuild/alternatives
  app-emulation/latx/autobuild/build
  app-emulation/latx/autobuild/defines
  app-emulation/latx/autobuild/overrides/usr/lib/binfmt.alternatives/latx-i386.conf
  app-emulation/latx/autobuild/overrides/usr/lib/binfmt.alternatives/latx-x86_64.conf
  app-emulation/latx/autobuild/overrides/usr/lib/sysctl.d/99-latx.conf
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system-preset/50-latx.preset
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-dev.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-etc.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-proc.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-run.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-sys.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-usr-share-fontconfig.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-usr-share-fonts.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-latx\x2dx86_64-usr-share-icons.mount
  app-emulation/latx/autobuild/postinst
  app-emulation/latx/autobuild/postrm
  app-emulation/latx/autobuild/prerm
  app-emulation/latx/autobuild/triggers
  app-emulation/latx/spec
Labels: new-packages

#5042 libiscsi: Fix FTBFS for mips64r6el
  runtime-network/libiscsi/autobuild/prepare
Labels: ftbfs, has-fix, cip-pilot

#5005 libseccomp: update to 2.5.5
  runtime-common/libseccomp/spec
Labels: upgrade

#5009 cargo-c: update to 0.9.24
  lang-rust/cargo-c/autobuild/defines
  lang-rust/cargo-c/autobuild/prepare
  lang-rust/cargo-c/spec
Labels: upgrade

#5038 kmod: update to 31
  app-admin/kmod/spec
Labels: upgrade

#5048 libhandy: (mips64r6el) drop glade dep
  desktop-gnome/libhandy/autobuild/defines
Labels: dependencies, drop-package, cip-pilot

#5052 openvpn: update to 2.5.4
  app-network/openvpn/spec
Labels: upgrade

#5054 ACBS (Autobuild CI Build System): update to 20231230
  app-devel/acbs/spec
Labels: upgrade

#5047 mcfly: update to 0.8.4
  app-utils/mcfly/spec
Labels: upgrade

#5036 libblkio: (upstream patch) update Cargo dependencies
  runtime-common/libblkio/autobuild/patches/0001-Update-Cargo.lock.patch
  runtime-common/libblkio/spec
Labels: upgrade, dependencies

#5056 aoscbootstrap: update to 0.3.5
  app-utils/aoscbootstrap/spec
Labels: upgrade
