Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-12, with the labels that each got.

#8831 hmcl: update to 3.6.11
  app-games/hmcl/spec
Labels: upgrade

#8825 system-config-printer: update to 1.5.18
  app-admin/system-config-printer/spec
Labels: upgrade

#8823 xdg-user-dirs: update to 0.18
  app-admin/xdg-user-dirs/spec
Labels: upgrade

#8838 osu-lazer: update to 2024.1130.0
  app-games/osu-lazer/spec
Labels: upgrade

#8837 dunst: update to 1.12.0
  app-utils/dunst/spec
Labels: upgrade

#8839 weechat: update to 4.4.4
  app-web/weechat/autobuild/defines
  app-web/weechat/spec
Labels: upgrade

#8815 xorg-server: allow the modesetting DDX to match Multimedia Video Controllers
  runtime-display/xorg-server/autobuild/patches/0001-Use-intel-ddx-only-on-pre-gen4-hw-newer-ones-will-fa.patch
  runtime-display/xorg-server/autobuild/patches/0002-xfree86-use-modesetting-driver-by-default-on-GeForce.patch
  runtime-display/xorg-server/autobuild/patches/0003-hw-xfree86-re-calculate-the-clock-and-refresh-rate.patch
  runtime-display/xorg-server/autobuild/patches/0004-xf86-Accept-devices-with-the-hyperv_drm-driver.patch
  runtime-display/xorg-server/autobuild/patches/0005-Allows-X-to-work-on-the-Lemote-Yeeloong-laptop.patch
  runtime-display/xorg-server/autobuild/patches/0006-modesetting-match-against-Multimedia-Video-Controlle.patch
  runtime-display/xorg-server/spec
Labels: enhancement, hardware-support

#8817 lxgwwenkai-font: update to 1.501
  desktop-fonts/lxgwwenkai-font/spec
Labels: upgrade

#8809 xrdp: update to 0.10.1
  app-network/xrdp/spec
Labels: upgrade

#8808 xf86-video-mach64: update to 6.10.0
  runtime-display/xf86-video-mach64/spec
Labels: upgrade

#8807 audacious: update to 4.4.2
  app-multimedia/audacious/spec
Labels: upgrade

#8830 hugo: update to 0.139.3
  app-web/hugo/spec
Labels: upgrade

#8813 vala: update to 0.56.17
  app-devel/vala/spec
Labels: upgrade

#8803 libburn: update to 1.5.6
  runtime-devices/libburn/spec
Labels: upgrade

#8800 libdvdread: update to 6.1.3
  runtime-multimedia/libdvdread/spec
Labels: upgrade

#8797 freerdp: update to 3.9.0
  app-network/freerdp/spec
Labels: upgrade

#8709 upower: update to 1.90.6
  app-admin/upower/autobuild/defines
  app-admin/upower/autobuild/patches/0001-build-Make-installation-of-tests-optional.patch
  app-admin/upower/spec
Labels: upgrade

#8848 libinput: update to 1.27.0
  runtime-devices/libinput/autobuild/patches/0001-fix-evdev-mt-touchpad-tap.c-enable-tap-to-click-by-d.patch
  runtime-devices/libinput/autobuild/patches/0002-quirks-add-pressure-pad-quirk-for-Lenovo-ThinkBook-1.patch
  runtime-devices/libinput/autobuild/patches/0003-quirks-lower-AttrTrackpointMultiplier-for-ThinkPad-X.patch
  runtime-devices/libinput/spec
Labels: upgrade

#8846 cryptsetup: update to 2.7.5
  app-admin/cryptsetup/spec
Labels: upgrade

#8849 linux-firmware: update to 20241128
  runtime-kernel/linux-firmware/spec
Labels: upgrade

#8851 praat: update to 6.4.24
  app-scientific/praat/spec
Labels: upgrade

#8840 shadowsocks-rust: update to 1.21.2
  app-network/shadowsocks-rust/spec
Labels: upgrade

#8857 vulkan-loader: rebuild for Spiral markers
  runtime-display/vulkan-loader/spec
Labels: spiral

#8871 wireplumber: update to 0.5.7
  app-multimedia/wireplumber/spec
Labels: upgrade

#8869 fastfetch: update to 2.31.0
  app-utils/fastfetch/spec
Labels: upgrade

#8870 mpd: update to 0.23.16
  app-multimedia/mpd/spec
Labels: upgrade

#8859 mcomix: update to 3.1.0
  app-utils/mcomix/autobuild/build
  app-utils/mcomix/autobuild/defines
  app-utils/mcomix/spec
Labels: upgrade

#8828 xray: update to 24.11.30
  app-network/xray/spec
Labels: upgrade

#8877 libdatachannel: update to 0.22.3
  runtime-multimedia/libdatachannel/spec
Labels: upgrade

#8872 nodejs-22: update to 22.12.0
  lang-js/nodejs-22/spec
Labels: upgrade

#8878 vim: update to 9.1.0905
  app-editors/vim/spec
Labels: upgrade

#8875 rosegarden: update to 24.12
  app-creativity/rosegarden/spec
Labels: upgrade

#8879 remmina: update to 1.4.36
  app-network/remmina/spec
Labels: upgrade

#8885 osu-lazer: update to 2024.1205.0
  app-games/osu-lazer/spec
Labels: upgrade

#8888 vim: update to 9.1.0906
  app-editors/vim/spec
Labels: upgrade

#8889 cmake: update to 3.31.2
  app-devel/cmake/spec
Labels: upgrade

#8881 llvm-19: update to 19.1.5
  app-devel/llvm-19/spec
Labels: upgrade

#8909 sarasa-gothic-fonts: update to 1.0.25
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#8908 iosevka-fonts: update to 32.2.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#8911 yazi: update to 0.4.0
  app-utils/yazi/spec
Labels: upgrade

#8912 praat: update to 6.4.25
  app-scientific/praat/spec
Labels: upgrade

#8913 osu-lazer: update to 2024.1208.0
  app-games/osu-lazer/spec
Labels: upgrade

#8915 mold: update to 2.35.0
  app-devel/mold/spec
Labels: upgrade

#8926 AOSC Logos: update to 12 (localhost) Ayy!
  runtime-data/aosc-logos/autobuild/overrides/usr/bin/aosc-logo
  runtime-data/aosc-logos/autobuild/overrides/usr/share/aosc-logos/localhost
  runtime-data/aosc-logos/spec
Labels: upgrade

#8914 tailscale: update to 1.78.1
  app-network/tailscale/spec
Labels: upgrade

#8923 egl-wayland: update to 1.1.17
  runtime-display/egl-wayland/spec
Labels: upgrade

#8861 muse: new, 4.2.1
  app-creativity/muse/autobuild/defines
  app-creativity/muse/autobuild/patches/0001-BACKPORT-Force-the-use-of-in-window-menu.patch
  app-creativity/muse/autobuild/patches/0002-BACKPORT-Fix-build-with-ninja-1.12.0-fix-1276.patch
  app-creativity/muse/spec
Labels: new-packages

#8930 yazi: update to 0.4.1
  app-utils/yazi/spec
Labels: upgrade

#8935 grub: empty GRUB_CMDLINE_LINUX by default
  app-admin/grub/autobuild/overrides/etc/default/grub
  app-admin/grub/spec
Labels: bug

#8936 libgbinder: update to 1.1.42
  runtime-common/libgbinder/spec
Labels: upgrade

#8939 scrcpy: update to 3.1
  app-devices/scrcpy/spec
Labels: upgrade, pre-release

#8940 vscode: update to 1.96.0
  app-editors/vscode/spec
Labels: upgrade

#8925 fscan: new, 1.8.4
  app-utils/fscan/autobuild/defines
  app-utils/fscan/autobuild/patches/neko205-fscan-fix-tls-error.patch
  app-utils/fscan/spec
Labels: new-package

#8919 geant4: update to 11.3.0
  app-productivity/geant4/spec
  app-scientific/geant4/autobuild/beyond
  app-scientific/geant4/autobuild/defines
  app-scientific/geant4/autobuild/overrides/etc/profile.d/geant4.sh
  app-scientific/geant4/spec
Labels: upgrade

#8944 bitwarden: update to 2024.12.0
  app-utils/bitwarden/spec
Labels: upgrade

#8945 deb-installer: update to 0.1.5
  app-admin/deb-installer/spec
Labels: upgrade

#8200 dpdk: update to 24.07
  runtime-network/dpdk/autobuild/defines
  runtime-network/dpdk/spec
Labels: upgrade

#8893 syncthing: update to 1.28.1
  app-network/syncthing/spec
Labels: upgrade

#8943 autobuild4: update to 4.6.0
  app-devel/autobuild4/spec
Labels: upgrade

#8950 just: update to 1.38.0
  app-devel/just/spec
Labels: upgrade

#8951 dnscontrol: update to 4.15.0
  app-network/dnscontrol/spec
Labels: upgrade

#8898 zvm: update to 0.8.2
  lang-ziglang/zvm/spec
Labels: upgrade

#8947 vscodium: update to 1.96.0.24347
  app-editors/vscodium/spec
Labels: upgrade

#8892 kicad: update to 8.0.7
  app-electronics/kicad/spec
Labels: upgrade

#8938 qemu: update to 9.2.0
  app-virtualization/qemu/01-shared/beyond
  app-virtualization/qemu/01-shared/build
  app-virtualization/qemu/01-shared/patches/0001-linux-user-mips64-target_elf-detect-and-use-EF_MIPS_.patch
  app-virtualization/qemu/01-shared/patches/9999-build-most-modules-statically-hack.patch.user-only
  app-virtualization/qemu/06-static-cris/build
  app-virtualization/qemu/06-static-cris/defines
  app-virtualization/qemu/06-static-cris/qemu-cris.conf
  app-virtualization/qemu/06-static-cris/triggers
  app-virtualization/qemu/13-static-mips64el/qemu-mips64el.conf
  app-virtualization/qemu/32-static-nios2/build
  app-virtualization/qemu/32-static-nios2/defines
  app-virtualization/qemu/32-static-nios2/triggers
  app-virtualization/qemu/99-static-meta/defines
  app-virtualization/qemu/spec
Labels: upgrade

#8961 autobuild4: update to 4.6.3
  app-devel/autobuild4/spec
Labels: upgrade

#8953 waylyrics: update to 0.3.20
  app-multimedia/waylyrics/spec
Labels: upgrade

#8899 timeshift: new, 24.06.5
  app-utils/timeshift/autobuild/defines
  app-utils/timeshift/autobuild/patches/0001-Specify-the-environment-variables-named-DISPLAY-and-.patch
  app-utils/timeshift/autobuild/patches/0002-Update-dekstop-entry-translations.patch
  app-utils/timeshift/spec
Labels: new-packages

#8958 ciel: update to 3.5.2
  app-devel/ciel/spec
Labels: upgrade

#8955 vkpeak: new, 20240505
  app-utils/vkpeak/autobuild/beyond
  app-utils/vkpeak/autobuild/defines
  app-utils/vkpeak/spec
Labels: new-packages

#8941 stunnel: update to 5.73
  app-network/stunnel/spec
Labels: upgrade

#8979 zfs: update to 2.2.7
  app-admin/zfs/autobuild/patches/0001-Block-manual-building-in-the-DKMS-source-tree.patch
  app-admin/zfs/autobuild/patches/0002-Enable-zed-emails.patch
  app-admin/zfs/autobuild/patches/0003-Explicitly-load-the-ZFS-module-via-systemd-service.patch
  app-admin/zfs/autobuild/patches/0004-Force-libtool-to-produce-verbose-output.patch
  app-admin/zfs/autobuild/patches/0005-META-Bump-Linux-Maximum-to-6.10.patch
  app-admin/zfs/spec
Labels: upgrade

#8968 lshw: update to 02.20
  app-utils/lshw/autobuild/build
  app-utils/lshw/autobuild/patches/0001-Drop-version-update-check.patch
  app-utils/lshw/spec
Labels: upgrade

#8981 weechat: update to 4.5.0
  app-web/weechat/spec
Labels: upgrade

#8969 librsvg: update to 2.59.2
  runtime-imaging/librsvg/autobuild/beyond
  runtime-imaging/librsvg/autobuild/defines
  runtime-imaging/librsvg/autobuild/prepare
  runtime-imaging/librsvg/spec
Labels: upgrade

#8973 fcitx5-pinyin-moegirl: update to 20241211
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#8965 picard: update to 2.12.3
  app-multimedia/picard/spec
Labels: upgrade

#8986 libpng: update to 1.6.44
  runtime-imaging/libpng/spec
Labels: upgrade

#8990 zathura: update to 0.5.11
  app-doc/zathura/spec
Labels: upgrade

#8993 dunst: update to 1.12.1
  app-utils/dunst/spec
Labels: upgrade

#8991 qbittorrent: update to 5.0.3
  app-web/qbittorrent/spec
Labels: upgrade

#8998 fastfetch: update to 2.32.1
  app-utils/fastfetch/spec
Labels: upgrade

#8995 intel-oneapi-basekit: update to 2025.0.1
  app-devel/intel-oneapi-basekit/autobuild/defines
  app-devel/intel-oneapi-basekit/spec
Labels: upgrade

#8999 dae: update to 0.9.0
  app-network/dae/autobuild/defines
  app-network/dae/spec
Labels: upgrade

#9004 vscode: update to 1.96.1
  app-editors/vscode/spec
Labels: upgrade

#9003 stress-ng: update to 0.18.07
  app-benchmarks/stress-ng/spec
Labels: upgrade

#8975 cloc: update to 2.02
  app-utils/cloc/autobuild/build
  app-utils/cloc/spec
Labels: upgrade

#8910 obs-studio: update to 31.0.0
  app-multimedia/obs-studio/autobuild/defines
  app-multimedia/obs-studio/autobuild/patches/0001-cmake-Add-executable-permission-to-CEF-binary-and-li.patch
  app-multimedia/obs-studio/autobuild/patches/0001-keep-CEF-binary-file-permissions.patch
  app-multimedia/obs-studio/autobuild/patches/0002-cef-122.0-api.patch
  app-multimedia/obs-studio/autobuild/patches/0002-obs-ffmpeg-Fix-deprecation-with-FFmpeg-7.1.patch
  app-multimedia/obs-studio/autobuild/patches/0003-libobs-opengl-Avoid-trying-to-allocate-0-byte-on-Lin.patch
  app-multimedia/obs-studio/spec
Labels: upgrade

#9008 vscode: update to 1.96.2
  app-editors/vscode/spec
Labels: upgrade

#9015 yazi: update to 0.4.2
  app-utils/yazi/spec
Labels: upgrade

#9014 wayland-protocols: update to 1.39
  app-devel/wayland-protocols/spec
Labels: upgrade

#9013 taskwarrior: update to 3.3.0
  app-productivity/taskwarrior/spec
Labels: upgrade

#9011 ostree: update to 2024.10
  app-admin/ostree/spec
Labels: upgrade

#9010 clpeak: update to 1.1.3
  app-benchmarks/clpeak/autobuild/defines
  app-benchmarks/clpeak/spec
Labels: upgrade

#9006 dnscontrol: update to 4.15.2
  app-network/dnscontrol/spec
Labels: upgrade

#8994 mesa: fix GLX w/o HW accel
  runtime-display/mesa/autobuild/patches/0003-Revert-dril-also-create-double-buffered-configs-in-s.patch
  runtime-display/mesa/autobuild/patches/0004-Revert-dril-use-the-super-fallback-path-for-software.patch
  runtime-display/mesa/autobuild/prepare
  runtime-display/mesa/spec
Labels: has-fix

#9016 autobuild4: update to 4.6.5
  app-devel/autobuild4/spec
Labels: upgrade

#9019 binutils: add two patches for LoongArch ld
  app-devel/binutils/01-main/patches/0003-FROMLIST-LoongArch-Fix-broken-DESC-IE-transition-for.patch
  app-devel/binutils/01-main/patches/0004-BACKPORT-LoongArch-Add-elfNN_loongarch_mkobject-to-i.patch
  app-devel/binutils/spec
Labels: has-fix

#8895 git-filter-repo: update to 2.47.0
  app-devel/git-filter-repo/spec
Labels: upgrade

#9012 osu-lazer: update to 2024.1219.2
  app-games/osu-lazer/spec
Labels: upgrade

#9017 mesa: update to 24.3.2+dxheaders1.614.1
  runtime-display/mesa/autobuild/patches/0001-AOSCOS-r600-disable-buggy-VC-1-hardware-decoding.patch
  runtime-display/mesa/autobuild/patches/0001-r600-disable-buggy-vc-1-hardware-decoding.patch
  runtime-display/mesa/autobuild/patches/0002-AOSCOS-LOONGARCH64-fix-iris_bufmgr.c-set-PAGE_SIZE-a.patch.loongarch64
  runtime-display/mesa/autobuild/prepare
  runtime-display/mesa/spec
Labels: upgrade

#9023 renderdoc: update to 1.36
  app-devel/renderdoc/spec
Labels: upgrade

#9027 flacon: new, 11.4.0
  app-multimedia/flacon/autobuild/defines
  app-multimedia/flacon/spec
Labels: new-packages

#9018 synaptic: update to 0.91.3
  app-admin/synaptic/spec
Labels: upgrade

#9025 sing-box: update to 1.10.5
  app-network/sing-box/spec
Labels: upgrade

#9029 autobuild4: update to 4.6.6
  app-devel/autobuild4/spec
Labels: upgrade

#9040 noto-fonts: fix some Qt program cannot display emoji
  desktop-fonts/noto-fonts/01-noto/overrides/etc/fonts/conf.avail/66-google-noto-color-emoji.conf
  desktop-fonts/noto-fonts/spec
Labels: has-fix

#9037 simh: fix strange executable paths
  app-emulation/simh/autobuild/build
  app-emulation/simh/spec
Labels: has-fix

#8658 rnote: new, 0.11.0
  app-doc/rnote/autobuild/defines
  app-doc/rnote/spec
Labels: new-package

#9035 llvm-19: update to 19.1.6
  app-devel/llvm-19/spec
Labels: upgrade

#8660 steam: update to 1.0.0.82
  app-games/steam/autobuild/patches/0001-fix-steam.desktop-make-sure-Steam-recognises-our-32-.patch
  app-games/steam/autobuild/patches/0002-hack-fix-IME-input-text.patch
  app-games/steam/spec
Labels: upgrade

#8575 id3: update to 0.81
  app-utils/id3/spec
Labels: upgrade

#9034 numactl: update to 2.0.19
  app-admin/numactl/spec
Labels: upgrade

#9036 rustc: update to 1.83.0
  lang-rust/rustc/autobuild/defines
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/autobuild/prepare
  lang-rust/rustc/spec
Labels: upgrade

#9039 cmake: update to 3.31.3
  app-devel/cmake/spec
Labels: upgrade

#9041 thunderbird: update to 128.5.2esr
  app-web/thunderbird/spec
Labels: upgrade, security

#9056 vim: update to 9.1.0958
  app-editors/vim/spec
Labels: upgrade

#9053 sarasa-gothic-fonts: update to 1.0.26
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#9054 iosevka-fonts: update to 32.3.0
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#9055 weechat: update to 4.5.1
  app-web/weechat/spec
Labels: upgrade

#9052 linux-firmware: update to 20241220
  runtime-kernel/linux-firmware/spec
Labels: upgrade

#9030 darktable: update to 5.0.0
  app-creativity/darktable/autobuild/defines
  app-creativity/darktable/spec
Labels: upgrade

#9060 clpeak: update to 1.1.4
  app-benchmarks/clpeak/spec
Labels: upgrade

#9059 mold: update to 2.35.1
  app-devel/mold/spec
Labels: upgrade

#9067 hmcl: backport a patch to fix Zink + amdgpu DDX
  app-games/hmcl/autobuild/patches/0001-fix-DefaultLauncher-also-set-LIBGL_KOPPER_DRI2-1-for.patch
  app-games/hmcl/spec
Labels: has-fix

#9063 vscodium: update to 1.96.2.24355 and add more architecture support
  app-editors/vscodium/autobuild/build
  app-editors/vscodium/autobuild/defines
  app-editors/vscodium/spec
Labels: upgrade, hardware-support

#9068 tsukimi: new 0.18.0
  app-multimedia/tsukimi/autobuild/defines
  app-multimedia/tsukimi/spec
Labels: new-packages

#8904 libxslt: update to 1.1.42
  runtime-common/libxslt/autobuild/defines
  runtime-common/libxslt/spec
Labels: upgrade

#8855 lutris: update to 0.5.18
  app-games/lutris/autobuild/defines
  app-games/lutris/autobuild/patches/0001-AOSC-OS-adaption.patch
  app-games/lutris/autobuild/patches/0001-feat-util-linux.py-add-AOSC-OS-optenv32-path-opt-32-.patch
  app-games/lutris/spec
Labels: upgrade

#9074 easyeffects: update to 7.2.1
  app-multimedia/easyeffects/spec
Labels: upgrade

#9075 fastfetch: update to 2.33.0
  app-utils/fastfetch/spec
Labels: upgrade

#9076 osu-lazer: update to 2024.1224.1
  app-games/osu-lazer/spec
Labels: upgrade

#9083 nano: update to 8.3+nanorc2024.1.16
  app-editors/nano/spec
Labels: upgrade, pre-release

#9081 lm-sensors: improve packaging
  app-utils/lm-sensors/autobuild/armv4
  app-utils/lm-sensors/autobuild/armv6hf
  app-utils/lm-sensors/autobuild/armv7hf
  app-utils/lm-sensors/autobuild/beyond
  app-utils/lm-sensors/autobuild/build
  app-utils/lm-sensors/autobuild/defines
  app-utils/lm-sensors/autobuild/i486
  app-utils/lm-sensors/autobuild/loongson2f
  app-utils/lm-sensors/autobuild/m68k
  app-utils/lm-sensors/autobuild/patches/0001-ARCHLINUX-use-etc-conf.d-as-the-configuration-prefix.patch
  app-utils/lm-sensors/autobuild/patches/0002-ARCHLINUX-do-not-throw-warning-if-etc-conf.d-lm_sens.patch
  app-utils/lm-sensors/autobuild/patches/0003-ARCHLINUX-install-sensord.patch
  app-utils/lm-sensors/autobuild/patches/0004-FEDORA-sensors-detect-Add-support-for-AMD-CPU-Family.patch
  app-utils/lm-sensors/autobuild/powerpc
  app-utils/lm-sensors/autobuild/ppc64
  app-utils/lm-sensors/autobuild/prepare
  app-utils/lm-sensors/autobuild/retro/build
  app-utils/lm-sensors/spec
Labels: enhancement, upgrade

#9072 chromium: update to 131.0.6778.204
  app-web/chromium/autobuild/build
  app-web/chromium/autobuild/patches/0001-FEDORA-Set-intial-prefs-path-to-etc-chromium.patch
  app-web/chromium/autobuild/patches/0002-FEDORA-third_party-zlib-Drop-dependency-to-chromecon.patch
  app-web/chromium/autobuild/patches/0003-FEDORA-Hard-code-std-hardware_destructive_interferen.patch
  app-web/chromium/autobuild/patches/0003-Fedora-update-rjsmin-to-1.2.0-to-see-if-Python-3.11-.patch
  app-web/chromium/autobuild/patches/0004-Fedora-chromium-98.0.4758.102-remoting-no-tests.patc.patch
  app-web/chromium/autobuild/patches/0004-GENTOO-www-client-chromium-work-around-dead-oauth2-c.patch
  app-web/chromium/autobuild/patches/0005-AOSCOS-devtools-frontend-disable-unreliable-terser-p.patch
  app-web/chromium/autobuild/patches/0005-Fedora-chromium-126-split-threshold-for-reg-with-hin.patch
  app-web/chromium/autobuild/patches/0006-AOSCOS-build-fix-invalid-flag-substitutions.patch
  app-web/chromium/autobuild/patches/0006-Debian-ruy-include.patch.patch
  app-web/chromium/autobuild/patches/0007-AOSCOS-build-correct-Clang-builtins-path.patch
  app-web/chromium/autobuild/patches/0007-iwyu-include-cstddef-for-nullptr_t-in-fragment_data_.patch
  app-web/chromium/autobuild/patches/0008-AOSCOS-third_party-swiftshader-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0009-AOSC-TBI-fix-invalid-substition-type.patch.patch
  app-web/chromium/autobuild/patches/0009-AOSCOS-sandbox-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0010-AOSC-fix-clang-builtins-path.patch.patch
  app-web/chromium/autobuild/patches/0010-AOSCOS-third_party-crashpad-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0011-AOSC-TBI-fix-missing-header.patch.patch
  app-web/chromium/autobuild/patches/0011-AOSCOS-third_party-dav1d-add-LoongArch-architecture-.patch
  app-web/chromium/autobuild/patches/0012-AOSC-TBI-fix-static-assertion.patch.patch
  app-web/chromium/autobuild/patches/0012-AOSCOS-third_party-ffmpeg-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0013-AOSC-TBI-swiftshader.patch.patch
  app-web/chromium/autobuild/patches/0013-AOSCOS-build-use-medium-code-model-for-LoongArch.patch
  app-web/chromium/autobuild/patches/0014-AOSCOS-feat-introduce-miscellaneous-LoongArch-suppor.patch
  app-web/chromium/autobuild/patches/0017-AOSC-medium-cmodel.patch.patch
  app-web/chromium/autobuild/patches/0019-IWYU-missing-include-for-usage-of-std-exchange-in-lo.patch
  app-web/chromium/autobuild/patches/0020-IWYU-missing-include-for-usage-of-std-optional-in-en.patch
  app-web/chromium/autobuild/patches/0021-IWYU-missing-include-for-usage-of-std-optional-in-pa.patch
  app-web/chromium/autobuild/patches/0022-chrome-browser-add-missing-dependency.patch
  app-web/chromium/autobuild/patches/0023-chrome-browser-ui-add-missing-dependency.patch
  app-web/chromium/autobuild/patches/0024-Move-chrome-browser-ui-webui_name_variants-to-public.patch
  app-web/chromium/autobuild/patches/0025-Build-LoongArch64-LSX-optimizations-in-libpng.patch
  app-web/chromium/autobuild/patches/0026-Make-more-deps-entries-public_deps-in-chrome-browser.patch
  app-web/chromium/autobuild/patches/0027-Reland-2-linux-build-Enable-fission-for-symbol_level.patch
  app-web/chromium/spec
Labels: upgrade

#9077 pandoc: update to 3.6.1
  app-doc/pandoc/spec
Labels: upgrade

#9032 git-cliff: update to 2.7.0
  app-vcs/git-cliff/spec
Labels: upgrade

#9086 qpwgraph: update to 0.8.1
  app-multimedia/qpwgraph/spec
Labels: upgrade

#9090 systemd: Fix booting problem with QEMU user emulation
  app-admin/systemd/autobuild/patches/0001-sleep.conf-AllowHibernation-no-by-default.patch
  app-admin/systemd/autobuild/patches/0002-main.c-revert-part-of-systemd-systemd-31442.patch
  app-admin/systemd/autobuild/patches/0003-fix-do-not-tint-terminal-by-default.patch
  app-admin/systemd/autobuild/patches/0004-exec-credential-try-forking-again-without-CLONE_NEWN.patch
  app-admin/systemd/spec
Labels: has-fix

#8824 go-md2man: update to 2.0.5
  app-doc/go-md2man/spec
Labels: upgrade

#9103 oma: update to 1.13.1
  app-admin/oma/spec
Labels: upgrade

#9105 kde-base: fix plasma-pk-update => plasma-pk-updates
  meta-bases/kde-base/autobuild/defines
  meta-bases/kde-base/spec
Labels: upgrade, has-fix

#9104 vim: update to 9.1.0969
  app-editors/vim/spec
Labels: upgrade

#9106 v2ray-rules-dat: update to 202412282210
  runtime-data/v2ray-rules-dat/spec
Labels: upgrade

#9111 autobuild4: update to 4.7.1
  app-devel/autobuild4/spec
Labels: upgrade

#9113 aoscbootstrap: update to 0.8.1
  app-utils/aoscbootstrap/spec
Labels: upgrade

#9115 graphviz: update to 12.2.1
  app-doc/graphviz/spec
Labels: upgrade

#9116 oma: update to 1.13.2
  app-admin/oma/spec
Labels: upgrade

#9084 davfs2: new, 1.7.1
  app-admin/davfs2/autobuild/defines
  app-admin/davfs2/autobuild/patches/0001-AOSCOS-configure.ac-support-detecting-neon-0.33.x.patch
  app-admin/davfs2/spec
Labels: new-packages

#9062 zed: update to 0.166.1
  app-editors/zed/spec
Labels: upgrade
