Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-07, with the labels that each got.

#6826 wireplumber: update to 0.5.5
  app-multimedia/wireplumber/spec
Labels: upgrade

#6830 openssh: update to 9.8p1
  app-network/openssh/spec
Labels: upgrade, security, 0day

#6831 openssh: update to 9.8p1-1
  app-network/openssh/autobuild/overrides/usr/lib/systemd/system/sshd.service
  app-network/openssh/autobuild/overrides/usr/lib/systemd/system/sshd.socket
  app-network/openssh/autobuild/overrides/usr/lib/systemd/system/sshd@.service
  app-network/openssh/autobuild/postinst
  app-network/openssh/spec
Labels: upgrade

#6819 firefox: update to 127.0.2
  app-web/firefox/autobuild/defines
  app-web/firefox/spec
Labels: upgrade

#6793 tig: update to 2.5.10
  app-utils/tig/spec
Labels: upgrade

#6817 handbrake: update to 1.8.1
  app-multimedia/handbrake/spec
Labels: upgrade

#6812 dill: update to 0.3.8
  lang-python/dill/spec
Labels: upgrade

#6794 shadowsocks-rust: update to 1.20.1
  app-network/shadowsocks-rust/spec
Labels: upgrade

#6818 vlc: update to 3.0.21
  app-multimedia/vlc/spec
Labels: upgrade

#6811 botocore: update to 1.34.133
  lang-python/botocore/spec
Labels: upgrade

#6806 sscg: update to 3.0.5
  app-cryptography/sscg/spec
Labels: upgrade

#6886 oma: update to 1.3.21
  app-admin/oma/spec
Labels: upgrade

#6896 autobuild4: add tomli dep for pep517-helper
  app-devel/autobuild4/autobuild/defines
  app-devel/autobuild4/spec
Labels: dependencies

#6893 libva: update to 2.22.0
  runtime-multimedia/libva/spec
Labels: upgrade

#6894 libva-nvidia-driver (nvidia-vaapi-driver): update to 0.0.12
  runtime-multimedia/libva-nvidia-driver/autobuild/config
  runtime-multimedia/libva-nvidia-driver/autobuild/defines
  runtime-multimedia/libva-nvidia-driver/autobuild/postinst
  runtime-multimedia/libva-nvidia-driver/autobuild/templates
  runtime-multimedia/libva-nvidia-driver/spec
Labels: upgrade

#6925 sdl2: update to 2.30.4
  runtime-multimedia/sdl2/spec
Labels: upgrade

#6929 ly: drop, orphaned
  desktop-displaymanagers/ly/autobuild/build
  desktop-displaymanagers/ly/autobuild/defines
  desktop-displaymanagers/ly/spec
Labels: drop-package

#6931 tailscale: update to 1.68.2
  app-network/tailscale/spec
Labels: upgrade

#6930 feh: update to 3.10.3
  app-imaging/feh/spec
Labels: upgrade

#6902 httpd (Apache HTTPD): update to 2.4.61
  app-web/httpd/autobuild/patches/0001-Fedora-Detect-systemd-dependency.patch
  app-web/httpd/autobuild/patches/0002-Fedora-More-verbose-startup-logging-for-mod_systemd.patch
  app-web/httpd/autobuild/patches/0003-Fedora-Implement-systemd-socket-activation.patch
  app-web/httpd/autobuild/patches/0004-Fedora-Fix-envvars-install-location.patch
  app-web/httpd/spec
Labels: upgrade, security, 0day

#6932 ca-certs: update to 20240703
  runtime-data/ca-certs/spec
Labels: upgrade

#6920 findutils: update to 4.10.0
  app-utils/findutils/spec
Labels: upgrade

#6898 superslicer: update to 2.5.60.0
  app-creativity/superslicer/autobuild/patches/0005-SeamPlacer-fix-potential-crashing-issue.patch
  app-creativity/superslicer/spec
Labels: upgrade

#6891 pcre2: update to 10.44
  runtime-common/pcre2/autobuild/defines
  runtime-common/pcre2/spec
Labels: upgrade

#6945 autobuild4: add python-{build,installer}, wheel deps
  app-devel/autobuild4/autobuild/defines
  app-devel/autobuild4/spec
Labels: dependencies

#6944 zig: update to 0.12.1
  lang-ziglang/zig/spec
Labels: upgrade

#6966 steam: fix input text
  app-games/steam/autobuild/patches/0001-fix-steam.desktop-make-sure-Steam-recognises-our-32-.patch
  app-games/steam/autobuild/patches/0002-hack-fix-IME-input-text.patch
  app-games/steam/spec
Labels: has-fix

#6969 qt-5: lessen total_mem to 60
  runtime-desktop/qt-5/spec
Labels: enhancement

#6971 deploykit-backend: update to 0.6.0
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#6967 deploykit-gui: update to 0.7.0
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#6970 aoscbootstrap: update to 0.5.1
  app-utils/aoscbootstrap/autobuild/beyond
  app-utils/aoscbootstrap/autobuild/defines
  app-utils/aoscbootstrap/autobuild/prepare
  app-utils/aoscbootstrap/spec
Labels: upgrade

#6972 lxgwnewcleargothic-font: update to 1.123.2
  desktop-fonts/lxgwnewcleargothic-font/spec
Labels: upgrade, new-packages

#6975 snapper: update to 0.11.1
  app-admin/snapper/spec
Labels: upgrade

#6977 deploykit-gui: update to 0.7.1
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#6980 deploykit-backend: update to 0.6.1
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#6965 oma: update to 1.3.22
  app-admin/oma/spec
Labels: upgrade

#6989 deploykit-gui: update to 0.7.2
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#6996 urfkill: fix ftbfs
  app-admin/urfkill/autobuild/patches/0001-fix-autoconf-ftbfs.patch
  app-admin/urfkill/spec
Labels: ftbfs, has-fix

#7001 pipewire: update to 1.2.1
  app-multimedia/pipewire/spec
Labels: upgrade

#6991 nodejs: security update to 20.15.1
  lang-js/nodejs/autobuild/defines
  lang-js/nodejs/autobuild/prepare
  lang-js/nodejs/spec
Labels: upgrade, security

#6982 gdb: update to 15.1
  app-devel/gdb/spec
Labels: upgrade

#6973 hugo: update to 0.128.2
  app-web/hugo/autobuild/defines
  app-web/hugo/spec
Labels: upgrade

#6814 tree-sitter: update to 0.22.6
  runtime-editors/tree-sitter/spec
Labels: upgrade

#6984 lxgwnewcleargothic-font: update to 1.124
  desktop-fonts/lxgwnewcleargothic-font/spec
Labels: upgrade, new-packages

#6990 fcitx5-pinyin-moegirl: update to 20240709
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#6983 abbs-update-checksum: update to 0.2.0
  app-devel/abbs-update-checksum/spec
Labels: upgrade

#6997 OBS Studio Rework - re-enable jack and update cef
  app-multimedia/obs-studio/autobuild/defines
  app-multimedia/obs-studio/autobuild/patches/0002-cef-122.0-api.patch
  app-multimedia/obs-studio/autobuild/prepare
  app-multimedia/obs-studio/spec
Labels: upstream-issue, rework

#7003 fastfetch: update to 2.17.2
  app-utils/fastfetch/spec
Labels: upgrade

#7009 xdg-user-dirs-gtk: update to 0.11
  desktop-gnome/xdg-user-dirs-gtk/spec
Labels: upgrade

#6805 picard: update to 2.12
  app-multimedia/picard/spec
Labels: upgrade

#6962 imath: update to 3.1.11
  runtime-display/imath/spec
Labels: upgrade

#7023 automake update to 1.17
  app-devel/automake/autobuild/patches/0001-Hack-bump-automake-version-to-1.16.5.patch
  app-devel/automake/spec
Labels: upgrade

#7000 powershell: update to 7.4.3
  app-shells/powershell/autobuild/defines
  app-shells/powershell/autobuild/patches/0001-add-aosc-to-support-list.patch
  app-shells/powershell/autobuild/prepare
  app-shells/powershell/spec
Labels: upgrade

#7027 osu-lazer: update to 2024.625.3
  app-games/osu-lazer/spec
Labels: upgrade

#6976 godot: new, 4.2.2
  app-devel/godot/autobuild/build
  app-devel/godot/autobuild/defines
  app-devel/godot/autobuild/overrides/usr/bin/godot
  app-devel/godot/autobuild/overrides/usr/share/applications/godot.desktop
  app-devel/godot/spec
Labels: new-packages

#7031 deploykit-backend: update to 0.6.3
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#7032 deploykit-gui: update to 0.7.3
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#7016 xwayland: update to 24.1.1
  runtime-display/xwayland/spec
Labels: upgrade

#6999 libaio: update to 0.3.113 and fix loongson3
  runtime-common/libaio/autobuild/build
  runtime-common/libaio/autobuild/defines
  runtime-common/libaio/autobuild/patches/0001-Fix-and-improve-MIPS-support.patch
  runtime-common/libaio/autobuild/patches/libaio-remove-nostartfiles-nostdlib-from-build-flags.patch
  runtime-common/libaio/spec
Labels: upgrade, has-fix

#6928 pygobject-3 update to 3.48.2
  lang-python/pygobject-3/autobuild/defines
  lang-python/pygobject-3/spec
Labels: upgrade

#7052 nano: update to 8.1+nanorc2024.1.16
  app-editors/nano/autobuild/patches/0001-Revert-bindings-set-up-modern-bindings-also-when-bin.patch
  app-editors/nano/spec
Labels: upgrade

#7061 udns: update to 0.5
  app-network/udns/spec
Labels: upgrade

#7062 opus: update to 1.5.2
  runtime-multimedia/opus/spec
Labels: upgrade

#7063 xsel: update to 1.2.1
  app-utils/xsel/autobuild/build
  app-utils/xsel/autobuild/prepare
  app-utils/xsel/spec
Labels: upgrade

#7059 telegram-desktop: update to 5.2.3
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#7065 libglvnd: temporary Spiral fix for Tencent QQ
  runtime-display/libglvnd/autobuild/defines
  runtime-display/libglvnd/spec
Labels: has-fix

#7069 oma: update to 1.3.23
  app-admin/oma/spec
Labels: upgrade

#7077 boost: fix a typo in PKGBREAK
  runtime-common/boost/autobuild/defines
  runtime-common/boost/spec
Labels: has-fix

#7079 oma: update to 1.3.24
  app-admin/oma/spec
Labels: upgrade

#7082 oma: update to 1.3.25
  app-admin/oma/spec
Labels: upgrade

#7083 nvidia (NVIDIA Proprietary Drivers): update to 555.58.02
  runtime-display/nvidia/spec
Labels: upgrade

#7092 oma: update to 1.3.26
  app-admin/oma/spec
Labels: upgrade

#7093 ciel: update to 3.2.7
  app-devel/ciel/spec
Labels: upgrade

#7099 acbs: update to 20240717.1
  app-devel/acbs/spec
Labels: upgrade

#7105 oma: update to 1.3.28
  app-admin/oma/spec
Labels: upgrade

#7095 docker (Docker): fix postinst for systemd 256
  app-containers/docker/autobuild/overrides/usr/lib/systemd/system-preset/40-docker.preset
  app-containers/docker/autobuild/postinst
  app-containers/docker/spec
Labels: has-fix

#7076 qemu (QEMU): install binfmt configuration conditionally for official ports
  app-virtualization/qemu/02-static-aarch64/arm64/beyond
  app-virtualization/qemu/02-static-aarch64/build
  app-virtualization/qemu/03-static-alpha/build
  app-virtualization/qemu/04-static-arm/build
  app-virtualization/qemu/08-static-m68k/build
  app-virtualization/qemu/13-static-mips64el/build
  app-virtualization/qemu/13-static-mips64el/loongson3/beyond
  app-virtualization/qemu/14-static-mipsel/build
  app-virtualization/qemu/14-static-mipsel/loongson3/beyond
  app-virtualization/qemu/18-static-ppc/build
  app-virtualization/qemu/18-static-ppc/ppc64el/beyond
  app-virtualization/qemu/19-static-ppc64/build
  app-virtualization/qemu/19-static-ppc64/ppc64el/beyond
  app-virtualization/qemu/21-static-ppc64le/build
  app-virtualization/qemu/21-static-ppc64le/ppc64el/beyond
  app-virtualization/qemu/25-static-sparc/build
  app-virtualization/qemu/27-static-sparc64/build
  app-virtualization/qemu/30-static-riscv64/build
  app-virtualization/qemu/30-static-riscv64/riscv64/beyond
  app-virtualization/qemu/33-static-loongarch64/build
  app-virtualization/qemu/spec
Labels: has-fix

#7014 fastfetch: update to 2.18.1
  app-utils/fastfetch/autobuild/defines
  app-utils/fastfetch/spec
Labels: upgrade

#7085 texlive: update to 20240312
  app-doc/texlive/spec
Labels: upgrade

#7119 boost: bump REL (again) due to icu update to 74.2
  runtime-common/boost/spec
Labels: upgrade

#7120 noise-suppression-for-voice: update to 1.10
  app-multimedia/noise-suppression-for-voice/autobuild/defines
  app-multimedia/noise-suppression-for-voice/spec
Labels: upgrade

#7121 waybar: update to 0.10.4
  app-utils/waybar/spec
Labels: upgrade

#7114 autobuild4: update to 4.3.7
  app-devel/autobuild4/spec
Labels: upgrade

#7128 zed: update to 0.144.3
  app-editors/zed/autobuild/patches/0001-Disable-check-update-and-not-use-rust-toolchain.toml.patch
  app-editors/zed/autobuild/patches/0001-cargo-use-default-release-build-settings.patch
  app-editors/zed/autobuild/prepare
  app-editors/zed/spec
Labels: upgrade

#7139 bili-sync: new, 2.1.1
  app-multimedia/bili-sync/autobuild/beyond
  app-multimedia/bili-sync/autobuild/defines
  app-multimedia/bili-sync/spec
Labels: new-package

#7053 exim: update to 4.98
  app-web/exim/spec
Labels: upgrade

#7149 dropbox: drop, orphaned
  app-web/dropbox/autobuild/build
  app-web/dropbox/autobuild/defines
  app-web/dropbox/autobuild/overrides/usr/lib/systemd/system/dropbox.service
  app-web/dropbox/autobuild/overrides/usr/lib/systemd/system/dropbox@.service
  app-web/dropbox/autobuild/overrides/usr/share/applications/dropbox.desktop
  app-web/dropbox/autobuild/overrides/usr/share/pixmaps/dropbox.svg
  app-web/dropbox/spec
Labels: drop-package

#7033 cairo update to 1.18.0
  runtime-imaging/cairo/autobuild/defines
  runtime-imaging/cairo/autobuild/patches/0001-cairo-lcdfilter-make-default-default.patch
  runtime-imaging/cairo/autobuild/patches/0002-cairo-respect-fontconfig_pb.patch
  runtime-imaging/cairo/autobuild/patches/0003-cairo-server-side-gradients.patch
  runtime-imaging/cairo/autobuild/patches/0004-cairo-webkit-html5-fix.patch
  runtime-imaging/cairo/spec
Labels: upgrade

#7150 containers-common: update to 0.59.2
  runtime-containers/containers-common/spec
Labels: upgrade

#7169 systemd: disable networkd related services in the default preset
  app-admin/systemd/autobuild/patches/0001-sleep.conf-AllowHibernation-no-by-default.patch
  app-admin/systemd/autobuild/patches/0002-vmspawn-define-default-machines-for-mips-targets.patch
  app-admin/systemd/autobuild/patches/0003-presets-disable-systemd-networkd-and-systemd-network.patch
  app-admin/systemd/spec
Labels: enhancement

#7100 bcrypt: update to 4.1.3
  lang-python/bcrypt/autobuild/defines
  lang-python/bcrypt/autobuild/patches/0001-Cargo.toml-enable-debug-info-for-release-profile.patch
  lang-python/bcrypt/spec
Labels: upgrade

#7127 kubectl: new, 1.30.3
  app-containers/kubectl/autobuild/build
  app-containers/kubectl/autobuild/defines
  app-containers/kubectl/spec
Labels: new-package

#7060 verilator: update to 5.026
  app-electronics/verilator/autobuild/patches/0001-Fix-binary-install-path.patch
  app-electronics/verilator/autobuild/prepare
  app-electronics/verilator/spec
Labels: upgrade

#7167 httpd: security update to 2.4.62
  app-web/httpd/spec
Labels: upgrade, security

#7144 libreoffice (LibreOffice): rework for ICU 74.2
  app-productivity/libreoffice/spec
Labels: rework

#7171 texlive: update to 20240312 (rework)
  app-doc/texlive/autobuild/postinst
  app-doc/texlive/spec
Labels: upgrade, rework

#7182 deploykit-backend: update to 0.6.4
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#7183 deploykit-gui: update to 0.7.4
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#7187 oma: update to 1.3.29
  app-admin/oma/spec
Labels: upgrade

#7174 jenkins: new, 2.468
  app-admin/jenkins/autobuild/build
  app-admin/jenkins/autobuild/defines
  app-admin/jenkins/autobuild/overrides/etc/conf.d/jenkins
  app-admin/jenkins/autobuild/overrides/usr/lib/systemd/system/jenkins.service
  app-admin/jenkins/autobuild/overrides/usr/lib/sysusers.d/jenkins.conf
  app-admin/jenkins/autobuild/overrides/usr/lib/tmpfiles.d/jenkins.conf
  app-admin/jenkins/autobuild/postinst
  app-admin/jenkins/spec
Labels: new-packages

#7198 libinput: update to 1.26.1
  runtime-devices/libinput/spec
Labels: upgrade

#7199 xorg-server: backport a patch to fix high-refresh panels' fitting
  runtime-display/xorg-server/autobuild/patches/0004-BACKPORT-hw-xfree86-re-calculate-the-clock-and-refresh-rate.patch
  runtime-display/xorg-server/spec
Labels: has-fix

#7200 oma: update to 1.3.30
  app-admin/oma/spec
Labels: upgrade

#7215 --now removal for systemctl preset commands in postinst (Wave 1)
  app-admin/cockpit/autobuild/postinst
  app-admin/cockpit/spec
Labels: has-fix

#7217 sof-firmware: update to 2024.06
  runtime-kernel/sof-firmware/spec
Labels: upgrade

#7224 discord: update to 0.0.61
  app-web/discord/spec
Labels: upgrade

#7211 wpa-supplicant: update to 2.11
  app-network/wpa-supplicant/autobuild/patches/0007-nl80211-add-extra-ies-only-if-allowed-by-driver.patch
  app-network/wpa-supplicant/spec
Labels: upgrade, has-fix, hardware-support

#7213 samtools: upgrade to 1.20
  app-scientific/htslib/autobuild/defines
  app-scientific/htslib/autobuild/patches/0001-fix-so-permission.patch
  app-scientific/htslib/spec
  app-scientific/samtools/spec
Labels: upgrade

#7223 lz4: update to 1.10.0
  app-utils/lz4/spec
Labels: upgrade

#7226 dkcli: new, 0.1.0
  app-admin/dkcli/autobuild/defines
  app-admin/dkcli/spec
Labels: new-packages

#7238 xray-plugin: update to 1.8.17
  app-network/xray-plugin/spec
Labels: upgrade

#7227 libolm: new, 3.2.16
  runtime-web/libolm/autobuild/defines
  runtime-web/libolm/spec
Labels: new-packages

#7241 oma: update to 1.3.31
  app-admin/oma/spec
Labels: upgrade

#7236 brltty: fix build
  app-a11y/brltty/autobuild/prepare
  app-a11y/brltty/spec
Labels: has-fix

#7232 bind: security update to 9.18.28
  app-network/bind/spec
Labels: upgrade, security

#7212 broadcom-wl: reinstate, 6.30.223.271-5
  runtime-kernel/broadcom-wl/autobuild/build
  runtime-kernel/broadcom-wl/autobuild/defines
  runtime-kernel/broadcom-wl/autobuild/dkms.conf.in
  runtime-kernel/broadcom-wl/autobuild/overrides/usr/lib/modprobe.d/broadcom-wl-dkms.conf
  runtime-kernel/broadcom-wl/autobuild/patch
  runtime-kernel/broadcom-wl/autobuild/patches/001-null-pointer-fix.patch
  runtime-kernel/broadcom-wl/autobuild/patches/002-rdtscl.patch
  runtime-kernel/broadcom-wl/autobuild/patches/003-linux47.patch
  runtime-kernel/broadcom-wl/autobuild/patches/004-linux48.patch
  runtime-kernel/broadcom-wl/autobuild/patches/005-debian-fix-kernel-warnings.patch
  runtime-kernel/broadcom-wl/autobuild/patches/006-linux411.patch
  runtime-kernel/broadcom-wl/autobuild/patches/007-linux412.patch
  runtime-kernel/broadcom-wl/autobuild/patches/008-linux415.patch
  runtime-kernel/broadcom-wl/autobuild/patches/010-linux56.patch
  runtime-kernel/broadcom-wl/autobuild/patches/011-linux59.patch
  runtime-kernel/broadcom-wl/autobuild/patches/012-linux517.patch
  runtime-kernel/broadcom-wl/autobuild/patches/013-linux518.patch
  runtime-kernel/broadcom-wl/autobuild/patches/014-linux414.patch
  runtime-kernel/broadcom-wl/autobuild/patches/015-linux600.patch
  runtime-kernel/broadcom-wl/autobuild/patches/016-linux601.patch
  runtime-kernel/broadcom-wl/autobuild/patches/05-remove-time-and-date-macros.patch
  runtime-kernel/broadcom-wl/autobuild/patches/aosc-1-wlan-ifname.patch
  runtime-kernel/broadcom-wl/autobuild/patches/aosc-2-blob-path.patch
  runtime-kernel/broadcom-wl/autobuild/postinst.in
  runtime-kernel/broadcom-wl/autobuild/prepare
  runtime-kernel/broadcom-wl/autobuild/prerm.in
  runtime-kernel/broadcom-wl/spec
Labels: new-package

#7244 autobuild4: update to 4.3.8
  app-devel/autobuild4/spec
Labels: upgrade

#7255 osu-lazer: update to 2024.718.1
  app-games/osu-lazer/spec
Labels: upgrade

#7254 obs-studio: update to 30.2.2
  app-multimedia/obs-studio/spec
Labels: upgrade

#7266 wine-emukit (Wine for EmuKit): update to 9.13
  app-emulation/wine-emukit/spec
Labels: upgrade

#7269 libcamera: update to 0.3.1
  runtime-devices/libcamera/spec
Labels: upgrade

#6927 cloud-init: update to 24.2
  app-admin/cloud-init/autobuild/patches/0001-feat-aosc-Add-AOSC-OS-support-5310.patch
  app-admin/cloud-init/autobuild/patches/0002-fix-add-host-template-for-AOSC.patch
  app-admin/cloud-init/spec
Labels: upgrade

#7271 libolm: 3.2.16 rework
  runtime-web/libolm/autobuild/defines
Labels: rework

#7272 oma: update to 1.3.32
  app-admin/oma/spec
Labels: upgrade

#7273 zed: update to 0.145.1
  app-editors/zed/spec
Labels: upgrade

#7283 oma: update to 1.3.33
  app-admin/oma/spec
Labels: upgrade

#7280 firefox: update to 128.0.3
  app-web/firefox/autobuild/patches/0001-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0002-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0003-Enable-WebRTC-for-LoongArch.patch
  app-web/firefox/autobuild/patches/0004-Fix-libyuv-build-with-LSX-LASX.patch
  app-web/firefox/autobuild/patches/0005-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0006-Keep-unsigned-32-bit-parameter-sign-extended-in-regi.patch
  app-web/firefox/autobuild/patches/0007-Implement-SummarizeTrapInstruction-for-MIPS64.patch
  app-web/firefox/autobuild/patches/0008-Bug-1855960-MIPS64-Make-some-assembler-routines-retu.patch
  app-web/firefox/autobuild/patches/0009-Add-missing-loongarch-lsx-code-for-libpng.patch
  app-web/firefox/autobuild/patches/0010-Revert-MoveEmitter-mips64.cpp-part-in-Bug-1870747-Us.patch
  app-web/firefox/autobuild/patches/0011-Add-move8ZeroExtend-for-mips.patch
  app-web/firefox/spec
Labels: upgrade

#7290 aoscbootstrap: update to 0.6.0
  app-utils/aoscbootstrap/spec
Labels: upgrade

#7289 deploykit-gui: update to 0.7.7
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#7281 systemd: update to 256.4
  app-admin/systemd/autobuild/patches/0001-sleep.conf-AllowHibernation-no-by-default.patch
  app-admin/systemd/autobuild/patches/0002-presets-disable-systemd-networkd-and-systemd-network.patch
  app-admin/systemd/autobuild/patches/0002-vmspawn-define-default-machines-for-mips-targets.patch
  app-admin/systemd/autobuild/patches/0003-main.c-revert-part-of-systemd-systemd-31442.patch
  app-admin/systemd/spec
Labels: upgrade

#7292 linux-kernel-lts: fix Kconfig for R6
  runtime-kernel/linux-kernel-lts/autobuild/mips64r6el/config
Labels: has-fix, cip-pilot

#7267 tio: new, 3.6
  app-utils/tio/autobuild/defines
  app-utils/tio/spec
Labels: new-packages

#7091 libvirt-python: update to 10.5.0
  runtime-virtualization/libvirt-python/spec
Labels: upgrade

#7162 mesa: update to 24.1.4+dxheaders1.614.0
  runtime-display/mesa/spec
Labels: upgrade

#7333 rclone: update to 1.67.0
  app-web/rclone/autobuild/defines
  app-web/rclone/spec
Labels: upgrade

#7347 oma: update to 1.3.35
  app-admin/oma/spec
Labels: upgrade

#7351 autobuild4: update to 4.3.9
  app-devel/autobuild4/spec
Labels: upgrade

#7287 fwupd: update to 1.9.22
  app-admin/fwupd/spec
Labels: upgrade

#7387 osu-lazer: fix StartWMClass in desktop entry, update mime types
  app-games/osu-lazer/autobuild/overrides/usr/share/applications/osu.desktop
  app-games/osu-lazer/autobuild/overrides/usr/share/mime/packages/osu-lazer.xml
  app-games/osu-lazer/spec
Labels: upgrade, has-fix

#7389 wine (WineHQ): update to 9.14
  app-emulation/wine/spec
Labels: upgrade

#7386 lilypond: update to 2.24.4
  app-multimedia/lilypond/autobuild/defines
  app-multimedia/lilypond/autobuild/prepare
  app-multimedia/lilypond/spec
Labels: upgrade

#7391 mirrormgr: update to 0.10.4
  app-admin/mirrormgr/spec
Labels: upgrade

#7402 openttd: update to 14.1
  app-games/openttd/spec
Labels: upgrade

#7409 deploykit-gui: update to 0.8.0
  app-admin/deploykit-gui/spec
Labels: upgrade

#7415 git: update to 2.46.0
  app-vcs/git/spec
Labels: upgrade

#7414 select-language-tui: update to 0.4.0
  app-utils/select-language-tui/spec
Labels: upgrade

#7397 aom update to 3.9.1
  runtime-multimedia/aom/autobuild/build
  runtime-multimedia/aom/autobuild/defines
  runtime-multimedia/aom/spec
Labels: upgrade

#7417 discord: update to 0.0.62
  app-web/discord/spec
Labels: upgrade

#7418 virtualbox (Oracle VM VirtualBox): update to 7.0.20
  app-virtualization/virtualbox/spec
Labels: upgrade

#7425 pushpkg: update to 0+git20240731
  app-devel/pushpkg/autobuild/build
  app-devel/pushpkg/spec
Labels: upgrade
