Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-10, with the labels that each got.

#8135 qbittorrent: update to 5.0.0
  app-web/qbittorrent/01-gui/defines
  app-web/qbittorrent/01-gui/patches/0001-Disable-strip-during-build-time.patch
  app-web/qbittorrent/02-nox/defines
  app-web/qbittorrent/spec
Labels: upgrade

#8133 zvm: update to 0.7.6
  lang-ziglang/zvm/autobuild/overrides/etc/bashrc.d/zvm.sh
  lang-ziglang/zvm/spec
Labels: upgrade

#8144 nvidia: add patches for Linux kernel 6.12.0-rc1
  runtime-display/nvidia/autobuild/patches/0001-FROM-CACHYOS-Fix-for-fbdev-on-Linux-kernel-6.11.patch
  runtime-display/nvidia/autobuild/patches/0002-FROM-AOSC-Fix-for-6.12.0-rc1-drm_mode_config_funcs.o.patch
  runtime-display/nvidia/spec
Labels: bug

#8143 stellarium: update to 24.3
  app-scientific/stellarium/spec
Labels: upgrade, security

#8140 squashfs-tools: update to 4.6.1
  app-admin/squashfs-tools/autobuild/build
  app-admin/squashfs-tools/autobuild/defines
  app-admin/squashfs-tools/autobuild/patches/0001-Avoid-use-of-INSTALL_DIR-for-symlink-targets.patch
  app-admin/squashfs-tools/autobuild/patches/0002-unsquashfs-use-squashfs_closedir-to-delete-directory.patch
  app-admin/squashfs-tools/autobuild/patches/0003-unsquashfs-dynamically-allocate-name.patch
  app-admin/squashfs-tools/autobuild/patches/0004-unsquashfs-use-linked-list-to-store-directory-names.patch
  app-admin/squashfs-tools/autobuild/patches/0005-Unsquashfs-additional-write-outside-destination-dire.patch
  app-admin/squashfs-tools/autobuild/patches/0006-Unsquashfs-Add-makefile-entry-for-unsquash-12.o.patch
  app-admin/squashfs-tools/autobuild/prepare
  app-admin/squashfs-tools/spec
Labels: upgrade

#8127 ffmpeg: update to 7.1
  app-multimedia/ffmpeg/autobuild/patches/0001-avcodec-mips-Add-switch-for-MADD-instruction.patch
  app-multimedia/ffmpeg/autobuild/patches/0001-fix-libavutil-mips-Only-use-cpuinfo-to-read-cpu-ISAs.patch
  app-multimedia/ffmpeg/autobuild/patches/0002-Add-av_stream_get_first_dts-for-Chromium.patch
  app-multimedia/ffmpeg/autobuild/patches/0003-lavc-vaapi_decode-Make-it-possible-to-send-multiple-.patch
  app-multimedia/ffmpeg/autobuild/patches/0004-lavc-vaapi_av1-Avoid-sending-the-same-slice-buffer-m.patch
  app-multimedia/ffmpeg/spec
Labels: upgrade

#8138 just: update to 1.36.0
  app-devel/just/autobuild/beyond
  app-devel/just/spec
Labels: upgrade

#8146 fastfetch: update to 2.26.1
  app-utils/fastfetch/spec
Labels: upgrade

#8142 powershell: update to 7.4.5
  app-shells/powershell/spec
Labels: upgrade

#8150 midori: drop a profile file that pollutes env for all gtk apps
  app-web/midori/autobuild/overrides/etc/profile.d/midori-csd.sh
  app-web/midori/spec
Labels: drop-package

#8148 podman: rework 5.2.3
  app-containers/podman/autobuild/defines
  app-containers/podman/spec
Labels: rework

#8131 virtualbox: update to 7.1.2
  app-virtualization/virtualbox/01-host/patches/0001-FROM-ARCHLINUX-fix-Frontends-VirtualBox-disable-upda.patch
  app-virtualization/virtualbox/01-host/patches/0002-FROM-ARCHLINUX-fix-VBox-Additions-disable-unneeded-v.patch
  app-virtualization/virtualbox/01-host/patches/0002-FROM-ARCHLINUX-properly-handle-i3wm.patch
  app-virtualization/virtualbox/01-host/patches/0003-FROM-ARCHLINUX-support-building-from-dkms.patch
  app-virtualization/virtualbox/01-host/patches/0004-FROM-ARCHLINUX-fix-VBox-Additions-disable-vbglR3Gues.patch
  app-virtualization/virtualbox/01-host/patches/0004-FROM-ARCHLINUX-upate-xclient-script.patch
  app-virtualization/virtualbox/01-host/patches/0005-FROM-AOSC-fix-libs-dxvk-fix-build-with-GCC-13.patch
  app-virtualization/virtualbox/01-host/patches/0006-FROM-AOSC-chore-use-the-wheel-group-for-hardware-acc.patch
  app-virtualization/virtualbox/01-host/patches/0007-FROM-AOSC-fix-dxvk-native-1.9.2a-fix-build-with-GCC-.patch
  app-virtualization/virtualbox/01-host/patches/0007-FROM-ARCHLINUX-fix-python-3.12-compatibility.patch
  app-virtualization/virtualbox/01-host/patches/0008-FROM-AOSC-Link-against-vorbisenc.patch
  app-virtualization/virtualbox/01-host/patches/0009-FROM-AOSC-Add-gitignore.patch
  app-virtualization/virtualbox/01-host/patches/0010-FROM-AOSC-Add-localinst.sh.patch
  app-virtualization/virtualbox/spec
Labels: upgrade

#8154 oma: update to 1.11.0
  app-admin/oma/spec
Labels: upgrade

#8156 stressapptest (Stressful Application Test): new, 1.0.11
  app-benchmarks/stressapptest/autobuild/defines
  app-benchmarks/stressapptest/spec
Labels: new-packages

#8159 oath-toolkit: update to 2.6.12
  app-admin/oath-toolkit/spec
Labels: upgrade, security

#8081 gmsynth.lv2: new, 0.6.0
  app-multimedia/gmsynth.lv2/autobuild/build
  app-multimedia/gmsynth.lv2/autobuild/defines
  app-multimedia/gmsynth.lv2/spec
Labels: new-packages

#8153 waylyrics: new, 0.3.16
  app-multimedia/waylyrics/autobuild/beyond
  app-multimedia/waylyrics/autobuild/defines
  app-multimedia/waylyrics/autobuild/prepare
  app-multimedia/waylyrics/spec
Labels: new-packages

#8089 dynamorio: new, 10.0.0
  app-devel/dynamorio/autobuild/beyond
  app-devel/dynamorio/autobuild/defines
  app-devel/dynamorio/autobuild/prepare
  app-devel/dynamorio/spec
Labels: new-packages

#8168 svt-av1: update to 2.2.1
  runtime-multimedia/svt-av1/spec
Labels: upgrade

#8166 qt-6: update to 6.7.3
  runtime-desktop/qt-6/autobuild/patches/0001-Arch-Linux-qtbase-respect-system-compiler-linker-fla.patch
  runtime-desktop/qt-6/autobuild/patches/0002-Fedora-qt3d-assimp-fix-build-with-GCC-13.patch
  runtime-desktop/qt-6/autobuild/patches/0003-Gentoo-qtwebengine-chromium-add-a-missing-header-for.patch
  runtime-desktop/qt-6/autobuild/patches/0004-Gentoo-qtwebengine-chromium-fix-build-time-race-cond.patch
  runtime-desktop/qt-6/autobuild/patches/0005-qtbase-fallback-to-GLES-if-GL-EGL-context-creation-f.patch
  runtime-desktop/qt-6/autobuild/patches/0006-Fixup-Fix-building-with-system-ffmpeg.patch
  runtime-desktop/qt-6/autobuild/patches/0007-Revert-xcb-handle-XI2-input-button-and-motion-events.patch
  runtime-desktop/qt-6/autobuild/patches/0008-Revert-QQmlDelegateModel-fix-delegates-not-being-cre.patch
  runtime-desktop/qt-6/autobuild/patches/0009-QQmlDelegateModel-fix-delegates-not-being-created-in.patch
  runtime-desktop/qt-6/autobuild/patches/0010-QAbstractItemModelPrivate-add-resetting-member.patch
  runtime-desktop/qt-6/autobuild/patches/0011-LOONGARCH64-qtwebengine-chromium-skip-unreliable-ter.patch.loongarch64
  runtime-desktop/qt-6/autobuild/patches/0012-LOONGARCH64-qtwebengine-chromium-add-LoongArch-suppo.patch.loongarch64
  runtime-desktop/qt-6/spec
Labels: upgrade

#8172 waylyrics: update to 0.3.17
  app-multimedia/waylyrics/spec
Labels: upgrade

#8165 mesa: update to 24.2.4+dxheaders1.614.1
  runtime-display/mesa/spec
Labels: upgrade

#8175 fvwm (F Virtual Window Manager): drop, orphaned
  desktop-wm/fvwm/autobuild/defines
  desktop-wm/fvwm/spec
Labels: drop-package

#8171 nodejs: update to 20.18.0
  lang-js/nodejs/spec
Labels: upgrade

#8179 pandoc: update to 3.5
  app-doc/pandoc/spec
Labels: upgrade

#8164 wine: update to 9.18+gecko2.47.4+mono9.3.0
  app-emulation/wine/spec
Labels: upgrade

#8182 iosevka-fonts: update to 31.8.0
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#8183 praat: update to 6.4.22
  app-scientific/praat/spec
Labels: upgrade

#8178 mldonkey: drop, orphaned
  app-web/mldonkey/autobuild/beyond
  app-web/mldonkey/autobuild/build
  app-web/mldonkey/autobuild/conffiles
  app-web/mldonkey/autobuild/defines
  app-web/mldonkey/autobuild/overrides/etc/conf.d/mldonkey
  app-web/mldonkey/autobuild/overrides/etc/logrotate.d/mldonkey
  app-web/mldonkey/autobuild/overrides/usr/lib/systemd/system/mldonkey.service
  app-web/mldonkey/autobuild/overrides/usr/lib/tmpfiles.d/mldonkey.conf
  app-web/mldonkey/autobuild/postinst
  app-web/mldonkey/autobuild/prepare
  app-web/mldonkey/spec
Labels: drop-package

#8184 upx: update to 4.2.4
  app-devel/upx/spec
Labels: upgrade

#8162 godot: add loongarch64 support
  app-devel/godot/autobuild/build
  app-devel/godot/autobuild/defines
  app-devel/godot/autobuild/patches/0001-Add-loongarch64-support.patch
  app-devel/godot/autobuild/patches/0002-Ignore-case-when-parse-proc-cpuinfo.patch
  app-devel/godot/autobuild/patches/0003-Add-loongarch-support-for-bundled-OpenXR.patch
  app-devel/godot/spec
Labels: pre-release

#8188 qmidiarp: new, 0.7.1
  app-multimedia/qmidiarp/autobuild/defines
  app-multimedia/qmidiarp/spec
Labels: new-packages

#8100 git: update to 2.47.0
  app-vcs/git/spec
Labels: upgrade

#8060 steam: update to 1.0.0.81
  app-games/steam/autobuild/patches/0001-fix-steam.desktop-make-sure-Steam-recognises-our-32-.patch
  app-games/steam/autobuild/patches/0002-hack-fix-IME-input-text.patch
  app-games/steam/autobuild/postinst
  app-games/steam/spec
Labels: upgrade

#8181 openrazer: update to 3.9.0
  app-devices/openrazer/spec
Labels: upgrade

#8193 p-vector: update to 0.7.0
  app-admin/p-vector/spec
Labels: upgrade

#8218 nvchecker: update to 2.15.1
  app-utils/nvchecker/autobuild/defines
  app-utils/nvchecker/spec
Labels: upgrade

#8224 Linux Firmware Survey 20241009
  runtime-kernel/linux-firmware/spec
Labels: upgrade, survey

#8237 fastfetch: update to 2.27.1
  app-utils/fastfetch/spec
Labels: upgrade

#8228 linyaps: new, 1.6.3
  app-admin/linglong/autobuild/defines
  app-admin/linglong/spec
  app-admin/linyaps/autobuild/defines
  app-admin/linyaps/autobuild/postinst
  app-admin/linyaps/spec
Labels: new-packages

#8235 vscode: update to 1.94.1
  app-editors/vscode/spec
Labels: upgrade

#8232 thunderbird: update to 128.3.0esr
  app-web/thunderbird/autobuild/patches/0001-Fedora-0001-GLIBCXX-fix-for-GCC-12.patch.patch
  app-web/thunderbird/autobuild/patches/0001-UPSTREAM-Bug-1905842-set-patch-application-order-for.patch
  app-web/thunderbird/autobuild/patches/0002-UPSTREAM-Bug-1905842-add-patch-for-NEON64-and-SVE-gy.patch
  app-web/thunderbird/autobuild/patches/0003-UPSTREAM-Bug-1905842-add-dotprod-and-SVE-CPU-config-.patch
  app-web/thunderbird/autobuild/patches/0004-UPSTREAM-Bug-1905842-non-unified-build-scale_uv.cc-d.patch
  app-web/thunderbird/autobuild/patches/0005-UPSTREAM-Bug-1905842-update-libyuv-to-616bee5420b-r-.patch
  app-web/thunderbird/autobuild/patches/0006-UPSTREAM-Bug-1905842-update-libyuv-to-616bee5420b-ap.patch
  app-web/thunderbird/autobuild/patches/0007-BACKPORT-Bug-1855960-MIPS64-Make-some-assembler-rout.patch
  app-web/thunderbird/autobuild/patches/0008-FEDORA-0001-GLIBCXX-fix-for-GCC-12.patch.patch
  app-web/thunderbird/autobuild/patches/0009-Bug-1905842-non-unified-build-scale_uv.cc-due-to-Abs.patch
  app-web/thunderbird/autobuild/patches/0009-FEDORA-expat-CVE-2022-25235.patch.patch
  app-web/thunderbird/autobuild/patches/0010-FEDORA-expat-CVE-2022-25236.patch.patch
  app-web/thunderbird/autobuild/patches/0011-FEDORA-expat-CVE-2022-25315.patch.patch
  app-web/thunderbird/autobuild/patches/0012-BACKPORT-LOONGARCHLINUX-Add-support-for-LoongArch64.patch
  app-web/thunderbird/autobuild/patches/0013-AOSCOS-Implement-SummarizeTrapInstruction-for-MIPS64.patch
  app-web/thunderbird/autobuild/patches/0014-AOSCOS-Add-missing-loongarch-lsx-code-for-libpng.patch
  app-web/thunderbird/autobuild/patches/0015-AOSCOS-comm-botan-add-loongarch64-to-archinfo.patch
  app-web/thunderbird/autobuild/patches/0016-AOSCOS-Build-Loongson-SIMD-EXtension-LSX-and-Loongso.patch
  app-web/thunderbird/autobuild/patches/0017-WIP-AOSCOS-fix-xptcall-riscv-linker-issue.patch
  app-web/thunderbird/autobuild/patches/0018-WIP-AOSCOS-Keep-unsigned-32-bit-parameter-sign-exten.patch
  app-web/thunderbird/spec
Labels: upgrade, security, 0day

#8240 vim: update to 9.1.0764
  app-editors/vim/spec
Labels: upgrade

#8242 systemd: update to 256.7
  app-admin/systemd/autobuild/patches/0001-sleep.conf-AllowHibernation-no-by-default.patch
  app-admin/systemd/autobuild/patches/0002-main.c-revert-part-of-systemd-systemd-31442.patch
  app-admin/systemd/autobuild/patches/0003-fix-do-not-tint-terminal-by-default.patch
  app-admin/systemd/spec
Labels: upgrade

#8244 bind: update to 9.20.2
  app-network/bind/spec
Labels: upgrade

#8245 mediainfo: update to 24.06
  app-multimedia/mediainfo/spec
Labels: upgrade

#8246 yt-dlp: update to 2024.10.07
  app-multimedia/yt-dlp/spec
Labels: upgrade

#8248 pygments: update to 2.18.0
  lang-python/pygments/autobuild/defines
  lang-python/pygments/spec
Labels: upgrade, security

#8247 grub (GRand Unified Bootloader): fix EFI removable path for grub-mkrescue
  app-admin/grub/autobuild/patches/0001-Revert-templates-Properly-disable-the-os-prober-by-d.patch
  app-admin/grub/autobuild/patches/0002-Revert-templates-Disable-the-os-prober-by-default.patch
  app-admin/grub/autobuild/patches/0003-Don-t-add-to-highlighted-row.patch
  app-admin/grub/autobuild/patches/0004-Fix-border-spacing-now-that-we-aren-t-displaying-it.patch
  app-admin/grub/autobuild/patches/0005-Indent-menu-entries.patch
  app-admin/grub/autobuild/patches/0006-Fix-margins.patch
  app-admin/grub/autobuild/patches/0007-Use-2-instead-of-1-for-our-right-hand-margin-so-line.patch
  app-admin/grub/autobuild/patches/0008-Don-t-say-GNU-Linux-in-generated-menus.patch
  app-admin/grub/autobuild/patches/0009-Don-t-draw-a-border-around-the-menu.patch
  app-admin/grub/autobuild/patches/0010-Use-the-standard-margin-for-the-timeout-string.patch
  app-admin/grub/autobuild/patches/0011-grub-mkrescue-specify-iso-level-3.patch
  app-admin/grub/autobuild/patches/0012-10_linux-do-not-count-intel-ucode-image-as-a-valid-i.patch
  app-admin/grub/autobuild/patches/0013-util-add-GRUB_COLOR_-variables.patch
  app-admin/grub/autobuild/patches/0014-grub-core-drop-GRUB-title-from-the-menu.patch
  app-admin/grub/autobuild/patches/0015-grub-install-add-efi-to-the-candidate-of-the-ESP-mou.patch
  app-admin/grub/autobuild/patches/0016-commands-add-new-command-memsize.patch
  app-admin/grub/autobuild/patches/0017-commands-add-new-command-pause.patch
  app-admin/grub/autobuild/patches/0018-normal-align-countdown-text-with-rest-of-the-UI.patch
  app-admin/grub/autobuild/patches/0019-po-add-patch-to-disable-parallel-execution.patch
  app-admin/grub/autobuild/patches/0020-util-bash-completion-Load-scripts-on-demand.patch
  app-admin/grub/autobuild/patches/0021-util-bash-completion-Fix-for-bash-completion-2.12.patch
  app-admin/grub/autobuild/patches/0022-util-grub-mkrescue-use-capitalised-paths-for-removab.patch
  app-admin/grub/autobuild/patches/0023-loongarch64-able-to-start-on-legacy-firmware.patch
  app-admin/grub/autobuild/patches/0024-Add-support-for-forcing-EFI-installation-to-the-remo.patch
  app-admin/grub/autobuild/patches/0025-grub-install-loongarch64-efi-also-install-BOOTLOONGA.patch
  app-admin/grub/autobuild/patches/0026-mips64-Add-support-for-64-bit-MIPS.patch
  app-admin/grub/autobuild/patches/0027-mips64-Add-support-for-Loongson.patch
  app-admin/grub/autobuild/patches/0028-loader-mips64-linux-fix-missing-type-args-while-load.patch
  app-admin/grub/autobuild/patches/0029-util-grub-mkimagexx-fix-uncorrect-section-var-in-mak.patch
  app-admin/grub/autobuild/patches/0030-loader-mips64-linux-drop-argv-args-when-calling-grub.patch
  app-admin/grub/autobuild/patches/0031-lib-mips64-drop-all-efi_call-wrappers.patch
  app-admin/grub/autobuild/patches/0032-lib-mips64-use-a-common-GUID-impl-in-GRUB.patch
  app-admin/grub/autobuild/patches/0033-kern-mips64-fix-error-catch-output-type-mismatch.patch
  app-admin/grub/autobuild/patches/0034-kern-mips64-fix-missing-grub_install_get_time_ms-pro.patch
  app-admin/grub/autobuild/patches/0035-lib-mips64-silence-werror.patch
  app-admin/grub/autobuild/patches/0036-loader-mips64-fix-warnings-and-style.patch
  app-admin/grub/autobuild/patches/0037-kern-efi-mm-mips64-allocate-more-memory-at-initializ.patch
  app-admin/grub/autobuild/patches/0038-util-grub-install-mips64el-efi-rename-removable-exec.patch
  app-admin/grub/autobuild/patches/0039-fix-util-grub-mkrescue-fix-EFI-executable-name-for-m.patch
  app-admin/grub/spec
Labels: has-fix

#8255 aoscbootstrap: update to 0.7.4
  app-utils/aoscbootstrap/spec
Labels: upgrade

#8252 fcitx5-pinyin-moegirl: update to 20241009
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#8161 httpie: update to 3.2.3
  app-web/httpie/autobuild/defines
  app-web/httpie/autobuild/patches/0001-Explicitly-load-default-certificates-when-creating-S.patch
  app-web/httpie/autobuild/patches/0002-Drop-the-upper-bound-on-the-requests-dependency-agai.patch
  app-web/httpie/spec
Labels: upgrade, security

#8256 open-vm-tools: update to 12.5.0
  app-virtualization/open-vm-tools/spec
Labels: upgrade

#8259 nettle: update to 3.10
  runtime-cryptography/nettle/spec
Labels: upgrade, security

#8260 feishin: update to 0.11.0
  app-multimedia/feishin/spec
Labels: upgrade

#8250 osu-lazer: update to 2024.1009.1
  app-games/osu-lazer/spec
Labels: upgrade

#8269 unifont: update to 16.0.01
  desktop-fonts/unifont/spec
Labels: upgrade

#8276 inetutils: update to 2.5
  app-utils/inetutils/autobuild/patches/0001-build-Disable-GFDL-info-files-and-useless-man-pages.patch
  app-utils/inetutils/autobuild/patches/0002-build-Use-runstatedir-for-run-directory.patch
  app-utils/inetutils/autobuild/patches/0003-inetd-Change-protocol-semantics-in-inetd.conf.patch
  app-utils/inetutils/autobuild/patches/0004-Use-krb5_auth_con_getsendsubkey-instead-of-krb5_auth.patch
  app-utils/inetutils/spec
Labels: upgrade

#8274 vscodium: update to 1.94.2.24284
  app-editors/vscodium/spec
Labels: upgrade

#8273 vscode: update to 1.94.2
  app-editors/vscode/spec
Labels: upgrade

#8271 tailscale: update to 1.76.0
  app-network/tailscale/spec
Labels: upgrade

#8287 abbs-update-checksum: update to 0.2.4
  app-devel/abbs-update-checksum/spec
Labels: upgrade

#8284 buildah: update to 1.37.4
  app-containers/buildah/spec
Labels: upgrade, security

#8283 podman: update to 5.2.4+vsock0.7.5
  app-containers/podman/spec
Labels: upgrade, security

#8288 pipewire: fix pw-jack record finish crash
  app-multimedia/pipewire/autobuild/patches/0001-BACKPORT-jack-actually-clear-the-mix-io.patch
  app-multimedia/pipewire/spec
Labels: has-fix

#8290 wayland-protocols: update to 1.38
  app-devel/wayland-protocols/spec
Labels: upgrade

#8289 picom: update to 12.2
  desktop-wm/picom/spec
Labels: upgrade

#8292 binutils: update to 2.43.1
  app-devel/binutils/spec
Labels: upgrade

#8291 zed: update to 0.156.1
  app-editors/zed/spec
Labels: upgrade

#8295 libarchive: update to 3.7.6
  runtime-common/libarchive/spec
Labels: upgrade

#8281 kexec-tools: update to 2.0.29
  app-admin/kexec-tools/autobuild/patches/0001-RISC-V-Add-support-for-riscv-kexec-kdump-on-kexec-to.patch.riscv64
  app-admin/kexec-tools/autobuild/patches/0002-riscv-add-stubs-of-arch_do_exclude_segment.patch.riscv64
  app-admin/kexec-tools/spec
Labels: upgrade

#8280 kose-font: update to 3.113
  desktop-fonts/kose-font/01-kose-font/build
  desktop-fonts/kose-font/01-kose-font/defines
  desktop-fonts/kose-font/02-xiaolai-font/build
  desktop-fonts/kose-font/02-xiaolai-font/defines
  desktop-fonts/kose-font/spec
Labels: upgrade

#8301 aoscbootstrap: update to 0.7.5
  app-utils/aoscbootstrap/spec
Labels: upgrade

#8300 hmcl: update to 3.5.9.257
  app-games/hmcl/spec
Labels: upgrade

#8297 firefox: fix build on loongson3
  app-web/firefox/autobuild/patches/0001-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0002-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0003-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0004-update-gn_processor.py-to-support-linux-on-loong64.patch
  app-web/firefox/autobuild/patches/0005-Re-generate-libwebrtc-moz.build-files.patch
  app-web/firefox/autobuild/patches/0006-enable-webrtc-for-loongarch64-in-toolkit-moz.configu.patch
  app-web/firefox/autobuild/patches/0007-Fix-libyuv-unified-source-and-LoongArch-SIMD-build.patch
  app-web/firefox/autobuild/patches/0008-Fix-missing-loongarch-subdir-in-libpng-moz.yaml.patch
  app-web/firefox/autobuild/patches/0009-Vendor-missing-loongarch-files-of-libpng.patch
  app-web/firefox/autobuild/patches/0010-Enable-LoongArch-LSX-optimization-for-libpng.patch
  app-web/firefox/autobuild/patches/0011-Remove-references-to-private-members-for-MIPS.patch
  app-web/firefox/autobuild/prepare
  app-web/firefox/spec
Labels: has-fix

#8317 sarasa-gothic-fonts: update to 1.0.22
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#8316 iosevka-fonts: update to 31.9.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#8305 firefox: update to 131.0.3
  app-web/firefox/spec
Labels: upgrade

#8309 android-udev: update to 20240829
  runtime-devices/android-udev/spec
Labels: upgrade

#8319 inkscape: update to 1.4
  app-creativity/inkscape/autobuild/defines
  app-creativity/inkscape/autobuild/overrides/usr/share/appdata/inkscape.appdata.xml
  app-creativity/inkscape/autobuild/patches/0001-src-ui-tool-node-add-atomic-header.patch
  app-creativity/inkscape/autobuild/prepare
  app-creativity/inkscape/spec
Labels: upgrade

#8318 autobuild4: update to 4.3.26
  app-devel/autobuild4/spec
Labels: upgrade

#8329 autobuild4: update to 4.3.27
  app-devel/autobuild4/spec
Labels: upgrade, rework, manual-build

#8326 maturin: update to 1.7.4
  lang-python/maturin/spec
Labels: upgrade

#8323 dex: update to 0.10.1
  app-utils/dex/spec
Labels: upgrade

#8324 mimalloc: update to 2.1.7
  runtime-common/mimalloc/spec
Labels: upgrade

#8325 lldpd: update to 1.0.18
  app-network/lldpd/spec
Labels: upgrade

#8322 libltc: update to 1.3.2
  runtime-multimedia/libltc/spec
Labels: upgrade

#8321 alacarte: update to 3.54.0
  desktop-gnome/alacarte/spec
Labels: upgrade

#8327 pcre: update to 8.45
  runtime-common/pcre/spec
Labels: upgrade

#8312 gnutls: update to 3.8.7
  runtime-cryptography/gnutls/spec
Labels: upgrade

#8332 p-vector: update to 0.8.0
  app-admin/p-vector/spec
Labels: upgrade

#8333 gh: update to 2.59.0
  app-devel/gh/spec
Labels: upgrade

#8334 vscodium: update to 1.94.2.24286
  app-editors/vscodium/spec
Labels: upgrade

#8335 cmake: update to 3.30.5
  app-devel/cmake/spec
Labels: upgrade

#8336 cloudflared: update to 2024.10.0
  app-network/cloudflared/spec
Labels: upgrade

#8343 feishin: update to 0.11.1
  app-multimedia/feishin/spec
Labels: upgrade

#8339 solaar: update to 1.1.13
  app-utils/solaar/spec
Labels: upgrade

#8344 starship: update to 1.21.0
  app-utils/starship/autobuild/patches/0001-feat-status-add-success_symbol_rootuser-option.patch
  app-utils/starship/autobuild/patches/0002-refactor-utils-move-is_root_user-function-to-utils-m.patch
  app-utils/starship/autobuild/postinst
  app-utils/starship/spec
Labels: upgrade

#8349 acbs: update to 20241018
  app-devel/acbs/spec
Labels: upgrade

#8355 starship: update to 1.21.1
  app-utils/starship/spec
Labels: upgrade

#8354 typst: update to 0.12.0
  app-doc/typst/spec
Labels: upgrade

#8357 bitwarden: update to 2024.10.1
  app-utils/bitwarden/spec
Labels: upgrade

#8360 xdg-utils: update to 1.2.1
  app-utils/xdg-utils/autobuild/patches/0001-add-slock-support.patch
  app-utils/xdg-utils/autobuild/patches/add_slock_support.patch
  app-utils/xdg-utils/spec
  lang-python/semver/spec
Labels: upgrade

#8359 syncthing: update to 1.28.0
  app-network/syncthing/spec
Labels: upgrade

#8361 ispc: update to 1.25.1
  app-devel/ispc/spec
Labels: upgrade

#8338 rng-tools: update to 6.17
  app-utils/rng-tools/spec
Labels: upgrade

#8358 kicad: update to 8.0.6
  app-electronics/kicad/spec
Labels: upgrade

#8362 osu-lazer: update to 2024.1018.0
  app-games/osu-lazer/spec
Labels: upgrade

#8371 meson: update to 1.6.0
  app-devel/meson/spec
Labels: upgrade

#8366 frp: update to 0.61.0
  app-network/frp/spec
Labels: upgrade

#8356 forgejo: update to 9.0.0
  app-web/forgejo/autobuild/patches/0001-edit-systemd-service-file-to-met-need-of-AOSC-OS.patch
  app-web/forgejo/spec
Labels: upgrade

#8328 virtualbox (Oracle VM VirtualBox): update to 7.1.4
  app-virtualization/virtualbox/01-host/patches/0001-FROM-ARCHLINUX-fix-Frontends-VirtualBox-disable-upda.patch
  app-virtualization/virtualbox/01-host/patches/0002-FROM-ARCHLINUX-properly-handle-i3wm.patch
  app-virtualization/virtualbox/01-host/patches/0003-FROM-ARCHLINUX-support-building-from-dkms.patch
  app-virtualization/virtualbox/01-host/patches/0004-FROM-ARCHLINUX-upate-xclient-script.patch
  app-virtualization/virtualbox/01-host/patches/0005-FROM-AOSC-fix-libs-dxvk-fix-build-with-GCC-13.patch
  app-virtualization/virtualbox/01-host/patches/0006-FROM-AOSC-chore-use-the-wheel-group-for-hardware-acc.patch
  app-virtualization/virtualbox/01-host/patches/0007-FROM-ARCHLINUX-fix-python-3.12-compatibility.patch
  app-virtualization/virtualbox/01-host/patches/0008-FROM-AOSC-Link-against-vorbisenc.patch
  app-virtualization/virtualbox/01-host/patches/0009-FROM-AOSC-Add-gitignore.patch
  app-virtualization/virtualbox/01-host/patches/0010-FROM-AOSC-Add-localinst.sh.patch
  app-virtualization/virtualbox/spec
Labels: upgrade

#8350 archlinux-keyring: update to 20241015
  app-admin/archlinux-keyring/spec
Labels: upgrade, pre-release

#8342 cdrdao: update to 1.2.5
  app-multimedia/cdrdao/spec
Labels: upgrade

#8311 nestopia: update to 1.52.1
  app-games/nestopia/spec
Labels: upgrade

#8364 mesa: update to 24.2.5+dxheaders1.614.1
  runtime-display/mesa/spec
Labels: upgrade

#8372 prismlauncher: update to 9.0
  app-games/prismlauncher/autobuild/defines
  app-games/prismlauncher/autobuild/patches/0001-javautils-add-a-filter-for-detecting-Java-paths-on-A.patch
  app-games/prismlauncher/autobuild/patches/0001-javautils-detect-Java-paths-on-AOSC-OS.patch
  app-games/prismlauncher/autobuild/patches/0002-mangohud-support-MangoHud-getLibraryString-should-re.patch
  app-games/prismlauncher/autobuild/prepare
  app-games/prismlauncher/spec
Labels: upgrade

#8373 gdb: update to 15.2
  app-devel/gdb/spec
Labels: upgrade

#8374 vim: update to 9.1.0794
  app-editors/vim/spec
Labels: upgrade

#8351 opensc: update to 0.25.1
  app-devices/opensc/spec
Labels: upgrade, abi-break

#7885 sudo: fix missing of PAM files
  app-admin/sudo/autobuild/overrides/etc/pam.d/sudo-i
  app-admin/sudo/spec
Labels: has-fix

#8379 alacritty: update to 0.14.0
  app-utils/alacritty/spec
Labels: upgrade

#8376 gitoxide: update to 0.38.0
  app-vcs/gitoxide/autobuild/patches/0001-bump-libz-ng-sys-for-loongarch.patch
  app-vcs/gitoxide/spec
Labels: upgrade

#8346 cargo-audit: update to 0.20.1
  lang-rust/cargo-audit/spec
Labels: upgrade

#8368 calibre: update to 7.20.0
  app-doc/calibre/spec
Labels: upgrade

#8380 abbs-update-checksum: update to 0.3.0
  app-devel/abbs-update-checksum/spec
Labels: upgrade

#8363 picom: update to 12.3
  desktop-wm/picom/spec
Labels: upgrade

#8382 fastfetch: update to 2.28.0
  app-utils/fastfetch/spec
Labels: upgrade

#8383 pipewire: update to 1.2.6
  app-multimedia/pipewire/autobuild/patches/0001-BACKPORT-jack-actually-clear-the-mix-io.patch
  app-multimedia/pipewire/spec
Labels: upgrade

#8310 serf: update to 1.3.10
  runtime-web/serf/autobuild/patches/0001-Gentoo-serf-1.3.9-openssl-3-errgetfunc.patch
  runtime-web/serf/autobuild/patches/0002-Gentoo-serf-1.3.9-openssl-3-bio-ctrl.patch
  runtime-web/serf/autobuild/prepare
  runtime-web/serf/spec
Labels: upgrade

#8395 prismlauncher: update to 9.1
  app-games/prismlauncher/spec
Labels: upgrade

#8392 git-extras: update to 7.3.0
  app-devel/git-extras/spec
Labels: upgrade

#8398 libetebase: update to 0.5.6
  runtime-cryptography/libetebase/autobuild/defines
  runtime-cryptography/libetebase/spec
Labels: upgrade

#8402 osu-lazer: update to 2024.1023.0
  app-games/osu-lazer/spec
Labels: upgrade

#8401 ncmpcpp: update to 0.10.1
  app-multimedia/ncmpcpp/autobuild/beyond
  app-multimedia/ncmpcpp/autobuild/build
  app-multimedia/ncmpcpp/autobuild/defines
  app-multimedia/ncmpcpp/autobuild/prepare
  app-multimedia/ncmpcpp/spec
Labels: upgrade

#8407 fftw+32: fix bitness
  runtime-optenv32/fftw+32/autobuild/build
  runtime-optenv32/fftw+32/autobuild/defines
  runtime-optenv32/fftw+32/spec
Labels: has-fix

#8393 podman: update to 5.2.5+vsock0.7.5
  app-containers/podman/spec
Labels: upgrade

#8352 random2: update to 1.0.2
  lang-python/random2/spec
Labels: upgrade

#8416 qpwgraph: update to 0.7.9
  app-multimedia/qpwgraph/spec
Labels: upgrade

#8417 praat: update to 6.4.23
  app-scientific/praat/spec
Labels: upgrade

#8418 qbittorrent: update to 5.0.1
  app-web/qbittorrent/spec
Labels: upgrade

#8420 pulsectl: drop, orphaned
  lang-python/pulsectl/autobuild/defines
  lang-python/pulsectl/spec
Labels: drop-package

#8421 telegram-qt: drop, orphaned
  runtime-web/telegram-qt/autobuild/defines
  runtime-web/telegram-qt/spec
Labels: drop-package

#8414 firefox: update to 132.0
  app-web/firefox/autobuild/defines
  app-web/firefox/autobuild/patches/0001-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0002-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0003-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0004-update-gn_processor.py-to-support-linux-on-loong64.patch
  app-web/firefox/autobuild/patches/0005-Re-generate-libwebrtc-moz.build-files.patch
  app-web/firefox/autobuild/patches/0006-enable-webrtc-for-loongarch64-in-toolkit-moz.configu.patch
  app-web/firefox/autobuild/patches/0007-Fix-libyuv-unified-source-and-LoongArch-SIMD-build.patch
  app-web/firefox/autobuild/patches/0008-Fix-missing-loongarch-subdir-in-libpng-moz.yaml.patch
  app-web/firefox/autobuild/patches/0009-Vendor-missing-loongarch-files-of-libpng.patch
  app-web/firefox/autobuild/patches/0010-Enable-LoongArch-LSX-optimization-for-libpng.patch
  app-web/firefox/autobuild/patches/0011-Remove-references-to-private-members-for-MIPS.patch
  app-web/firefox/spec
Labels: upgrade, security

#8428 vscode: update to 1.95.0
  app-editors/vscode/spec
Labels: upgrade

#8429 intel-ucode: update to 20241029
  runtime-data/intel-ucode/spec
Labels: upgrade

#8434 autobuild4: update to 4.3.28
  app-devel/autobuild4/spec
Labels: upgrade

#8436 intel-oneapi-basekit: update to 2025.0.0
  app-devel/intel-oneapi-basekit/autobuild/build
  app-devel/intel-oneapi-basekit/spec
Labels: upgrade

#8411 peazip: update to 10.0.0
  app-utils/peazip/spec
Labels: upgrade

#8440 bitwarden: fix description in the desktop entry
  app-utils/bitwarden/autobuild/overrides/usr/share/applications/bitwarden.desktop
  app-utils/bitwarden/spec
Labels: has-fix
