Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-06, with the labels that each got.

#6363 clash-verge-rev: update to 1.6.4
  app-network/clash-verge-rev/autobuild/build
  app-network/clash-verge-rev/autobuild/patches/0001-fix-package.json-allow-building-on-platforms-without.patch
  app-network/clash-verge-rev/autobuild/patches/0002-chore-src-tauri-update-Cargo-dependencies.patch
  app-network/clash-verge-rev/autobuild/patches/0003-feat-src-assets-add-XDG-.desktop-entry.patch
  app-network/clash-verge-rev/autobuild/patches/0004-fix-tauri.conf.json-disable-bundle-distribution.patch
  app-network/clash-verge-rev/autobuild/patches/0005-fix-scripts-use-ABI2-New-World-Mihomo-binary-for-loo.patch
  app-network/clash-verge-rev/autobuild/patches/0006-feat-drop-clash-meta-alpha-support.patch
  app-network/clash-verge-rev/autobuild/patches/0007-fix-check.mjs-do-not-fetch-Mihomo-Clash-Meta-binarie.patch
  app-network/clash-verge-rev/autobuild/patches/0008-fix-src-tauri-tauri.conf.json-disable-Mihomo-Clash-M.patch
  app-network/clash-verge-rev/autobuild/patches/0009-fix-check.mjs-do-not-check-Mihomo-Clash-Meta-platfor.patch
  app-network/clash-verge-rev/autobuild/patches/0010-Do-not-find-clash-meta-binary-in-current-dir.patch
  app-network/clash-verge-rev/autobuild/patches/0011-Drop-check-update-feature.patch
  app-network/clash-verge-rev/autobuild/patches/0012-Drop-upgrade-core-feature.patch
  app-network/clash-verge-rev/spec
Labels: upgrade

#6357 corsixth: update to 0.67
  app-games/corsixth/autobuild/patches/0001-Use-wqy-microhei.patch
  app-games/corsixth/spec
Labels: upgrade

#6415 hashcat: fix CHKUPDATE
  app-penetration/hashcat/spec
Labels: upgrade, has-fix

#6417 deploykit-backend: update to 0.2.1
  app-admin/deploykit-backend/spec
Labels: upgrade

#6412 rathole: new, 0.5.0
  app-network/rathole/autobuild/defines
  app-network/rathole/spec
Labels: new-packages

#6411 coreutils: update to 9.5
  app-utils/coreutils/autobuild/patches/0001-split-do-not-shrink-hold-buffer.patch
  app-utils/coreutils/spec
Labels: upgrade

#6358 enet: update to 1.3.18
  runtime-network/enet/spec
Labels: upgrade

#6428 discord (Discord): mark CHKUPDATE
  app-web/discord/spec
Labels: upgrade

#6429 nodejs (Node.js): fix CHKUPDATE for LTS 20.x
  lang-js/nodejs/spec
Labels: upgrade, has-fix

#6492 deploykit-backend: update to 0.2.2
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#6493 deploykit-backend: update to 0.2.3
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#6494 deploykit-gui: update to 0.3.1
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#6424 wayland-utils: update to 1.2.0
  app-utils/wayland-utils/spec
Labels: upgrade

#6404 frp: update to 0.58.1
  app-network/frp/spec
Labels: upgrade

#6504 32subsystem: make wrappers change PATH for the 32-bit compilers
  runtime-optenv32/32subsystem/autobuild/wrappers/clang++-multilib-wrapper
  runtime-optenv32/32subsystem/autobuild/wrappers/clang-multilib-wrapper
  runtime-optenv32/32subsystem/autobuild/wrappers/g++-multilib-wrapper
  runtime-optenv32/32subsystem/autobuild/wrappers/gcc-multilib-wrapper
  runtime-optenv32/32subsystem/spec
Labels: upgrade, has-fix

#6505 abseil-cpp: update to 20240116.2 (rework again)
  desktop-gnome/evolution-data-server/autobuild/patches/0001-fix-abseil-ftbfs.patch
  desktop-gnome/evolution-data-server/spec
Labels: upgrade, rework

#6425 requests: update to 2.32.3
  lang-python/requests/spec
Labels: upgrade

#6420 openh264 (OpenH264): update to 2.4.1+gmp114+2
  app-multimedia/openh264/spec
Labels: upgrade

#6421 usbutils: update to 017
  app-utils/usbutils/spec
Labels: upgrade

#6353 coreboot-utils: update to 24.05
  app-admin/coreboot-utils/autobuild/defines
  app-admin/coreboot-utils/spec
Labels: upgrade, core

#6508 deploykit-gui: update to 0.3.4
  app-admin/deploykit-gui/spec
Labels: upgrade, dependencies

#6401 netease-cloud-music-gtk: update to 2.4.0
  app-multimedia/netease-cloud-music-gtk/spec
Labels: upgrade

#6501 firefox: update to 126.0.1
  app-web/firefox/spec
Labels: upgrade

#6502 chromium: update to 125.0.6422.141
  app-web/chromium/spec
Labels: upgrade

#6499 oma: update to 1.3.15
  app-admin/oma/spec
Labels: upgrade

#6423 hdrhistogram-c: update to 0.11.8
  runtime-common/hdrhistogram-c/spec
Labels: upgrade

#6515 latx (Loongson Architecture Translator for x86): rework dependencies
  app-emulation/latx/autobuild/defines
  app-emulation/latx/spec
Labels: dependencies, rework

#6084 isomd5sum: update to 1.2.4
  app-utils/isomd5sum/autobuild/build
  app-utils/isomd5sum/autobuild/defines
  app-utils/isomd5sum/spec
Labels: upgrade

#6516 byobu: update to 6.12
  app-utils/byobu/spec
Labels: upgrade

#6522 x11-proto: update to 2024.1
  runtime-display/x11-proto/spec
Labels: upgrade

#6521 catdoc: fix build
  app-doc/catdoc/autobuild/patches/0001-CVE-2017-11110.patch
  app-doc/catdoc/spec
Labels: has-fix

#6524 gdk-pixbuf: enable "others" loaders
  runtime-imaging/gdk-pixbuf/autobuild/defines
  runtime-imaging/gdk-pixbuf/spec
Labels: bug

#6408 dhcpcd: update to 10.0.8
  app-network/dhcpcd/spec
Labels: upgrade

#6532 wmctrl: (no build) fix source link
  desktop-wm/wmctrl/spec
Labels: has-fix

#6512 zram-generator: rework 1.1.2
  app-admin/zram-generator/autobuild/defines
  app-admin/zram-generator/autobuild/prepare
  app-admin/zram-generator/spec
Labels: rework

#6539 superslicer: update to 2.5.59.11
  app-creativity/superslicer/autobuild/patches/0001-fix-build-with-boost-1.83.patch
  app-creativity/superslicer/autobuild/patches/0004-fix-build-with-cereal-1.3.2.patch
  app-creativity/superslicer/autobuild/patches/0005-fix-test-utils-build-on-Linux.patch
  app-creativity/superslicer/autobuild/patches/0006-fix-Linux-installation-creating-broken-superslicer-g.patch
  app-creativity/superslicer/autobuild/patches/0007-fill_aligned_z-fix-uninitialized-atomic_int64_t.patch
  app-creativity/superslicer/spec
Labels: upgrade

#6535 ciel: update to 3.2.6
  app-devel/ciel/spec
Labels: upgrade

#6531 clit: fix build
  app-utils/clit/autobuild/patch
  app-utils/clit/autobuild/patches/0001-use-System-libtommath.patch
  app-utils/clit/autobuild/patches/0002-inject-CFLAGS.patch
  app-utils/clit/spec
Labels: has-fix

#6544 libarchive: update to 3.7.4
  runtime-common/libarchive/spec
Labels: upgrade

#6552 stow: update to 2.4.0
  app-admin/stow/autobuild/defines
  app-admin/stow/spec
Labels: upgrade

#6553 tree: fix manpage path
  app-utils/tree/autobuild/build
  app-utils/tree/spec
Labels: has-fix

#6556 qtcreator: update to 13.0.2
  app-devel/qtcreator/spec
Labels: upgrade

#6090 fontconfig: update to 2.15.0
  runtime-desktop/fontconfig/autobuild/patches/0001-fix-60-latin.conf-prefer-Noto-Sans-and-Source-Code-P.patch
  runtime-desktop/fontconfig/autobuild/patches/0002-Create-a-symlink-with-relative-patch.patch
  runtime-desktop/fontconfig/autobuild/patches/0002-fix-conf.d-disable-bitmap-fonts-by-default.patch
  runtime-desktop/fontconfig/autobuild/patches/0003-let-us-deny-bitmaps.patch
  runtime-desktop/fontconfig/spec
Labels: upgrade

#6507 libphonenumber update to 8.13.38
  runtime-i18n/libphonenumber/autobuild/defines
  runtime-i18n/libphonenumber/spec
Labels: upgrade

#6394 pyside2: update to 5.15.14
  lang-python/pyside2/autobuild/defines
  lang-python/pyside2/autobuild/patches/0001-Fedora-python-pyside2-options_py.patch
  lang-python/pyside2/autobuild/patches/0002-Fedora-fix-build-with-python-3.10.patch
  lang-python/pyside2/spec
Labels: upgrade

#6375 menulibre: update to 2.4.0
  app-utils/menulibre/autobuild/beyond
  app-utils/menulibre/spec
Labels: upgrade

#6530 lyx (LyX): update to 2.4.0
  app-doc/lyx/autobuild/defines
  app-doc/lyx/spec
Labels: upgrade

#6426 libgdiplus: update to 6.1
  lang-dotnet/libgdiplus/spec
Labels: upgrade

#6333 zziplib: update to 0.13.75
  runtime-common/zziplib/autobuild/patches/0001-chore-fix-version-0.13.72-0.13.74.patch
  runtime-common/zziplib/spec
Labels: upgrade

#6287 zeromq: update to 4.3.5
  runtime-common/zeromq/autobuild/patches/0001-fix-pgm-linkage.patch
  runtime-common/zeromq/autobuild/patches/0002-src-secure_allocator.hpp-define-missing-rebind-type.patch
  runtime-common/zeromq/spec
Labels: upgrade

#6175 memcached: update to 1.6.27
  app-admin/memcached/autobuild/overrides/usr/lib/sysusers.d/memcached.conf
  app-admin/memcached/autobuild/postinst
  app-admin/memcached/autobuild/usergroup
  app-admin/memcached/spec
Labels: upgrade

#6322 xdg-desktop-portal-gtk: update to 1.15.1
  app-admin/xdg-desktop-portal-gtk/autobuild/defines
  app-admin/xdg-desktop-portal-gtk/spec
Labels: upgrade

#6570 qbittorrent: update to 4.6.5
  app-web/qbittorrent/spec
Labels: upgrade

#6568 rhythmbox: update to 3.4.7
  app-multimedia/rhythmbox/autobuild/beyond
  app-multimedia/rhythmbox/spec
Labels: upgrade

#6405 intel-oneapi-basekit: new, 2024.1.0
  app-devel/intel-oneapi-basekit/autobuild/beyond
  app-devel/intel-oneapi-basekit/autobuild/build
  app-devel/intel-oneapi-basekit/autobuild/config
  app-devel/intel-oneapi-basekit/autobuild/defines
  app-devel/intel-oneapi-basekit/autobuild/postinst
  app-devel/intel-oneapi-basekit/autobuild/templates
  app-devel/intel-oneapi-basekit/spec
Labels: new-packages

#6546 openssl: update to 3.3.1
  runtime-cryptography/openssl/spec
Labels: upgrade

#6545 nginx: update to 1.27.0
  app-web/nginx/autobuild/defines
  app-web/nginx/autobuild/prepare
  app-web/nginx/spec
Labels: upgrade

#6080 rng-tools: update to 6.16
  app-utils/rng-tools/autobuild/defines
  app-utils/rng-tools/spec
Labels: upgrade

#6095 srain: update to 1.7.0
  app-web/srain/autobuild/defines
  app-web/srain/spec
Labels: upgrade

#6586 yelp-xsl: update to 42.1
  desktop-gnome/yelp-xsl/spec
Labels: upgrade

#6587 yelp-tools: update to 42.1
  desktop-gnome/yelp-tools/spec
Labels: upgrade

#6588 libgee: update to 0.20.6
  desktop-gnome/libgee/spec
Labels: upgrade

#6589 colord-gtk: update to 0.3.1
  desktop-gnome/colord-gtk/spec
Labels: upgrade

#6583 brltty: backport fix in python binding
  app-a11y/brltty/autobuild/patches/0001-brlapi-Fix-python-crash-on-connection-error.patch
  app-a11y/brltty/spec
Labels: has-fix

#6572 libinput: update to 1.26.0
  runtime-devices/libinput/spec
Labels: upgrade

#6566 postgresql: update to 13.15 and use sysusers
  app-database/postgresql/autobuild/overrides/usr/lib/sysusers.d/postgresql.conf
  app-database/postgresql/autobuild/postinst
  app-database/postgresql/autobuild/usergroup
  app-database/postgresql/spec
Labels: upgrade

#6564 cmake: update to 3.29.5
  app-devel/cmake/autobuild/postinst
  app-devel/cmake/spec
Labels: upgrade

#6555 php: update to 8.3.8
  app-devel/php/spec
Labels: upgrade

#6225 binutils+w64: update to 2.42
  runtime-optenvw64/binutils+w64/autobuild/build
  runtime-optenvw64/binutils+w64/autobuild/defines
  runtime-optenvw64/binutils+w64/spec
Labels: upgrade

#6584 discord: update to 0.0.56
  app-web/discord/spec
Labels: upgrade

#6581 soundtouch update to 2.3.3 (rework)
  app-games/dolphin-emu/autobuild/defines
  app-games/dolphin-emu/spec
Labels: upgrade, rework

#6590 libhandy: update to 1.8.3
  desktop-gnome/libhandy/spec
Labels: upgrade

#6571 mold: update to 2.32.0
  app-devel/mold/spec
Labels: upgrade

#6610 greetd: update to 0.10.3
  desktop-displaymanagers/greetd/autobuild/defines
  desktop-displaymanagers/greetd/autobuild/patches/0001-cargo-Update-nix-to-0.27.patch
  desktop-displaymanagers/greetd/spec
Labels: upgrade

#6576 grub (GRand Unified Bootloader): improve compliance with UEFI Specification
  app-admin/grub/autobuild/patches/0001-Revert-templates-Properly-disable-the-os-prober-by-d.patch
  app-admin/grub/autobuild/patches/0002-Revert-templates-Disable-the-os-prober-by-default.patch
  app-admin/grub/autobuild/patches/0003-Don-t-add-to-highlighted-row.patch
  app-admin/grub/autobuild/patches/0004-Fix-border-spacing-now-that-we-aren-t-displaying-it.patch
  app-admin/grub/autobuild/patches/0005-Indent-menu-entries.patch
  app-admin/grub/autobuild/patches/0006-Fix-margins.patch
  app-admin/grub/autobuild/patches/0007-Use-2-instead-of-1-for-our-right-hand-margin-so-line.patch
  app-admin/grub/autobuild/patches/0008-Don-t-say-GNU-Linux-in-generated-menus.patch
  app-admin/grub/autobuild/patches/0009-Don-t-draw-a-border-around-the-menu.patch
  app-admin/grub/autobuild/patches/0010-Use-the-standard-margin-for-the-timeout-string.patch
  app-admin/grub/autobuild/patches/0011-grub-mkrescue-specify-iso-level-3.patch
  app-admin/grub/autobuild/patches/0012-10_linux-do-not-count-intel-ucode-image-as-a-valid-i.patch
  app-admin/grub/autobuild/patches/0013-util-add-GRUB_COLOR_-variables.patch
  app-admin/grub/autobuild/patches/0014-grub-core-drop-GRUB-title-from-the-menu.patch
  app-admin/grub/autobuild/patches/0015-grub-install-add-efi-to-the-candidate-of-the-ESP-mou.patch
  app-admin/grub/autobuild/patches/0016-commands-add-new-command-memsize.patch
  app-admin/grub/autobuild/patches/0017-commands-add-new-command-pause.patch
  app-admin/grub/autobuild/patches/0018-normal-align-countdown-text-with-rest-of-the-UI.patch
  app-admin/grub/autobuild/patches/0019-po-add-patch-to-disable-parallel-execution.patch
  app-admin/grub/autobuild/patches/0020-util-bash-completion-Load-scripts-on-demand.patch
  app-admin/grub/autobuild/patches/0021-util-bash-completion-Fix-for-bash-completion-2.12.patch
  app-admin/grub/autobuild/patches/0022-util-grub-mkrescue-use-capitalised-paths-for-removab.patch
  app-admin/grub/spec
Labels: enhancement

#6592 superslicer: update to 2.5.59.12
  app-creativity/superslicer/spec
Labels: upgrade

#6625 vscode: update to 1.90.0
  app-editors/vscode/autobuild/prepare
  app-editors/vscode/spec
Labels: upgrade

#6650 colordiff: update to 1.0.21
  app-utils/colordiff/spec
Labels: upgrade

#6646 palp: update to 2.21
  app-scientific/palp/spec
Labels: upgrade

#6651 openrgb: update to 0.9
  app-utils/openrgb/autobuild/beyond
  app-utils/openrgb/autobuild/defines
  app-utils/openrgb/autobuild/patches/0001-nostrip.patch
  app-utils/openrgb/spec
Labels: upgrade

#6647 cowsay: update to 3.7.0
  app-utils/cowsay/autobuild/build
  app-utils/cowsay/autobuild/defines
  app-utils/cowsay/autobuild/patches/set-install-prefix.patch
  app-utils/cowsay/autobuild/prepare
  app-utils/cowsay/spec
Labels: upgrade

#6648 mupdf: update to 1.24.3
  app-doc/mupdf/spec
Labels: upgrade

#6640 perl-par-dist: update to 0.52
  lang-perl/perl-par-dist/spec
Labels: upgrade

#6637 iperf3: update to 3.17.1
  app-network/iperf3/spec
Labels: upgrade

#6635 diffuse: update to 0.9.0
  app-devel/diffuse/spec
Labels: upgrade

#6427 xcowsay: update to 1.6
  app-utils/xcowsay/autobuild/defines
  app-utils/xcowsay/spec
Labels: upgrade

#6634 libxdmcp: update to 1.1.5
  runtime-display/libxdmcp/spec
Labels: upgrade

#6632 osdlyrics: update to 0.5.15
  app-multimedia/osdlyrics/autobuild/defines
  app-multimedia/osdlyrics/spec
Labels: upgrade

#6641 telepathy-mission-control: update to 5.16.6
  runtime-web/telepathy-mission-control/spec
Labels: upgrade

#6627 ddrescueview: update to 0.4.5
  app-utils/ddrescueview/autobuild/build
  app-utils/ddrescueview/autobuild/defines
  app-utils/ddrescueview/autobuild/patches/0001-enable-debug-symbol-generation.patch
  app-utils/ddrescueview/spec
Labels: upgrade

#6636 streamlink: update to 6.7.4
  app-multimedia/streamlink/spec
Labels: upgrade

#6661 alsa-ucm-conf: update to 1.2.12
  runtime-multimedia/alsa-ucm-conf/spec
Labels: upgrade

#6662 tor: update to 0.4.8.12
  app-network/tor/autobuild/overrides/usr/lib/sysusers.d/tor.conf
  app-network/tor/autobuild/postinst
  app-network/tor/autobuild/usergroup
  app-network/tor/spec
Labels: upgrade

#6314 snapd-glib: update to 1.65
  runtime-admin/snapd-glib/autobuild/defines
  runtime-admin/snapd-glib/spec
Labels: upgrade

#6644 fwupd: update to 1.9.21
  app-admin/fwupd/spec
Labels: upgrade

#6677 oma: update to 1.3.17
  app-admin/oma/spec
Labels: upgrade

#6172 libnumbertext: update to 1.0.11
  runtime-productivity/libnumbertext/autobuild/patches/libnumbertext-updateautotools.patch
  runtime-productivity/libnumbertext/spec
Labels: upgrade

#6624 webkit2gtk: add webkitgtk-6.0 variant
  runtime-web/webkit2gtk/autobuild/build
  runtime-web/webkit2gtk/autobuild/defines
  runtime-web/webkit2gtk/spec
Labels: enhancement

#6664 json-glib: update to 1.8.0
  runtime-common/json-glib/autobuild/defines
  runtime-common/json-glib/spec
Labels: upgrade

#6665 nokogiri: update to 1.16.6
  lang-ruby/nokogiri/spec
Labels: upgrade

#6671 icewm: update to 3.6.0
  desktop-wm/icewm/autobuild/patches/0001-AOSC-Defaults.patch
  desktop-wm/icewm/autobuild/patches/0001-feat-src-default.h-set-AOSC-OS-defaults.patch
  desktop-wm/icewm/spec
Labels: upgrade

#6611 firefox (Mozilla Firefox): update to 127.0
  app-web/firefox/autobuild/patches/0001-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0002-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0003-Enable-WebRTC-for-LoongArch.patch
  app-web/firefox/autobuild/patches/0004-Fix-libyuv-build-with-LSX-LASX.patch
  app-web/firefox/autobuild/patches/0005-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0006-Keep-unsigned-32-bit-parameter-sign-extended-in-regi.patch
  app-web/firefox/autobuild/patches/0007-Implement-SummarizeTrapInstruction-for-MIPS64.patch
  app-web/firefox/autobuild/patches/0008-Bug-1855960-MIPS64-Make-some-assembler-routines-retu.patch
  app-web/firefox/autobuild/patches/0009-Add-missing-loongarch-lsx-code-for-libpng.patch
  app-web/firefox/spec
Labels: upgrade

#6162 gloox: update to 1.0.28
  runtime-web/gloox/autobuild/patches/0001-add-missing-headers-gcc-13.patch
  runtime-web/gloox/spec
Labels: upgrade

#6342 sticky: update to 1.19
  desktop-cinnamon/sticky/autobuild/build
  desktop-cinnamon/sticky/spec
Labels: upgrade

#6350 upower: update to 1.90.4
  app-admin/upower/autobuild/patches/0001-linux-Fix-BlueZ-device-names-not-synchronising.patch
  app-admin/upower/autobuild/patches/0002-linux-Allow-filling-only-the-serial-from-sibling.patch
  app-admin/upower/autobuild/patches/0003-linux-Fix-reading-capacity_level-with-newer-libgudev.patch
  app-admin/upower/autobuild/patches/0006-battery-Quiet-debug-message.patch
  app-admin/upower/autobuild/patches/0007-device-Make-it-possible-to-remove-devices-from-D-Bus.patch
  app-admin/upower/autobuild/patches/0008-daemon-Don-t-add-unexported-devices-to-the-array.patch
  app-admin/upower/autobuild/patches/0009-daemon-Don-t-warn-if-a-device-gets-unexported.patch
  app-admin/upower/autobuild/patches/0010-daemon-Don-t-count-hidden-devices.patch
  app-admin/upower/autobuild/patches/0011-linux-Hide-duplicate-Logitech-Bluetooth-devices.patch
  app-admin/upower/autobuild/patches/0012-linux-Make-BT-mice-use-the-same-address-in-tests.patch
  app-admin/upower/autobuild/patches/0013-linux-Make-BT-mouse-export-its-serial-number.patch
  app-admin/upower/autobuild/patches/0014-linux-Test-whether-BT-mice-get-de-duplicated.patch
  app-admin/upower/autobuild/patches/0015-supply-battery-Assume-battery-is-present-if-the-attr.patch
  app-admin/upower/autobuild/patches/0016-enumerator-udev-actually-check-for-an-idevice.patch
  app-admin/upower/autobuild/patches/0017-enumerator-udev-also-check-for-an-idevice-on-usb-sub.patch
  app-admin/upower/autobuild/patches/0019-idevice-Prefer-the-user-chosen-name-when-available.patch
  app-admin/upower/autobuild/patches/0020-idevice-Simplify-setting-the-model.patch
  app-admin/upower/autobuild/patches/0021-rules-Update-hwdb-from-upstream-NUT.patch
  app-admin/upower/spec
Labels: upgrade

#6337 idna: update to 3.7
  lang-python/idna/autobuild/defines
  lang-python/idna/spec
Labels: upgrade

#6689 upower (UPower): rework to remove installed tests
  app-admin/upower/autobuild/defines
  app-admin/upower/autobuild/patches/0001-build-Make-installation-of-tests-optional.patch
  app-admin/upower/spec
Labels: rework

#6676 rustc: update to 1.79.0
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/autobuild/patches/0003-Add-MIPSR6-definitions-to-vendored-nix-rs.patch
  lang-rust/rustc/autobuild/patches/0004-Add-MIPSR6-definitions-to-vendored-nix-0.26.patch
  lang-rust/rustc/autobuild/patches/0005-Avoid-debuginfo-for-MIPSR6-in-proc-macro-test.patch
  lang-rust/rustc/autobuild/patches/0006-Fix-missing-ioctl-for-loongarch64-and-mips64r6.patch
  lang-rust/rustc/autobuild/prepare
  lang-rust/rustc/spec
Labels: upgrade

#6691 autobuild4: update to 4.3.2
  app-devel/autobuild4/spec
Labels: upgrade

#6692 PrismLauncher: fix Java version detection
  app-games/prismlauncher/autobuild/patches/0001-javautils-detect-Java-paths-on-AOSC-OS.patch
  app-games/prismlauncher/spec
Labels: has-fix

#6690 caddy: update to 2.8.4
  app-web/caddy/spec
Labels: upgrade

#6422 bigsh0t: update to 2.7
  runtime-multimedia/bigsh0t/autobuild/patch
  runtime-multimedia/bigsh0t/autobuild/patches/0001-Do-not-pass-DSSE-unconditionally.patch.deferred
  runtime-multimedia/bigsh0t/spec
Labels: upgrade

#6695 aoscbootstrap: update to 0.5.0
  app-utils/aoscbootstrap/spec
Labels: upgrade

#5932 bandwhich: update to 0.22.2
  app-network/bandwhich/autobuild/defines
  app-network/bandwhich/spec
Labels: upgrade

#6528 fcron: update to 3.3.1
  app-admin/fcron/autobuild/beyond
  app-admin/fcron/autobuild/defines
  app-admin/fcron/autobuild/overrides/usr/lib/sysusers.d/fcron.conf
  app-admin/fcron/autobuild/overrides/usr/lib/tmpfiles.d/fcron.conf
  app-admin/fcron/autobuild/postinst
  app-admin/fcron/autobuild/prepare
  app-admin/fcron/spec
Labels: upgrade

#6708 oma: update to 1.3.18
  app-admin/oma/spec
Labels: upgrade

#6698 mariadb: update to 10.9.8
  app-database/mariadb/autobuild/conffiles
  app-database/mariadb/autobuild/overrides/etc/my.cnf
  app-database/mariadb/autobuild/overrides/usr/lib/sysusers.d/mysql.conf
  app-database/mariadb/autobuild/patches/0001-Fedora-mariadb-10.5-gcc13.patch
  app-database/mariadb/autobuild/patches/0002-Fedora-rocksdb-6.8-gcc13.patch
  app-database/mariadb/autobuild/postinst
  app-database/mariadb/autobuild/usergroup
  app-database/mariadb/spec
Labels: upgrade

#6688 flaky: new, 3.8.1
  lang-python/flaky/autobuild/defines
  lang-python/flaky/spec
Labels: new-packages

#6663 libpeas: update to 1.36.0
  desktop-gnome/libpeas/spec
Labels: upgrade

#6699 varnish: update to 7.5.0
  app-network/varnish/spec
Labels: upgrade

#6687 cmake: update to 3.29.6
  app-devel/cmake/spec
Labels: upgrade

#6633 buildbot-benchmark: new, 20240327
  app-benchmarks/buildbot-benchmark/autobuild/build
  app-benchmarks/buildbot-benchmark/autobuild/defines
  app-benchmarks/buildbot-benchmark/spec
Labels: new-packages

#6712 acbs (Autobuild CI Build System): update to 20240620
  app-devel/acbs/spec
Labels: upgrade

#6578 deno: update to 1.44.1
  lang-js/deno/autobuild/beyond
  lang-js/deno/autobuild/defines
  lang-js/deno/autobuild/patches/0001-fix-v8-build.patch.deferred
  lang-js/deno/autobuild/patches/0001-use-O3-optimization.patch
  lang-js/deno/autobuild/prepare
  lang-js/deno/spec
Labels: upgrade

#6315 python-evdev: update to 1.7.1
  lang-python/python-evdev/autobuild/defines
  lang-python/python-evdev/spec
Labels: upgrade

#6310 dnspython: update to 2.6.1
  lang-python/dnspython/autobuild/defines
  lang-python/dnspython/spec
Labels: upgrade

#6182 raptor2: update to 2.0.16
  runtime-common/raptor2/autobuild/patches/0001-Calculate-max-nspace-declarations-correctly-for-XML-writer.patch
  runtime-common/raptor2/spec
Labels: upgrade

#6316 crazydiskinfo: update to 1.1.0
  app-utils/crazydiskinfo/autobuild/defines
  app-utils/crazydiskinfo/autobuild/patches/0001-fix-CMakeLists.txt-install-exeuctable-to-usr-bin.patch
  app-utils/crazydiskinfo/autobuild/patches/0002-fix-CMakeLists.txt-link-against-ltinfo.patch
  app-utils/crazydiskinfo/autobuild/prepare
  app-utils/crazydiskinfo/spec
Labels: upgrade

#6185 wimlib: update to 1.14.4
  app-utils/wimlib/autobuild/defines
  app-utils/wimlib/spec
Labels: upgrade

#6719 osu-lazer: update to 2024.523.0
  app-games/osu-lazer/spec
Labels: upgrade

#6724 tornado update to 6.4.1
  lang-python/tornado/autobuild/defines
  lang-python/tornado/spec
Labels: upgrade

#6718 fcron: fix sysusers.d, fcron.conf permissions, and EPERM
  app-admin/fcron/autobuild/beyond
  app-admin/fcron/autobuild/overrides/usr/lib/sysusers.d/fcron.conf
  app-admin/fcron/autobuild/patch
  app-admin/fcron/autobuild/patches/0001-fix-set-effective-UID-after-setting-effective-GID-to.patch
  app-admin/fcron/autobuild/patches/0002-fix-Makefile.in-do-not-strip-during-install-time.patch
  app-admin/fcron/autobuild/postinst
  app-admin/fcron/spec
Labels: has-fix

#6717 xa: update to 2.4.1
  app-devel/xa/spec
Labels: upgrade

#6715 cmake: fix postinst script
  app-devel/cmake/autobuild/build
  app-devel/cmake/spec
Labels: has-fix

#6716 powerpc-utils: update to 1.3.12
  app-admin/powerpc-utils/autobuild/defines
  app-admin/powerpc-utils/spec
Labels: upgrade

#6723 pycurl update to 7.45.3
  lang-python/pycurl/autobuild/build
  lang-python/pycurl/autobuild/defines
  lang-python/pycurl/autobuild/patch
  lang-python/pycurl/spec
Labels: upgrade

#6734 cmake (CMake): rework postinst
  app-devel/cmake/autobuild/build
  app-devel/cmake/spec
Labels: rework

#6733 perl-dbd-mysql (DBD::mysql): update to 4.052
  lang-perl/perl-dbd-mysql/spec
Labels: upgrade

#6176 pyyaml: update to 6.0.1
  lang-python/pyyaml/autobuild/defines
  lang-python/pyyaml/autobuild/prepare
  lang-python/pyyaml/spec
Labels: upgrade

#5924 aspell: update to 0.60.8.1+dict20161024
  app-i18n/aspell/01-main/beyond
  app-i18n/aspell/01-main/defines
  app-i18n/aspell/02-dict/build
  app-i18n/aspell/spec
Labels: upgrade

#6756 chromium: update to 126.0.6478.114
  app-web/chromium/autobuild/patches/1000-Fedora-chromium-120-split-threshold-for-reg-with-hint.patch
  app-web/chromium/autobuild/patches/2002-Debian-fixes-blink.patch
  app-web/chromium/autobuild/patches/2003-Debian-fixes-quiche-deque.patch
  app-web/chromium/autobuild/patches/2003-Debian-upstream-ninja.patch
  app-web/chromium/autobuild/patches/2005-Debian-upstream-appservice-include.patch
  app-web/chromium/autobuild/patches/2005-Debian-upstream-gpu-header.patch
  app-web/chromium/autobuild/patches/2006-Debian-upstream-blink-header.patch
  app-web/chromium/autobuild/patches/2006-Debian-upstream-lens-optional.patch
  app-web/chromium/autobuild/patches/2007-Debian-upstream-blink-header3.patch
  app-web/chromium/autobuild/patches/2007-Debian-upstream-mojo-bindings-include.patch
  app-web/chromium/autobuild/patches/2008-Debian-upstream-no-vector-consts.patch
  app-web/chromium/autobuild/patches/2008-Debian-upstream-realtime-reporting.patch
  app-web/chromium/autobuild/patches/2010-Debian-upstream-urlvisit-header.patch
  app-web/chromium/autobuild/patches/2010-Debian-upstream-vulkan-include.patch
  app-web/chromium/autobuild/patches/2012-Debian-upstream-accessibility-format.patch
  app-web/chromium/autobuild/patches/3001-rust-ld-bfd.patch
  app-web/chromium/autobuild/patches/3004-fix-clang-builtins-path.patch
  app-web/chromium/autobuild/patches/3006-fix-static-assertion.patch
  app-web/chromium/autobuild/patches/4000-loongarch64-clang-no-lsx.patch
  app-web/chromium/autobuild/patches/4001-loongarch64-swiftshader.patch
  app-web/chromium/autobuild/patches/4002-loongarch64-sandbox.patch
  app-web/chromium/autobuild/patches/4003-loongarch64-crashpad.patch
  app-web/chromium/autobuild/patches/4005-loongarch64-ffmpeg.patch
  app-web/chromium/autobuild/patches/4007-loongarch64.patch
  app-web/chromium/spec
Labels: upgrade

#6763 grsync: update to 1.3.1
  app-network/grsync/spec
Labels: upgrade

#6762 yad: update to 14.0
  app-utils/yad/autobuild/defines
  app-utils/yad/spec
Labels: upgrade

#6765 emacs: update to 29.4
  app-editors/emacs/spec
Labels: upgrade

#6770 prismlauncher: update to 8.4
  app-games/prismlauncher/spec
Labels: upgrade

#6766 lmdb: update to 0.9.31
  app-database/lmdb/autobuild/overrides/usr/lib/pkgconfig/lmdb.pc
  app-database/lmdb/spec
Labels: upgrade

#6777 autobuild4: update to 4.3.3
  app-devel/autobuild4/spec
Labels: upgrade

#6774 haruna: do not execute new mpv window
  desktop-kde/haruna/autobuild/patches/0001-mpv-set-vo-to-libmpv-otherwise-mpv-creates-it-s-own-.patch
  desktop-kde/haruna/spec
Labels: new-packages

#6786 scenefx: add CHKUPDATE
  runtime-display/scenefx/spec
Labels: autopr

#6739 xfce4-screenshooter: update to 1.10.6
  desktop-xfce/xfce4-screenshooter/spec
Labels: upgrade
