Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-08, with the labels that each got.

#7432 oma: update to 1.3.36
  app-admin/oma/spec
Labels: upgrade

#7433 deploykit-backend: update to 0.6.5
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#7416 ffmpeg (FFmpeg): fix AMD GPU AV1 hardware decoding with Mesa >= 24.1.4
  app-multimedia/ffmpeg/autobuild/patches/0001-avcodec-mips-Add-switch-for-MADD-instruction.patch
  app-multimedia/ffmpeg/autobuild/patches/0002-avutil-mips-Use-MMI_-L-S-QC1-macro-in-SAVE-RECOVER-_.patch
  app-multimedia/ffmpeg/autobuild/patches/0003-avutil-mips-Extract-load-store-with-shift-C1-pair-ma.patch
  app-multimedia/ffmpeg/autobuild/patches/0004-avcodec-mips-Use-MMI-marcos-to-replace-Loongson3-ins.patch
  app-multimedia/ffmpeg/autobuild/patches/0005-avutil-mips-Use-at-as-MMI-macro-temporary-register.patch
  app-multimedia/ffmpeg/autobuild/patches/0006-avcodec-x86-mathops-clip-constants-used-with-shift-i.patch
  app-multimedia/ffmpeg/autobuild/patches/0007-Only-use-cpuinfo-to-read-cpu-ISAs.patch
  app-multimedia/ffmpeg/autobuild/patches/0008-Add-mips64r6-generic-options.patch
  app-multimedia/ffmpeg/autobuild/patches/0009-doc-t2h.pm-fix-missing-CSS-with-texinfo-6.8-and-abov.patch
  app-multimedia/ffmpeg/autobuild/patches/0010-doc-t2h.pm-fix-missing-TOC-with-texinfo-6.8-and-abov.patch
  app-multimedia/ffmpeg/autobuild/patches/0011-doc-html-support-texinfo-7.0.patch
  app-multimedia/ffmpeg/autobuild/patches/0012-lavc-vaapi_decode-Make-it-possible-to-send-multiple-.patch
  app-multimedia/ffmpeg/autobuild/patches/0013-lavc-vaapi_av1-Avoid-sending-the-same-slice-buffer-m.patch
  app-multimedia/ffmpeg/autobuild/patches/0014-configure-use-non-deprecated-nvenc-GUID-for-conftest.patch
  app-multimedia/ffmpeg/autobuild/patches/0015-avcodec-nvenc-stop-using-deprecated-rc-modes-with-SD.patch
  app-multimedia/ffmpeg/spec
Labels: has-fix, hardware-support

#7435 pipewire: update to 1.2.2
  app-multimedia/pipewire/spec
Labels: upgrade

#7437 feishin: update to 0.7.3
  app-multimedia/feishin/spec
Labels: upgrade

#7436 btrfs-progs: update to 6.10
  app-admin/btrfs-progs/spec
Labels: upgrade

#7439 yazi: Replace unar with 7-zip, add ImageMagick as recommendation
  app-utils/yazi/autobuild/defines
Labels: enhancement

#7410 chafa: new, 1.14.2
  app-utils/chafa/autobuild/defines
  app-utils/chafa/spec
Labels: new-packages

#7440 yazi: Add chafa to recommended packages
  app-utils/yazi/autobuild/defines
  app-utils/yazi/spec
Labels: enhancement

#7434 adaptivecpp: update to 24.06.0
  app-devel/adaptivecpp/autobuild/defines
  app-devel/adaptivecpp/spec
Labels: upgrade

#7445 ffcall: update to 2.4
  runtime-common/ffcall/autobuild/beyond
  runtime-common/ffcall/autobuild/defines
  runtime-common/ffcall/autobuild/patches/0001-loongarch-Add-support-for-loongarch64-ABI.patch
  runtime-common/ffcall/autobuild/patches/0002-loongarch-Use-the-now-released-GCC-12.patch
  runtime-common/ffcall/autobuild/patches/0003-Fix-compilation-error-with-ISO-C-23-compliant-compil.patch
  runtime-common/ffcall/autobuild/patches/0004-HACK-use-standard-__loongarch64_lp64-macro.patch
  runtime-common/ffcall/spec
Labels: upgrade

#7447 oma: update to 1.3.38
  app-admin/oma/spec
Labels: upgrade

#7448 gradle: update to 8.9
  lang-java/gradle/spec
Labels: upgrade

#7451 cutter: update description
  app-devel/cutter/autobuild/defines
  app-devel/cutter/spec
Labels: enchantment

#7398 Cloudflared: new, 2024.7.1
  app-network/cloudflared/autobuild/build
  app-network/cloudflared/autobuild/defines
  app-network/cloudflared/spec
Labels: new-packages

#7443 firefox: fix AV1 playback bug using VAAPI
  app-web/firefox/autobuild/patches/0001-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0002-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0003-Enable-WebRTC-for-LoongArch.patch
  app-web/firefox/autobuild/patches/0004-Fix-libyuv-build-with-LSX-LASX.patch
  app-web/firefox/autobuild/patches/0005-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0006-Keep-unsigned-32-bit-parameter-sign-extended-in-regi.patch
  app-web/firefox/autobuild/patches/0007-Implement-SummarizeTrapInstruction-for-MIPS64.patch
  app-web/firefox/autobuild/patches/0008-Bug-1855960-MIPS64-Make-some-assembler-routines-retu.patch
  app-web/firefox/autobuild/patches/0009-Add-missing-loongarch-lsx-code-for-libpng.patch
  app-web/firefox/autobuild/patches/0010-Revert-MoveEmitter-mips64.cpp-part-in-Bug-1870747-Us.patch
  app-web/firefox/autobuild/patches/0011-Add-move8ZeroExtend-for-mips.patch
  app-web/firefox/autobuild/patches/0012-Bug-1902227-Linux-VA-API-Backport-AV1-VA-API-playbac.patch
  app-web/firefox/spec
Labels: has-fix

#7455 git-extras: new, 7.2.0
  app-devel/git-extras/autobuild/beyond
  app-devel/git-extras/autobuild/build
  app-devel/git-extras/autobuild/defines
  app-devel/git-extras/spec
Labels: new-package

#7467 difftastic: update to 0.60.0
  app-utils/difftastic/autobuild/patches/0001-Fix-text-diff-of-large-chunks-to-not-emit-last-blank-line.patch
  app-utils/difftastic/spec
Labels: upgrade

#7453 git-review: new, 2.4.0
  app-devel/git-review/autobuild/defines
  app-devel/git-review/spec
Labels: new-package

#7476 oma: update to 1.3.39
  app-admin/oma/spec
Labels: upgrade

#7478 oma: install command-not-found handler for fish
  app-admin/oma/autobuild/beyond
  app-admin/oma/spec
Labels: enchantment

#7364 ghidra: update to 11.1.2
  app-devel/ghidra/spec
Labels: upgrade

#7461 pavucontrol: update to 6.1
  app-multimedia/pavucontrol/spec
Labels: upgrade

#7450 fractal: update to 8
  desktop-gnome/fractal/autobuild/defines
  desktop-gnome/fractal/spec
Labels: upgrade

#7444 mirrormgr: update to 0.11.1
  app-admin/mirrormgr/spec
Labels: upgrade

#7471 opendoas: new, 6.8.2
  app-admin/opendoas/autobuild/build
  app-admin/opendoas/autobuild/conffiles
  app-admin/opendoas/autobuild/defines
  app-admin/opendoas/spec
Labels: new-package

#7473 just: update to 1.34.0
  app-devel/just/spec
Labels: upgrade

#7460 kmail: fix runtime dependencies
  desktop-kde/kmail/autobuild/defines
  desktop-kde/kmail/spec
Labels: has-fix, dependencies

#7468 nasm: update to 2.16.03
  app-devel/nasm/spec
Labels: upgrade

#7474 octave: update to 9.2.0
  app-scientific/octave/spec
Labels: upgrade

#7475 kicad: update to 8.0.4
  app-electronics/kicad/spec
Labels: upgrade

#7449 mesa (Mesa 3D Graphics Library): update to 24.1.5
  runtime-display/mesa/autobuild/patches/0001-meson-set-default-drivers-for-ppc-ppc64.patch
  runtime-display/mesa/autobuild/patches/0002-meson-set-default-Vulkan-drivers-for-ppc-ppc64.patch
  runtime-display/mesa/autobuild/patches/0003-fix-meson.build-more-Gallium-Vulkan-drivers-for-on-a.patch
  runtime-display/mesa/autobuild/patches/0004-gallivm-add-lp_context_ref-for-combine-usage-of-LLVM.patch
  runtime-display/mesa/autobuild/patches/0005-gallivm-move-ppc-denorm-disable-to-inline.patch
  runtime-display/mesa/autobuild/patches/0006-gallivm-split-some-code-out-from-init-module.patch
  runtime-display/mesa/autobuild/patches/0007-gallivm-make-lp_bld_coro.h-c-include-safe.patch
  runtime-display/mesa/autobuild/patches/0008-gallivm-export-target-init-code-for-orc-jit-to-reuse.patch
  runtime-display/mesa/autobuild/patches/0009-gallivm-split-out-generating-LLVM-Mattrs.patch
  runtime-display/mesa/autobuild/patches/0010-gallivm-create-a-pass-manager-wrapper.patch
  runtime-display/mesa/autobuild/patches/0011-llvmpipe-add-gallivm_add_global_mapping.patch
  runtime-display/mesa/autobuild/patches/0012-llvmpipe-make-unnamed-global-have-internal-linkage.patch
  runtime-display/mesa/autobuild/patches/0013-util-detect-RISC-V-architecture.patch
  runtime-display/mesa/autobuild/patches/0014-gallivm-add-riscv-support-to-the-mattrs-setting-code.patch
  runtime-display/mesa/autobuild/patches/0015-llvmpipe-add-function-name-to-gallivm_jit_function.patch
  runtime-display/mesa/autobuild/patches/0016-llvmpipe-tests-add-a-new-test-for-multiple-symbols-f.patch
  runtime-display/mesa/autobuild/patches/0017-llvmpipe-add-an-implementation-with-llvm-orcjit.patch
  runtime-display/mesa/autobuild/patches/0018-llvmpipe-append-partial-mask-to-partial-fs_variant-f.patch
  runtime-display/mesa/autobuild/patches/0019-llvmpipe-add-shader-cache-support-for-ORCJIT-impleme.patch
  runtime-display/mesa/autobuild/patches/0020-util-detect-LoongArch-architecture.patch
  runtime-display/mesa/autobuild/patches/0021-gallivm-add-LoongArch-support-to-the-mattrs-setting-.patch
  runtime-display/mesa/autobuild/patches/0022-llvmpipe-add-LoongArch-support-in-ORCJIT.patch
  runtime-display/mesa/autobuild/patches/0023-vulkan-runtime-Rename-vk_meta_object_list-to-vk_obje.patch
  runtime-display/mesa/autobuild/patches/0024-vulkan-runtime-Split-vk_object_list-into-separate-fi.patch
  runtime-display/mesa/autobuild/patches/0025-zink-reject-Imagination-proprietary-driver-w-o-geome.patch
  runtime-display/mesa/autobuild/patches/0026-fix-iris_bufmgr.c-set-PAGE_SIZE-as-16384.patch.loongarch64
  runtime-display/mesa/spec
Labels: upgrade

#7494 vscode, vscodium: fix open files from desktop
  app-editors/vscode/autobuild/overrides/usr/share/applications/vscode.desktop
  app-editors/vscode/spec
  app-editors/vscodium/autobuild/overrides/usr/share/applications/vscodium.desktop
  app-editors/vscodium/spec
Labels: has-fix

#7495 vscodium: improve desktop entry
  app-editors/vscodium/autobuild/overrides/usr/share/applications/vscodium.desktop
Labels: amd64 arm64

#7498 vscode: update to 1.92.0
  app-editors/vscode/spec
Labels: upgrade

#7506 discord: update to 0.0.63
  app-web/discord/spec
Labels: upgrade

#7505 oma: update to 1.4.1
  app-admin/oma/spec
Labels: upgrade

#7508 yt-dlp: update to 2024.08.01
  app-multimedia/yt-dlp/spec
Labels: upgrade

#7492 peazip: update to 9.9.0
  app-utils/peazip/spec
Labels: upgrade

#7489 buildah: new, 1.37.0
  app-containers/buildah/autobuild/build
  app-containers/buildah/autobuild/defines
  app-containers/buildah/spec
Labels: new-packages

#7480 passt: new, 2024.07.26
  app-network/passt/autobuild/build
  app-network/passt/autobuild/defines
  app-network/passt/spec
Labels: new-packages

#7477 podman: update to 5.2.0+vsock0.7.4
  app-containers/podman/autobuild/defines
  app-containers/podman/spec
Labels: upgrade, dependencies

#7497 fontconfig: exclude emoji fonts from the no-bitmap default config
  runtime-desktop/fontconfig/autobuild/patches/0001-fix-60-latin.conf-prefer-Noto-Sans-and-Source-Code-P.patch
  runtime-desktop/fontconfig/autobuild/patches/0002-Sort-out-bitmap-related-config-files.patch
  runtime-desktop/fontconfig/autobuild/patches/0002-fix-conf.d-disable-bitmap-fonts-by-default.patch
  runtime-desktop/fontconfig/autobuild/patches/0003-fix-conf.d-disable-non-emoji-bitmap-fonts-by-default.patch
  runtime-desktop/fontconfig/spec
Labels: has-fix

#7483 containers-common: use pasta by default
  runtime-containers/containers-common/autobuild/defines
  runtime-containers/containers-common/spec
Labels: dependencies

#7464 botan-2: add loongarch64 to archinfo
  runtime-cryptography/botan-2/autobuild/patches/0001-Add-loongarch64-to-archinfo.patch
  runtime-cryptography/botan-2/spec
Labels: has-fix

#7452 openssh: add ssh-agent.service
  app-network/openssh/autobuild/overrides/usr/lib/systemd/user/ssh-agent.service
  app-network/openssh/spec
Labels: enhancement

#7510 audacity: update to 3.6.1
  app-creativity/audacity/spec
Labels: upgrade

#7519 starship: update to 1.20.1
  app-utils/starship/spec
Labels: upgrade

#7520 i3status-rust: update to 0.33.1
  desktop-wm/i3status-rust/spec
Labels: upgrade

#7522 osu-lazer: update to 2024.731.0
  app-games/osu-lazer/spec
Labels: upgrade

#5914 ack: update to 3.7.0
  app-utils/ack/spec
Labels: upgrade

#6159 ktoblzcheck: update to 1.57
  runtime-productivity/ktoblzcheck/autobuild/defines
  runtime-productivity/ktoblzcheck/spec
Labels: help-wanted, upgrade

#7541 hub: drop, orphaned
  app-vcs/hub/autobuild/build
  app-vcs/hub/autobuild/defines
  app-vcs/hub/autobuild/postinst
  app-vcs/hub/spec
Labels: drop-package

#7482 distrobox: move docker dependency to suggests
  app-utils/distrobox/autobuild/defines
  app-utils/distrobox/spec
Labels: enhancement

#7540 autobuild4: update to 4.3.14
  app-devel/autobuild4/spec
Labels: upgrade

#7530 ghidra: 11.1.2 rework
  app-devel/ghidra/autobuild/build
  app-devel/ghidra/spec
Labels: dependencies, rework

#7523 intel-graphics-compiler: update to 1.0.17193.4
  app-devel/intel-graphics-compiler/spec
Labels: upgrade

#7521 boinc: update to 8.0.4
  app-scientific/boinc/autobuild/overrides/usr/lib/systemd/system/boinc.service
  app-scientific/boinc/autobuild/overrides/usr/lib/sysusers.d/boinc.conf
  app-scientific/boinc/autobuild/postinst
  app-scientific/boinc/spec
Labels: upgrade

#7576 acbs: update to 20240808
  app-devel/acbs/spec
Labels: upgrade

#7549 zed: update to 0.146.5
  app-editors/zed/spec
Labels: upgrade

#7589 oma: update to 1.4.2
  app-admin/oma/spec
Labels: upgrade

#7591 mpvpaper: update to 1.7
  app-utils/mpvpaper/spec
Labels: upgrade

#7587 hmcl: update to 3.5.9
  app-games/hmcl/autobuild/build
  app-games/hmcl/spec
Labels: upgrade

#7588 antlr4: update to 4.13.2
  app-devel/antlr4/spec
  runtime-common/antlr4-cpp-runtime/autobuild/defines
  runtime-common/antlr4-cpp-runtime/spec
Labels: upgrade

#7545 mold: update to 2.32.1
  app-devel/mold/spec
Labels: upgrade

#7598 autobuild4: update to 4.3.19
  app-devel/autobuild4/spec
Labels: upgrade

#7590 rustc: update to 1.80.0
  lang-rust/rustc/autobuild/defines
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/autobuild/patches/0003-Add-MIPSR6-definitions-to-vendored-nix-rs.patch
  lang-rust/rustc/autobuild/patches/0004-Add-MIPSR6-definitions-to-vendored-nix-0.26.patch
  lang-rust/rustc/autobuild/patches/0005-Avoid-debuginfo-for-MIPSR6-in-proc-macro-test.patch
  lang-rust/rustc/autobuild/patches/0006-Fix-missing-ioctl-for-loongarch64-and-mips64r6.patch
  lang-rust/rustc/autobuild/prepare
  lang-rust/rustc/spec
Labels: upgrade

#7599 s-tui: update to 1.1.6
  app-utils/s-tui/spec
Labels: upgrade

#7602 abbs-update-checksum: update to 0.2.1
  app-devel/abbs-update-checksum/spec
Labels: upgrade

#7554 igv: drop, orphaned
  app-scientific/igv/autobuild/build
  app-scientific/igv/autobuild/conffiles
  app-scientific/igv/autobuild/defines
  app-scientific/igv/autobuild/overrides/usr/bin/igv
  app-scientific/igv/autobuild/overrides/usr/share/applications/igv.desktop
  app-scientific/igv/spec
Labels: drop-package

#7548 audiveris: drop, orphaned
  app-doc/audiveris/autobuild/build
  app-doc/audiveris/autobuild/defines
  app-doc/audiveris/autobuild/patches/0001-add-support-for-ppc64el.patch
  app-doc/audiveris/autobuild/prepare
  app-doc/audiveris/spec
Labels: drop-package

#7605 lazygit: new, 0.43.1
  app-vcs/lazygit/autobuild/defines
  app-vcs/lazygit/autobuild/prepare
  app-vcs/lazygit/spec
Labels: new-package

#7609 forgejo: update to 8.0.1
  app-web/forgejo/spec
Labels: upgrade

#7611 fend: update to 1.5.1
  app-utils/fend/spec
Labels: upgrade

#7601 linux-kernel-lts (Linux Kernel, Longterm): introduce old-world firmware compatibility for LoongArch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0001-lib-cpumask-Make-CPUMASK_OFFSTACK-usable-without-deb.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0002-input-kill-stupid-messages.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0003-lis3-improve-handling-of-null-rate.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0004-Input-synaptics-pin-3-touches-when-the-firmware-repo.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0004-ath9k-rx-dma-stop-check.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0005-driver-sisfb-add-resolution-1368-768-for-loongson-ly.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0006-Revert-video-output-Drop-display-output-class-suppor.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0007-pci-Enable-overrides-for-missing-ACS-capabilities-5..patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0008-usb-phy-tegra-Add-38.4MHz-clock-table-entry.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0009-more-uarches-for-kernel.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0010-MIPS-Loongson64-Disable-writecombine-for-Loongson-3A.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0011-platform-surface-hid.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0012-loongson64-init-suppress-memcpy-out-of-bound-checkin.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0013-arm64-dts-rockchip-change-GMAC-rx_delay-for-RockPro6.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0014-arm64-dts-rockchip-add-out-of-band-IRQ-for-RK3399-Wi.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0015-arm64-rockchip-dts-rk3399-fix-PD-on-Pinebook-Pro.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0016-HACK-arm64-dts-rockchip-disable-usb3-on-quartz64.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0017-arm64-add-Kconfig-option-for-Phytium-SoCs.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0018-net-stmmac-add-a-glue-driver-for-GMACs-in-Phytium-So.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0019-HID-logitech-dj-add-support-for-the-new-lightspeed-r.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0020-HACK-arm64-drop-hisi_ddrc_pmu-driver.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0021-arch-loongarch-add-la_ow_syscall-as-in-tree-module.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0021-iommu-make-IPMMU_VMSA-dependencies-more-strict.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0022-la_ow_syscall-add-kconfig-for-module.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0023-LOONGARCH64-drivers-firmware-Move-sysfb_init-from-de.patch.loongarch64
  runtime-kernel/linux-kernel-lts/autobuild/patches/0024-drm-Makefile-Move-tiny-drivers-before-native-drivers.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0025-LOONGARCH64-drm-radeon-Workaround-radeon-driver-bug-.patch.loongarch64
  runtime-kernel/linux-kernel-lts/autobuild/patches/0026-LOONGARCH64-drm-radeon-Call-mmiowb-at-the-end-of-rad.patch.loongarch64
  runtime-kernel/linux-kernel-lts/autobuild/patches/0027-LOONGARCH64-HACK-drm-amdgpu-disable-DPM-in-auto-mode.patch.loongarch64
  runtime-kernel/linux-kernel-lts/autobuild/patches/0028-loongarch-basic-boot-support-for-legacy-firmware.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0029-loongarch-parse-BPI-data-and-add-memory-mapping.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0030-loongarch-add-MADT-ACPI-table-conversion.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0031-loongarch-correct-missing-offset-of-PCI-root-control.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0032-loongarch-fix-missing-dependency-info-in-DSDT.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0033-loongarch-reset-use-general-efi-poweroff.patch
  runtime-kernel/linux-kernel-lts/spec
Labels: enhancement

#7613 ffmpeg: fix bilibili av1 metadata bug
  app-multimedia/ffmpeg/autobuild/patches/0001-avcodec-mips-Add-switch-for-MADD-instruction.patch
  app-multimedia/ffmpeg/autobuild/patches/0002-avutil-mips-Use-MMI_-L-S-QC1-macro-in-SAVE-RECOVER-_.patch
  app-multimedia/ffmpeg/autobuild/patches/0003-avutil-mips-Extract-load-store-with-shift-C1-pair-ma.patch
  app-multimedia/ffmpeg/autobuild/patches/0004-avcodec-mips-Use-MMI-marcos-to-replace-Loongson3-ins.patch
  app-multimedia/ffmpeg/autobuild/patches/0005-avutil-mips-Use-at-as-MMI-macro-temporary-register.patch
  app-multimedia/ffmpeg/autobuild/patches/0006-avcodec-x86-mathops-clip-constants-used-with-shift-i.patch
  app-multimedia/ffmpeg/autobuild/patches/0007-Only-use-cpuinfo-to-read-cpu-ISAs.patch
  app-multimedia/ffmpeg/autobuild/patches/0008-Add-mips64r6-generic-options.patch
  app-multimedia/ffmpeg/autobuild/patches/0009-doc-t2h.pm-fix-missing-CSS-with-texinfo-6.8-and-abov.patch
  app-multimedia/ffmpeg/autobuild/patches/0010-doc-t2h.pm-fix-missing-TOC-with-texinfo-6.8-and-abov.patch
  app-multimedia/ffmpeg/autobuild/patches/0011-doc-html-support-texinfo-7.0.patch
  app-multimedia/ffmpeg/autobuild/patches/0012-lavc-vaapi_decode-Make-it-possible-to-send-multiple-.patch
  app-multimedia/ffmpeg/autobuild/patches/0013-lavc-vaapi_av1-Avoid-sending-the-same-slice-buffer-m.patch
  app-multimedia/ffmpeg/autobuild/patches/0014-configure-use-non-deprecated-nvenc-GUID-for-conftest.patch
  app-multimedia/ffmpeg/autobuild/patches/0015-avcodec-nvenc-stop-using-deprecated-rc-modes-with-SD.patch
  app-multimedia/ffmpeg/autobuild/patches/0016-avcodec-av1dec-reset-the-fragment-on-extradata-readi.patch
  app-multimedia/ffmpeg/autobuild/patches/0017-cbs_av1-Don-t-reject-unknown-metadata.patch
  app-multimedia/ffmpeg/spec
Labels: has-fix

#7615 primus+32: drop, orphaned
  runtime-optenv32/primus+32/autobuild/build
  runtime-optenv32/primus+32/autobuild/defines
  runtime-optenv32/primus+32/spec
Labels: drop-package

#7616 libmikmod+32: update to 3.3.11.1
  runtime-optenv32/libmikmod+32/autobuild/build
  runtime-optenv32/libmikmod+32/autobuild/defines
  runtime-optenv32/libmikmod+32/spec
Labels: upgrade

#7614 ciel: update to 3.3.1
  app-devel/ciel/spec
Labels: upgrade

#7619 kdewebdev: fix dependency and use dummy ABTYPE
  desktop-kde/kdewebdev/autobuild/build
  desktop-kde/kdewebdev/autobuild/defines
  desktop-kde/kdewebdev/spec
Labels: has-fix, dependencies

#7623 gmetadom: drop again
  desktop-gnome/gmetadom/spec
Labels: drop-package

#7625 os-prober: properly map autobuild4 arch to os-prober arch
  app-utils/os-prober/autobuild/build
  app-utils/os-prober/spec
Labels: has-fix

#7603 rustc: update to 1.80.1
  lang-rust/rustc/spec
Labels: upgrade

#7631 mold: update to 2.33.0
  app-devel/mold/spec
Labels: upgrade

#7632 ciel: update to 3.3.2
  app-devel/ciel/spec
Labels: upgrade

#7633 autobuild4: update to 4.3.21
  app-devel/autobuild4/spec
Labels: upgrade

#7584 zed: update to 0.147.2
  app-editors/zed/spec
Labels: upgrade

#7636 bash-startup: update to 0.6.7
  runtime-data/bash-startup/spec
Labels: upgrade

#7635 wavemon: update to 0.9.6
  app-network/wavemon/autobuild/patches/0001-fix-Makefile.in-honor-system-CC-variable.patch
  app-network/wavemon/autobuild/patches/0002-fix-Makefile.in-honor-Autobuild-flags.patch
  app-network/wavemon/autobuild/prepare
  app-network/wavemon/spec
Labels: upgrade

#7637 oma: update to 1.4.3
  app-admin/oma/spec
Labels: upgrade

#7647 mcfly: update to 0.9.2
  app-utils/mcfly/spec
Labels: upgrade

#7645 intel-compute-runtime: update to 24.26.30049.6
  runtime-scientific/intel-compute-runtime/spec
Labels: upgrade

#7639 handbrake: update to 1.8.2
  app-multimedia/handbrake/spec
Labels: upgrade

#7640 wine: update to 9.15+gecko2.47.4+mono9.2.0
  app-emulation/wine/spec
Labels: upgrade

#7641 stress-ng: new, 0.18.02
  app-benchmarks/stress-ng/autobuild/build
  app-benchmarks/stress-ng/autobuild/defines
  app-benchmarks/stress-ng/spec
  runtime-cryptography/intel-ipsec-mb/autobuild/beyond
  runtime-cryptography/intel-ipsec-mb/autobuild/defines
  runtime-cryptography/intel-ipsec-mb/spec
Labels: new-packages

#7648 intel-oneapi-basekit: update to 2024.2.1
  app-devel/intel-oneapi-basekit/autobuild/defines
  app-devel/intel-oneapi-basekit/spec
Labels: upgrade

#7650 ast-grep: update to 0.26.1
  app-devel/ast-grep/spec
Labels: upgrade

#7653 dua: update to 2.29.2
  app-utils/dua/spec
Labels: upgrade

#7654 fastfetch: update to 2.21.1
  app-utils/fastfetch/spec
Labels: upgrade

#7658 open-rs: update to 5.3.0
  app-utils/open-rs/spec
Labels: upgrade

#7644 postgresql (PostgreSQL): update to 13.16
  app-database/postgresql/spec
Labels: upgrade

#7660 pnpm: update to 9.7.0
  lang-js/pnpm/spec
Labels: upgrade

#7661 vscode: update to 1.92.1
  app-editors/vscode/spec
Labels: upgrade

#7657 noto-fonts: update to 24.8.1+emoji2.042+cjksans2.004+cjkserif2.003
  desktop-fonts/noto-fonts/spec
Labels: upgrade

#7655 hugo: update to 0.131.0
  app-web/hugo/spec
Labels: upgrade

#6974 kitty: update to 0.35.2
  app-utils/kitty/autobuild/defines
  app-utils/kitty/spec
Labels: upgrade

#7668 praat: new, 6.4.17
  app-scientific/praat/autobuild/build
  app-scientific/praat/autobuild/defines
  app-scientific/praat/autobuild/prepare
  app-scientific/praat/spec
Labels: new-packages

#7669 chore: add notes for developers on Windows
  README.md
Labels: enhancement

#7026 iodine: update to 0.8.0
  app-network/iodine/autobuild/build
  app-network/iodine/autobuild/config
  app-network/iodine/autobuild/defines
  app-network/iodine/autobuild/patches/0001-Fedora-iodine-0.7.0.split-man.patch
  app-network/iodine/autobuild/postinst
  app-network/iodine/autobuild/prepare
  app-network/iodine/autobuild/templates
  app-network/iodine/spec
Labels: upgrade

#7676 ciel: update to 3.4.1
  app-devel/ciel/spec
Labels: upgrade

#7671 vscodium: update to 1.92.1.24225
  app-editors/vscodium/spec
Labels: upgrade

#7670 tailscale: update to 1.70.0
  app-network/tailscale/spec
Labels: upgrade

#7678 zerotier-one: update to 1.14.0
  app-network/zerotier-one/autobuild/build
  app-network/zerotier-one/autobuild/defines
  app-network/zerotier-one/autobuild/patches/0001-Update-dependencies.patch
  app-network/zerotier-one/spec
Labels: upgrade

#7679 syncthing: update to 1.27.10
  app-network/syncthing/autobuild/build
  app-network/syncthing/autobuild/overrides/usr/lib/systemd/system/syncthing-relaysrv.service
  app-network/syncthing/autobuild/overrides/usr/lib/sysusers.d/syncthing-relaysrv.conf
  app-network/syncthing/autobuild/overrides/usr/lib/sysusers.d/syncthing.conf
  app-network/syncthing/autobuild/overrides/usr/lib/tmpfiles.d/syncthing-relaysrv.conf
  app-network/syncthing/autobuild/overrides/usr/lib/tmpfiles.d/syncthing.conf
  app-network/syncthing/autobuild/postinst
  app-network/syncthing/spec
Labels: upgrade

#7683 sqlite: update to 3.46.1
  app-database/sqlite/spec
Labels: upgrade

#7684 qtcreator: update to 14.0.1
  app-devel/qtcreator/spec
Labels: upgrade

#7686 fwupd: update to 1.9.23
  app-admin/fwupd/spec
Labels: upgrade

#7667 judy: new, 1.0.5
  app-benchmarks/stress-ng/autobuild/defines
  app-benchmarks/stress-ng/spec
  app-devel/judy/autobuild/defines
  app-devel/judy/autobuild/patches/0001-Debian-02_remove_duplicate_man.patch.patch
  app-devel/judy/autobuild/patches/0002-Debian-03_add_man_section_to_filename.patch.patch
  app-devel/judy/autobuild/patches/0003-fix-bootstrap-remove-automake-version-restriction.patch
  app-devel/judy/autobuild/patches/0004-fix-configure.ac-remove-unneeded-m64-flag.patch
  app-devel/judy/spec
Labels: new-packages

#7688 linux-kernel-lts: improve support for LoongArch old-world multiprocessor system
  runtime-kernel/linux-kernel-lts/autobuild/patches/0001-lib-cpumask-Make-CPUMASK_OFFSTACK-usable-without-deb.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0002-input-kill-stupid-messages.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0003-lis3-improve-handling-of-null-rate.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0004-Input-synaptics-pin-3-touches-when-the-firmware-repo.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0005-driver-sisfb-add-resolution-1368-768-for-loongson-ly.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0006-Revert-video-output-Drop-display-output-class-suppor.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0007-pci-Enable-overrides-for-missing-ACS-capabilities-5..patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0008-usb-phy-tegra-Add-38.4MHz-clock-table-entry.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0009-more-uarches-for-kernel.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0010-MIPS-Loongson64-Disable-writecombine-for-Loongson-3A.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0011-platform-surface-hid.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0012-loongson64-init-suppress-memcpy-out-of-bound-checkin.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0013-arm64-dts-rockchip-change-GMAC-rx_delay-for-RockPro6.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0014-arm64-dts-rockchip-add-out-of-band-IRQ-for-RK3399-Wi.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0015-arm64-rockchip-dts-rk3399-fix-PD-on-Pinebook-Pro.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0016-HACK-arm64-dts-rockchip-disable-usb3-on-quartz64.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0017-arm64-add-Kconfig-option-for-Phytium-SoCs.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0018-net-stmmac-add-a-glue-driver-for-GMACs-in-Phytium-So.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0019-HID-logitech-dj-add-support-for-the-new-lightspeed-r.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0020-HACK-arm64-drop-hisi_ddrc_pmu-driver.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0021-arch-loongarch-add-la_ow_syscall-as-in-tree-module.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0022-la_ow_syscall-add-kconfig-for-module.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0023-drm-Makefile-Move-tiny-drivers-before-native-drivers.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0024-loongarch-basic-boot-support-for-legacy-firmware.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0025-loongarch-parse-BPI-data-and-add-memory-mapping.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0026-loongarch-add-MADT-ACPI-table-conversion.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0027-loongarch-correct-missing-offset-of-PCI-root-control.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0028-loongarch-fix-missing-dependency-info-in-DSDT.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0029-loongarch-fix-DMA-address-offset.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0030-loongarch-fix-HT_RX_INT_TRANS-register.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0031-loongarch-reset-use-general-efi-poweroff.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0032-irqchip-loongarch-cpu-Fix-return-value-of-lpic_gsi_t.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0033-LOONGARCH64-drivers-firmware-Move-sysfb_init-from-de.patch.loongarch64
  runtime-kernel/linux-kernel-lts/autobuild/patches/0034-LOONGARCH64-drm-radeon-Workaround-radeon-driver-bug-.patch.loongarch64
  runtime-kernel/linux-kernel-lts/autobuild/patches/0035-LOONGARCH64-drm-radeon-Call-mmiowb-at-the-end-of-rad.patch.loongarch64
  runtime-kernel/linux-kernel-lts/autobuild/patches/0036-LOONGARCH64-HACK-drm-amdgpu-disable-DPM-in-auto-mode.patch.loongarch64
  runtime-kernel/linux-kernel-lts/spec
Labels: enhancement

#7675 sof-tools: update to 2.10
  app-multimedia/sof-tools/autobuild/patches/0001-tools-logger-convert-work-around-implicit-sign-conve.patch
  app-multimedia/sof-tools/spec
Labels: upgrade

#7685 exfatprogs: update to 1.2.5
  app-admin/exfatprogs/spec
Labels: upgrade

#7692 grub: Add support for forcing EFI installation to the removable media path
  app-admin/grub/autobuild/patches/0001-Revert-templates-Properly-disable-the-os-prober-by-d.patch
  app-admin/grub/autobuild/patches/0002-Revert-templates-Disable-the-os-prober-by-default.patch
  app-admin/grub/autobuild/patches/0003-Don-t-add-to-highlighted-row.patch
  app-admin/grub/autobuild/patches/0004-Fix-border-spacing-now-that-we-aren-t-displaying-it.patch
  app-admin/grub/autobuild/patches/0005-Indent-menu-entries.patch
  app-admin/grub/autobuild/patches/0006-Fix-margins.patch
  app-admin/grub/autobuild/patches/0007-Use-2-instead-of-1-for-our-right-hand-margin-so-line.patch
  app-admin/grub/autobuild/patches/0008-Don-t-say-GNU-Linux-in-generated-menus.patch
  app-admin/grub/autobuild/patches/0009-Don-t-draw-a-border-around-the-menu.patch
  app-admin/grub/autobuild/patches/0010-Use-the-standard-margin-for-the-timeout-string.patch
  app-admin/grub/autobuild/patches/0011-grub-mkrescue-specify-iso-level-3.patch
  app-admin/grub/autobuild/patches/0012-10_linux-do-not-count-intel-ucode-image-as-a-valid-i.patch
  app-admin/grub/autobuild/patches/0013-util-add-GRUB_COLOR_-variables.patch
  app-admin/grub/autobuild/patches/0014-grub-core-drop-GRUB-title-from-the-menu.patch
  app-admin/grub/autobuild/patches/0015-grub-install-add-efi-to-the-candidate-of-the-ESP-mou.patch
  app-admin/grub/autobuild/patches/0016-commands-add-new-command-memsize.patch
  app-admin/grub/autobuild/patches/0017-commands-add-new-command-pause.patch
  app-admin/grub/autobuild/patches/0018-normal-align-countdown-text-with-rest-of-the-UI.patch
  app-admin/grub/autobuild/patches/0019-po-add-patch-to-disable-parallel-execution.patch
  app-admin/grub/autobuild/patches/0020-util-bash-completion-Load-scripts-on-demand.patch
  app-admin/grub/autobuild/patches/0021-util-bash-completion-Fix-for-bash-completion-2.12.patch
  app-admin/grub/autobuild/patches/0022-util-grub-mkrescue-use-capitalised-paths-for-removab.patch
  app-admin/grub/autobuild/patches/0023-loongarch64-able-to-start-on-legacy-firmware.patch
  app-admin/grub/autobuild/patches/0024-Add-support-for-forcing-EFI-installation-to-the-remo.patch
  app-admin/grub/autobuild/patches/0024-grub-install-loongarch64-efi-also-install-BOOTLOONGA.patch
  app-admin/grub/autobuild/patches/0025-grub-install-loongarch64-efi-also-install-BOOTLOONGA.patch
  app-admin/grub/spec
Labels: enhancement, hardware-support

#7693 depthcharge-tools: new, 0.6.2
  app-admin/depthcharge-tools/autobuild/beyond
  app-admin/depthcharge-tools/autobuild/defines
  app-admin/depthcharge-tools/spec
Labels: dependencies, new-packages

#7484 lighttpd: refresh configs with upstream
  app-network/lighttpd/autobuild/defines
  app-network/lighttpd/autobuild/overrides/etc/lighttpd/lighttpd.conf
  app-network/lighttpd/autobuild/overrides/usr/lib/systemd/system/lighttpd.service
  app-network/lighttpd/spec
Labels: enhancement

#7472 git-interactive-rebase-tool: new, 2.4.1
  app-devel/git-interactive-rebase-tool/autobuild/defines
  app-devel/git-interactive-rebase-tool/autobuild/prepare
Labels: new-packages

#7695 Core 11.5.1
  core-misc/aosc-aaa/autobuild/overrides/etc/sysctl.d/01-vm.conf
  core-misc/aosc-aaa/spec
Labels: enhancement, core

#7699 intel-ucode: update to 20240813
  runtime-data/intel-ucode/spec
Labels: upgrade, security

#7708 oma: update to 1.5.2
  app-admin/oma/spec
Labels: upgrade

#7696 podman: update to 5.2.1+vsock0.7.4
  app-containers/podman/spec
Labels: upgrade

#7703 kdev-php: 23.08.5 rework
  desktop-kde/kdev-php/autobuild/defines
  desktop-kde/kdev-php/spec
Labels: rework

#7715 yazi: update to 0.3.1
  app-utils/yazi/spec
Labels: upgrade

#7718 vscode: update to 1.92.2
  app-editors/vscode/spec
Labels: upgrade

#7719 vscodium: update to 1.92.2.24228
  app-editors/vscodium/spec
Labels: upgrade

#7720 zola: update to 0.19.2
  app-web/zola/spec
Labels: upgrade

#7716 btrfs-progs: update to 6.10.1
  app-admin/btrfs-progs/spec
Labels: upgrade

#7723 7-zip: update to 24.08
  app-utils/7-zip/spec
Labels: upgrade

#7721 fastfetch: update to 2.21.3
  app-utils/fastfetch/spec
Labels: upgrade

#7722 zed: update to 0.148.1
  app-editors/zed/spec
Labels: upgrade

#7728 libantlr3c: drop, orphaned
  runtime-common/libantlr3c/autobuild/defines
  runtime-common/libantlr3c/spec
Labels: drop-package

#7725 obs-studio: update to 30.2.3
  app-multimedia/obs-studio/spec
Labels: upgrade

#7732 osu-lazer: update to 2024.817.0
  app-games/osu-lazer/spec
Labels: upgrade

#7709 mesa (The Mesa 3D Graphics Library): update to 24.2.0
  runtime-display/mesa/autobuild/defines
  runtime-display/mesa/autobuild/patches/0001-meson-set-default-drivers-for-ppc-ppc64.patch
  runtime-display/mesa/autobuild/patches/0001-zink-reject-Imagination-proprietary-driver-w-o-geome.patch
  runtime-display/mesa/autobuild/patches/0002-fix-iris_bufmgr.c-set-PAGE_SIZE-as-16384.patch.loongarch64
  runtime-display/mesa/autobuild/patches/0002-meson-set-default-Vulkan-drivers-for-ppc-ppc64.patch
  runtime-display/mesa/autobuild/patches/0003-fix-meson.build-more-Gallium-Vulkan-drivers-for-on-a.patch
  runtime-display/mesa/autobuild/patches/0004-gallivm-add-lp_context_ref-for-combine-usage-of-LLVM.patch
  runtime-display/mesa/autobuild/patches/0005-gallivm-move-ppc-denorm-disable-to-inline.patch
  runtime-display/mesa/autobuild/patches/0006-gallivm-split-some-code-out-from-init-module.patch
  runtime-display/mesa/autobuild/patches/0007-gallivm-make-lp_bld_coro.h-c-include-safe.patch
  runtime-display/mesa/autobuild/patches/0008-gallivm-export-target-init-code-for-orc-jit-to-reuse.patch
  runtime-display/mesa/autobuild/patches/0009-gallivm-split-out-generating-LLVM-Mattrs.patch
  runtime-display/mesa/autobuild/patches/0010-gallivm-create-a-pass-manager-wrapper.patch
  runtime-display/mesa/autobuild/patches/0011-llvmpipe-add-gallivm_add_global_mapping.patch
  runtime-display/mesa/autobuild/patches/0012-llvmpipe-make-unnamed-global-have-internal-linkage.patch
  runtime-display/mesa/autobuild/patches/0013-util-detect-RISC-V-architecture.patch
  runtime-display/mesa/autobuild/patches/0014-gallivm-add-riscv-support-to-the-mattrs-setting-code.patch
  runtime-display/mesa/autobuild/patches/0015-llvmpipe-add-function-name-to-gallivm_jit_function.patch
  runtime-display/mesa/autobuild/patches/0016-llvmpipe-tests-add-a-new-test-for-multiple-symbols-f.patch
  runtime-display/mesa/autobuild/patches/0017-llvmpipe-add-an-implementation-with-llvm-orcjit.patch
  runtime-display/mesa/autobuild/patches/0018-llvmpipe-append-partial-mask-to-partial-fs_variant-f.patch
  runtime-display/mesa/autobuild/patches/0019-llvmpipe-add-shader-cache-support-for-ORCJIT-impleme.patch
  runtime-display/mesa/autobuild/patches/0020-util-detect-LoongArch-architecture.patch
  runtime-display/mesa/autobuild/patches/0021-gallivm-add-LoongArch-support-to-the-mattrs-setting-.patch
  runtime-display/mesa/autobuild/patches/0022-llvmpipe-add-LoongArch-support-in-ORCJIT.patch
  runtime-display/mesa/autobuild/patches/0023-vulkan-runtime-Rename-vk_meta_object_list-to-vk_obje.patch
  runtime-display/mesa/autobuild/patches/0024-vulkan-runtime-Split-vk_object_list-into-separate-fi.patch
  runtime-display/mesa/spec
Labels: upgrade

#7713 chromium: update to 127.0.6533.119
  app-web/chromium/autobuild/patches/0001-Fedora-chromium-115-initial_prefs-etc-path.patch.patch
  app-web/chromium/autobuild/patches/0002-Fedora-chromium-77.0.3865.75-no-zlib-mangle.patch.patch
  app-web/chromium/autobuild/patches/0003-Fedora-update-rjsmin-to-1.2.0-to-see-if-Python-3.11-.patch
  app-web/chromium/autobuild/patches/0004-Fedora-chromium-98.0.4758.102-remoting-no-tests.patc.patch
  app-web/chromium/autobuild/patches/0005-Fedora-chromium-126-split-threshold-for-reg-with-hin.patch
  app-web/chromium/autobuild/patches/0006-Debian-ruy-include.patch.patch
  app-web/chromium/autobuild/patches/0007-iwyu-include-cstddef-for-nullptr_t-in-fragment_data_.patch
  app-web/chromium/autobuild/patches/0008-AOSC-TBI-rollup.patch.patch
  app-web/chromium/autobuild/patches/0009-AOSC-TBI-fix-invalid-substition-type.patch.patch
  app-web/chromium/autobuild/patches/0010-AOSC-fix-clang-builtins-path.patch.patch
  app-web/chromium/autobuild/patches/0011-AOSC-TBI-fix-missing-header.patch.patch
  app-web/chromium/autobuild/patches/0012-AOSC-TBI-fix-static-assertion.patch.patch
  app-web/chromium/autobuild/patches/0013-AOSC-TBI-swiftshader.patch.patch
  app-web/chromium/autobuild/patches/0014-AOSC-sandbox.patch.patch
  app-web/chromium/autobuild/patches/0015-AOSC-crashpad.patch.patch
  app-web/chromium/autobuild/patches/0016-AOSC-ffmpeg.patch.patch
  app-web/chromium/autobuild/patches/0017-AOSC-medium-cmodel.patch.patch
  app-web/chromium/autobuild/patches/0018-AOSC-patch.patch
  app-web/chromium/autobuild/patches/0019-IWYU-missing-include-for-usage-of-std-exchange-in-lo.patch
  app-web/chromium/autobuild/patches/0020-IWYU-missing-include-for-usage-of-std-optional-in-en.patch
  app-web/chromium/autobuild/patches/0021-IWYU-missing-include-for-usage-of-std-optional-in-pa.patch
  app-web/chromium/autobuild/patches/0022-chrome-browser-add-missing-dependency.patch
  app-web/chromium/autobuild/patches/0023-chrome-browser-ui-add-missing-dependency.patch
  app-web/chromium/autobuild/patches/0024-Move-chrome-browser-ui-webui_name_variants-to-public.patch
  app-web/chromium/autobuild/patches/0025-Build-LoongArch64-LSX-optimizations-in-libpng.patch
  app-web/chromium/autobuild/patches/0026-Make-more-deps-entries-public_deps-in-chrome-browser.patch
  app-web/chromium/autobuild/patches/0027-Reland-2-linux-build-Enable-fission-for-symbol_level.patch
  app-web/chromium/spec
Labels: upgrade

#7736 jo: new, 1.9
  app-utils/jo/autobuild/defines
  app-utils/jo/spec
Labels: new-packages

#7551 sagemath: new, 10.4
  app-scientific/sagemath/autobuild/beyond
  app-scientific/sagemath/autobuild/build
  app-scientific/sagemath/autobuild/defines
  app-scientific/sagemath/autobuild/patches/0001-Trac-23712-aarch64-support-for-tachyon-spkg.patch
  app-scientific/sagemath/autobuild/patches/0002-fix-always-use-the-latest-autoconf-scripts.patch
  app-scientific/sagemath/autobuild/patches/0003-fix-make-ntl-use-the-latest-ac-scripts.patch
  app-scientific/sagemath/autobuild/patches/0004-fix-make-tachyon-work-on-loongarch64-mips64el-and-ri.patch
  app-scientific/sagemath/autobuild/patches/0005-fix-make-sympow-work-on-loongarch64.patch.loongarch64
  app-scientific/sagemath/spec
Labels: new-package

#7743 oma: update to 1.6.0
  app-admin/oma/spec
Labels: upgrade

#7745 qbittorrent: update to 4.6.6
  app-web/qbittorrent/spec
Labels: upgrade

#7738 polkit: update to 125
  app-admin/polkit/autobuild/defines
  app-admin/polkit/spec
Labels: upgrade

#7748 frp: update to 0.60.0
  app-network/frp/autobuild/defines
  app-network/frp/autobuild/patches/0001-feat-update-go.mod-to-support-loong64-with-latest-ve.patch
  app-network/frp/spec
Labels: upgrade

#7750 Racket: update to 8.14
  lang-lisp/racket/autobuild/beyond
  lang-lisp/racket/autobuild/defines
  lang-lisp/racket/spec
Labels: upgrade
