Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-09, with the labels that each got.

#7867 vim: update to 9.1.0707
  app-editors/vim/01-vim/armv4
  app-editors/vim/01-vim/armv6hf
  app-editors/vim/01-vim/armv7hf
  app-editors/vim/01-vim/i486
  app-editors/vim/01-vim/loongson2f
  app-editors/vim/01-vim/m68k
  app-editors/vim/01-vim/patches/0001-Fix-for-kmscon.patch
  app-editors/vim/01-vim/powerpc
  app-editors/vim/01-vim/ppc64
  app-editors/vim/spec
Labels: upgrade

#7866 zed: update to 0.150.4
  app-editors/zed/spec
Labels: upgrade

#7862 tailscale: update to 1.72.1
  app-network/tailscale/spec
Labels: upgrade

#7864 plymouth: fix blank screen on frame buffer devices
  app-admin/plymouth/autobuild/patches/0001-main-Go-back-to-text-mode-when-quitting-if-appropria.patch
  app-admin/plymouth/autobuild/patches/0002-main-Correctly-switch-back-to-text-mode-if-the-splas.patch
  app-admin/plymouth/spec
Labels: has-fix

#7868 qjackctl: update to 1.0.1
  app-multimedia/qjackctl/autobuild/defines
  app-multimedia/qjackctl/spec
Labels: upgrade

#7869 open-vm-tools: update to 12.4.5
  app-virtualization/open-vm-tools/autobuild/defines
  app-virtualization/open-vm-tools/autobuild/overrides/usr/lib/systemd/system/vgauthd.service
  app-virtualization/open-vm-tools/autobuild/overrides/usr/lib/systemd/system/vmtoolsd.service
  app-virtualization/open-vm-tools/autobuild/postinst
  app-virtualization/open-vm-tools/autobuild/prerm
  app-virtualization/open-vm-tools/spec
Labels: upgrade

#7855 forgejo: update to 8.0.2
  app-web/forgejo/spec
Labels: upgrade, security

#7874 wayland-protocols: update to 1.37
  app-devel/wayland-protocols/spec
Labels: upgrade

#7880 x11-base: downrank all xf86 drivers
  meta-bases/x11-base/autobuild/defines
  meta-bases/x11-base/spec
Labels: dependencies

#7875 aoscbootstrap: update to 0.7.0
  app-utils/aoscbootstrap/spec
Labels: upgrade

#7881 intel-oneapi-basekit: fix package dependency
  app-devel/intel-oneapi-basekit/autobuild/defines
  app-devel/intel-oneapi-basekit/spec
Labels: has-fix, dependencies

#7857 mugshot: update to 0.4.3
  app-utils/mugshot/spec
Labels: upgrade

#7882 sudo: update to 1.9.16
  app-admin/sudo/spec
Labels: upgrade

#7742 jack: update to 1.9.22
  app-multimedia/jack/spec
Labels: upgrade

#7887 ncmpcpp: update to 0.10
  app-multimedia/ncmpcpp/autobuild/build
  app-multimedia/ncmpcpp/spec
Labels: upgrade

#7897 snapper: update to 0.11.2
  app-admin/snapper/spec
Labels: upgrade

#7898 systemd-boot-friend: update to 0.27.3
  app-admin/systemd-boot-friend/spec
Labels: upgrade

#7899 egl-wayland: update to 1.1.16
  runtime-display/egl-wayland/autobuild/defines
  runtime-display/egl-wayland/autobuild/overrides/usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json
  runtime-display/egl-wayland/spec
Labels: upgrade

#7894 coreboot-utils: update to 24.08
  app-admin/coreboot-utils/spec
Labels: upgrade, core

#7889 bandwhich: update to 0.23.0
  app-network/bandwhich/spec
Labels: upgrade

#7858 distorm: update to 3.5.2b
  app-devel/distorm/spec
Labels: upgrade

#7901 yazi: update to 0.3.3
  app-utils/yazi/spec
Labels: upgrade

#7863 cloudflared: update to 2024.8.3
  app-network/cloudflared/spec
Labels: upgrade

#7896 audacity: update to 3.6.2
  app-creativity/audacity/spec
Labels: upgrade

#7903 stress-ng: update to 0.18.03
  app-benchmarks/stress-ng/spec
Labels: upgrade

#7905 scrcpy: update to 2.6.1
  app-devices/scrcpy/spec
Labels: upgrade

#7904 weston: update to 14.0.0
  runtime-display/weston/spec
Labels: upgrade

#7909 xray-plugin: update to 1.8.24
  app-network/xray-plugin/autobuild/beyond
  app-network/xray-plugin/spec
Labels: upgrade

#7911 feishin: update to 0.8.1
  app-multimedia/feishin/spec
Labels: upgrade

#7910 sing-box: update to 1.9.4
  app-network/sing-box/spec
Labels: upgrade

#7908 p-vector: update to 0.6.0
  app-admin/p-vector/spec
Labels: upgrade

#7878 qemu (QEMU): split guest agent (qemu-guest-agent) from main package
  app-virtualization/qemu/01-shared/build
  app-virtualization/qemu/01-shared/overrides/usr/lib/systemd/system/qemu-ga-virtio@.service
  app-virtualization/qemu/34-guest-agent/build
  app-virtualization/qemu/34-guest-agent/defines
  app-virtualization/qemu/34-guest-agent/overrides/usr/lib/systemd/system/qemu-guest-agent.service
  app-virtualization/qemu/34-guest-agent/overrides/usr/lib/udev/rules.d/99-qemu-guest-agent.rules
  app-virtualization/qemu/spec
Labels: dependencies

#7916 kernel-build-common: detect if objtool source code is available
  app-devel/kernel-build-common/autobuild/ab4/build
  app-devel/kernel-build-common/spec
Labels: pre-release

#7915 wireplumber: update to 0.5.6
  app-multimedia/wireplumber/spec
Labels: upgrade

#7912 syncthing: update to 1.27.11
  app-network/syncthing/spec
Labels: upgrade

#7752 u-boot-menu: new, 4.2.3
  app-admin/u-boot-menu/autobuild/build
  app-admin/u-boot-menu/autobuild/conffiles
  app-admin/u-boot-menu/autobuild/defines
  app-admin/u-boot-menu/autobuild/patches/0001-replace-linux-version-script-with-plain-shell-comman.patch
  app-admin/u-boot-menu/autobuild/patches/0002-fix-kernel-path.patch
  app-admin/u-boot-menu/autobuild/patches/0003-customize-configuration-files.patch
  app-admin/u-boot-menu/autobuild/patches/0004-make-the-initrd-matching-pattern-suitable-for-AOSC-s.patch
  app-admin/u-boot-menu/autobuild/postinst
  app-admin/u-boot-menu/autobuild/triggers
  app-admin/u-boot-menu/spec
Labels: new-package

#7917 xviewer: update to 3.4.6
  app-imaging/xviewer/spec
Labels: upgrade

#7914 endless-sky: new, 0.10.8
  app-games/endless-sky/autobuild/beyond
  app-games/endless-sky/autobuild/defines
  app-games/endless-sky/spec
Labels: new-packages

#7922 syncthing: update to 1.27.12
  app-network/syncthing/spec
Labels: upgrade

#7925 logisim-evolution: new, 3.9.0
  app-scientific/logisim-evolution/autobuild/build
  app-scientific/logisim-evolution/autobuild/defines
  app-scientific/logisim-evolution/autobuild/overrides/usr/bin/logisim-evolution
  app-scientific/logisim-evolution/autobuild/overrides/usr/share/applications/logisim-evolution.desktop
  app-scientific/logisim-evolution/spec
Labels: new-packages

#7926 shotcut: fix desktop categories
  app-creativity/shotcut/autobuild/overrides/usr/share/applications/shotcut.desktop
  app-creativity/shotcut/spec
Labels: has-fix

#7918 rustc: update to 1.81.0
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/spec
Labels: upgrade

#7933 oma: update to 1.9.1
  app-admin/oma/spec
Labels: upgrade

#7934 oma: update to 1.9.2
  app-admin/oma/spec
Labels: upgrade

#7936 oma: update to 1.9.3
  app-admin/oma/spec
Labels: upgrade

#7941 praat: update to 6.4.19
  app-scientific/praat/spec
Labels: upgrade

#7940 bitwarden: update to 2024.8.2
  app-utils/bitwarden/spec
Labels: upgrade

#7942 osu-lazer: update to 2024.906.2
  app-games/osu-lazer/spec
Labels: upgrade

#7938 stress-ng: update to 0.18.04
  app-benchmarks/stress-ng/spec
Labels: upgrade

#7945 ripgrep: update to 14.1.1
  app-utils/ripgrep/spec
Labels: upgrade

#7944 oma: update to 1.9.4
  app-admin/oma/spec
Labels: upgrade

#7949 stow: update to 2.4.1
  app-admin/stow/spec
Labels: upgrade

#7950 fuzzel: update to 1.11.0
  app-utils/fuzzel/spec
Labels: upgrade

#7952 fcitx5-pinyin-moegirl: update to 20240909
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#7954 oma: update to 1.9.5
  app-admin/oma/spec
Labels: upgrade

#7930 ca-certs: update to 20240828
  runtime-data/ca-certs/spec
Labels: upgrade

#7955 gc: update to 8.2.8
  runtime-common/gc/spec
Labels: upgrade

#7932 kicad: update to 8.0.5
  app-electronics/kicad/spec
Labels: upgrade

#7963 select-language-gui: resurrect and update to 0.2.1
  app-utils/select-language-gui/autobuild/defines
  app-utils/select-language-gui/autobuild/prepare
  app-utils/select-language-gui/spec
Labels: upgrade

#7969 mesa: revert two DRI patches to prevent the usage of LLVMpipe on Hyper-V virtual machines
  runtime-display/mesa/autobuild/patches/0001-zink-reject-Imagination-proprietary-driver-w-o-geome.patch
  runtime-display/mesa/autobuild/patches/0002-r600-disable-buggy-vc-1-hardware-decoding.patch
  runtime-display/mesa/autobuild/patches/0003-LOONGARCH64-fix-iris_bufmgr.c-set-PAGE_SIZE-as-16384.patch.loongarch64
  runtime-display/mesa/autobuild/patches/0004-Revert-dril-also-create-double-buffered-configs-in-s.patch
  runtime-display/mesa/autobuild/patches/0005-Revert-dril-use-the-super-fallback-path-for-software.patch
  runtime-display/mesa/spec
Labels: bug, has-fix

#7972 feishin: update to 0.9.0
  app-multimedia/feishin/spec
Labels: upgrade

#7973 fisher: update to 4.4.5
  app-shells/fisher/autobuild/build
  app-shells/fisher/spec
Labels: upgrade

#7974 sway-audio-idle-inhibit: update to 0.1.2
  app-utils/sway-audio-idle-inhibit/spec
Labels: upgrade

#7977 intel-ucode: update to 20240910
  runtime-data/intel-ucode/spec
Labels: upgrade, security

#7981 iosevka-fonts: update to 31.6.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#7975 pandoc: update to 3.4
  app-doc/pandoc/spec
Labels: upgrade

#7986 ncmpc: update to 0.50
  app-multimedia/ncmpc/autobuild/beyond
  app-multimedia/ncmpc/autobuild/defines
  app-multimedia/ncmpc/spec
Labels: upgrade

#7987 osu-lazer: update to 2024.911.0
  app-games/osu-lazer/spec
Labels: upgrade

#7989 openssh: revoke more leaked keys
  app-network/openssh/autobuild/config
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_dsa_key
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_dsa_key.pub
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_ecdsa_key
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_ecdsa_key.pub
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_ed25519_key
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_ed25519_key.pub
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_rsa_key
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/aosa-2017-0034/ssh_host_rsa_key.pub
  app-network/openssh/autobuild/overrides/usr/share/doc/openssh/revoked-keys/revoked_hosts
  app-network/openssh/autobuild/postinst
  app-network/openssh/autobuild/templates
  app-network/openssh/spec
Labels: security

#7994 openssh: update revoke instructions and restart daemon on revoke
  app-network/openssh/autobuild/postinst
  app-network/openssh/autobuild/templates
  app-network/openssh/spec
Labels: upgrade

#7998 vscode: update to 1.93.1
  app-editors/vscode/spec
Labels: upgrade

#8000 dkcli: update to 0.4.1
  app-admin/dkcli/spec
Labels: upgrade

#7999 vscodium: update to 1.93.1.24256
  app-editors/vscodium/spec
Labels: upgrade

#8002 fuzzel: update to 1.11.1
  app-utils/fuzzel/spec
Labels: upgrade

#8004 zed: update to 0.152.3
  app-editors/zed/autobuild/patches/0001-cargo-use-default-release-build-settings.patch
  app-editors/zed/spec
Labels: upgrade

#8014 oma: update to 1.10.0
  app-admin/oma/spec
Labels: upgrade

#8009 tailscale: update to 1.74.0
  app-network/tailscale/spec
Labels: upgrade

#8003 zerotier-one: update to 1.14.1
  app-network/zerotier-one/autobuild/patches/0001-Update-dependencies.patch
  app-network/zerotier-one/spec
Labels: upgrade

#7997 binsider: new, 0.1.0
  app-devel/binsider/autobuild/defines
  app-devel/binsider/autobuild/patches/0001-Use-lurk-git-source-to-support-aarch64.patch
  app-devel/binsider/autobuild/patches/0002-Disable-dynamic-feature-in-unsupport-architecture.patch
  app-devel/binsider/spec
Labels: new-packages

#8018 fastfetch: update to 2.24.0
  app-utils/fastfetch/spec
Labels: upgrade

#8017 waybar: update to 0.11.0
  app-utils/waybar/autobuild/patches/0001-fix-tray-revert-ustring-formatting-changes.patch
  app-utils/waybar/autobuild/patches/0002-chore-update-fmt-wrap-to-11.0.2.patch
  app-utils/waybar/spec
Labels: upgrade

#7931 acbs: update to 20240907
  app-devel/acbs/spec
Labels: upgrade

#8022 qpwgraph: new, 0.7.7
  app-multimedia/qpwgraph/autobuild/defines
  app-multimedia/qpwgraph/spec
Labels: new-packages

#8016 rosegarden: update to 24.06
  app-creativity/rosegarden/autobuild/defines
  app-creativity/rosegarden/spec
Labels: upgrade

#8023 qbittorrent: update to 4.6.7
  app-web/qbittorrent/spec
Labels: upgrade

#8034 qsynth: update to 1.0.1
  app-multimedia/qsynth/autobuild/defines
  app-multimedia/qsynth/spec
Labels: upgrade

#8032 git: update to 2.46.1
  app-vcs/git/spec
Labels: upgrade

#7976 orca: drop autostart hack
  desktop-gnome/orca/autobuild/patches/0001-Autostart-on-all-desktops.patch
  desktop-gnome/orca/spec
Labels: has-fix

#8038 abbs-update-checksum: update to 0.2.3
  app-devel/abbs-update-checksum/spec
Labels: upgrade

#8045 slang: update to 2.3.3
  runtime-common/slang/autobuild/build
  runtime-common/slang/autobuild/conffiles
  runtime-common/slang/autobuild/defines
  runtime-common/slang/autobuild/prepare
  runtime-common/slang/spec
Labels: upgrade

#8049 autobuild4: update to 4.3.24
  app-devel/autobuild4/spec
Labels: upgrade

#8048 acbs: update to 20240920
  app-devel/acbs/spec
Labels: upgrade

#8056 openssh: update to 9.9p1
  app-network/openssh/spec
Labels: upgrade

#8015 php: update to 8.3.11
  app-devel/php/spec
Labels: upgrade

#7946 wine: update to 9.17+gecko2.47.4+mono9.2.0
  app-emulation/wine/spec
Labels: upgrade

#8059 alsa-plugins: disable maemo plugins (to fix audacity startup issue)
  runtime-multimedia/alsa-plugins/autobuild/defines
  runtime-multimedia/alsa-plugins/spec
Labels: has-fix

#8064 tailscale: update to 1.74.1
  app-network/tailscale/spec
Labels: upgrade

#8067 lsp-plugins: new, 1.2.17
  app-multimedia/lsp-plugins/autobuild/build
  app-multimedia/lsp-plugins/autobuild/defines
  app-multimedia/lsp-plugins/spec
Labels: new-packages

#8069 liquidsfz: new, 0.3.2
  app-multimedia/liquidsfz/autobuild/defines
  app-multimedia/liquidsfz/spec
Labels: new-packages

#8066 plasma-default-settings: update to 2024.09.2
  runtime-data/plasma-default-settings/spec
Labels: upgrade

#8070 bitwarden: update to 2024.9.0
  app-utils/bitwarden/spec
Labels: upgrade

#8076 oma: update to 1.10.1
  app-admin/oma/spec
Labels: upgrade

#8071 btop: update to 1.4.0
  app-utils/btop/spec
Labels: upgrade

#8072 fastfetch: update to 2.25.0
  app-utils/fastfetch/spec
Labels: upgrade

#8073 iosevka-fonts: update to 31.7.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#8074 praat: update to 6.4.20
  app-scientific/praat/spec
Labels: upgrade

#8075 sarasa-gothic-fonts: update to 1.0.21
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#8078 ostree: update to 2024.8
  app-admin/ostree/spec
Labels: upgrade

#8079 ncmpc: update to 0.51
  app-multimedia/ncmpc/spec
Labels: upgrade

#8010 nginx: update to 1.27.1
  app-web/nginx/spec
Labels: upgrade

#8080 x42-plugins: new, 0.6.0
  app-multimedia/x42-plugins/autobuild/build
  app-multimedia/x42-plugins/autobuild/defines
  app-multimedia/x42-plugins/spec
Labels: new-packages

#8083 fluida.lv2: new, 0.9.2
  app-multimedia/fluida.lv2/autobuild/build
  app-multimedia/fluida.lv2/autobuild/defines
  app-multimedia/fluida.lv2/spec
Labels: new-packages

#8086 oma: update to 1.10.2
  app-admin/oma/spec
Labels: upgrade

#8087 libcamera: update to 0.3.2
  runtime-devices/libcamera/autobuild/beyond
  runtime-devices/libcamera/autobuild/defines
  runtime-devices/libcamera/spec
Labels: upgrade

#8088 git: update to 2.46.2
  app-vcs/git/spec
Labels: upgrade

#8094 binutils: add support for OUTPUT_FORMAT("binary") on LoongArch
  app-devel/binutils/01-main/patches/0002-LoongArch-Add-support-for-OUTPUT_FORMAT-binary.patch
  app-devel/binutils/spec
Labels: pre-release

#8093 praat: update to 6.4.21
  app-scientific/praat/spec
Labels: upgrade

#8101 plasma-default-settings: update to 2024.09.3
  runtime-data/plasma-default-settings/spec
Labels: upgrade

#8095 showmethekey: update to 1.14.0
  app-utils/showmethekey/autobuild/defines
  app-utils/showmethekey/spec
Labels: upgrade

#8102 apt: rework current stable package
  app-admin/apt/autobuild/patches/0001-Hack-disable-seccomp-for-riscv64.patch.riscv64
  app-admin/apt/autobuild/patches/0001-fix-CMake-Documentation.cmake-fix-XSL-stylesheets-in.patch
  app-admin/apt/autobuild/patches/0002-fix-completions-do-not-assume-RPM-even-if-etc-debian.patch
  app-admin/apt/autobuild/patches/0002-fix-xsl-path.patch
  app-admin/apt/autobuild/patches/0003-AFTERGLOW-hack-CMakeLists.txt-disable-libseccomp-eve.patch.retro
  app-admin/apt/autobuild/patches/0004-Actually-disable-seccomp.patch.retro
  app-admin/apt/spec
Labels: rework

#7840 screen: update to 5.0.0
  app-utils/screen/autobuild/defines
  app-utils/screen/spec
Labels: upgrade

#8108 pipewire: update to 1.2.5
  app-multimedia/pipewire/spec
Labels: upgrade

#8109 libvpl: update to 2.13.0
  runtime-multimedia/libvpl/spec
Labels: upgrade

#8117 typos: new, 1.24.6
  app-utils/typos/autobuild/defines
  app-utils/typos/spec
Labels: new-packages

#8104 tilda: update to 2.0.0
  app-utils/tilda/spec
Labels: upgrade

#8115 libcava: update to 0.10.3
  runtime-multimedia/libcava/spec
Labels: upgrade

#8122 feishin: update to 0.10.1
  app-multimedia/feishin/spec
Labels: upgrade

#8121 picom: update to 12.1
  desktop-wm/picom/autobuild/defines
  desktop-wm/picom/spec
Labels: upgrade

#8107 cmake: update to 3.30.4
  app-devel/cmake/spec
Labels: upgrade

#8123 mesa: update to 24.2.3+dxheaders1.614.1
  runtime-display/mesa/spec
Labels: upgrade

#8126 smplayer (SMPlayer): update to 24.5.0
  app-multimedia/smplayer/autobuild/defines
  app-multimedia/smplayer/autobuild/patches/0001-fix-qt-5.5.patch
  app-multimedia/smplayer/autobuild/patches/0002-AOSC-Use-Autobuild3-flags.patch
  app-multimedia/smplayer/autobuild/prepare
  app-multimedia/smplayer/spec
Labels: upgrade
