Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-02, with the labels that each got.

#5236 ast-grep: update to 0.18.0
  app-devel/ast-grep/autobuild/beyond
  app-devel/ast-grep/spec
Labels: upgrade

#5242 vscode: update to 1.86.0
  app-editors/vscode/autobuild/defines
  app-editors/vscode/spec
Labels: upgrade

#5101 httpd (Apache HTTPD): update to 2.4.58
  app-web/httpd/autobuild/build
  app-web/httpd/autobuild/defines
  app-web/httpd/autobuild/overrides/usr/lib/sysusers.d/httpd.conf
  app-web/httpd/autobuild/postinst
  app-web/httpd/autobuild/prepare
  app-web/httpd/autobuild/usergroup
  app-web/httpd/spec
Labels: upgrade

#5244 autobuild4: update to 4.0.16
  app-devel/autobuild4/spec
Labels: upgrade

#5247 acbs (Autobuild CI Build System): update to 20240124
  app-devel/acbs/spec
Labels: upgrade

#5245 prismlauncher: update to 8.0
  app-games/prismlauncher/spec
Labels: upgrade

#5250 autobuild4: update to 4.0.17
  app-devel/autobuild4/spec
Labels: upgrade

#5241 perl (Perl): update to 5.36.3
  lang-perl/perl/autobuild/build
  lang-perl/perl/autobuild/overrides/etc/bashrc.d/perl.sh
  lang-perl/perl/autobuild/prepare
  lang-perl/perl/spec
Labels: upgrade

#5246 aoscbootstrap: update to 0.4.4
  app-utils/aoscbootstrap/spec
Labels: upgrade

#5253 autobuild4: update to 4.0.18
  app-devel/autobuild4/spec
Labels: upgrade

#5261 autobuild4: update to 4.0.19
  app-devel/autobuild4/spec
Labels: upgrade

#5257 picom: update to 11.1
  desktop-wm/picom/spec
Labels: upgrade

#5258 sudo: update to 1.9.15p5
  app-admin/sudo/autobuild/build
  app-admin/sudo/autobuild/conffiles
  app-admin/sudo/spec
Labels: upgrade

#5254 dejagnu: update to 1.6.3 and mark as noarch
  app-devel/dejagnu/autobuild/defines
  app-devel/dejagnu/spec
Labels: upgrade, noarch

#5256 cava: update to 0.10.1
  app-multimedia/cava/spec
Labels: upgrade

#5263 libpng: update to 1.6.42
  runtime-imaging/libpng/autobuild/armv4
  runtime-imaging/libpng/autobuild/armv6hf
  runtime-imaging/libpng/autobuild/armv7hf
  runtime-imaging/libpng/autobuild/beyond
  runtime-imaging/libpng/autobuild/defines
  runtime-imaging/libpng/autobuild/defines.stage2
  runtime-imaging/libpng/autobuild/i486
  runtime-imaging/libpng/autobuild/loongson2f
  runtime-imaging/libpng/autobuild/m68k
  runtime-imaging/libpng/autobuild/patches/0001-Import-APNG-patch-1.6.40.patch
  runtime-imaging/libpng/autobuild/patches/libpng-fix-arm-neon.patch
  runtime-imaging/libpng/autobuild/powerpc
  runtime-imaging/libpng/autobuild/ppc64
  runtime-imaging/libpng/autobuild/prepare
  runtime-imaging/libpng/spec
Labels: upgrade

#5274 acbs (Autobuild CI Build System): update to 20240207
  app-devel/acbs/spec
Labels: upgrade

#5276 autobuild4: update to 4.0.20
  app-devel/autobuild4/spec
Labels: upgrade

#5273 gc: update to 8.2.6
  runtime-common/gc/spec
Labels: upgrade

#5278 autobuild4: update to 4.0.21
  app-devel/autobuild4/spec
Labels: upgrade

#5279 autobuild4: update to 4.0.22
  app-devel/autobuild4/spec
Labels: upgrade

#5268 aosc-findupdate: update to 0.3.2
  app-utils/aosc-findupdate/spec
Labels: upgrade

#5266 aoscbootstrap: update to 0.4.5
  app-utils/aoscbootstrap/spec
Labels: upgrade

#5280 kodi (KODI): update to 20.3
  app-multimedia/kodi/autobuild/patches/0001-settings-force-Arial-based-fonts.patch
  app-multimedia/kodi/autobuild/patches/0002-Adjust-addons.patch
  app-multimedia/kodi/autobuild/patches/0003-Fix-build-for-other-architectures.patch
  app-multimedia/kodi/autobuild/patches/0004-allow-separate-windowing-binaries-being-launched-fro.patch
  app-multimedia/kodi/autobuild/patches/0005-ffmpeg-fix-build-with-binutils-update.patch
  app-multimedia/kodi/spec
Labels: upgrade

#5287 bash-git-status: update to 0.2.2
  app-vcs/bash-git-status/spec
Labels: upgrade

#5289 chore: promote loongarch64 as primary architecture
  .github/PULL_REQUEST_TEMPLATE
Labels: meta

#5296 gdb: update to 14.1
  app-devel/gdb/spec
Labels: upgrade

#5294 vim: update to 9.1.0095
  app-editors/vim/01-vim/patches/0002-remove-nolto-flag-from-perl-libs.patch
  app-editors/vim/spec
Labels: upgrade

#5297 autobuild4: update to 4.0.23
  app-devel/autobuild4/spec
Labels: upgrade

#5299 aoscdk-rs (DeployKit): update to 1.0.2
  app-admin/aoscdk-rs/spec
Labels: upgrade, dependencies

#5300 discord: update to 0.0.43
  app-web/discord/spec
Labels: upgrade

#5292 inputplug: new, 0.4.0
  app-utils/inputplug/autobuild/beyond
  app-utils/inputplug/autobuild/defines
  app-utils/inputplug/autobuild/patches/0001-Update-nix-to-0.27.0-to-fix-build.patch
  app-utils/inputplug/autobuild/patches/0002-Run-cargo-update-and-update-x11rb-to-0.13.patch
  app-utils/inputplug/autobuild/patches/0003-Use-Rust-2021-Edition.patch
  app-utils/inputplug/autobuild/patches/0004-Apply-cargo-fmt-and-cargo-clippy-suggest.patch
  app-utils/inputplug/autobuild/prepare
  app-utils/inputplug/spec
Labels: new-packages

#5298 zsh-syntax-highlighting: update to 0.8.0
  app-shells/zsh-syntax-highlighting/spec
Labels: upgrade

#5303 autoconf: update to 2.72
  app-devel/autoconf/spec
Labels: upgrade

#5301 LLVM Rework for RISCV
  app-devel/llvm/01-runtime/build
  app-devel/llvm/01-runtime/patches/0001-Add-AOSC-exclusive-target-tuples.patch
  app-devel/llvm/01-runtime/patches/0002-Fix-fuzzer-objects-building-when-LTO-is-enabled.patch
  app-devel/llvm/01-runtime/patches/0003-Fix-MSVC-detection.patch
  app-devel/llvm/01-runtime/patches/0004-mips-Add-stub-for-mips64-LLDB-impl.patch
  app-devel/llvm/01-runtime/patches/0005-mips-Fix-compiler-rt-tailcall-on-mips.patch
  app-devel/llvm/01-runtime/patches/0006-mips-Add-stub-for-lldb-arch-functions-on-loongson3.patch
  app-devel/llvm/01-runtime/patches/0007-mips-HACK-force-enable-cacheflush-function.patch
  app-devel/llvm/01-runtime/patches/0008-mips-Fix-build-of-LinuxSignals-on-Mips.patch
  app-devel/llvm/01-runtime/patches/0009-mips-Use-pc-relative-relocations-in-.eh_frame.patch
  app-devel/llvm/01-runtime/patches/0010-mips-Fix-Mips-N64-detection-and-set-znotext-as-defau.patch
  app-devel/llvm/01-runtime/patches/0011-rust-Add-accessors-for-MCSubtargetInfo-CPU-and-Featu.patch
  app-devel/llvm/01-runtime/patches/0012-rust-Compile-with-MT-on-MSVC.patch
  app-devel/llvm/01-runtime/patches/0013-rust-Comment-out-__builtin_available-use-21.patch
  app-devel/llvm/01-runtime/patches/0014-rust-Changes-needed-for-x86_64-fortanix-unknown-sgx-.patch
  app-devel/llvm/01-runtime/patches/0015-rust-Fix-FreeBSD-12-build.patch
  app-devel/llvm/01-runtime/patches/0016-RISCV-Support-R_RISCV_SET_ULEB128-R_RISCV_SUB_ULEB12.patch
  app-devel/llvm/01-runtime/patches/0017-ELF-Support-R_RISCV_SET_ULEB128-R_RISCV_SUB_ULEB128-.patch
  app-devel/llvm/01-runtime/patches/0018-ELF-Support-R_RISCV_SET_ULEB128-R_RISCV_SUB_ULEB128-.patch
  app-devel/llvm/spec
Labels: rework

#5283 lsd: new, 1.0.0
  app-utils/lsd/autobuild/defines
  app-utils/lsd/spec
Labels: new-packages

#5304 atuin: update to 18.0.1
  app-utils/atuin/autobuild/patches/0001-Fix-loongarch64-build.patch.loongarch64
  app-utils/atuin/spec
Labels: upgrade

#5307 tmux: update to 3.4
  app-utils/tmux/autobuild/patches/0001-Fix-utf8proc.h-location.patch
  app-utils/tmux/autobuild/patches/0001-Fix-utf8proc_h-location.patch
  app-utils/tmux/spec
Labels: upgrade

#5310 btop (BTOP++): update to 1.3.2
  app-utils/btop/autobuild/build
  app-utils/btop/spec
Labels: upgrade

#5311 ast-grep: update to 0.19.0
  app-devel/ast-grep/autobuild/defines
  app-devel/ast-grep/spec
Labels: upgrade

#5315 fwupd: update to 1.9.13
  app-admin/fwupd/spec
Labels: upgrade

#5309 lftp: update to 4.9.2
  app-network/lftp/autobuild/patches/0001-Fedora-lftp-4.9.2-cdefs.patch
  app-network/lftp/autobuild/prepare
  app-network/lftp/spec
Labels: upgrade

#5319 oma: update to 1.2.13
  app-admin/oma/autobuild/postinst
  app-admin/oma/spec
Labels: upgrade

#5323 grub-customizer (GRUB Customizer): new, 5.2.4
  app-admin/grub-customizer/autobuild/defines
  app-admin/grub-customizer/autobuild/overrides/etc/grub-customizer/grub.cfg
  app-admin/grub-customizer/spec
Labels: new-packages

#5324 Mesa LoongArch LLVMPipe fix
  runtime-display/mesa/autobuild/patches/0003-llvmpipe-add-LoongArch-support-in-ORCJIT.patch
  runtime-display/mesa/spec
Labels: has-fix

#5321 obs-studio (OBS Studio): fix build with autobuild4
  app-multimedia/obs-studio/autobuild/beyond
  app-multimedia/obs-studio/spec
Labels: has-fix

#5316 rav1e: update to 0.7.1
  runtime-multimedia/rav1e/autobuild/patches/0001-Set-lto-to-true.patch
  runtime-multimedia/rav1e/autobuild/patches/0001-rust-lto.diff
  runtime-multimedia/rav1e/spec
Labels: upgrade

#5326 grub-customizer (GRUB Customizer): fix .desktop entry
  app-admin/grub-customizer/autobuild/patches/0001-misc-use-pkexec-in-.desktop-entry.patch
  app-admin/grub-customizer/spec
Labels: has-fix

#5329 libpgm fix build
  runtime-network/libpgm/autobuild/patches/0002-Fedora-openpgm-03-pkgconfig.patch
  runtime-network/libpgm/spec
Labels: has-fix

#5330 sshpass: fix wrong package section
  app-network/sshpass/autobuild/defines
  app-network/sshpass/spec
Labels: has-fix

#5328 ddcutil: update to 2.1.3
  app-utils/ddcutil/autobuild/defines
  app-utils/ddcutil/spec
Labels: upgrade

#5334 solid: fix loongarch64 /proc/cpuinfo parsing
  desktop-kde/solid/autobuild/patches/0001-cpuinfo-add-loongarch64-proc-cpuinfo-parsing.patch
  desktop-kde/solid/spec
Labels: has-fix

#5340 luajit: fix build on arm64
  lang-lua/luajit/autobuild/build
  lang-lua/luajit/autobuild/defines
  lang-lua/luajit/spec
Labels: has-fix

#5341 fsearch: update to 0.2.3
  app-utils/fsearch/spec
Labels: upgrade

#5337 rdfind: update to 1.6.0
  app-utils/rdfind/spec
Labels: upgrade

#5344 gifsicle: update to 1.95
  app-utils/gifsicle/spec
Labels: upgrade

#5335 peewee: new, 3.17.1
  lang-python/peewee/autobuild/defines
  lang-python/peewee/spec
Labels: new-packages

#5336 lunarsolarconverter: new, 1.1.0
  lang-python/lunarsolarconverter/autobuild/defines
  lang-python/lunarsolarconverter/spec
Labels: new-packages

#5348 ast-grep: update to 0.19.2
  app-devel/ast-grep/spec
Labels: upgrade

#5349 grc: update to 1.13
  app-utils/grc/spec
Labels: upgrade

#5331 open-vm-tools: update to 12.3.5
  app-virtualization/open-vm-tools/spec
Labels: upgrade

#5249 bcachefs-tools: new, 1.4.1
  app-admin/bcachefs-tools/autobuild/beyond
  app-admin/bcachefs-tools/autobuild/build
  app-admin/bcachefs-tools/autobuild/defines
  app-admin/bcachefs-tools/spec
Labels: new-packages

#5285 fpc: update to 3.2.2
  lang-pascal/fpc/autobuild/defines
  lang-pascal/fpc/autobuild/patches/fix-weak-symbols-on-aarch64.patch
  lang-pascal/fpc/autobuild/prepare
  lang-pascal/fpc/spec
Labels: upgrade

#5351 texlive (TeXLive): rebuild against latest zlib
  app-doc/texlive/spec
Labels: abi-break

#5354 qt-6: update to 6.6.2
  runtime-desktop/qt-6/autobuild/patches/0005-loongarch64.patch.loongarch64
  runtime-desktop/qt-6/spec
Labels: upgrade

#5356 fuse-3: update to 3.16.2
  app-admin/fuse-3/02-fuse-3/patches/do-not-mknod-dev-fuse-on-install.patch
  app-admin/fuse-3/spec
Labels: upgrade

#5342 luajit: update to 2.1.0b3+git20240222
  lang-lua/luajit/autobuild/build
  lang-lua/luajit/spec
Labels: upgrade

#5358 oma: update to 1.2.14
  app-admin/oma/spec
Labels: upgrade

#5360 zfs: update to 2.2.3
  app-admin/zfs/autobuild/build
  app-admin/zfs/spec
Labels: upgrade

#5363 CRIU Rework 20240226
  app-admin/criu/autobuild/defines
  app-admin/criu/spec
Labels: rework

#5343 hmcl: new, 3.5.5.236
  app-games/hmcl/autobuild/build
  app-games/hmcl/autobuild/defines
  app-games/hmcl/autobuild/overrides/usr/bin/hmcl
  app-games/hmcl/autobuild/overrides/usr/share/applications/hmcl.desktop
  app-games/hmcl/spec
Labels: new-packages

#5362 hexedit: update to 1.6
  app-utils/hexedit/spec
Labels: upgrade

#5368 fish: fix wildcard globbing
  app-shells/fish/autobuild/patches/0001-Revert-wildcard-Remove-useless-access-call-for-trail.patch
  app-shells/fish/spec
Labels: has-fix

#5367 btrfs-progs: update to 6.7.1
  app-admin/btrfs-progs/spec
Labels: upgrade

#5365 autobuild4: update to 4.0.25
  app-devel/autobuild4/spec
Labels: upgrade

#5372 xreader: update to 3.8.5
  app-doc/xreader/spec
Labels: upgrade

#5371 argyllcms: update to 3.1.0
  app-imaging/argyllcms/spec
Labels: upgrade

#5377 you-get: update to 0.4.1650
  app-multimedia/you-get/spec
Labels: upgrade

#5375 git (Git): update to 2.44.0
  app-vcs/git/spec
Labels: upgrade

#5391 ccache: update to 4.9.1
  app-devel/ccache/spec
Labels: upgrade
