Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-03, with the labels that each got.

#5394 autobuild4: update to 4.0.26
  app-devel/autobuild4/spec
Labels: upgrade

#5381 wine (Wine Is Not an Emulator): update to 9.3
  app-emulation/wine/spec
Labels: upgrade

#5387 mold: update to 2.4.0
  app-devel/mold/spec
Labels: upgrade

#5352 libLoL 0.1.4
  runtime-emulation/liblol/autobuild/build
  runtime-emulation/liblol/autobuild/patches/glibc/0001-add-old-world-abi-compatibility.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0002-add-sigset-ops.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0003-add-signal-functions.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0004-add-sigaction-ucontext-compat.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0005-add-stubs-for-signal-related-io-funcs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0006-add-syscall-fallback-for-stat-at.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0007-add-more-pthread-symbols.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0008-remove-clone3-for-compatibility-with-qq.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0009-able-to-prepend-trusted-dirs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0009-prepend-trusted-dirs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0010-Add-___brk_addr-symbol.patch
  runtime-emulation/liblol/autobuild/patches/patchelf/0001-add-remap-symvers.patch
  runtime-emulation/liblol/spec
  runtime-emulation/liblol/spec.main
Labels: upgrade

#5388 micro: new, 2.0.13
  app-editors/micro/autobuild/build
  app-editors/micro/autobuild/defines
  app-editors/micro/autobuild/patches/0001-remove-nodisplay-in-desktop-file.patch
  app-editors/micro/spec
Labels: new-packages

#5382 haruna (Haruna Media Player): update to 0.12.3
  desktop-kde/haruna/spec
Labels: upgrade

#5400 wezterm: update to 20240203+110809+5046fc22
  app-utils/wezterm/autobuild/defines
  app-utils/wezterm/spec
Labels: upgrade

#5398 LLVM: Enable full set for loongarch64
  app-devel/llvm/01-runtime/defines
  app-devel/llvm/01-runtime/defines.stage2
  app-devel/llvm/02-compiler/build
  app-devel/llvm/spec
Labels: loongarch64

#5393 mesa (Mesa 3D Graphics Library): update to 24.0.2
  runtime-display/mesa/autobuild/defines
  runtime-display/mesa/autobuild/patches/0001-llvmpipe-make-unnamed-global-have-internal-linkage.patch
  runtime-display/mesa/autobuild/patches/0002-llvmpipe-add-an-implementation-with-llvm-orcjit.patch
  runtime-display/mesa/autobuild/patches/0003-llvmpipe-add-LoongArch-support-in-ORCJIT.patch
  runtime-display/mesa/autobuild/patches/0004-llvmpipe-append-partial-mask-to-partial-fs_variant-f.patch
  runtime-display/mesa/spec
Labels: upgrade, has-fix

#5411 htop: update to 3.3.0
  app-admin/htop/autobuild/patches/0001-BACKPORT-Remove-LXC-special-handling-for-the-CPU-count.patch
  app-admin/htop/spec
Labels: upgrade

#5406 redis: update to 7.2.4
  app-database/redis/spec
Labels: upgrade

#5405 sqlite: update to 3.45.1
  app-database/sqlite/spec
Labels: upgrade

#5370 fontforge: update to 20230101
  app-creativity/fontforge/autobuild/patches/0001-fsys-resolve-symlinks-on-nix-platforms.patch
  app-creativity/fontforge/spec
Labels: upgrade

#5404 mesa: fix xwayland apps requiring new vulkan extensions
  runtime-display/mesa/autobuild/patches/0005-vulkan-dispatch-table-add-an-uncompacted-version.patch
  runtime-display/mesa/spec
Labels: has-fix, new-packages

#5409 aria2: update to 1.37.0
  app-web/aria2/spec
Labels: upgrade

#5414 ninja: update to 1.11.1
  app-devel/ninja/spec
Labels: upgrade

#5410 cryptsetup: update to 2.7.0
  app-admin/cryptsetup/spec
Labels: upgrade

#5416 wofi: update to 1.4.1
  app-utils/wofi/spec
Labels: upgrade

#5408 php: update to 8.3.3
  app-devel/php/spec
Labels: upgrade

#5383 gparted (GParted): update to 1.6.0
  app-admin/gparted/spec
Labels: upgrade

#5417 cava: enable all audio system support
  app-multimedia/cava/autobuild/defines
  app-multimedia/cava/spec
Labels: rework

#5403 Firefox: update to 123.0
  app-web/firefox/autobuild/defines
  app-web/firefox/autobuild/patches/0001-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0001-Disable-libyuf-asm-on-MIPS2.patch
  app-web/firefox/autobuild/patches/0003-Enable-WebRTC-for-LoongArch.patch
  app-web/firefox/autobuild/patches/0003-LoongArchLinux-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0004-Fix-libyuv-build-with-LSX-LASX.patch
  app-web/firefox/autobuild/patches/0005-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0005-Remove-architectural-limit-on-VA-API-support.patch
  app-web/firefox/autobuild/patches/0006-Enable-WebRTC-for-LoongArch.patch
  app-web/firefox/autobuild/prepare
  app-web/firefox/spec
Labels: upgrade

#5420 oma: update to 1.2.16
  app-admin/oma/spec
Labels: upgrade

#5418 steam (Steam): update to 1.0.0.79
  app-games/steam/autobuild/defines
  app-games/steam/autobuild/overrides/usr/share/appdata/steam.appdata.xml
  app-games/steam/autobuild/overrides/usr/share/applications/steam.desktop
  app-games/steam/autobuild/patches/0001-fix-steam.desktop-make-sure-Steam-recognises-our-32-.patch
  app-games/steam/spec
Labels: upgrade

#5412 glances: new, 3.4.0.2
  app-admin/glances/autobuild/defines
  app-admin/glances/spec
Labels: new-packages

#5423 seatd: update to 0.8.0
  app-admin/seatd/autobuild/beyond
  app-admin/seatd/autobuild/defines
  app-admin/seatd/autobuild/overrides/usr/lib/sysusers.d/seatd.conf
  app-admin/seatd/autobuild/postinst
  app-admin/seatd/spec
Labels: upgrade

#5422 texlive: allow TeX to run extractbb by default (to fix many document building issues)
  app-doc/texlive/autobuild/overrides/etc/texmf/web2c/texmf.cnf
  app-doc/texlive/spec
Labels: has-fix

#5424 mako-notification-daemon: update to 1.8.0
  app-utils/mako-notification-daemon/autobuild/defines
  app-utils/mako-notification-daemon/spec
Labels: upgrade

#5421 aoscdk-rs: update to 1.0.3
  app-admin/aoscdk-rs/spec
Labels: upgrade

#5413 gettext: update to 0.22.5
  app-devel/gettext/autobuild/patches/0001-Tweak-libc-config_h-for-IEEE-long-double-compatibility.patch.ppc64el
  app-devel/gettext/spec
Labels: upgrade

#5428 oma: update to 1.2.17
  app-admin/oma/spec
Labels: upgrade

#5431 autobuild4: update to 4.0.29
  app-devel/autobuild4/spec
Labels: upgrade

#5434 WezTerm: enable Wayland support
  app-utils/wezterm/autobuild/defines
  app-utils/wezterm/spec
Labels: enhancement

#5436 Feishin: update to 0.6.0
  app-multimedia/feishin/autobuild/patches/0001-app-outlet-use-usr-bin-mpv-as-fallback-MPV-path.patch
  app-multimedia/feishin/autobuild/patches/0001-mpv-settings-use-usr-bin-mpv-as-default-path.patch
  app-multimedia/feishin/spec
Labels: upgrade

#5435 discord: update to 0.0.44
  app-web/discord/spec
Labels: upgrade

#5438 python-3 rework for mips64r6el
  lang-python/python-3/autobuild/defines
Labels: rework, cip-pilot

#5419 graphviz: update to 10.0.1
  app-doc/graphviz/autobuild/defines
  app-doc/graphviz/autobuild/prepare
  app-doc/graphviz/spec
Labels: upgrade

#5440 iperf3: update to 3.16
  app-network/iperf3/spec
Labels: upgrade

#5439 bird: update to 2.14
  app-network/bird/spec
Labels: upgrade

#5443 polkit: update to 124
  app-admin/polkit/autobuild/overrides/usr/lib/sysusers.d/polkit.conf
  app-admin/polkit/autobuild/postinst
  app-admin/polkit/autobuild/usergroup
  app-admin/polkit/spec
Labels: upgrade

#5442 colord: update to 1.4.7
  app-admin/colord/autobuild/overrides/usr/lib/sysusers.d/colord.conf
  app-admin/colord/autobuild/postinst
  app-admin/colord/autobuild/usergroup
  app-admin/colord/spec
Labels: upgrade

#5447 stress: update to 1.0.7
  app-benchmarks/stress/autobuild/patches/0001-Docs-need-update-for-newer-texinfo.patch
  app-benchmarks/stress/spec
Labels: upgrade

#5448 libjxl rework for mips64r6el
  runtime-imaging/libjxl/autobuild/defines
Labels: rework, cip-pilot

#5445 pulseaudio: update to 17.0
  app-multimedia/pulseaudio/autobuild/beyond
  app-multimedia/pulseaudio/autobuild/defines
  app-multimedia/pulseaudio/autobuild/defines.stage2
  app-multimedia/pulseaudio/autobuild/overrides/usr/lib/sysusers.d/pulseaudio.conf
  app-multimedia/pulseaudio/autobuild/postinst
  app-multimedia/pulseaudio/autobuild/prepare
  app-multimedia/pulseaudio/autobuild/usergroup
  app-multimedia/pulseaudio/spec
Labels: upgrade

#5456 repo: update to 2.43
  app-devel/repo/spec
Labels: upgrade

#5455 z3: update to 4.13.0
  app-devel/z3/spec
Labels: upgrade

#5457 nasm: update to 2.16.01
  app-devel/nasm/autobuild/beyond
  app-devel/nasm/autobuild/build
  app-devel/nasm/autobuild/defines
  app-devel/nasm/spec
Labels: upgrade

#5458 patchelf: update to 0.18.0
  app-devel/patchelf/spec
Labels: upgrade

#5462 sqlcipher: update to 4.5.6
  app-database/sqlcipher/spec
Labels: upgrade

#5463 emacs: update to 29.2
  app-editors/emacs/spec
Labels: upgrade

#5459 lynx: update to 2.9.0
  app-web/lynx/spec
Labels: upgrade

#5460 elinks: update to 0.17.0
  app-web/elinks/autobuild/patches/0001-Fedora-0000-elinks-0.15.0-ssl-noegd.patch
  app-web/elinks/autobuild/patches/0002-Fedora-0001-elinks-0.15.1-utf_8_io-default.patch
  app-web/elinks/autobuild/patches/0003-Fedora-elinks-0.11.0-getaddrinfo.patch
  app-web/elinks/autobuild/patches/0004-Fedora-0004-elinks-0.15.0-sysname.patch
  app-web/elinks/autobuild/patches/0005-Fedora-0005-elinks-0.15.0-xterm.patch
  app-web/elinks/autobuild/patches/0006-Fedora-0006-elinks-0.16.0-libidn2.patch
  app-web/elinks/autobuild/patches/0007-Fedora-elinks-0.12pre6-list_is_singleton.patch
  app-web/elinks/spec
Labels: upgrade

#5461 httpie: update to 3.2.2
  app-web/httpie/spec
Labels: upgrade

#5465 fcitx5-pinyin-moegirl: update to 20240309
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#5467 subversion: update to 1.14.3
  app-vcs/subversion/spec
Labels: upgrade

#5464 busybox update to 1.36.1
  app-utils/busybox/autobuild/config
  app-utils/busybox/spec
Labels: upgrade

#5454 musl: update to 1.12.5
  app-devel/musl/autobuild/defines
  app-devel/musl/autobuild/prepare
  app-devel/musl/spec
Labels: upgrade

#5470 feh: update to 3.10.2
  app-imaging/feh/autobuild/build
  app-imaging/feh/autobuild/defines
  app-imaging/feh/spec
Labels: upgrade

#5430 oma: update to 1.2.19
  app-admin/oma/spec
Labels: upgrade

#5473 ly: new, 0.6.0
  desktop-displaymanagers/ly/autobuild/build
  desktop-displaymanagers/ly/autobuild/defines
  desktop-displaymanagers/ly/spec
Labels: new-package

#5478 Kvantum: update to 1.0.10, enable Qt 6 support
  desktop-kde/kvantum/autobuild/build
  desktop-kde/kvantum/autobuild/defines
  desktop-kde/kvantum/spec
Labels: upgrade

#5477 vasm: update to 1.9f
  app-devel/vasm/spec
Labels: upgrade

#5479 bzip3: new, 1.4.0
  app-utils/bzip3/autobuild/defines
  app-utils/bzip3/spec
Labels: new-packages

#5493 quickjs: update to 2024.01.13
  lang-js/quickjs/autobuild/patches/0001-Disable-strip-for-debug-symbol-in-AOSC.patch
  lang-js/quickjs/autobuild/prepare
  lang-js/quickjs/spec
Labels: upgrade

#5488 jpegoptim: update to 1.5.5
  app-utils/jpegoptim/spec
Labels: upgrade

#5487 font-manager: update to 0.8.8
  app-utils/font-manager/spec
Labels: upgrade

#5489 libxmlb update to 0.3.15
  runtime-common/libxmlb/spec
Labels: upgrade

#5486 valgrind: update to 3.22.0
  app-devel/valgrind/autobuild/defines
  app-devel/valgrind/autobuild/patches/0001-cachegrind-improvements.patch
  app-devel/valgrind/autobuild/patches/0002-helgrind-race-supp.patch
  app-devel/valgrind/autobuild/patches/0002-valgrind-3.9.0-helgrind-race-supp.patch
  app-devel/valgrind/autobuild/patches/0003-ldso-supp.patch
  app-devel/valgrind/autobuild/patches/0004-some-Wl-z-now.patch
  app-devel/valgrind/spec
Labels: upgrade

#5496 nodejs (Node.js): security update to 20.11.1
  lang-js/nodejs/autobuild/defines
  lang-js/nodejs/autobuild/patches/0001-Debian-hack-disable-segfaulting-jitless-option.patch
  lang-js/nodejs/spec
Labels: upgrade, security

#5498 v2raya: update to 2.2.5.1
  app-network/v2raya/autobuild/defines
  app-network/v2raya/spec
Labels: upgrade, amd64, arm64, loongson3, riscv64

#5497 plocate: update to 1.1.22
  app-utils/plocate/spec
Labels: upgrade

#5501 dunst: update to 1.10.0
  app-utils/dunst/autobuild/build
  app-utils/dunst/autobuild/defines
  app-utils/dunst/spec
Labels: upgrade

#5505 PrismLauncher: update to 8.2
  app-games/prismlauncher/spec
Labels: upgrade

#5504 SwayWM: fix input method candidate window
  desktop-wm/sway/autobuild/patches/0001-text_input-Implement-input-method-popups.patch
  desktop-wm/sway/autobuild/patches/0002-chore-fractal-scale-handle.patch
  desktop-wm/sway/autobuild/patches/0003-chore-left_pt-on-method-popup.patch
  desktop-wm/sway/spec
Labels: has-fix

#5499 plzip: update to 1.11
  app-utils/plzip/autobuild/build
  app-utils/plzip/autobuild/defines
  app-utils/plzip/spec
Labels: upgrade

#5506 Feishin: update to 0.6.1
  app-multimedia/feishin/spec
Labels: upgrade

#5508 acbs: update to 20240315
  app-devel/acbs/spec
Labels: upgrade

#5512 yosys: update to 0.39
  app-electronics/yosys/autobuild/build
  app-electronics/yosys/autobuild/defines
  app-electronics/yosys/autobuild/patches/0001-Fix-global-cache-destruction-in-IdString-class.patch
  app-electronics/yosys/autobuild/prepare
  app-electronics/yosys/spec
Labels: upgrade

#5514 oma: update to 1.2.21
  app-admin/oma/spec
Labels: upgrade

#5517 imchooser: update to 20240317
  app-i18n/imchooser/autobuild/build
  app-i18n/imchooser/spec
Labels: upgrade

#5518 acbs (Autobuild CI Build System): update to 20240317
  app-devel/acbs/spec
Labels: upgrade

#5527 rmlint: update to 2.10.2
  app-utils/rmlint/spec
Labels: upgrade

#5533 vala: update to 0.56.16
  app-devel/vala/autobuild/defines
  app-devel/vala/autobuild/defines.stage2
  app-devel/vala/spec
Labels: upgrade

#5543 solaar: update to 1.1.11
  app-utils/solaar/spec
Labels: upgrade

#5548 suitesparse (SuiteSparse): fix dependency
  runtime-scientific/suitesparse/autobuild/defines
  runtime-scientific/suitesparse/spec
Labels: has-fix, dependencies

#5553 picom: update to 11.2
  desktop-wm/picom/autobuild/defines
  desktop-wm/picom/spec
Labels: upgrade

#5539 libtorrent-rasterbar: update to 2.0.10
  runtime-web/libtorrent-rasterbar/spec
Labels: upgrade

#5542 rt-tests: update to 2.6
  app-utils/rt-tests/spec
Labels: upgrade

#5550 discord: update to 0.0.46
  app-web/discord/spec
Labels: upgrade

#5552 pushpkg: update to 0+git20240320
  app-devel/pushpkg/spec
Labels: upgrade

#5556 bat: update to 0.24.0
  app-utils/bat/spec
Labels: upgrade

#5557 ast-grep: update to 0.19.4
  app-devel/ast-grep/spec
Labels: upgrade

#5563 devscripts: new, 2.23.7
  app-devel/devscripts/autobuild/beyond
  app-devel/devscripts/autobuild/build
  app-devel/devscripts/autobuild/defines
  app-devel/devscripts/autobuild/patches/0001-fix-docbook-xsl-path.patch
  app-devel/devscripts/spec
Labels: new-packages

#5572 gn: update to 0+git20240313
  app-devel/gn/autobuild/prepare
  app-devel/gn/spec
Labels: upgrade

#5565 difftastic: new, 0.56.1
  app-utils/difftastic/autobuild/defines
  app-utils/difftastic/spec
Labels: new-packages

#5574 telegram-desktop (Telegram Desktop): update to 4.15.2
  app-web/telegram-desktop/spec
Labels: upgrade

#5578 thefuck: update to 3.32
  app-utils/thefuck/spec
Labels: upgrade

#5584 discord: update to 0.0.47
  app-web/discord/spec
Labels: upgrade

#5586 MPD: fix dependency
  app-multimedia/mpd/autobuild/defines
  app-multimedia/mpd/spec
Labels: has-fix, dependencies

#5585 pandoc: update to 3.1.12.3
  app-doc/pandoc/autobuild/build
  app-doc/pandoc/autobuild/defines
  app-doc/pandoc/autobuild/prepare
  app-doc/pandoc/spec
Labels: upgrade

#5587 nss: update to 3.99
  runtime-cryptography/nss/autobuild/build
  runtime-cryptography/nss/spec
Labels: upgrade

#5588 cups: update to 2.4.7
  app-admin/cups/spec
Labels: upgrade

#5592 x11-lib: update to 7.7.20240327
  runtime-display/x11-lib/autobuild/build
  runtime-display/x11-lib/spec
Labels: upgrade

#5593 libxcb: update to 1.16.1
  runtime-display/libxcb/spec
Labels: upgrade

#5594 libxkbcommon: update to 1.7.0
  runtime-display/libxkbcommon/spec
Labels: upgrade

#5613 util-linux: update to 2.40
  app-utils/util-linux/spec
Labels: upgrade, security

#5614 devil: fix FTBFS on mips64r6el
  runtime-imaging/devil/autobuild/prepare
  runtime-imaging/devil/spec
Labels: ftbfs, has-fix, cip-pilot

#5615 curl: security update to 8.7.1
  app-web/curl/spec
Labels: upgrade, security

#5616 gnutls: security update to 3.8.4
  runtime-cryptography/gnutls/spec
Labels: upgrade, security

#5598 oma: update to 1.2.23
  app-admin/oma/spec
Labels: upgrade

#5618 openssl: security update to 3.2.1
  runtime-cryptography/openssl/spec
Labels: upgrade, security

#5604 qt-6: update to 6.6.3
  runtime-desktop/qt-6/autobuild/patches/0005-loongarch64.patch.loongarch64
  runtime-desktop/qt-6/spec
Labels: upgrade

#5601 choose: new, 1.3.4
  app-utils/choose/autobuild/defines
  app-utils/choose/autobuild/patches/0001-feat-use-own-argument-parser-to-replace-structopt.patch
  app-utils/choose/autobuild/patches/0002-chore-use-once_cell-to-replace-lazy_static.patch
  app-utils/choose/autobuild/patches/0003-style-apply-cargo-clippy-suggest.patch
  app-utils/choose/spec
Labels: new-packages

#5617 emacs: security update to 29.3
  app-editors/emacs/spec
Labels: upgrade, security

#5600 qt-5: runtime GLES selection
  runtime-desktop/qt-5/autobuild/patches/0020-Deepin-auto-select-opengl-or-opengles.patch
  runtime-desktop/qt-5/spec
Labels: preview

#5603 mesa (Mesa 3D Library): update to 24.0.4
  runtime-display/mesa/autobuild/patches/0001-llvmpipe-make-unnamed-global-have-internal-linkage.patch
  runtime-display/mesa/autobuild/patches/0002-llvmpipe-add-an-implementation-with-llvm-orcjit.patch
  runtime-display/mesa/autobuild/patches/0003-llvmpipe-add-LoongArch-support-in-ORCJIT.patch
  runtime-display/mesa/autobuild/patches/0004-llvmpipe-append-partial-mask-to-partial-fs_variant-f.patch
  runtime-display/mesa/autobuild/patches/0005-fix-iris_bufmgr.c-set-PAGE_SIZE-as-16384-for-LoongAr.patch.loongarch64
  runtime-display/mesa/autobuild/patches/0005-vulkan-dispatch-table-add-an-uncompacted-version.patch
  runtime-display/mesa/spec
Labels: upgrade

#5612 7-zip: 23.01, new
  app-utils/7-zip/autobuild/build
  app-utils/7-zip/autobuild/defines
  app-utils/7-zip/autobuild/patches/0001-fix-CPP-clang-llvm-build-errors.patch
  app-utils/7-zip/spec
Labels: new-package

#5385 netease-cloud-music-gtk: update to 2.3.0 and fix shortcut
  app-multimedia/netease-cloud-music-gtk/autobuild/beyond
  app-multimedia/netease-cloud-music-gtk/autobuild/defines
  app-multimedia/netease-cloud-music-gtk/autobuild/prepare
  app-multimedia/netease-cloud-music-gtk/spec
Labels: upgrade, has-fix

#5619 musescore: update to 4.2.1
  app-creativity/musescore/autobuild/beyond
  app-creativity/musescore/autobuild/build
  app-creativity/musescore/autobuild/defines
  app-creativity/musescore/spec
Labels: upgrade, core

#5621 harfbuzz: update to 8.4.0
  runtime-desktop/harfbuzz/spec
Labels: upgrade

#5622 c-ares: update to 1.28.1
  runtime-network/c-ares/autobuild/prepare
  runtime-network/c-ares/spec
Labels: upgrade

#5623 pcre2: update to 10.43
  runtime-common/pcre2/spec
Labels: upgrade

#5632 editorconfig-core-c: update to 0.12.6
  runtime-editors/editorconfig-core-c/spec
Labels: upgrade, core

#5633 exim: update to 4.97.1
  app-web/exim/spec
Labels: upgrade
