Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-11, with the labels that each got.

#8463 oma: update to 1.12.1
  app-admin/oma/spec
Labels: upgrade

#8453 zed: update to 0.159.5
  app-editors/zed/spec
Labels: upgrade

#8441 hwdata: update to 0.388
  runtime-data/hwdata/spec
Labels: upgrade

#8455 libuninameslist: update to 20240910
  runtime-i18n/libuninameslist/spec
Labels: upgrade

#8409 pciutils: update to 3.13.0
  app-utils/pciutils/autobuild/patches/0001-Fedora-pciutils-3.9.0-extvisible.patch
  app-utils/pciutils/spec
Labels: upgrade

#8465 oma: update to 1.12.2
  app-admin/oma/spec
Labels: upgrade

#8477 vscode: update to 1.95.1
  app-editors/vscode/spec
Labels: upgrade

#8410 distrobox: update to 1.8.0
  app-utils/distrobox/spec
Labels: upgrade

#8488 zvm: update to 0.7.9
  lang-ziglang/zvm/spec
Labels: upgrade

#8485 zerotier-one: update to 1.14.2
  app-network/zerotier-one/spec
Labels: upgrade

#8487 gnupg: update to 2.4.6
  app-cryptography/gnupg/spec
Labels: upgrade

#8466 xray: update to 24.10.31
  app-network/xray/spec
Labels: upgrade

#8484 audacity: update to 3.7.0
  app-creativity/audacity/spec
Labels: upgrade

#8496 tailscale: update to 1.76.1
  app-network/tailscale/spec
Labels: upgrade

#8498 dua: update to 2.29.4
  app-utils/dua/spec
Labels: upgrade

#8340 asahi-fwextract: update to 0.7.8
  app-utils/asahi-fwextract/spec
Labels: upgrade

#8494 mdbook: update to 0.4.40
  app-doc/mdbook/autobuild/defines
  app-doc/mdbook/spec
Labels: upgrade

#8503 oma: update to 1.12.3
  app-admin/oma/spec
Labels: upgrade

#8457 mesa: update to 24.2.6+dxheaders1.614.1
  runtime-display/mesa/spec
Labels: upgrade

#8499 autobuild4: update to 4.4.0
  app-devel/autobuild4/spec
Labels: upgrade

#8500 acbs: update to 20241103
  app-devel/acbs/spec
Labels: upgrade

#8501 ciel: update to 3.5.0
  app-devel/ciel/spec
Labels: upgrade

#8502 aoscbootstrap: update to 0.7.6
  app-utils/aoscbootstrap/spec
Labels: upgrade

#8516 srain: drop, orphaned
  app-web/srain/autobuild/defines
  app-web/srain/spec
Labels: drop-package

#8511 iosevka-fonts: update to 32.0.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#8512 sarasa-gothic-fonts: update to 1.0.23
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#8514 osu-lazer: update to 2024.1104.0
  app-games/osu-lazer/spec
Labels: upgrade

#8483 telegram-desktop: update to 5.7.1
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-Fix-some-ffmpeg-7.x-related-errors.patch
  app-web/telegram-desktop/autobuild/patches/0010-Use-alternate-fix-for-ffmpeg-const-issue.patch
  app-web/telegram-desktop/autobuild/patches/1001-Add-compatibility-with-FFMPEG-7.0.patch.deferred
  app-web/telegram-desktop/autobuild/prepare
  app-web/telegram-desktop/spec
Labels: upgrade

#8462 readymedia: new, 1.3.3
  app-multimedia/readymedia/autobuild/beyond
  app-multimedia/readymedia/autobuild/conffiles
  app-multimedia/readymedia/autobuild/defines
  app-multimedia/readymedia/autobuild/overrides/usr/lib/systemd/system/readymedia.service
  app-multimedia/readymedia/autobuild/overrides/usr/lib/sysusers.d/readymedia.conf
  app-multimedia/readymedia/autobuild/overrides/usr/lib/tmpfiles.d/readymedia.conf
  app-multimedia/readymedia/autobuild/patches/0001-libav-api-fix.patch
  app-multimedia/readymedia/autobuild/postinst
  app-multimedia/readymedia/spec
Labels: new-packages

#8517 xray: update to 24.11.5
  app-network/xray/spec
Labels: upgrade

#8520 intel-ipsec-mb: add pkgbreak
  runtime-cryptography/intel-ipsec-mb/autobuild/defines
  runtime-cryptography/intel-ipsec-mb/spec
Labels: rework

#8515 zellij: update to 0.41.1
  app-utils/zellij/autobuild/defines
  app-utils/zellij/spec
Labels: upgrade

#8476 xcb-util-cursor: update to 0.1.5
  runtime-display/xcb-util-cursor/spec
Labels: upgrade

#8468 nodejs-22: update to 22.11.0
  lang-js/nodejs-22/spec
Labels: upgrade

#8471 po4a: update to 0.73
  app-i18n/po4a/spec
Labels: upgrade

#8479 svt-av1: update to 2.3.0
  runtime-multimedia/svt-av1/spec
Labels: upgrade

#8475 lxgwfasmartgothic-font: update to 1.201
  desktop-fonts/lxgwfasmartgothic-font/spec
Labels: upgrade

#8527 oma: update to 1.12.4
  app-admin/oma/spec
Labels: upgrade

#8529 racket: update to 8.15
  lang-lisp/racket/spec
Labels: upgrade

#8530 fastfetch: update to 2.29.0
  app-utils/fastfetch/spec
Labels: upgrade

#8526 ciel: update to 3.5.1
  app-devel/ciel/spec
Labels: upgrade

#8506 lsof: update to 4.99.3
  app-utils/lsof/spec
Labels: upgrade

#8531 ostree: update to 2024.9
  app-admin/ostree/spec
Labels: upgrade

#8467 docker: update to 27.3.1+tini0.19.0
  app-containers/docker/autobuild/build
  app-containers/docker/spec
Labels: upgrade

#8522 pngquant: update to 2.18.0
  app-utils/pngquant/spec
Labels: upgrade

#8536 papirus-icon-theme: update to 20240501
  desktop-themes/papirus-icon-theme/spec
Labels: upgrade

#8540 opencl-registry-api: update to 2024.10.24
  app-devel/opencl-registry-api/spec
Labels: upgrade

#8539 cmake: update to 3.31.0
  app-devel/cmake/spec
Labels: upgrade

#8492 mihomo-party: new, 1.5.6
  app-network/mihomo-party/autobuild/build
  app-network/mihomo-party/autobuild/defines
  app-network/mihomo-party/autobuild/overrides/usr/share/applications/mihomo-party.desktop
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Remove-auto-update-feature.patch
  app-network/mihomo-party/spec
Labels: new-packages

#8524 git-absorb: update to 0.6.16
  app-devel/git-absorb/spec
Labels: upgrade

#8408 usbutils: update to 018
  app-utils/usbutils/autobuild/defines
  app-utils/usbutils/autobuild/m68k
  app-utils/usbutils/spec
Labels: upgrade

#8474 gtkwave: update to 3.3.121
  app-electronics/gtkwave/spec
Labels: upgrade

#8470 networkmanager-pptp: update to 1.2.12
  app-network/networkmanager-pptp/spec
Labels: upgrade

#8544 hmcl: update to 3.5.10
  app-games/hmcl/spec
Labels: upgrade

#8542 v2ray-rules-dat: update to 202411072211
  runtime-data/v2ray-rules-dat/spec
Labels: upgrade

#8535 sing-box: add completion files
  app-network/sing-box/autobuild/build
  app-network/sing-box/autobuild/defines
  app-network/sing-box/autobuild/prepare
  app-network/sing-box/spec
Labels: enhancement

#8548 vscode: update to 1.95.2
  app-editors/vscode/spec
Labels: upgrade

#8549 ghidra: update to 11.2.1
  app-devel/ghidra/spec
Labels: upgrade

#8550 x264: update to master HEAD 20241027
  runtime-multimedia/x264/autobuild/defines
  runtime-multimedia/x264/autobuild/prepare
  runtime-multimedia/x264/spec
Labels: upgrade

#8552 fcitx5-pinyin-moegirl: update to 20241109
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#8553 glbinding: new, 3.3.0
  runtime-display/glbinding/autobuild/defines
  runtime-display/glbinding/autobuild/patches/0001-Prefix-tool-names.patch
  runtime-display/glbinding/spec
Labels: new-packages

#8559 libarchive: update to 3.7.7
  runtime-common/libarchive/spec
Labels: upgrade, pre-release

#8560 xz: update to 5.6.3
  app-utils/xz/spec
Labels: upgrade

#8580 cargo-audit: update to 0.21.0
  lang-rust/cargo-audit/spec
Labels: upgrade

#8563 i3status-rust: update to 0.33.2
  desktop-wm/i3status-rust/spec
Labels: upgrade

#8586 cloudflared: update to 2024.11.0
  app-network/cloudflared/spec
Labels: upgrade

#8594 os-prober: fix /var/lib/os-prober/mount not exist
  app-utils/os-prober/autobuild/beyond
  app-utils/os-prober/spec
Labels: has-fix

#8599 hyperfine: update to 1.19.0
  app-devel/hyperfine/spec
Labels: upgrade

#8591 systemtap: update to 5.2
  app-utils/systemtap/spec
Labels: upgrade

#8589 xray: update to 24.11.11
  app-network/xray/autobuild/prepare
  app-network/xray/spec
Labels: upgrade

#8598 memtest86plus: update to 7.20
  app-benchmarks/memtest86plus/autobuild/patches/0001-Bump-actions-stale-from-8-to-9-362.patch
  app-benchmarks/memtest86plus/autobuild/patches/0002-Add-detection-for-various-JEDEC-Manufacturers.patch
  app-benchmarks/memtest86plus/autobuild/patches/0003-Add-boot-options-to-perform-display-rotation-and-set.patch
  app-benchmarks/memtest86plus/autobuild/patches/0004-Fix-typo-in-README.patch
  app-benchmarks/memtest86plus/autobuild/patches/0005-Note-that-BadRAM-patterns-exclude-errors-found-in-te.patch
  app-benchmarks/memtest86plus/autobuild/patches/0006-Add-initial-NUMA-awareness-support-378.patch
  app-benchmarks/memtest86plus/autobuild/patches/0007-Fix-the-behaviour-of-sort_pm_map-issue-392.patch
  app-benchmarks/memtest86plus/autobuild/patches/0008-Add-GPT-partition-support.patch
  app-benchmarks/memtest86plus/autobuild/patches/0009-Fix-read_value-to-correctly-scale-value-when-shift-p.patch
  app-benchmarks/memtest86plus/autobuild/patches/0010-Fix-hexadecimal-conversion-in-read_value.patch
  app-benchmarks/memtest86plus/autobuild/patches/0011-boot-peimage-Add-LoongArch-and-RISC-V-PE-machine-num.patch
  app-benchmarks/memtest86plus/autobuild/patches/0012-boot-Export-the-startup64-symbol.patch
  app-benchmarks/memtest86plus/autobuild/patches/0013-app-main-Adjust-the-inline-ASM-to-i386-only.patch
  app-benchmarks/memtest86plus/autobuild/patches/0014-Refactor-the-memrw-functions-to-reduce-the-redundanc.patch
  app-benchmarks/memtest86plus/autobuild/patches/0015-Add-the-64-bit-and-32-bit-CC-flag.patch
  app-benchmarks/memtest86plus/autobuild/patches/0016-Split-SPD-parsing-and-printing-code-from-smbus.c-to-.patch
  app-benchmarks/memtest86plus/autobuild/patches/0017-lib-assert-Add-LoongArch-assert-support.patch
  app-benchmarks/memtest86plus/autobuild/patches/0018-lib-barrier-Add-barrier-method-for-LoongArch.patch
  app-benchmarks/memtest86plus/autobuild/patches/0019-lib-spinlock-Add-LoongArch-CPU-pause.patch
  app-benchmarks/memtest86plus/autobuild/patches/0020-lib-string-Make-LoongArch-use-the-string-function-in.patch
  app-benchmarks/memtest86plus/autobuild/patches/0021-lib-unistd-Add-LoongArch-CPU-pause.patch
  app-benchmarks/memtest86plus/autobuild/patches/0022-system-acpi-Reduce-the-way-of-search-RSDP-for-non-x8.patch
  app-benchmarks/memtest86plus/autobuild/patches/0023-system-cache-Add-LoongArch64-cache-operations-suppor.patch
  app-benchmarks/memtest86plus/autobuild/patches/0024-system-cpuid-Add-the-compile-limit.patch
  app-benchmarks/memtest86plus/autobuild/patches/0025-system-heap-Add-heap-support-for-LoongArch64.patch
  app-benchmarks/memtest86plus/autobuild/patches/0026-system-memrw-Add-8-bit-and-16-bit-memory-operations.patch
  app-benchmarks/memtest86plus/autobuild/patches/0027-system-memrw-Add-LoongArch-memory-access-operations.patch
  app-benchmarks/memtest86plus/autobuild/patches/0028-system-Add-Loongson-PCI-vendor-ID-and-Loongson-7A-ch.patch
  app-benchmarks/memtest86plus/autobuild/patches/0029-system-io-Add-LoongArch64-IO-port-operations.patch
  app-benchmarks/memtest86plus/autobuild/patches/0030-system-reloc64-Add-LoongArch64-relocations-support.patch
  app-benchmarks/memtest86plus/autobuild/patches/0031-system-serial-Add-Loongson-CPU-serial-port-support.patch
  app-benchmarks/memtest86plus/autobuild/patches/0032-system-smbus-Rename-smbus.c-to-i2c_x86.c.patch
  app-benchmarks/memtest86plus/autobuild/patches/0033-system-smp-Add-LoongArch-SMP-support.patch
  app-benchmarks/memtest86plus/autobuild/patches/0034-system-timers-Add-LoongArch-supports.patch
  app-benchmarks/memtest86plus/autobuild/patches/0035-system-tsc-Add-LoongArch-support.patch
  app-benchmarks/memtest86plus/autobuild/patches/0036-system-usbhcd-Add-LoongArch-MMIO-perfix.patch
  app-benchmarks/memtest86plus/autobuild/patches/0037-system-Add-a-method-of-readout-SPD-via-I2C.patch
  app-benchmarks/memtest86plus/autobuild/patches/0038-system-Add-the-way-to-IO-access-via-MMIO.patch
  app-benchmarks/memtest86plus/autobuild/patches/0039-system-Add-the-way-to-access-PCI-memory-space-via-MM.patch
  app-benchmarks/memtest86plus/autobuild/patches/0040-app-Add-LoongArch-version-support.patch
  app-benchmarks/memtest86plus/autobuild/patches/0041-test-block_move-Add-block-move-test-via-ASM-for-Loon.patch
  app-benchmarks/memtest86plus/autobuild/patches/0042-test-mov_inv_fixed-Add-LoongArch-ASM-version-word-wr.patch
  app-benchmarks/memtest86plus/autobuild/patches/0043-boot-Adjust-the-AP-stack-size-for-LoongArch.patch
  app-benchmarks/memtest86plus/autobuild/patches/0044-boot-efisetup-Add-LoongArch-CPU-halt-instruction.patch
  app-benchmarks/memtest86plus/autobuild/patches/0045-boot-efi-Limiting-the-ms_abi-using-scope.patch
  app-benchmarks/memtest86plus/autobuild/patches/0046-system-imc-loongson-Add-Loongson-LoongArch-IMC-suppo.patch
  app-benchmarks/memtest86plus/autobuild/patches/0047-boot-Add-LoongArch-startup-and-header.patch
  app-benchmarks/memtest86plus/autobuild/patches/0048-system-loongarch-Add-LoongArch-ARCH-specific-files.patch
  app-benchmarks/memtest86plus/autobuild/patches/0049-app-loongarch-Add-intrrupt-handler-for-LoongArch.patch
  app-benchmarks/memtest86plus/autobuild/patches/0050-build64-la64-Add-LoongArch64-build-files.patch
  app-benchmarks/memtest86plus/autobuild/patches/0051-workflows-Add-LoongArch64-CI-supports.patch
  app-benchmarks/memtest86plus/spec
Labels: upgrade

#8600 zed: update to 0.160.7
  app-editors/zed/spec
Labels: upgrade

#8482 lzip: update to 1.24.1
  app-utils/lzip/spec
Labels: upgrade

#8577 tor: update to 0.4.8.13
  app-network/tor/spec
Labels: upgrade

#8609 libgbinder: update to 1.1.41
  runtime-common/libgbinder/spec
Labels: upgrade

#8547 wine: update to 9.21+gecko2.47.4+mono9.3.0
  app-emulation/wine/spec
Labels: upgrade

#8578 intel-gpu-tools: update to 1.29
  app-admin/intel-gpu-tools/spec
Labels: upgrade

#8579 findlib: update to 1.9.7
  lang-ocaml/findlib/spec
Labels: upgrade

#8581 sndio: update to 1.10.0
  app-multimedia/sndio/spec
Labels: upgrade

#8582 blinker: update to 1.9.0
  lang-python/blinker/spec
Labels: upgrade

#8570 sdl2-ttf: update to 2.22.0
  runtime-multimedia/sdl2-ttf/spec
Labels: upgrade

#8567 libfdk-aac: update to 2.0.3
  runtime-multimedia/libfdk-aac/spec
Labels: upgrade

#8607 picom: update to 12.4
  desktop-wm/picom/spec
Labels: upgrade

#8619 libinput: fix touchpad on Lenovo ThinkBook 14 G7+ ASP
  runtime-devices/libinput/autobuild/patches/0001-fix-evdev-mt-touchpad-tap.c-enable-tap-to-click-by-d.patch
  runtime-devices/libinput/autobuild/patches/0002-quirks-add-pressure-pad-quirk-for-Lenovo-ThinkBook-1.patch
  runtime-devices/libinput/spec
Labels: has-fix, hardware-support

#8621 snapper: update to 0.12.0
  app-admin/snapper/spec
Labels: upgrade

#8613 pngquant: update to 3.0.3
  app-utils/pngquant/autobuild/beyond
  app-utils/pngquant/autobuild/defines
  app-utils/pngquant/spec
Labels: upgrade

#8480 mstflint: update to 4.29.0-1
  app-admin/mstflint/spec
Labels: upgrade

#8622 adaptivecpp: fix rpath
  app-devel/adaptivecpp/autobuild/defines
  app-devel/adaptivecpp/spec
Labels: has-fix

#8627 libinput: fix TrackPoint acceleration on ThinkPad X200/201
  runtime-devices/libinput/autobuild/patches/0001-fix-evdev-mt-touchpad-tap.c-enable-tap-to-click-by-d.patch
  runtime-devices/libinput/autobuild/patches/0002-quirks-add-pressure-pad-quirk-for-Lenovo-ThinkBook-1.patch
  runtime-devices/libinput/autobuild/patches/0003-quirks-lower-AttrTrackpointMultiplier-for-ThinkPad-X.patch
  runtime-devices/libinput/spec
Labels: has-fix

#8633 qpwgraph: update to 0.8.0
  app-multimedia/qpwgraph/spec
Labels: upgrade

#8630 bitwarden: update to 2024.11.1
  app-utils/bitwarden/spec
Labels: upgrade

#8626 Linux Firmware Survey 20241114
  runtime-kernel/linux-firmware/spec
Labels: survey

#8573 gawk: update to 5.3.1
  app-utils/gawk/spec
Labels: upgrade

#8566 openh264: update to 2.5.0+gmp114+2
  app-multimedia/openh264/spec
Labels: upgrade

#8634 firefox: update to 132.0.2
  app-web/firefox/autobuild/patches/0001-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0002-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0003-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0004-update-gn_processor.py-to-support-linux-on-loong64.patch
  app-web/firefox/autobuild/patches/0005-Re-generate-libwebrtc-moz.build-files.patch
  app-web/firefox/autobuild/patches/0006-enable-webrtc-for-loongarch64-in-toolkit-moz.configu.patch
  app-web/firefox/autobuild/patches/0007-Fix-libyuv-unified-source-and-LoongArch-SIMD-build.patch
  app-web/firefox/autobuild/patches/0008-Fix-missing-loongarch-subdir-in-libpng-moz.yaml.patch
  app-web/firefox/autobuild/patches/0009-Vendor-missing-loongarch-files-of-libpng.patch
  app-web/firefox/autobuild/patches/0010-Enable-LoongArch-LSX-optimization-for-libpng.patch
  app-web/firefox/autobuild/patches/0011-Remove-references-to-private-members-for-MIPS.patch
  app-web/firefox/spec
Labels: upgrade

#8640 oma: update to 1.12.7
  app-admin/oma/spec
Labels: upgrade

#8632 picom: update to 12.5
  desktop-wm/picom/spec
Labels: upgrade

#8631 osu-lazer: update to 2024.1115.0
  app-games/osu-lazer/spec
Labels: upgrade

#8647 vscode: update to 1.95.3
  app-editors/vscode/spec
Labels: upgrade

#8568 linux-pam: update to 1.7.0
  app-admin/linux-pam/autobuild/beyond
  app-admin/linux-pam/autobuild/defines
  app-admin/linux-pam/autobuild/patches/0001-build-add-static_library-targets-for-libpam-libpam_m.patch
  app-admin/linux-pam/autobuild/patches/0002-limits.conf-add-default-settings-for-AOSC-OS.patch
  app-admin/linux-pam/spec
Labels: upgrade

#8649 xdg-desktop-portal: update to 1.18.4
  app-admin/xdg-desktop-portal/spec
Labels: upgrade

#8652 oma: update to 1.12.8
  app-admin/oma/spec
Labels: upgrade

#8648 zvm: update to 0.8.1
  lang-ziglang/zvm/spec
Labels: upgrade

#8646 waylyrics: update to 0.3.18
  app-multimedia/waylyrics/spec
Labels: upgrade

#8653 cava: update to 0.10.3
  app-multimedia/cava/autobuild/patches/0001-bump-hardcoded-version-to-0.10.3.patch
  app-multimedia/cava/spec
Labels: upgrade

#8657 bash-startup: update to 0.6.8
  runtime-data/bash-startup/spec
Labels: upgrade

#8674 dnscontrol: new, 4.14.3
  app-network/dnscontrol/autobuild/beyond
  app-network/dnscontrol/autobuild/defines
  app-network/dnscontrol/spec
Labels: new-packages

#8654 osu-lazer: update to 2024.1115.3
  app-games/osu-lazer/spec
Labels: upgrade

#8677 [SECURITY] postgresql: update to 13.17
  app-database/postgresql/spec
Labels: upgrade, security

#8678 kakasi: new, 2.3.6
  app-i18n/kakasi/autobuild/defines
  app-i18n/kakasi/spec
Labels: new-packages

#8675 lfortran: new, 0.42.0
  app-devel/lfortran/autobuild/defines
  app-devel/lfortran/spec
Labels: new-packages

#8683 fastfetch: update to 2.30.0
  app-utils/fastfetch/spec
Labels: upgrade

#8684 iosevka-fonts: update to 32.1.0
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#8685 sarasa-gothic-fonts: update to 1.0.24
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#8686 qbittorrent: update to 5.0.2
  app-web/qbittorrent/spec
Labels: upgrade

#8689 fastfetch: update to 2.30.1
  app-utils/fastfetch/spec
Labels: upgrade

#8691 Telegram Desktop: update to 5.8.1
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-Fix-some-ffmpeg-7.x-related-errors.patch
  app-web/telegram-desktop/autobuild/patches/0010-Use-alternate-fix-for-ffmpeg-const-issue.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#8681 pocl: new, 6.0
  runtime-common/pocl/autobuild/defines
  runtime-common/pocl/spec
Labels: new-packages

#8696 deb-installer: update to 0.1.4
  app-admin/deb-installer/spec
Labels: upgrade

#8687 sof-firmware: update to 2024.09.1
  runtime-kernel/sof-firmware/spec
Labels: upgrade

#8697 grub: correct efi_removable_quirk() implementation
  app-admin/grub/autobuild/postinst
  app-admin/grub/spec
Labels: has-fix, hardware-support

#8711 fantasque-sans-mono-nerd-fonts: update to 3.3.0
  desktop-fonts/fantasque-sans-mono-nerd-fonts/spec
Labels: upgrade

#8718 feishin: update to 0.12.0
  app-multimedia/feishin/spec
Labels: upgrade

#8719 zellij: update to 0.41.2
  app-utils/zellij/spec
Labels: upgrade

#8712 man-pages: update to 6.9.1+posix2017a
  runtime-data/man-pages/spec
Labels: upgrade

#8713 libjpeg-turbo: update to 3.0.4
  runtime-imaging/libjpeg-turbo/spec
Labels: upgrade

#8708 ethtool: update to 6.11
  app-network/ethtool/spec
Labels: upgrade

#8666 xf86-video-fbdev: update to 0.5.1
  runtime-display/xf86-video-fbdev/spec
Labels: upgrade

#8665 editorconfig-core-c: update to 0.12.9
  runtime-editors/editorconfig-core-c/spec
Labels: upgrade, core

#8722 docker-compose: update to 2.30.3
  app-containers/docker-compose/spec
Labels: upgrade

#8721 zed: update to 0.161.2
  app-editors/zed/spec
Labels: upgrade

#8725 oma: update to 1.12.9
  app-admin/oma/spec
Labels: upgrade

#8698 docker-buildx: new, 0.18.0
  app-containers/docker-buildx/autobuild/build
  app-containers/docker-buildx/autobuild/defines
  app-containers/docker-buildx/spec
Labels: new-packages

#8733 feishin: update to 0.12.1
  app-multimedia/feishin/spec
Labels: upgrade

#8735 freecad: update to 1.0
  app-creativity/freecad/autobuild/defines
  app-creativity/freecad/autobuild/patches/0001-fix-build-with-vtk9.patch
  app-creativity/freecad/spec
Labels: upgrade

#8737 plasma-desktop: drop possible mis-set Flat mouse acceleration profile
  desktop-kde/plasma-desktop/autobuild/patches/0001-Revert-If-no-config-option-for-accel-profile-is-sele.patch
  desktop-kde/plasma-desktop/autobuild/patches/0002-AOSCOS-feat-kickoff-set-default-applications-for-AOS.patch
  desktop-kde/plasma-desktop/spec
Labels: has-fix, hardware-support

#8739 mihomo-party: update to 1.5.11
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Remove-auto-update-feature.patch
  app-network/mihomo-party/spec
Labels: upgrade

#8744 znc: update to 1.9.1
  app-web/znc/autobuild/defines
  app-web/znc/autobuild/patches/0001-Install-systemd-unit-to-correct-location.patch
  app-web/znc/spec
Labels: upgrade

#8741 bitwarden: update to 2024.11.2
  app-utils/bitwarden/spec
Labels: upgrade

#8746 vim: update to 9.1.0880
  app-editors/vim/01-vim/defines
  app-editors/vim/02-gvim/defines
  app-editors/vim/spec
Labels: upgrade

#8745 xray: update to 24.11.21
  app-network/xray/spec
Labels: upgrade

#8750 hashcat: fix undefined symbol caused by unrar
  app-penetration/hashcat/autobuild/build
  app-penetration/hashcat/autobuild/defines
  app-penetration/hashcat/spec
Labels: has-fix

#8738 cloudflared: update to 2024.11.1
  app-network/cloudflared/spec
Labels: upgrade

#8703 php: update to 8.3.13
  app-devel/php/spec
Labels: upgrade

#8754 osu-lazer: update to 2024.1122.0
  app-games/osu-lazer/spec
Labels: upgrade

#8760 podman: update to 5.3.1+vsock0.7.5
  app-containers/podman/spec
Labels: upgrade

#8757 just: update to 1.37.0
  app-devel/just/spec
Labels: upgrade

#8732 spdx-licenses: update to 3.25.0
  runtime-data/spdx-licenses/spec
Labels: upgrade

#8742 perl-term-readkey: rework for missing rebuild
  lang-perl/perl-term-readkey/spec
Labels: rework

#8758 sing-box: update to 1.10.2
  app-network/sing-box/spec
Labels: upgrade
