Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-01, with the labels that each got.

#5053 linux-kernel-lts ("Longterm" Linux Kernel): update to 6.1.69
  runtime-kernel/linux+kernel+lts/autobuild/defines
  runtime-kernel/linux+kernel+lts/spec
  runtime-kernel/linux-kernel-lts/autobuild/amd64/config
  runtime-kernel/linux-kernel-lts/autobuild/arm64/config
  runtime-kernel/linux-kernel-lts/autobuild/defines
  runtime-kernel/linux-kernel-lts/autobuild/patches/0001-lib-cpumask-Make-CPUMASK_OFFSTACK-usable-without-deb.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0002-input-kill-stupid-messages.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0003-lis3-improve-handling-of-null-rate.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0004-ath9k-rx-dma-stop-check.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0005-Input-synaptics-pin-3-touches-when-the-firmware-repo.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0006-driver-sisfb-add-resolution-1368-768-for-loongson-ly.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0007-Revert-video-output-Drop-display-output-class-suppor.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0008-pci-Enable-overrides-for-missing-ACS-capabilities-5..patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0009-usb-phy-tegra-Add-38.4MHz-clock-table-entry.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0010-more-uarches-for-kernel-5.15.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0011-MIPS-Loongson64-Disable-writecombine-for-Loongson-3A.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0012-platform-surface-hid.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0013-x86-platform-add-MAT0028-to-ACPI-identifiers-for-pan.patch
  runtime-kernel/linux-kernel-lts/autobuild/patches/0014-iommu-make-IPMMU_VMSA-dependencies-more-strict.patch
  runtime-kernel/linux-kernel-lts/autobuild/ppc64el/config
  runtime-kernel/linux-kernel-lts/spec
Labels: upgrade

#5032 atm (AOSC Topic Manager): update to 0.6.2
  app-admin/atm/autobuild/defines
  app-admin/atm/spec
Labels: upgrade

#5070 archlinux-keyring: update to 20231222
  app-admin/archlinux-keyring/autobuild/build
  app-admin/archlinux-keyring/autobuild/defines
  app-admin/archlinux-keyring/spec
Labels: upgrade

#5028 OpenJDK: Add LoongArch support; clean up patches and scripts
  lang-java/openjdk/autobuild/build
  lang-java/openjdk/autobuild/build.stage2
  lang-java/openjdk/autobuild/patches/1000-8277417-C1-LIR-instruction-for-load-klass.patch
  lang-java/openjdk/autobuild/patches/1000-8277417-C1-LIR-instruction-for-load-klass.patch.arm64
  lang-java/openjdk/autobuild/patches/1000-8277417-C1-LIR-instruction-for-load-klass.patch.ppc64el
  lang-java/openjdk/autobuild/patches/1000-8277417-C1-LIR-instruction-for-load-klass.patch.riscv64
  lang-java/openjdk/autobuild/patches/1001-8276799-Implementation-of-JEP-422-Linux-RISC-V-Port.patch.riscv64
  lang-java/openjdk/spec
Labels: enhancement, new-port

#5071 elfutils: disable thread-safety to workaround poor multi-threaded Pahole performance
  app-utils/elfutils/autobuild/defines
  app-utils/elfutils/spec
Labels: has-fix

#5064 libmbim: update to 1.30.0
  runtime-devices/libmbim/spec
Labels: upgrade

#5067 fish: update to 3.7.0
  app-shells/fish/spec
Labels: upgrade

#5075 tzdata (Time Zone Database): update to 2023d
  runtime-data/tzdata/spec
Labels: upgrade

#5074 yt-dlp: update to 2023.12.30
  app-multimedia/yt-dlp/spec
Labels: upgrade

#5027 Pahole: update to 1.25
  app-utils/pahole/autobuild/patches/0001-Debian-store-the-CU-being-processed-to-avoid-changing-many-functions.patch
  app-utils/pahole/autobuild/patches/0001-dwarf_loader-Add-support-for-DW_TAG_constant.patch
  app-utils/pahole/autobuild/patches/0002-Debian-record-if-a-CU-has-a-DW_TAG_unspecified_type.patch
  app-utils/pahole/autobuild/patches/0002-fprintf-Add-DW_TAG_constant-pretty-printer-constant_.patch
  app-utils/pahole/autobuild/patches/0003-Debian-encode-DW_TAG_unspecified_type-returning-routines-as-void.patch
  app-utils/pahole/autobuild/patches/0003-pdwtags-Print-DW_TAG_constant-tags.patch
  app-utils/pahole/autobuild/patches/0004-dwarf_loader-DW_TAG_subroutine_type-may-have-a-DW_AT.patch
  app-utils/pahole/spec
Labels: upgrade

#5039 OpenCOLLADA: update to 1.6.68
  runtime-creativity/opencollada/autobuild/defines
  runtime-creativity/opencollada/autobuild/patch
  runtime-creativity/opencollada/autobuild/patches/0001-Gentoo-opencollada-1.6.63-pcre-fix.patch
  runtime-creativity/opencollada/autobuild/patches/0001-pcre.patch
  runtime-creativity/opencollada/autobuild/patches/0002-Gentoo-opencollada-1.6.68-cmake-fixes.patch
  runtime-creativity/opencollada/autobuild/patches/0003-Gentoo-opencollada-1.6.68-fix-null-conversion.patch
  runtime-creativity/opencollada/autobuild/patches/0004-Gentoo-opencollada-1.6.68-gcc13.patch
  runtime-creativity/opencollada/autobuild/patches/0005-Gentoo-opencollada-1.6.68-disable-werror.patch
  runtime-creativity/opencollada/autobuild/prepare
  runtime-creativity/opencollada/spec
Labels: upgrade

#5072 glib (GLib): update to 2.78.3
  runtime-common/glib/spec
Labels: upgrade, has-fix

#5076 mesa (Mesa 3D Graphics Library): update to 23.3.2
  runtime-display/mesa/autobuild/patches/0004-Revert-d3d12-Only-destroy-the-winsys-during-screen-d.patch
  runtime-display/mesa/spec
Labels: upgrade

#5081 pushpkg: update to 0+git20240103
  app-devel/pushpkg/spec
Labels: upgrade

#5082 pigz: update to 2.8
  app-utils/pigz/spec
Labels: upgrade

#5084 linux-kernel: allow hid-lenovo to recover from false positives
  runtime-kernel/linux-kernel/autobuild/amd64/config
  runtime-kernel/linux-kernel/autobuild/arm64/config
  runtime-kernel/linux-kernel/autobuild/mips64r6el/config
  runtime-kernel/linux-kernel/autobuild/patches/0023-hid-lenovo-detect-false-positives.patch
  runtime-kernel/linux-kernel/autobuild/ppc64el/config
  runtime-kernel/linux-kernel/autobuild/riscv64/config
  runtime-kernel/linux-kernel/spec
Labels: has-fix, hardware-support

#5090 ripgrep: update to 14.1.0
  app-utils/ripgrep/spec
Labels: upgrade

#5093 dua: update to 2.26.0
  app-utils/dua/spec
Labels: upgrade

#5094 aoscbootstrap: update to 0.4.2
  app-utils/aoscbootstrap/spec
Labels: upgrade

#5097 pushpkg: update to 0+git20240108
  app-devel/pushpkg/spec
Labels: upgrade

#5095 nvm (Node.js Version Manager): update to 0.39.7
  lang-js/nvm/autobuild/build
  lang-js/nvm/autobuild/defines
  lang-js/nvm/autobuild/patches/0001-nvm.sh-drop-hash-r.patch
  lang-js/nvm/spec
Labels: upgrade

#5110 aoscbootstrap: update to 0.4.3
  app-utils/aoscbootstrap/spec
Labels: upgrade

#5112 systemd: fix getty@.service alternative
  app-admin/systemd/autobuild/alternatives
  app-admin/systemd/autobuild/beyond
  app-admin/systemd/autobuild/postinst
  app-admin/systemd/spec
Labels: has-fix

#5119 discord (Discord): update to 0.0.40
  app-web/discord/spec
Labels: upgrade

#5117 openssl{,+32}: update to 3.2.0
  runtime-cryptography/openssl/spec
  runtime-optenv32/openssl+32/spec
Labels: upgrade, optenv, security

#5122 vc: update to 1.4.4
  app-devel/vc/spec
Labels: upgrade

#5125 transmission: disbale qt frontend
  app-web/transmission/autobuild/defines
  app-web/transmission/spec
Labels: enhancement

#5128 bluez (BlueZ Bluetooth Stack): security update to 5.71
  app-devices/bluez/spec
Labels: upgrade, security

#5130 mm-common update to1.0.6
  app-devel/mm-common/autobuild/defines
  app-devel/mm-common/spec
Labels: upgrade

#5137 yazi: update to 0.2.0
  app-utils/yazi/autobuild/beyond
  app-utils/yazi/autobuild/patches/0001-fix-compile.patch
  app-utils/yazi/autobuild/prepare
  app-utils/yazi/spec
Labels: upgrade

#5135 chromium: update to 120.0.6099.216
  app-web/chromium/autobuild/build
  app-web/chromium/autobuild/patches/0006-Fedora-chromium-71.0.3578.98-widevine-r3.patch
  app-web/chromium/autobuild/patches/0009-Fedora-chromium-96.0.4664.45-gcc-remoting-constexpr.patch
  app-web/chromium/autobuild/patches/0016-Fedora-chromium-108-EnumTable-crash.patch
  app-web/chromium/autobuild/patches/0028-Fedora-chromium-116-missing-header-files.patch
  app-web/chromium/autobuild/patches/0028-Fedora-chromium-120-missing-header-files.patch
  app-web/chromium/autobuild/patches/0029-Fedora-chromium-117-mnemonic-error.patch
  app-web/chromium/autobuild/patches/0030-Fedora-chromium-120-split-threshold-for-reg-with-hint.patch
  app-web/chromium/autobuild/patches/0031-Fedora-chromium-120-nullptr_t-without-namespace-std.patch
  app-web/chromium/autobuild/patches/0032-Debian-absl-optional.patch
  app-web/chromium/autobuild/patches/0033-fix-invalid-substition-type.patch
  app-web/chromium/autobuild/prepare
  app-web/chromium/spec
Labels: upgrade

#5131 miniserve: update to 0.26.0
  app-web/miniserve/spec
Labels: upgrade

#5086 sbt: update to 1.9.8
  app-devel/sbt/spec
Labels: upgrade

#5124 texlive (TeXLive): rebuild against latest zlib
  app-doc/texlive/spec
Labels: abi-break

#5156 pixman: update to 0.43.0
  runtime-display/pixman/autobuild/defines
  runtime-display/pixman/autobuild/patches/0001-LoongArch-SIMD-support.patch
  runtime-display/pixman/spec
Labels: upgrade

#5144 linux-pam: security update to 1.6.0
  app-admin/linux-pam/spec
Labels: upgrade, security

#5149 xserver: security update survey
  runtime-display/xorg-server/spec
  runtime-display/xwayland/spec
Labels: upgrade, security, survey

#5104 git (Git SCM): update to 2.43.0
  app-vcs/git/spec
Labels: upgrade, security

#5142 qt-6: update to 6.6.1
  runtime-desktop/qt-6/autobuild/patches/0003-Fedora-qtbase-libxkbcommon-1.6.0.patch
  runtime-desktop/qt-6/autobuild/patches/0004-Fix-ffmpeg-assembly-with-newer-binutil.patch
  runtime-desktop/qt-6/spec
Labels: upgrade

#5155 liteide: new, 38.3
  app-editors/liteide/autobuild/build
  app-editors/liteide/autobuild/defines
  app-editors/liteide/autobuild/patches/0001-update-gotools.patch
  app-editors/liteide/spec
Labels: new-package

#5157 openh264: rebase mips64r6el-only patch
  app-multimedia/openh264/autobuild/patches/0002-Do-not-enable-MIPS-assembly-for-r6.patch.mips64r6el
Labels: cip-pilot

#5160 autobuild3: update to 1.8.7
  app-devel/autobuild3/spec
Labels: upgrade

#5100 nginx: update to 1.25.3
  app-web/nginx/spec
Labels: upgrade

#5166 glew: (loongarch64) disable LTO
  runtime-display/glew/autobuild/defines
  runtime-display/glew/spec
Labels: has-fix, new-port

#5167 pushpkg: update to 0+git20240120
  app-devel/pushpkg/spec
Labels: upgrade

#5168 curl{,+32}: security update to 8.5.0
  app-web/curl/spec
  runtime-optenv32/curl+32/spec
Labels: upgrade, security

#5171 nghttp2: security update to 1.58.0
  runtime-web/nghttp2/autobuild/defines
  runtime-web/nghttp2/spec
Labels: upgrade, security

#5173 ca-certs: update to 20231115
  runtime-data/ca-certs/spec
Labels: upgrade

#5179 sdl-gfx: (loongarch64) fix build
  runtime-multimedia/sdl-gfx/autobuild/defines
  runtime-multimedia/sdl-gfx/spec
Labels: has-fix, new-port

#5181 systemd: use our own NTP Pool vendor zone
  app-admin/systemd/autobuild/defines
  app-admin/systemd/autobuild/defines.stage2
  app-admin/systemd/spec
Labels: enhancement

#5161 oma: update to 1.2.10
  app-admin/oma/spec
Labels: upgrade

#5176 cyrus-sasl (libsasl2): fix sover compatibility and symbol versioning
  app-network/cyrus-sasl/autobuild/beyond
  app-network/cyrus-sasl/autobuild/patches/0003-Debian-Make-the-libsasl2-symbols-versioned.patch
  app-network/cyrus-sasl/spec
Labels: has-fix

#5186 discord: update to 0.0.41
  app-web/discord/spec
Labels: upgrade

#5187 gstreamer: fix mips64r6el build
  runtime-multimedia/gstreamer/autobuild/defines
  runtime-multimedia/gstreamer/spec
Labels: has-fix, cip-pilot

#5194 chore: demote MIPS64 R6 to experimental
  .github/PULL_REQUEST_TEMPLATE
Labels: cip-pilot

#5192 gpgme update to 1.23.2
  runtime-cryptography/gpgme/spec
Labels: upgrade

#5188 xfsprogs: update to 6.5.0
  app-admin/xfsprogs/spec
Labels: upgrade

#5180 sdcc: fix parallelism breaking build
  app-devel/sdcc/autobuild/defines
Labels: has-fix

#5190 kexec-tools: new, 2.0.28
  app-admin/kexec-tools/autobuild/defines
  app-admin/kexec-tools/autobuild/patches/0001-Fedora-RISCV-kexec-tools-rv64-support.patch
  app-admin/kexec-tools/spec
Labels: new-packages

#5185 dua: update to 2.27.2
  app-utils/dua/spec
Labels: upgrade

#5199 autobuild4: update to 4.0.12
  app-devel/autobuild4/spec
Labels: upgrade

#5204 autobuild4: update to 4.0.13
  app-devel/autobuild4/spec
Labels: upgrade

#5195 iptables: add missing section header in iptables.service
  app-network/iptables/autobuild/overrides/usr/lib/systemd/system/iptables.service
  app-network/iptables/spec
Labels: has-fix

#5203 fend: update to 1.4.2
  app-utils/fend/spec
Labels: upgrade

#5215 openssh (OpenSSH): fix LoongArch seccomp architecture
  app-network/openssh/autobuild/patches/0002-Add-seccomp-audit-arch-for-loongarch64.patch
Labels: has-fix

#5214 openssl (OpenSSL): fix LoongArch runtime error
  runtime-cryptography/openssl/autobuild/defines
Labels: has-fix

#5213 LATX (Loongson Architecture Translator for x86): update to update to 1.4.4+emukit20231027
  app-emulation/latx/autobuild/build
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system-preset/50-latx.preset
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-dev.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-etc.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-proc.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-run.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-sys.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-usr-share-fontconfig.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-usr-share-fonts.mount
  app-emulation/latx/autobuild/overrides/usr/lib/systemd/system/usr-gnemul-lat\x2dx86_64-usr-share-icons.mount
  app-emulation/latx/autobuild/postinst
  app-emulation/latx/autobuild/postrm
  app-emulation/latx/autobuild/prerm
  app-emulation/latx/spec
Labels: upgrade

#5221 wps-office: update to 11.1.0.11711
  app-productivity/wps-office/autobuild/build
  app-productivity/wps-office/autobuild/postinst
  app-productivity/wps-office/spec
Labels: upgrade

#5211 Qt 6: enable WebEngine for LoongArch64
  runtime-desktop/qt-6/autobuild/defines
  runtime-desktop/qt-6/autobuild/patches/0001-Arch-Linux-qt6-base-prefer-to-use-system-cflags.patch
  runtime-desktop/qt-6/autobuild/patches/0005-loongarch64.patch.loongarch64
Labels: enhancement

#5033 Helix: update to 23.10
  app-editors/helix/autobuild/beyond
  app-editors/helix/autobuild/defines
  app-editors/helix/autobuild/patches/0001-Fix-gemini-remote-ref.patch
  app-editors/helix/autobuild/patches/0001-remove-pre-defined-LTO-settings.patch
  app-editors/helix/autobuild/patches/0002-Fix-build-with-Clang.patch
  app-editors/helix/spec
Labels: upgrade

#5206 libcue: update to 2.3.0
  runtime-multimedia/libcue/spec
Labels: upgrade

#5217 autobuild4: update to 4.0.14
  app-devel/autobuild4/spec
Labels: upgrade

#5189 tlp: update to 1.6.1
  app-admin/tlp/spec
Labels: upgrade

#5175 autobuild3: update to 1.9.0
  app-devel/autobuild3/spec
Labels: upgrade

#5220 presenterm: new, 0.5.0
  app-productivity/presenterm/autobuild/defines
  app-productivity/presenterm/spec
Labels: new-packages

#5225 Steam: update to 1.0.0.78
  app-games/steam/autobuild/overrides/usr/share/applications/steam.desktop
  app-games/steam/spec
Labels: upgrade

#5226 Chromium 121.0.6167.85 Rework
  app-devel/llvm/01-runtime/patches/temp
Labels: rework

#5212 libLoL (LoongArch on LoongArch): new, 0.1.3
  runtime-emulation/liblol/autobuild/additional-files/hooks/postinst.in
  runtime-emulation/liblol/autobuild/build
  runtime-emulation/liblol/autobuild/defines
  runtime-emulation/liblol/autobuild/overrides/usr/lib/modules-load.d/liblol.conf
  runtime-emulation/liblol/autobuild/patch
  runtime-emulation/liblol/autobuild/patches/glibc/0001-add-old-world-abi-compatibility.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0002-add-sigset-ops.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0003-add-signal-functions.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0004-add-sigaction-ucontext-compat.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0005-add-stubs-for-signal-related-io-funcs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0006-add-syscall-fallback-for-stat-at.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0007-add-more-pthread-symbols.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0008-remove-clone3-for-compatibility-with-qq.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0009-able-to-prepend-trusted-dirs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0009-prepend-trusted-dirs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0010-Add-___brk_addr-symbol.patch
  runtime-emulation/liblol/autobuild/patches/glibc/series
  runtime-emulation/liblol/autobuild/patches/patchelf/0001-add-remap-symvers.patch
  runtime-emulation/liblol/autobuild/patches/patchelf/series
  runtime-emulation/liblol/genspec
  runtime-emulation/liblol/manifest
  runtime-emulation/liblol/spec
  runtime-emulation/liblol/spec.main
Labels: new-packages

#5224 helix (Helix): drop extraneous executables
  app-editors/helix/autobuild/alternatives
  app-editors/helix/autobuild/beyond
  app-editors/helix/spec
Labels: rework

#5229 discord: update to 0.0.42
  app-web/discord/spec
Labels: upgrade

#5230 autobuild3: update to 1.9.1
  app-devel/autobuild3/spec
Labels: upgrade

#5231 autobuild4: update to 4.0.15
  app-devel/autobuild4/spec
Labels: upgrade
