Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-05, with the labels that each got.

#5782 r: security update to 4.4.0
  app-scientific/r/spec
Labels: upgrade, security

#5788 virtualbox (Oracle VM VirtualBox): update to 7.0.16
  app-virtualization/virtualbox/01-host/patches/0001-Arch-Linux-fix-Frontends-VirtualBox-disable-update-c.patch
  app-virtualization/virtualbox/01-host/patches/0002-Arch-Linux-fix-VBox-Additions-disable-unneeded-vboxv.patch
  app-virtualization/virtualbox/01-host/patches/0003-properly-handle-i3wm.patch
  app-virtualization/virtualbox/01-host/patches/0004-Arch-Linux-fix-VBox-Additions-disable-vbglR3GuestCtr.patch
  app-virtualization/virtualbox/01-host/patches/0005-support-building-from-dkms.patch
  app-virtualization/virtualbox/01-host/patches/0006-upate-xclient-script.patch
  app-virtualization/virtualbox/01-host/patches/0007-chore-use-the-wheel-group-for-hardware-access.patch
  app-virtualization/virtualbox/01-host/patches/0008-fix-dxvk-native-1.9.2a-fix-build-with-GCC-13.patch
  app-virtualization/virtualbox/spec
Labels: upgrade

#5792 openssh (OpenSSH): update to 9.7p1
  app-network/openssh/spec
Labels: upgrade

#5796 iotop: update to 1.26, migrate to iotop-c
  app-utils/iotop/autobuild/build
  app-utils/iotop/autobuild/defines
  app-utils/iotop/autobuild/patches/0001-Fedora-iotop-python3build.patch
  app-utils/iotop/autobuild/prepare
  app-utils/iotop/spec
Labels: upgrade

#5799 handbrake: update to 1.7.3
  app-multimedia/handbrake/autobuild/defines
  app-multimedia/handbrake/spec
Labels: upgrade

#5795 git: update to 2.45.0
  app-vcs/git/autobuild/build
  app-vcs/git/spec
Labels: upgrade

#5794 nano: update to 8.0+nanorc2024.1.16
  app-editors/nano/spec
Labels: upgrade

#5801 oma: update to 1.3.2
  app-admin/oma/spec
Labels: upgrade

#5814 wayland-protocols: update to 1.36
  app-devel/wayland-protocols/spec
Labels: upgrade

#5369 hydrapaper: update to 3.3.2
  app-utils/hydrapaper/autobuild/defines
  app-utils/hydrapaper/spec
Labels: upgrade

#5806 oma: update to 1.3.3
  app-admin/oma/spec
Labels: upgrade

#5804 transcode: fix FTBFS
  app-multimedia/transcode/spec
Labels: ftbfs, has-fix

#5807 rustc: update to 1.78.0
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/autobuild/patches/0003-Add-MIPSR6-definitions-to-vendored-nix-rs.patch
  lang-rust/rustc/autobuild/patches/0004-Add-MIPSR6-definitions-to-vendored-nix-0.26.patch
  lang-rust/rustc/autobuild/patches/0005-Avoid-debuginfo-for-MIPSR6-in-proc-macro-test.patch
  lang-rust/rustc/autobuild/patches/0006-Fix-missing-ioctl-for-loongarch64-and-mips64r6.patch
  lang-rust/rustc/spec
Labels: upgrade

#5821 oma: update to 1.3.4
  app-admin/oma/spec
Labels: upgrade

#5825 librime: update to 1.11.2
  runtime-i18n/librime/autobuild/defines
  runtime-i18n/librime/autobuild/librime-lua-patches/0001-Let-pkgconfig-find-lua5.3.patch
  runtime-i18n/librime/autobuild/prepare
  runtime-i18n/librime/spec
Labels: upgrade

#5826 intel-compute-runtime: new, 24.13.29138.7
  app-devel/intel-graphics-compiler/autobuild/beyond
  app-devel/intel-graphics-compiler/autobuild/defines
  app-devel/intel-graphics-compiler/autobuild/prepare
  app-devel/intel-graphics-compiler/spec
  runtime-common/level-zero/spec
  runtime-devices/igsc/autobuild/defines
  runtime-devices/igsc/spec
  runtime-devices/metee/autobuild/defines
  runtime-devices/metee/spec
  runtime-scientific/intel-compute-runtime/autobuild/defines
  runtime-scientific/intel-compute-runtime/patches/01-intel-compute-runtime-disable-werror.patch
  runtime-scientific/intel-compute-runtime/spec
Labels: new-package

#5831 uriparser: security update to 0.9.8
  runtime-web/uriparser/spec
Labels: upgrade, security

#5832 nano: disable implicit --modernbinding for e-prefixed-executables
  app-editors/nano/autobuild/patches/0001-Revert-bindings-set-up-modern-bindings-also-when-bin.patch
  app-editors/nano/spec
Labels: has-fix

#5838 aoscdk-rs: update to 1.0.4
  app-admin/aoscdk-rs/spec
Labels: upgrade

#5833 js-102 (Mozilla SpiderMonkey): update to 102.15.1
  lang-js/js-102/autobuild/patches/0001-Bug-1792981-loong64-Enable-JIT-compiler-of-loong64-p.patch
  lang-js/js-102/spec
Labels: upgrade

#5784 glib: skip document generation for mips64r6el
  runtime-common/glib/autobuild/defines
  runtime-common/glib/spec
Labels: cip-pilot

#5808 cpio: update to 2.15
  app-utils/cpio/autobuild/patches/0001-Fedora-cpio-2.13-multiple-definition.patch
  app-utils/cpio/autobuild/patches/0002-Fedora-cpio-2.13-revert-CVE-2015-1197-fix.patch
  app-utils/cpio/spec
Labels: upgrade

#5809 dos2unix: update to 7.5.2
  app-utils/dos2unix/spec
Labels: upgrade

#5810 ed: update to 1.20.2
  app-editors/ed/spec
Labels: upgrade

#5811 file: update to 5.45
  app-utils/file/autobuild/patches/0001-Fix-seccomp-module-build-on-ppc64el.patch
  app-utils/file/spec
Labels: upgrade

#5813 tree: update to 2.1.1
  app-utils/tree/spec
Labels: upgrade

#5816 gh: update to 2.49.0
  app-devel/gh/spec
Labels: upgrade

#5820 socat: update to 1.8.0.0
  app-network/socat/spec
Labels: upgrade

#5819 texinfo: update to 7.1
  app-utils/texinfo/spec
Labels: upgrade

#5818 tar: update to 1.35
  app-utils/tar/spec
Labels: upgrade

#5817 tcsh: update to 6.24.12
  app-shells/tcsh/spec
Labels: upgrade

#5845 discord: update to 0.0.53
  app-web/discord/spec
Labels: upgrade

#5835 telegram-desktop (Telegram Desktop): update to 5.0.1
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-style-respect-system-font-configuration.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#5849 wine (WineHQ): update to 9.8
  app-emulation/wine/spec
Labels: upgrade

#5827 mokutil: new, 0.6.0
  app-admin/mokutil/autobuild/defines
  app-admin/mokutil/spec
Labels: new-package

#5851 foomatic-db (Foomatic Database): update to 20240504
  app-doc/foomatic-db/spec
Labels: upgrade

#5858 mokutil: fix typo in PKGDEP
  app-admin/mokutil/autobuild/defines
Labels: has-fix, dependencies, rework

#5860 ffmpeg: fix FTBFS
  app-multimedia/ffmpeg/autobuild/patches/0001-avcodec-mips-Add-switch-for-MADD-instruction.patch
  app-multimedia/ffmpeg/autobuild/patches/0002-avutil-mips-Use-MMI_-L-S-QC1-macro-in-SAVE-RECOVER-_.patch
  app-multimedia/ffmpeg/autobuild/patches/0003-avutil-mips-Extract-load-store-with-shift-C1-pair-ma.patch
  app-multimedia/ffmpeg/autobuild/patches/0004-avcodec-mips-Use-MMI-marcos-to-replace-Loongson3-ins.patch
  app-multimedia/ffmpeg/autobuild/patches/0005-avutil-mips-Use-at-as-MMI-macro-temporary-register.patch
  app-multimedia/ffmpeg/autobuild/patches/0006-avcodec-x86-mathops-clip-constants-used-with-shift-i.patch
  app-multimedia/ffmpeg/autobuild/patches/0007-Only-use-cpuinfo-to-read-cpu-ISAs.patch
  app-multimedia/ffmpeg/autobuild/patches/0008-Add-mips64r6-generic-options.patch
  app-multimedia/ffmpeg/autobuild/patches/0009-doc-t2h.pm-fix-missing-CSS-with-texinfo-6.8-and-abov.patch
  app-multimedia/ffmpeg/autobuild/patches/0010-doc-t2h.pm-fix-missing-TOC-with-texinfo-6.8-and-abov.patch
  app-multimedia/ffmpeg/autobuild/patches/0011-doc-html-support-texinfo-7.0.patch
  app-multimedia/ffmpeg/spec
Labels: ftbfs, has-fix

#5852 oma: update to 1.3.6
  app-admin/oma/spec
Labels: upgrade

#5874 aosc-findupdate: update to 0.4.0
  app-utils/aosc-findupdate/spec
Labels: upgrade

#5787 dpkg: update to 1.22.6
  app-admin/dpkg/01-update-alternatives/build
  app-admin/dpkg/01-update-alternatives/patches/0001-HACK-feat-data-add-AOSC-OS-specific-armv4-architectu.patch
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-armv4-recognition.patch.armv4
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-armv6hf-recognition.patch.armv6hf
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-armv7hf-recognition.patch.armv7hf
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-i486-recognition.patch.i486
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-loongarch64-recognition.patch.loongarch64
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-loongson2f-recognition.patch.loongson2f
  app-admin/dpkg/01-update-alternatives/patches/0001-Hack-loongson3-recognition.patch.loongson3
  app-admin/dpkg/01-update-alternatives/patches/0002-HACK-ARMV6HF-fix-data-rename-armhf-as-AOSC-OS-specif.patch.armv6hf
  app-admin/dpkg/01-update-alternatives/patches/0003-HACK-fix-data-rename-i-86-as-AOSC-OS-specific-i486.patch
  app-admin/dpkg/01-update-alternatives/patches/0004-HACK-fix-data-rename-loong64-as-AOSC-OS-specific-loo.patch
  app-admin/dpkg/01-update-alternatives/patches/0005-HACK-LOONGSON2F-fix-data-rename-mips64el-as-AOSC-OS-.patch.loongson2f
  app-admin/dpkg/01-update-alternatives/patches/0006-feat-drop-multiarch-features-add-remove-architecture.patch
  app-admin/dpkg/01-update-alternatives/patches/0007-po-update-translation-catalogue.patch
  app-admin/dpkg/01-update-alternatives/patches/0008-po-add-translation-for-AOSC-OS-add-remove-architectu.patch
  app-admin/dpkg/01-update-alternatives/patches/0009-HACK-ARMV7HF-fix-data-rename-armhf-as-AOSC-OS-specif.patch.armv7hf
  app-admin/dpkg/01-update-alternatives/patches/0010-HACK-LOONGSON3-fix-data-rename-mips64el-as-AOSC-OS-.patch.loongson3
  app-admin/dpkg/spec
Labels: upgrade

#5871 scrcpy: update to 2.4
  app-devices/scrcpy/autobuild/defines
  app-devices/scrcpy/spec
Labels: upgrade

#5869 android-udev (Android UDev Rules): update to 20240221
  app-devices/android-udev/spec
  runtime-devices/android-udev/autobuild/build
  runtime-devices/android-udev/autobuild/defines
  runtime-devices/android-udev/autobuild/overrides/usr/lib/sysusers.d/android-udev.conf
  runtime-devices/android-udev/autobuild/postinst
  runtime-devices/android-udev/spec
Labels: upgrade

#5868 android-platform-tools (Android Platform Tools): update to 35.0.1
  app-devices/android-platform-tools/spec
Labels: upgrade

#5854 zoxide: update to 0.9.4
  app-utils/zoxide/autobuild/defines
  app-utils/zoxide/spec
Labels: upgrade

#5853 zola: update to 0.18.0
  app-web/zola/spec
Labels: upgrade

#5840 tailscale: update to 1.64.2
  app-network/tailscale/spec
Labels: upgrade

#5879 lmms: update to 1.2.2+git20240508
  app-creativity/lmms/autobuild/defines
  app-creativity/lmms/spec
Labels: upgrade

#5862 nodejs: update to 20.13.0
  lang-js/nodejs/spec
Labels: upgrade

#5880 aosc-findupdate: update to 0.4.6
  app-utils/aosc-findupdate/spec
Labels: upgrade

#5884 yazi: update to 0.2.5
  app-utils/yazi/autobuild/beyond
  app-utils/yazi/spec
Labels: upgrade

#5885 ast-grep: update to 0.22.0
  app-devel/ast-grep/spec
Labels: upgrade

#5890 fcitx5-pinyin-moegirl: update to 20240509
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#5891 feishin: update to 0.7.1
  app-multimedia/feishin/spec
Labels: upgrade

#5855 zziplib: update to 0.13.74
  runtime-common/zziplib/autobuild/defines
  runtime-common/zziplib/autobuild/patches/0001-chore-fix-version-0.13.72-0.13.74.patch
  runtime-common/zziplib/spec
Labels: upgrade

#5903 ciel: update to 3.2.5
  app-devel/ciel/spec
Labels: upgrade, manual-build

#5893 digikam: rebuild against x265 3.6 update
  desktop-kde/digikam/spec
Labels: upgrade

#5908 cava: depend on sndio as it now defaults to sndio
  app-multimedia/cava/autobuild/defines
  app-multimedia/cava/spec
Labels: dependencies

#5896 jack-capture: fix build
  app-multimedia/jack-capture/autobuild/beyond
  app-multimedia/jack-capture/autobuild/build
  app-multimedia/jack-capture/autobuild/patches/0001-fix_hardening.patch
  app-multimedia/jack-capture/autobuild/patches/0002-spelling.patch
  app-multimedia/jack-capture/autobuild/patches/0003-fix_asprintf.patch
  app-multimedia/jack-capture/autobuild/prepare
  app-multimedia/jack-capture/spec
Labels: has-fix

#5912 fcitx5: add dependencies for classic ui plugin
  app-i18n/fcitx5/autobuild/defines
  app-i18n/fcitx5/spec
Labels: dependencies

#5904 gdb: update to 14.2
  app-devel/gdb/spec
Labels: upgrade

#5905 cmake: update to 3.29.3
  app-devel/cmake/spec
Labels: upgrade

#5906 php: update to 8.3.7
  app-devel/php/spec
Labels: upgrade

#5911 xwayland: update to 23.2.6
  runtime-display/xwayland/spec
Labels: upgrade

#5910 xorg-server: update to 21.1.13
  runtime-display/xorg-server/spec
Labels: upgrade

#5902 Autobuild4: update to 4.2.0
  app-devel/autobuild4/spec
Labels: upgrade

#5950 vscode: update to 1.89.1
  app-editors/vscode/spec
Labels: upgrade

#5948 mcfly: update to 0.8.5
  app-utils/mcfly/autobuild/patches/0001-feat-add-paste-from-clipboard-support-in-emacs-mode.patch
  app-utils/mcfly/spec
Labels: upgrade

#5952 difftastic: update to 0.58.0
  app-utils/difftastic/spec
Labels: upgrade

#5955 ast-grep: update to 0.22.2
  app-devel/ast-grep/spec
Labels: upgrade

#5956 fend: update to 1.4.8
  app-utils/fend/spec
Labels: upgrade

#5803 astyle: update to 3.4.14
  app-devel/astyle/autobuild/build
  app-devel/astyle/spec
Labels: upgrade

#5949 vscodium: update to 1.89.1
  app-editors/vscodium/spec
Labels: upgrade

#5944 pandoc: update to 3.1.13
  app-doc/pandoc/autobuild/defines
  app-doc/pandoc/spec
Labels: upgrade

#5945 ninja: update to 1.12.1
  app-devel/ninja/spec
Labels: upgrade

#5946 vim: update to 9.1.0393
  app-editors/vim/spec
Labels: upgrade

#5961 autobuild4: correct CHKUPDATE
  app-devel/autobuild4/spec
Labels: upgrade

#5901 mesa (Mesa 3D Library): update to 24.0.7+dxheaders1.613.1
  runtime-display/mesa/spec
Labels: upgrade

#5934 bear: update to 3.1.3
  app-devel/bear/spec
Labels: upgrade

#5929 axel: update to 2.17.14
  app-web/axel/spec
Labels: upgrade

#5921 arping: update to 2.24
  app-network/arping/spec
Labels: upgrade

#5927 autoconf-archive: update to 2023.02.20
  app-devel/autoconf-archive/spec
Labels: upgrade

#5972 zstandard: update to 0.22.0
  lang-python/zstandard/spec
Labels: upgrade

#5974 zeal: update to 0.7.0
  app-doc/zeal/autobuild/defines
  app-doc/zeal/autobuild/patches/0001-Debian-Fix-compilation-error-with-Qt-5.15.patch
  app-doc/zeal/spec
Labels: upgrade

#5973 zstd-static: update to 1.5.6
  app-utils/zstd-static/spec
Labels: upgrade

#5981 typst: update to 0.11.0
  app-doc/typst/spec
Labels: upgrade

#5988 prismlauncher: update to 8.3
  app-games/prismlauncher/spec
Labels: upgrade

#5992 swaybg: update to 1.2.1
  app-utils/swaybg/spec
Labels: upgrade

#5994 i3lock: update to 2.15
  desktop-wm/i3lock/spec
Labels: upgrade

#5990 snapper: update to 0.11.0
  app-admin/snapper/autobuild/patches/0001-Arch-Linux-use-conf-d-instead-of-sysconfig.patch
  app-admin/snapper/autobuild/patches/0002-Arch-Linux-fix-suse-cron-dir-name.patch
  app-admin/snapper/autobuild/patches/0004-Arch-Linux-use-usr-path.patch
  app-admin/snapper/spec
Labels: upgrade

#5997 git: update to 2.45.1
  app-vcs/git/spec
Labels: upgrade

#5987 caligula: new, 0.4.5
  app-utils/caligula/autobuild/defines
  app-utils/caligula/autobuild/prepare
  app-utils/caligula/spec
Labels: new-packages

#5983 util-linux: update to 2.40.1
  app-utils/util-linux/spec
Labels: upgrade

#5942 bpftrace: update to 0.20.3
  app-admin/bpftrace/spec
Labels: upgrade

#5941 bolt: update to 0.9.7
  app-admin/bolt/spec
Labels: upgrade

#5933 bcc: update to 0.30.0
  app-devel/bcc/spec
Labels: upgrade

#5998 polybar: update to 3.7.1
  app-utils/polybar/spec
Labels: upgrade

#5918 aoscbootstrap: update to 0.4.7
  app-utils/aoscbootstrap/spec
Labels: upgrade

#5937 blueman: update to 2.4.1
  app-utils/blueman/spec
Labels: upgrade

#5938 bluez (BlueZ): update to 5.75
  app-devices/bluez/autobuild/beyond
  app-devices/bluez/spec
Labels: upgrade

#6007 cava: update to 0.10.2
  app-multimedia/cava/spec
Labels: upgrade

#6004 discord: update to 0.0.54
  app-web/discord/spec
Labels: upgrade

#5986 firefox: update to 125.0.3
  app-web/firefox/autobuild/defines
  app-web/firefox/autobuild/patches/0001-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0002-Declare-AOSC-OS-in-user-agent.patch
  app-web/firefox/autobuild/patches/0002-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0003-Enable-WebRTC-for-LoongArch.patch
  app-web/firefox/autobuild/patches/0004-Fix-libyuv-build-with-LSX-LASX.patch
  app-web/firefox/autobuild/patches/0005-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0006-Keep-unsigned-32-bit-parameter-sign-extended-in-regi.patch
  app-web/firefox/autobuild/patches/0007-Implement-SummarizeTrapInstruction-for-MIPS64.patch
  app-web/firefox/autobuild/patches/0007-loongarch64-Keep-unsigned-32-bit-parameter-sign-exte.patch
  app-web/firefox/autobuild/patches/0008-Bug-1855960-MIPS64-Make-some-assembler-routines-retu.patch
  app-web/firefox/autobuild/patches/0009-Add-missing-loongarch-lsx-code-for-libpng.patch
  app-web/firefox/autobuild/prepare
  app-web/firefox/spec
Labels: upgrade

#6012 power-profiles-daemon: new, 0.21
  app-admin/power-profiles-daemon/autobuild/defines
  app-admin/power-profiles-daemon/spec
Labels: new-packages

#6011 playerctl: update to 2.4.1
  app-multimedia/playerctl/autobuild/defines
  app-multimedia/playerctl/spec
Labels: upgrade

#6021 sarasa-gothic-fonts: update to 1.0.12
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#6019 ibm-plex-fonts: update to 6.4.0
  desktop-fonts/ibm-plex-fonts/spec
Labels: upgrade

#6018 unifont: update to 15.1.05
  desktop-fonts/unifont/spec
Labels: upgrade

#6017 lxgwwenkai-font: update to 1.330
  desktop-fonts/lxgwwenkai-font/spec
Labels: upgrade

#6016 lxgwnewcleargothic-font: update to 1.121
  desktop-fonts/lxgwnewcleargothic-font/spec
Labels: upgrade

#6015 lxgwcleargothic-font: update to 0.300.4
  desktop-fonts/lxgwcleargothic-font/autobuild/build
  desktop-fonts/lxgwcleargothic-font/spec
Labels: upgrade

#5979 cloud-utils: new, 0.33
  app-admin/cloud-utils/autobuild/build
  app-admin/cloud-utils/autobuild/defines
  app-admin/cloud-utils/autobuild/patches/0001-growpart-use-pt_size_bytes-when-partition-cannot-be-.patch
  app-admin/cloud-utils/spec
Labels: new-packages

#6026 1-ming: update to 8.10
  desktop-fonts/1-ming/spec
Labels: upgrade

#6008 frp: update to 0.58.0
  app-network/frp/spec
Labels: upgrade

#6002 level-zero: update to 1.17.0
  runtime-common/level-zero/autobuild/defines
  runtime-common/level-zero/autobuild/prepare
  runtime-common/level-zero/spec
Labels: upgrade

#6000 just: update to 1.26.0
  app-devel/just/autobuild/patches/0001-chore-switch-target-to-github-source-to-fix-loongarc.patch
  app-devel/just/spec
Labels: upgrade

#6024 gh: update to 2.49.2
  app-devel/gh/spec
Labels: upgrade

#6023 dua: update to 2.29.0
  app-utils/dua/spec
Labels: upgrade

#6003 intel-ucode: update to 20240514
  runtime-data/intel-ucode/autobuild/build
  runtime-data/intel-ucode/spec
Labels: upgrade

#5940 bochs (Bochs): update to 2.8
  app-emulation/bochs/autobuild/patches/0001-smp-debug.patch
  app-emulation/bochs/spec
Labels: upgrade

#5915 mihomo: update to 1.18.4
  app-network/mihomo/spec
Labels: upgrade

#5931 bamf: update to 0.5.6
  runtime-desktop/bamf/spec
Labels: upgrade

#5930 balsa: update to 2.6.4
  desktop-gnome/balsa/spec
Labels: upgrade

#5928 autofs: update to 5.1.9
  app-admin/autofs/autobuild/patches/0001-Fedora-autofs-5.1.8-fix-kernel-mount-status-notification.patch
  app-admin/autofs/autobuild/patches/0002-Fedora-autofs-5.1.8-fix-fedfs-build-flags.patch
  app-admin/autofs/autobuild/patches/0003-Fedora-autofs-5.1.8-fix-set-open-file-limit.patch
  app-admin/autofs/autobuild/patches/0004-Fedora-autofs-5.1.8-improve-descriptor-open-error-reporting.patch
  app-admin/autofs/autobuild/patches/0005-Fedora-autofs-5.1.8-fix-root-offset-error-handling.patch
  app-admin/autofs/autobuild/patches/0006-Fedora-autofs-5.1.8-fix-fix-root-offset-error-handling.patch
  app-admin/autofs/autobuild/patches/0007-Fedora-autofs-5.1.8-fix-nonstrict-fail-handling-of-last-offset-mount.patch
  app-admin/autofs/autobuild/patches/0008-Fedora-autofs-5.1.8-dont-fail-on-duplicate-host-export-entry.patch
  app-admin/autofs/autobuild/patches/0009-Fedora-autofs-5.1.8-fix-loop-under-run-in-cache_get_offset_parent.patch
  app-admin/autofs/autobuild/patches/0010-Fedora-autofs-5.1.8-bailout-on-rpc-systemerror.patch
  app-admin/autofs/autobuild/patches/0011-Fedora-autofs-5.1.8-fix-nfsv4-only-mounts-should-not-use-rpcbind.patch
  app-admin/autofs/autobuild/patches/0012-Fedora-autofs-5.1.8-simplify-cache_add-a-little.patch
  app-admin/autofs/autobuild/patches/0013-Fedora-autofs-5.1.8-fix-use-after-free-in-tree_mapent_delete_offset_tree.patch
  app-admin/autofs/autobuild/patches/0014-Fedora-autofs-5.1.8-fix-memory-leak-in-xdr_exports.patch
  app-admin/autofs/autobuild/patches/0015-Fedora-autofs-5.1.8-avoid-calling-pthread_getspecific-with-NULL-key_thread_attempt_id.patch
  app-admin/autofs/autobuild/patches/0016-Fedora-autofs-5.1.8-fix-sysconf-return-handling.patch
  app-admin/autofs/autobuild/patches/0017-Fedora-autofs-5.1.8-remove-nonstrict-parameter-from-tree_mapent_umount_offsets.patch
  app-admin/autofs/autobuild/patches/0018-Fedora-autofs-5.1.8-fix-handling-of-incorrect-return-from-umount_ent.patch
  app-admin/autofs/autobuild/patches/0019-Fedora-autofs-5.1.8-dont-use-initgroups-at-spawn.patch
  app-admin/autofs/autobuild/patches/0020-Fedora-autofs-5.1.8-fix-missing-unlock-in-sasl_do_kinit_ext_cc.patch
  app-admin/autofs/autobuild/patches/0021-Fedora-autofs-5.1.8-fix-invalid-tsv-access.patch
  app-admin/autofs/autobuild/patches/0022-fix-build-with-glibc-2.36.patch
  app-admin/autofs/spec
Labels: upgrade

#5923 asciidoc: update to 10.2.0
  app-doc/asciidoc/autobuild/beyond
  app-doc/asciidoc/spec
Labels: upgrade

#6029 intel-graphics-compiler: update to 1.0.16695.4
  app-devel/intel-graphics-compiler/spec
Labels: upgrade

#5925 assimp: update to 5.4.0
  runtime-multimedia/assimp/spec
Labels: upgrade

#5922 arp-scan: update to 1.10.0
  app-network/arp-scan/spec
Labels: upgrade

#5920 apt-fast: update to 1.11.0
  app-admin/apt-fast/spec
Labels: upgrade

#5917 apache-maven: update to 3.9.6
  lang-java/apache-maven/spec
Labels: upgrade

#5919 apr-util: update to 1.6.3
  runtime-common/apr-util/spec
Labels: upgrade

#5916 appres: update to 1.0.6
  app-utils/appres/spec
Labels: upgrade

#6040 zellij: update to 0.40.1
  app-utils/zellij/spec
Labels: upgrade

#6039 clash-verge-rev: update to 1.6.2
  app-network/clash-verge-rev/autobuild/patches/0001-fix-package.json-allow-building-on-platforms-without.patch
  app-network/clash-verge-rev/autobuild/patches/0002-chore-src-tauri-update-Cargo-dependencies.patch
  app-network/clash-verge-rev/autobuild/patches/0003-feat-src-assets-add-XDG-.desktop-entry.patch
  app-network/clash-verge-rev/autobuild/patches/0004-fix-tauri.conf.json-disable-bundle-distribution.patch
  app-network/clash-verge-rev/autobuild/patches/0005-fix-scripts-use-ABI2-New-World-Mihomo-binary-for-loo.patch
  app-network/clash-verge-rev/autobuild/patches/0006-feat-drop-clash-meta-alpha-support.patch
  app-network/clash-verge-rev/autobuild/patches/0007-fix-check.mjs-do-not-fetch-Mihomo-Clash-Meta-binarie.patch
  app-network/clash-verge-rev/autobuild/patches/0008-fix-src-tauri-tauri.conf.json-disable-Mihomo-Clash-M.patch
  app-network/clash-verge-rev/autobuild/patches/0009-fix-check.mjs-do-not-check-Mihomo-Clash-Meta-platfor.patch
  app-network/clash-verge-rev/autobuild/patches/0010-Drop-check-update-feature.patch
  app-network/clash-verge-rev/spec
Labels: upgrade

#6030 libmpack: fix FTBFS
  runtime-common/libmpack/autobuild/build
  runtime-common/libmpack/spec
Labels: ftbfs, has-fix

#6032 srtp: update to 2.6.0
  runtime-multimedia/srtp/spec
Labels: upgrade

#5935 bird: update to 2.15.1
  app-network/bird/autobuild/beyond
  app-network/bird/spec
Labels: upgrade

#6038 ast-grep: update to 0.22.3
  app-devel/ast-grep/spec
Labels: upgrade

#6041 gitui: update to 0.26.2
  app-utils/gitui/spec
Labels: upgrade

#6037 bash-git-status: update to 0.3.0
  app-vcs/bash-git-status/spec
Labels: upgrade

#6033 open-rs: update to 5.1.3
  app-utils/open-rs/spec
Labels: upgrade

#6031 bread-dog: update to 0.2.0
  app-utils/bread-dog/spec
Labels: upgrade

#5675 bcachefs-tools: update to 1.6.4
  app-admin/bcachefs-tools/autobuild/defines
  app-admin/bcachefs-tools/spec
Labels: upgrade

#6058 KiCAD: update to 8.0.2
  app-electronics/kicad/autobuild/beyond
  app-electronics/kicad/autobuild/defines
  app-electronics/kicad/autobuild/patches/0002-Update-zh_CN-translation-for-plugin-updater-dialog.patch
  app-electronics/kicad/spec
Labels: upgrade

#6057 pam-u2f: update to 1.3.0
  runtime-admin/pam-u2f/autobuild/patches/i10n.diff
  runtime-admin/pam-u2f/spec
Labels: upgrade

#6063 mcfly: update to 0.8.6
  app-utils/mcfly/spec
Labels: upgrade

#6060 mpvpaper: update to 1.6
  app-utils/mpvpaper/spec
Labels: upgrade

#6025 helix: update to 24.03
  app-editors/helix/autobuild/beyond
  app-editors/helix/autobuild/patches/0001-Fix-gemini-remote-ref.patch
  app-editors/helix/autobuild/patches/0002-Fix-build-with-Clang.patch
  app-editors/helix/spec
Labels: upgrade

#6056 debconf: update to 1.5.86
  app-admin/debconf/spec
Labels: upgrade

#6055 cyrus-sasl: update to 2.1.28
  app-network/cyrus-sasl/autobuild/patches/0001-Fix-build-with-Wl-as-needed.patch
  app-network/cyrus-sasl/autobuild/patches/0002-Debian-Fix-CVE-2019-19906.patch
  app-network/cyrus-sasl/autobuild/patches/0002-Make-the-libsasl2-symbols-versioned.patch
  app-network/cyrus-sasl/spec
Labels: upgrade
