Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2024-04, with the labels that each got.

#5626 fish: update to 3.7.1
  app-shells/fish/autobuild/patches/0001-Revert-wildcard-Remove-useless-access-call-for-trail.patch
  app-shells/fish/spec
Labels: upgrade

#5629 android-platform-tools: update to 34.0.5
  app-devices/android-platform-tools/autobuild/patches/0001-HACK-Bring-basic-support-for-ppc64el-loongarch64-to-boringssl.patch
  app-devices/android-platform-tools/autobuild/patches/0003-boringssl-add-support-for-LoongArch64.patch.loongarch64
  app-devices/android-platform-tools/spec
Labels: upgrade

#5630 brltty: update to 6.6
  app-a11y/brltty/autobuild/beyond
  app-a11y/brltty/spec
Labels: upgrade

#5635 uriparser: update to 0.9.7
  runtime-web/uriparser/autobuild/defines
  runtime-web/uriparser/autobuild/patches/0001-Fedora-uriparser_buildtests.patch
  runtime-web/uriparser/spec
Labels: upgrade

#5638 openssl-1.1: update to 1.1.1w
  runtime-cryptography/openssl-1.1/spec
Labels: upgrade

#5639 libcap: update to 2.69
  runtime-common/libcap/spec
Labels: upgrade

#5640 mcfly: add paste from clipboard feature
  app-utils/mcfly/autobuild/patches/0001-feat-add-paste-from-clipboard-support-in-emacs-mode.patch
  app-utils/mcfly/spec
Labels: enhancement

#5642 kde-base (KDE Base Package): adjust dependencies
  meta-bases/kde-base/autobuild/defines
  meta-bases/kde-base/spec
Labels: dependencies

#5645 util-linux 20240401 rework
  app-utils/util-linux/01-libraries/defines
  app-utils/util-linux/spec
Labels: rework

#5646 debootstrap: update to 1.0.134
  app-utils/debootstrap/autobuild/build
  app-utils/debootstrap/spec
Labels: upgrade

#5647 aosc-media-writer: new, 0.3.1
  app-utils/aosc-media-writer/autobuild/defines
  app-utils/aosc-media-writer/spec
Labels: new-packages

#5643 system-config-printer: fix .ui data installation path
  app-admin/system-config-printer/01-runtime/beyond
  app-admin/system-config-printer/01-runtime/prepare
  app-admin/system-config-printer/spec
Labels: has-fix

#5657 Rework for kde-base adjustments
  meta-bases/plasma-distro-base/autobuild/defines
  meta-bases/plasma-distro-base/spec
Labels: rework

#5644 colord: apply usability fixes
  app-admin/colord/autobuild/overrides/usr/lib/sysusers.d/colord.conf
  app-admin/colord/autobuild/patches/0001-Fix-writing-to-the-database-with-ProtectSystem-stric.patch
  app-admin/colord/autobuild/patches/0002-Fix-USB-scanners-not-working-with-RestrictAddressFam.patch
  app-admin/colord/autobuild/patches/0003-fix-NULL-passed-to-free-with-sqlite3-error_msg-point.patch
  app-admin/colord/autobuild/patches/0004-use-char-instead-of-gchar-for-pointers-passed-to-sql.patch
  app-admin/colord/autobuild/patches/0005-use-g_autoptr-again-but-with-a-custom-CLEANUP_FUNC.patch
  app-admin/colord/spec
Labels: has-fix

#5659 wtf: update to 20230906
  app-utils/wtf/spec
Labels: upgrade

#5656 lapack: update to 3.12.0
  app-scientific/lapack/autobuild/beyond
  app-scientific/lapack/autobuild/patches/0001-migrate-manpage-secton-to-section-3l.patch
  app-scientific/lapack/spec
Labels: upgrade

#5655 superslicer: update to 2.5.59.8
  app-creativity/superslicer/autobuild/patches/0003-fix-NULL-dereference-on-wxWidgets-3.2.patch
  app-creativity/superslicer/autobuild/patches/0004-fix-build-with-cereal-1.3.0.patch
  app-creativity/superslicer/autobuild/patches/0005-fix-test-utils-build-on-Linux.patch
  app-creativity/superslicer/autobuild/patches/0006-fix-Linux-installation-creating-broken-superslicer-g.patch
  app-creativity/superslicer/autobuild/patches/9998-kill-occtwrapper-so.patch
  app-creativity/superslicer/autobuild/patches/9999-disable-version-check-by-default.patch
  app-creativity/superslicer/spec
Labels: upgrade

#5665 bind Rework 20240404
  app-network/bind/spec
Labels: rework

#5672 php7: fix FTBFS
  app-devel/php7/autobuild/defines
  app-devel/php7/spec
Labels: ftbfs, has-fix

#5669 antlr4-cpp-runtime: 4.13.1, new
  runtime-common/antlr4-cpp-runtime/autobuild/beyond
  runtime-common/antlr4-cpp-runtime/autobuild/defines
  runtime-common/antlr4-cpp-runtime/spec
Labels: new-packages

#5667 xwayland: update to 23.2.5
  runtime-display/xwayland/spec
Labels: upgrade

#5666 xorg-server: update to 21.1.12
  runtime-display/xorg-server/spec
Labels: upgrade

#5664 gtkwave: update to 3.3.119
  app-electronics/gtkwave/spec
Labels: upgrade

#5670 chromium 123 rework
  app-web/chromium/autobuild/build
  app-web/chromium/autobuild/defines
  app-web/chromium/autobuild/patches/4003-loongarch64-crashpad.patch
  app-web/chromium/spec
Labels: rework

#5671 nodejs: update to 20.12.1
  lang-js/nodejs/autobuild/patches/0002-Revert-deps-V8-cherry-pick-13192d6e10fa.patch
  lang-js/nodejs/spec
Labels: upgrade

#5673 postfix: fix FTBFS
  app-web/postfix/autobuild/build
  app-web/postfix/autobuild/build.stage2
  app-web/postfix/spec
Labels: ftbfs, has-fix

#5679 wxwidgets: fix FTBFS
  runtime-desktop/wxwidgets/01-wxbase/prepare
  runtime-desktop/wxwidgets/02-wxgtk3/prepare
  runtime-desktop/wxwidgets/spec
Labels: ftbfs, has-fix

#5686 sssd: update to 2.9.4
  app-admin/sssd/autobuild/beyond
  app-admin/sssd/autobuild/defines
  app-admin/sssd/autobuild/prepare
  app-admin/sssd/spec
Labels: upgrade

#5680 imagemagick: update to 6.9.13+7
  app-utils/imagemagick/autobuild/patches/0001-disable-unsafe-codecs-by-default.patch
  app-utils/imagemagick/spec
Labels: upgrade

#5678 aosc-media-writer: update to 0.3.4
  app-utils/aosc-media-writer/spec
Labels: upgrade

#5684 fontforge: fix FTBFS
  app-creativity/fontforge/autobuild/patches/0001-ArchLinux-fix-po-files.patch
  app-creativity/fontforge/spec
Labels: ftbfs, has-fix

#5677 qbittorrent: update to 4.6.4
  app-web/qbittorrent/spec
Labels: upgrade

#5689 xclock: update to 1.1.1
  app-utils/xclock/spec
Labels: upgrade

#5687 adaptivecpp: 24.02.0, new
  app-devel/adaptivecpp/autobuild/defines
  app-devel/adaptivecpp/spec
Labels: new-package

#5691 sysstat: update to 12.7.5
  app-utils/sysstat/autobuild/defines
  app-utils/sysstat/spec
Labels: upgrade

#5690 freecad: update to 0.21.2
  app-creativity/freecad/spec
Labels: upgrade

#5694 sunshine: update to 0.23.0
  app-multimedia/sunshine/autobuild/defines
  app-multimedia/sunshine/spec
Labels: upgrade

#5698 linux-firmware (Linux Firmware): update to 20240115+debian20230210-5~bpo11+1
  runtime-kernel/linux-firmware/spec
Labels: upgrade

#5697 qemu (QEMU): update to 8.2.2
  app-virtualization/qemu/spec
Labels: upgrade

#5695 pulseaudio-module-xrdp: new, 0.7+pa17.0
  app-multimedia/pulseaudio/autobuild/beyond
  app-multimedia/pulseaudio/spec
Labels: new-packages

#5701 weston: update to 13.0.0
  runtime-display/weston/autobuild/patches/0001-ci-backend-vnc-update-to-Neat-VNC-0.7.0.patch
  runtime-display/weston/spec
Labels: upgrade

#5706 xdotool: update to 3.20211022.1
  app-utils/xdotool/spec
Labels: upgrade

#5705 xfe: update to 1.46.1
  app-utils/xfe/spec
Labels: upgrade

#5704 xterm: update to 390
  app-utils/xterm/spec
Labels: upgrade

#5708 yara: update to 4.5.0
  app-utils/yara/spec
Labels: upgrade

#5710 acpica-unix: update to 20240322
  app-devel/acpica-unix/autobuild/patches/OPT_LDFLAGS.patch
  app-devel/acpica-unix/spec
Labels: upgrade

#5713 libarchive: update to 3.7.3
  runtime-common/libarchive/spec
Labels: upgrade

#5709 openssl: update to 3.3.0
  runtime-cryptography/openssl/autobuild/build
  runtime-cryptography/openssl/spec
Labels: upgrade

#5717 rustc: update to 1.77.2
  lang-rust/rustc/autobuild/defines
  lang-rust/rustc/autobuild/prepare
  lang-rust/rustc/spec
Labels: upgrade

#5716 nodejs: security update to 20.12.2
  lang-js/nodejs/spec
Labels: upgrade, security

#5702 nvtop (Neat Videocard TOP): update to 3.1.0
  app-admin/nvtop/autobuild/defines
  app-admin/nvtop/autobuild/patches/0001-fedora-nvtop-fix-icon-path.diff
  app-admin/nvtop/autobuild/patches/0001-fix-CMakeLists.txt-fix-scalable-SVG-icon-installatio.patch
  app-admin/nvtop/spec
Labels: upgrade

#5724 GIMP: fix crashing on exit without saving
  app-creativity/gimp/autobuild/patches/0002-QuitDialog-disconnect-signal-handler-on-dialog-destroy.patch
  app-creativity/gimp/spec
Labels: has-fix

#5730 Racket: update to 8.12
  lang-lisp/racket/spec
Labels: upgrade

#5729 dvd+rw-tools update patches
  app-multimedia/dvd+rw-tools/autobuild/patches/dvddl.patch
  app-multimedia/dvd+rw-tools/autobuild/patches/wctomb.patch
  app-multimedia/dvd+rw-tools/autobuild/patches/wexit.patch
  app-multimedia/dvd+rw-tools/spec
Labels: upgrade

#5743 discord (Discord): update to 0.0.50
  app-web/discord/spec
Labels: upgrade

#5715 hysteria: 2.4.0, new
  app-network/hysteria/autobuild/build
  app-network/hysteria/autobuild/defines
  app-network/hysteria/autobuild/overrides/usr/lib/systemd/system/hysteria-server.service
  app-network/hysteria/autobuild/overrides/usr/lib/systemd/system/hysteria.service
  app-network/hysteria/spec
Labels: new-package

#5723 onefetch: update to 2.20.0
  app-utils/onefetch/autobuild/defines
  app-utils/onefetch/spec
Labels: upgrade

#5727 php: update to 8.3.6
  app-devel/php/spec
Labels: upgrade

#5737 ninja: update to 1.12.0
  app-devel/ninja/autobuild/beyond
  app-devel/ninja/autobuild/build
  app-devel/ninja/autobuild/defines
  app-devel/ninja/autobuild/defines.stage2
  app-devel/ninja/spec
Labels: upgrade

#5738 wget: update to 1.24.5
  app-web/wget/spec
Labels: upgrade

#5739 cmake: update to 3.29.2
  app-devel/cmake/spec
Labels: upgrade

#5742 freerdp: update to 2.11.2
  app-network/freerdp/spec
Labels: upgrade

#5736 putty: update to 0.81
  app-network/putty/autobuild/defines
  app-network/putty/autobuild/overrides/usr/share/applications/putty.desktop
  app-network/putty/autobuild/overrides/usr/share/pixmaps/putty.svg
  app-network/putty/spec
Labels: upgrade

#5740 libproxy: update to 0.5.5
  runtime-network/libproxy/autobuild/defines
  runtime-network/libproxy/autobuild/patches/libproxy-0.4.11-crash.patch
  runtime-network/libproxy/spec
Labels: upgrade

#5749 meson: update to 1.4.0
  app-devel/meson/spec
Labels: upgrade

#5750 sway-audio-idle-inhibit: new, 0.1.1
  app-utils/sway-audio-idle-inhibit/autobuild/defines
  app-utils/sway-audio-idle-inhibit/spec
Labels: new-packages

#5756 discord (Discord): update to 0.0.51
  app-web/discord/spec
Labels: upgrade

#5757 mirrormgr: update to 0.10.2
  app-admin/mirrormgr/spec
Labels: upgrade

#5751 zig: update to 0.12.0
  lang-ziglang/zig/spec
Labels: upgrade

#5758 gmpy2: update to 2.1.5
  lang-python/gmpy2/spec
Labels: upgrade

#5760 papirus-icon-theme: new, 20240201
  desktop-themes/papirus-icon-theme/autobuild/build
  desktop-themes/papirus-icon-theme/autobuild/defines
  desktop-themes/papirus-icon-theme/spec
Labels: new-packages

#5711 cups-pdf (PDF Driver for CUPS): fix build
  runtime-doc/cups-pdf/autobuild/build
  runtime-doc/cups-pdf/autobuild/defines
  runtime-doc/cups-pdf/autobuild/patches/0001-Fedora-feat-cups-pdf.c-use-document-title-where-poss.patch
  runtime-doc/cups-pdf/autobuild/patches/0002-feat-cups-pdf.c-implement-error-reporting.patch
  runtime-doc/cups-pdf/autobuild/patches/0003-fix-make-cups-pdf-compatible-with-Ghostscript-9.54.patch
  runtime-doc/cups-pdf/autobuild/patches/0004-fix-cups-pdf.conf-output-PDFs-to-a-more-convenient-l.patch
  runtime-doc/cups-pdf/spec
Labels: has-fix

#5712 xpra: update to 5.0.8
  app-network/xpra/autobuild/conffiles
  app-network/xpra/autobuild/patches/0001-disable-doc-generation-by-default.patch
  app-network/xpra/spec
Labels: upgrade

#5761 sympy: new, 1.12
  lang-python/sympy/autobuild/defines
  lang-python/sympy/spec
Labels: new-packages

#5764 mesa (Mesa 3D Library): update to 24.0.6
  runtime-display/mesa/autobuild/defines
  runtime-display/mesa/autobuild/patches/0001-llvmpipe-make-unnamed-global-have-internal-linkage.patch
  runtime-display/mesa/autobuild/patches/0002-llvmpipe-add-an-implementation-with-llvm-orcjit.patch
  runtime-display/mesa/autobuild/patches/0003-llvmpipe-add-LoongArch-support-in-ORCJIT.patch
  runtime-display/mesa/autobuild/patches/0004-llvmpipe-append-partial-mask-to-partial-fs_variant-f.patch
  runtime-display/mesa/autobuild/patches/0005-llvmpipe-add-shader-cache-support-for-ORCJIT-impleme.patch
  runtime-display/mesa/autobuild/patches/0006-fix-iris_bufmgr.c-set-PAGE_SIZE-as-16384-for-LoongAr.patch.loongarch64
  runtime-display/mesa/spec
Labels: upgrade

#5773 oma: update to 1.3.1
  app-admin/oma/spec
Labels: upgrade

#5770 fix dotnet-8.0 build
  lang-dotnet/dotnet-host/spec
Labels: has-fix

#5783 osu-lazer: update to 2024.412.1
  app-games/osu-lazer/autobuild/defines
  app-games/osu-lazer/spec
Labels: upgrade

#5778 qt-5: fix FTBFS after libproxy and ninja update
  runtime-desktop/qt-5/autobuild/patches/0001-Fedora-QtBase-Fix-build-with-libxkbcommon-1.6.0.patch
  runtime-desktop/qt-5/autobuild/patches/0002-LoongArchLinux-QtBase-Add-LoongArch-definition-for-d.patch
  runtime-desktop/qt-5/autobuild/patches/0003-OpenMandriva-QtBase-Work-around-PySide2-brokenness.patch
  runtime-desktop/qt-5/autobuild/patches/0004-Fedora-QtLocation-Fix-build-with-GCC-10.patch
  runtime-desktop/qt-5/autobuild/patches/0005-ALT-Linux-QtLocation-Fix-build-with-GCC-13.patch
  runtime-desktop/qt-5/autobuild/patches/0006-LoongArchLinux-QtScript-Add-LoongArch-support.patch
  runtime-desktop/qt-5/autobuild/patches/0007-QtWebEngine-AArch64-Enable-condbranch-fix.patch
  runtime-desktop/qt-5/autobuild/patches/0008-QtWebEngine-Add-missing-include-for-GCC-13.patch
  runtime-desktop/qt-5/autobuild/patches/0009-QtWebEngine-Enable-GL-acceleration-on-Lima.patch
  runtime-desktop/qt-5/autobuild/patches/0010-Fedora-QtWebEngine-Fix-build-with-GCC-13.patch
  runtime-desktop/qt-5/autobuild/patches/0011-QtWebKit-Fix-build-with-Python-3.9.patch
  runtime-desktop/qt-5/autobuild/patches/0012-QtWebKit-Fix-build-with-Bison-3.7.patch
  runtime-desktop/qt-5/autobuild/patches/0013-QtWebKit-Fix-build-with-GLib-2.70.patch
  runtime-desktop/qt-5/autobuild/patches/0014-LoongArchLinux-QtWebKit-Add-LoongArch-support.patch
  runtime-desktop/qt-5/autobuild/patches/0015-Debian-QtWebKit-Fix-build-for-riscv64.patch
  runtime-desktop/qt-5/autobuild/patches/0016-Fedora-QtWebKit-Fix-missing-cstdint-for-GCC-13.patch
  runtime-desktop/qt-5/autobuild/patches/0017-FreeBSD-QtWebKit-Fix-build-with-Ruby-3.2.patch
  runtime-desktop/qt-5/autobuild/patches/0018-forkfd-linux-add-support-for-LoongArch.patch
  runtime-desktop/qt-5/autobuild/patches/0019-QPageSize-make-PageSizeId-ctor-non-explicit.patch
  runtime-desktop/qt-5/autobuild/patches/0020-Deepin-auto-select-opengl-or-opengles.patch
  runtime-desktop/qt-5/autobuild/patches/0021-Use-pkgconfig-in-order-to-find-libproxy-configuratio.patch
  runtime-desktop/qt-5/autobuild/patches/0022-Gentoo-Fix-ninja-race-condition-in-webengine.patch
  runtime-desktop/qt-5/spec
Labels: upgrade, ftbfs, has-fix

#5779 bash: update to 5.2.26
  app-shells/bash/autobuild/patches/0022-bash52-022.patch
  app-shells/bash/autobuild/patches/0023-bash52-023.patch
  app-shells/bash/autobuild/patches/0024-bash52-024.patch
  app-shells/bash/autobuild/patches/0025-bash52-025.patch
  app-shells/bash/autobuild/patches/0026-bash52-026.patch
  app-shells/bash/spec
Labels: upgrade

#5780 bash-completion: update to 2.13.0
  app-shells/bash-completion/spec
Labels: upgrade

#5785 neofetch (Neofetch): update to 7.3.11
  app-utils/neofetch/autobuild/patches/0001-neofetch-AOSC-OS-print-dpkg-architecture-where-possi.patch
  app-utils/neofetch/autobuild/patches/0002-neofetch-AOSC-OS-add-quotation-marks-around-architec.patch
  app-utils/neofetch/spec
Labels: upgrade

#5777 lowdown: update to 1.1.0
  app-doc/lowdown/autobuild/build
  app-doc/lowdown/autobuild/patches/0001-Generate-a-shared-library-as-well.patch
  app-doc/lowdown/autobuild/patches/0002-Add-lmd-if-applicable-to-shared-library.patch
  app-doc/lowdown/spec
Labels: upgrade

#5776 qemu (QEMU): update to 9.0.0
  app-virtualization/qemu/01-shared/build
  app-virtualization/qemu/01-shared/patches/0001-linux-headers-Synchronize-linux-headers-from-linux-v.patch.system-only
  app-virtualization/qemu/01-shared/patches/0002-target-loongarch-Define-some-kvm_arch-interfaces.patch.system-only
  app-virtualization/qemu/01-shared/patches/0003-target-loongarch-Supplement-vcpu-env-initial-when-vc.patch.system-only
  app-virtualization/qemu/01-shared/patches/0004-target-loongarch-Implement-kvm-get-set-registers.patch.system-only
  app-virtualization/qemu/01-shared/patches/0005-target-loongarch-Implement-kvm_arch_init-function.patch.system-only
  app-virtualization/qemu/01-shared/patches/0006-target-loongarch-Implement-kvm_arch_init_vcpu.patch.system-only
  app-virtualization/qemu/01-shared/patches/0007-target-loongarch-Implement-kvm_arch_handle_exit.patch.system-only
  app-virtualization/qemu/01-shared/patches/0008-target-loongarch-Implement-set-vcpu-intr-for-kvm.patch.system-only
  app-virtualization/qemu/01-shared/patches/0009-target-loongarch-Add-loongarch-kvm-into-meson-build.patch.system-only
  app-virtualization/qemu/01-shared/patches/0010-Add-LSX-LASX-support.patch.system-only
  app-virtualization/qemu/01-shared/patches/9999-build-most-modules-statically-hack.patch.user-only
  app-virtualization/qemu/spec
Labels: upgrade

#5472 [Preview] libLoL 0.1.5
  runtime-emulation/liblol/autobuild/abiversions/ld.abilist
  runtime-emulation/liblol/autobuild/abiversions/libBrokenLocale.abilist
  runtime-emulation/liblol/autobuild/abiversions/libanl.abilist
  runtime-emulation/liblol/autobuild/abiversions/libc.abilist
  runtime-emulation/liblol/autobuild/abiversions/libcrypt.abilist
  runtime-emulation/liblol/autobuild/abiversions/libdl.abilist
  runtime-emulation/liblol/autobuild/abiversions/libm.abilist
  runtime-emulation/liblol/autobuild/abiversions/libnsl.abilist
  runtime-emulation/liblol/autobuild/abiversions/libpthread.abilist
  runtime-emulation/liblol/autobuild/abiversions/libresolv.abilist
  runtime-emulation/liblol/autobuild/abiversions/librt.abilist
  runtime-emulation/liblol/autobuild/abiversions/libthread_db.abilist
  runtime-emulation/liblol/autobuild/abiversions/libutil.abilist
  runtime-emulation/liblol/autobuild/build
  runtime-emulation/liblol/autobuild/patches/glibc/0001-add-old-world-abi-compatibility.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0002-add-sigset-ops.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0003-add-signal-functions.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0004-add-sigaction-ucontext-compat.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0005-add-stubs-for-signal-related-io-funcs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0006-add-syscall-fallback-for-stat-at.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0007-add-more-pthread-symbols.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0008-remove-clone3-for-compatibility-with-qq.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0009-prepend-trusted-dirs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0010-Add-___brk_addr-symbol.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0011-LoongArch-Correct-__ieee754-_-_scalb-__ieee754-_-_sc.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0012-siglist-errlist-add-compact-statements.patch
  runtime-emulation/liblol/autobuild/patches/glibc/series
  runtime-emulation/liblol/spec
  runtime-emulation/liblol/spec.main
Labels: upgrade, pre-release, preview

#5791 libvirt: fix sysusers conflict
  app-virtualization/libvirt/autobuild/overrides/usr/lib/sysusers.d/libvirt-qemu.conf
  app-virtualization/libvirt/autobuild/postinst
  app-virtualization/libvirt/spec
Labels: has-fix

#5790 grub: fix bash completions
  app-admin/grub/autobuild/patches/0001-Revert-templates-Properly-disable-the-os-prober-by-d.patch
  app-admin/grub/autobuild/patches/0002-Revert-templates-Disable-the-os-prober-by-default.patch
  app-admin/grub/autobuild/patches/0003-Don-t-add-to-highlighted-row.patch
  app-admin/grub/autobuild/patches/0004-Fix-border-spacing-now-that-we-aren-t-displaying-it.patch
  app-admin/grub/autobuild/patches/0005-Indent-menu-entries.patch
  app-admin/grub/autobuild/patches/0006-Fix-margins.patch
  app-admin/grub/autobuild/patches/0007-Use-2-instead-of-1-for-our-right-hand-margin-so-line.patch
  app-admin/grub/autobuild/patches/0008-Don-t-say-GNU-Linux-in-generated-menus.patch
  app-admin/grub/autobuild/patches/0009-Don-t-draw-a-border-around-the-menu.patch
  app-admin/grub/autobuild/patches/0010-Use-the-standard-margin-for-the-timeout-string.patch
  app-admin/grub/autobuild/patches/0011-grub-mkrescue-specify-iso-level-3.patch
  app-admin/grub/autobuild/patches/0012-10_linux-do-not-count-intel-ucode-image-as-a-valid-i.patch
  app-admin/grub/autobuild/patches/0013-util-add-GRUB_COLOR_-variables.patch
  app-admin/grub/autobuild/patches/0014-grub-core-drop-GRUB-title-from-the-menu.patch
  app-admin/grub/autobuild/patches/0015-grub-install-add-efi-to-the-candidate-of-the-ESP-mou.patch
  app-admin/grub/autobuild/patches/0016-commands-add-new-command-memsize.patch
  app-admin/grub/autobuild/patches/0017-commands-add-new-command-pause.patch
  app-admin/grub/autobuild/patches/0018-normal-align-countdown-text-with-rest-of-the-UI.patch
  app-admin/grub/autobuild/patches/0019-po-add-patch-to-disable-parallel-execution.patch
  app-admin/grub/autobuild/patches/0020-util-bash-completion-Load-scripts-on-demand.patch
  app-admin/grub/autobuild/patches/0021-util-bash-completion-Fix-for-bash-completion-2.12.patch
  app-admin/grub/spec
Labels: has-fix
