Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-09, with the labels that each got.

#12342 pinentry: move gtk-2 from PKGDEP to PKGSUG
  app-utils/pinentry/autobuild/defines
  app-utils/pinentry/autobuild/overrides/usr/bin/pinentry
  app-utils/pinentry/spec
Labels: dependencies

#12359 vala: update to 0.56.18
  app-devel/vala/spec
Labels: upgrade

#12358 pdal: update to 2.9.2
  runtime-gis/pdal/spec
Labels: upgrade

#12365 pixi: update to 0.54.0
  app-devel/pixi/spec
Labels: upgrade

#12366 stress-ng: update to 0.19.04
  app-benchmarks/stress-ng/spec
Labels: upgrade

#12354 pcre2: update to 10.46
  runtime-common/pcre2/spec
Labels: upgrade, security

#12377 pixi: update to 0.54.1
  app-devel/pixi/spec
Labels: upgrade

#12378 zed: update to 0.202.5
  app-editors/zed/spec
Labels: upgrade

#12387 iosevka-fonts: update to 33.2.9
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#12388 neovim: update to 0.11.4
  app-editors/neovim/spec
Labels: upgrade

#12390 tuba: update to 0.10.2
  app-web/tuba/spec
Labels: upgrade

#12391 wireplumber: update to 0.5.11
  app-multimedia/wireplumber/spec
Labels: upgrade

#12201 pkgsite-tools: update to 0.7.6
  app-utils/pkgsite-tools/autobuild/defines
  app-utils/pkgsite-tools/spec
Labels: upgrade

#12278 element-desktop: update to 1.11.110
  app-web/element-desktop/spec
Labels: upgrade

#12282 ostree: update to 2025.5
  app-admin/ostree/spec
Labels: upgrade

#12393 vkmark: update to 2025.01
  app-benchmarks/vkmark/spec
Labels: upgrade

#12394 osu-lazer: update to 2025.816.0
  app-games/osu-lazer/spec
Labels: upgrade

#12398 cherry-studio: remove update button
  app-utils/cherry-studio/autobuild/patches/0001-disable-auto-update-feature-by-default.patch
  app-utils/cherry-studio/spec
Labels: upgrade

#12372 xfsprogs: update to 6.16.0
  app-admin/xfsprogs/spec
Labels: upgrade

#12399 zed: update to 0.202.6
  app-editors/zed/spec
Labels: upgrade

#12397 miller: update to 6.15.0
  app-utils/miller/spec
Labels: upgrade

#12408 fastfetch: update to 2.52.0
  app-utils/fastfetch/spec
Labels: upgrade

#12319 linux-firmware: update to 20250829+debian20250808+1
  runtime-kernel/linux-firmware/01-nonfree/build
  runtime-kernel/linux-firmware/spec
Labels: upgrade

#12424 clash-verge-rev: downgrade to 2.3.1
  app-proxy/clash-verge-rev/autobuild/defines
  app-proxy/clash-verge-rev/autobuild/patches/0001-feat-src-assets-add-XDG-.desktop-entry.patch
  app-proxy/clash-verge-rev/autobuild/patches/0002-fix-tauri.conf.json-disable-bundle-distribution.patch
  app-proxy/clash-verge-rev/autobuild/patches/0003-fix-scripts-use-ABI2-New-World-Mihomo-binary-for-loo.patch
  app-proxy/clash-verge-rev/autobuild/patches/0004-feat-drop-clash-meta-alpha-support.patch
  app-proxy/clash-verge-rev/autobuild/patches/0005-fix-check.mjs-do-not-fetch-Mihomo-Clash-Meta-binarie.patch
  app-proxy/clash-verge-rev/autobuild/patches/0006-fix-src-tauri-tauri.conf.json-disable-Mihomo-Clash-M.patch
  app-proxy/clash-verge-rev/autobuild/patches/0007-fix-check.mjs-do-not-check-Mihomo-Clash-Meta-platfor.patch
  app-proxy/clash-verge-rev/autobuild/patches/0008-Do-not-create-any-bundle-package.patch
  app-proxy/clash-verge-rev/autobuild/patches/0009-Drop-check-update-feature.patch
  app-proxy/clash-verge-rev/autobuild/patches/0010-Set-core-binary-name-as-mihomo.patch
  app-proxy/clash-verge-rev/autobuild/patches/0011-feat-always-not-portable.patch
  app-proxy/clash-verge-rev/autobuild/patches/0012-Set-service-install-uninstall-script-path-to-usr-lib.patch
  app-proxy/clash-verge-rev/autobuild/patches/0013-Unset-all-release-profile.patch
  app-proxy/clash-verge-rev/autobuild/patches/0014-Do-not-use-gcc.patch
  app-proxy/clash-verge-rev/autobuild/patches/0015-Drop-Upgrade-core-button.patch
  app-proxy/clash-verge-rev/autobuild/patches/0016-ppc64el-Use-rollup-wasm-node-to-fix-build-on-POWER8.patch
  app-proxy/clash-verge-rev/autobuild/patches/0017-Do-not-sidecar-mihomo-program.patch
  app-proxy/clash-verge-rev/autobuild/patches/0018-Fix-if-mihomo-geoip-file-src_path-is-symlink.patch
  app-proxy/clash-verge-rev/autobuild/patches/0019-fix-components-drop-update-checker.patch
  app-proxy/clash-verge-rev/autobuild/patches/0020-fix-drop-Open-Core-Dir-function.patch
  app-proxy/clash-verge-rev/autobuild/patches/0021-fix-disable-GeoData-update.patch
  app-proxy/clash-verge-rev/autobuild/patches/0022-fix-remove-unused-code.patch
  app-proxy/clash-verge-rev/autobuild/patches/0023-fix-edit-mihomo-path.patch
  app-proxy/clash-verge-rev/spec
Labels: downgrade

#12313 netbird: new, 0.55.1
  app-network/netbird/autobuild/beyond
  app-network/netbird/autobuild/build
  app-network/netbird/autobuild/defines
  app-network/netbird/autobuild/overrides/etc/netbird/config.json
  app-network/netbird/autobuild/overrides/usr/lib/systemd/system/netbird.service
  app-network/netbird/spec
Labels: new-package

#12422 containers-common: update to 0.64.2+image5.34.3+shortnames2025.03.19+skopeo1.18.0+storage1.57.2
  runtime-containers/containers-common/spec
Labels: upgrade

#12407 syncthing: update to 2.0.6
  app-network/syncthing/spec
Labels: upgrade

#12405 flclash: new, 0.8.87
  app-proxy/flclash/autobuild/build
  app-proxy/flclash/autobuild/defines
  app-proxy/flclash/autobuild/overrides/usr/share/applications/FlClash.desktop
  app-proxy/flclash/autobuild/patches/0001-use-pkexec.patch
  app-proxy/flclash/autobuild/patches/0002-fix-submodule.patch
  app-proxy/flclash/autobuild/prepare
  app-proxy/flclash/spec
Labels: new-package

#12402 ignis: drop, orphaned
  lang-python/ignis/autobuild/defines
  lang-python/ignis/spec
Labels: drop-package

#12401 yambar: drop, orphaned
  app-utils/yambar/autobuild/defines
  app-utils/yambar/spec
Labels: drop-package

#12338 gcc-15: Update to 15.2.0
  app-devel/gcc-15/autobuild/beyond
  app-devel/gcc-15/autobuild/patches/0001-LoongArch-Define-hook-TARGET_COMPUTE_PRESSURE_CLASSE.patch
  app-devel/gcc-15/autobuild/patches/0002-LoongArch-Fix-ICE-in-highway-1.3.0-testsuite-PR12163.patch
  app-devel/gcc-15/autobuild/patches/0002-ext-dce-Don-t-refine-live-width-with-SUBREG-mode-if-.patch
  app-devel/gcc-15/autobuild/patches/0003-libiberty-also-generate-a-PIC-version-of-libiberty.a.patch
  app-devel/gcc-15/spec
Labels: upgrade

#12434 unixbench: update to 6.0.0
  app-benchmarks/unixbench/spec
Labels: upgrade

#12400 xmake: update to 3.0.2
  app-devel/xmake/spec
Labels: upgrade

#12444 rofi: update to 2.0.0
  app-utils/rofi/autobuild/defines
  app-utils/rofi/spec
Labels: upgrade

#12445 boinc: update to 8.2.4
  app-scientific/boinc/spec
Labels: upgrade

#12429 ostree: update to 2025.6
  app-admin/ostree/spec
Labels: upgrade

#12428 feishin: update to 0.20.0
  app-multimedia/feishin/spec
Labels: upgrade

#12412 openfortivpn: update to 1.23.1
  app-network/openfortivpn/autobuild/defines
  app-network/openfortivpn/spec
Labels: upgrade

#12447 ab-download-manager: update to 1.6.11
  app-web/ab-download-manager/spec
Labels: upgrade

#12361 angie: new, 1.10.2
  app-web/angie/autobuild/beyond
  app-web/angie/autobuild/build
  app-web/angie/autobuild/conffiles
  app-web/angie/autobuild/defines
  app-web/angie/autobuild/overrides/etc/logrotate.d/angie
  app-web/angie/autobuild/overrides/usr/lib/systemd/system/angie.service
  app-web/angie/autobuild/overrides/usr/lib/tmpfiles.d/angie.conf
  app-web/angie/autobuild/overrides/usr/share/angie/html/index.html
  app-web/angie/autobuild/patches/0001-angie.conf-adapt-to-AOSC-OS-defaults.patch
  app-web/angie/autobuild/postinst
  app-web/angie/spec
Labels: new-package

#12439 aarty: update to 0.6.1
  app-utils/aarty/spec
Labels: upgrade

#12436 crush: update to 0.7.6
  app-utils/crush/spec
Labels: upgrade

#12417 typos: update to 1.36.2
  app-utils/typos/spec
Labels: upgrade

#12450 zfs: update to 2.3.4
  app-admin/zfs/autobuild/defines
  app-admin/zfs/autobuild/patches/0001-Block-manual-building-in-the-DKMS-source-tree.patch
  app-admin/zfs/autobuild/patches/0002-Enable-zed-emails.patch
  app-admin/zfs/autobuild/patches/0003-Explicitly-load-the-ZFS-module-via-systemd-service.patch
  app-admin/zfs/autobuild/patches/0004-Force-libtool-to-produce-verbose-output.patch
  app-admin/zfs/autobuild/patches/0005-linux-zvols-correctly-detect-flush-requests.patch
  app-admin/zfs/spec
Labels: upgrade

#12458 wezterm: update to 20240203+110809+5046fc22+git20250909
  app-utils/wezterm/spec
Labels: upgrade

#12466 pixi: update to 0.54.2
  app-devel/pixi/spec
Labels: upgrade

#12461 snapper: update to 0.13.0
  app-admin/snapper/autobuild/patches/0002-Arch-Linux-fix-suse-cron-dir-name.patch
  app-admin/snapper/autobuild/patches/0004-Arch-Linux-use-usr-path.patch
  app-admin/snapper/spec
Labels: upgrade

#12476 fcitx5-pinyin-moegirl: update to 20250909
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#12514 bash-pinyin-completion-rs: update to 0.3.2
  app-shells/bash-pinyin-completion-rs/spec
Labels: upgrade

#12521 sing-box: update to 1.12.8
  app-proxy/sing-box/spec
Labels: upgrade

#12519 maple-font: update to 7.7
  desktop-fonts/maple-font/spec
Labels: upgrade

#12493 deno: update to 2.5.0
  lang-js/deno/autobuild/patches/0001-use-local-patched-rusty_v8.patch
  lang-js/deno/autobuild/patches/0002-Disable-cross-compilation-setup-on-arm64.patch.v8
  lang-js/deno/autobuild/patches/0003-compiler-rt-rejust-paths.patch.v8.build
  lang-js/deno/autobuild/prepare
  lang-js/deno/spec
Labels: upgrade

#12511 linux-kernel: (amd64) enable CONFIG_DEBUG_INFO_BTF
  runtime-kernel/linux-kernel/autobuild/amd64/config
  runtime-kernel/linux-kernel/spec
Labels: has-fix, kernel

#12513 libchewing: update to 0.10.3
  runtime-i18n/libchewing/autobuild/defines
  runtime-i18n/libchewing/spec
Labels: upgrade

#12508 an-anime-game-launcher: update to 3.15.6
  app-games/an-anime-game-launcher/spec
Labels: upgrade

#12524 cherry-studio: update to 1.5.11
  app-utils/cherry-studio/spec
Labels: upgrade

#12525 wine: update to 10.15+gecko2.47.4+mono10.2.0
  app-emulation/wine/spec
Labels: upgrade

#12528 libkate: update to 0.4.3
  runtime-multimedia/libkate/autobuild/defines
  runtime-multimedia/libkate/spec
Labels: upgrade

#12534 rnote: update to 0.13.1
  app-doc/rnote/spec
Labels: upgrade

#12537 crush: update to 0.8.1
  app-utils/crush/spec
Labels: upgrade

#12500 feishin: update to 0.20.1
  app-multimedia/feishin/spec
Labels: upgrade

#12557 nwg-look: remove useless dep
  app-utils/nwg-look/autobuild/defines
  app-utils/nwg-look/spec
Labels: dependencies

#12558 pixi: update to 0.55.0
  app-devel/pixi/spec
Labels: upgrade

#12560 fex: update to 2509.1
  app-emulation/fex/spec
Labels: upgrade

#12362 duckdb: new, 1.3.2
  app-database/duckdb/autobuild/defines
  app-database/duckdb/autobuild/patches/0001-Add-ppc64le-spin-wait-instruction-17837.patch
  app-database/duckdb/spec
Labels: new-package

#12564 libgnome-keyring: fix SRCS link
  desktop-gnome/libgnome-keyring/autobuild/defines
  desktop-gnome/libgnome-keyring/spec
Labels: has-fix

#11062 a52dec: fix build
  runtime-multimedia/a52dec/autobuild/beyond
  runtime-multimedia/a52dec/autobuild/build
  runtime-multimedia/a52dec/autobuild/defines
  runtime-multimedia/a52dec/autobuild/prepare
  runtime-multimedia/a52dec/spec
Labels: has-fix

#12583 lighttpd: update to 1.4.82
  app-network/lighttpd/spec
Labels: upgrade

#12586 oma: update to 1.21.1
  app-admin/oma/spec
Labels: upgrade

#12584 libpst: update to 0.6.76+git20250122
  runtime-productivity/libpst/autobuild/beyond
  runtime-productivity/libpst/autobuild/defines
  runtime-productivity/libpst/autobuild/patches/0001-AOSCOS-Fix-man-generation.patch
  runtime-productivity/libpst/autobuild/patches/0001-Fedora-fix-Python-3.10-detection.patch
  runtime-productivity/libpst/spec
Labels: upgrade

#12572 deno: update to 2.5.1
  lang-js/deno/spec
Labels: upgrade

#12260 gitea: new, 1.24.5
  app-vcs/gitea/autobuild/beyond
  app-vcs/gitea/autobuild/build
  app-vcs/gitea/autobuild/conffiles
  app-vcs/gitea/autobuild/defines
  app-vcs/gitea/autobuild/overrides/usr/lib/systemd/system/gitea.service
  app-vcs/gitea/autobuild/overrides/usr/lib/sysusers.d/gitea.conf
  app-vcs/gitea/autobuild/overrides/usr/lib/tmpfiles.d/gitea.conf
  app-vcs/gitea/autobuild/postinst
  app-vcs/gitea/autobuild/prepare
  app-vcs/gitea/spec
Labels: new-package

#12567 libodfgen: update to 0.1.8
  runtime-productivity/libodfgen/autobuild/defines
  runtime-productivity/libodfgen/spec
Labels: upgrade

#12579 vim: update to 9.1.1766
  app-editors/vim/spec
Labels: upgrade

#12600 teams-for-linux: update to 2.2.1
  app-web/teams-for-linux/spec
Labels: upgrade

#12601 cargo-c: update to 0.10.15
  lang-rust/cargo-c/spec
Labels: upgrade

#12598 q: update to 0.19.9
  app-network/q/spec
Labels: upgrade

#12594 fish: update to 4.0.8
  app-shells/fish/spec
Labels: upgrade

#12549 sarasa-gothic-fonts: update to 1.0.33
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#12548 praat: update to 6.4.43
  app-scientific/praat/spec
Labels: upgrade

#12547 iosevka-fonts: update to 33.3.0
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#12546 eza: update to 0.23.3
  app-utils/eza/spec
Labels: upgrade

#12580 iptraf-ng: update to 1.2.2
  app-network/iptraf-ng/autobuild/alternatives
  app-network/iptraf-ng/autobuild/build
  app-network/iptraf-ng/autobuild/defines
  app-network/iptraf-ng/spec
Labels: upgrade

#12614 supertuxkart: update patch to fix apply failure
  app-games/supertuxkart/autobuild/defines
  app-games/supertuxkart/autobuild/patches/0001-Add-missing-includes-to-fix-the-build-with-gcc-13.patch
  app-games/supertuxkart/autobuild/prepare
  app-games/supertuxkart/spec
Labels: has-fix

#12608 gnome-flashback: fix patch
  desktop-gnome/gnome-flashback/autobuild/patches/0001-do-not-call-clear.patch
  desktop-gnome/gnome-flashback/autobuild/patches/do-not-call-clear-in-get_global_engine_cb.patch
  desktop-gnome/gnome-flashback/spec
Labels: has-fix

#12551 xdg-desktop-portal-termfilechooser: update to 1.2.1
  app-admin/xdg-desktop-portal-termfilechooser/spec
Labels: upgrade

#12618 firefox: update to 143.0.1
  app-web/firefox/autobuild/patches/0001-Bug-1984978-Part-1-Implement-Add-Sub-Mul-Shift-IntPt.patch
  app-web/firefox/autobuild/patches/0002-Bug-1984978-Part-2-Implement-Add-Sub-Mul-Shift-IntPt.patch
  app-web/firefox/autobuild/patches/0003-Bug-1984978-Part-3-Remove-unnecessary-and-instructio.patch
  app-web/firefox/autobuild/patches/0004-Bug-1985581-Update-shift-instruction-codegen-to-use-.patch
  app-web/firefox/autobuild/patches/0005-AOSCOS-Disable-LASX-by-default-for-libyuv.patch
  app-web/firefox/spec
Labels: upgrade, has-fix

#12626 mesa: update to 25.1.9 and fix llvmpipe orcjit cache race condition
  runtime-display/mesa/autobuild/patches/0009-FROMLIST-gallivm-orcjit-put-object-cache-under-the-p.patch
  runtime-display/mesa/spec
Labels: upgrade, has-fix

#12635 onig: update to 6.9.10
  runtime-common/onig/autobuild/defines
  runtime-common/onig/spec
Labels: upgrade

#12633 matugen: new, 2.4.1
  app-utils/matugen/autobuild/defines
  app-utils/matugen/spec
Labels: new-package

#12632 brightnessctl: new, 0.5.1
  app-devices/brightnessctl/autobuild/build
  app-devices/brightnessctl/autobuild/defines
  app-devices/brightnessctl/spec
Labels: new-package

#12631 btop: update to 1.4.5
  app-utils/btop/spec
Labels: upgrade

#12627 swww: update to 0.11.2
  app-utils/swww/autobuild/beyond
  app-utils/swww/autobuild/defines
  app-utils/swww/spec
Labels: upgrade

#12611 gtksourceview-3: fix build with GCC>=14
  runtime-editors/gtksourceview-3/autobuild/defines
  runtime-editors/gtksourceview-3/autobuild/patches/0001-FEDORA-Fix-build-with-GCC-14.patch
  runtime-editors/gtksourceview-3/spec
Labels: has-fix

#12619 librecad: new, 2.2.1.2
  app-creativity/librecad/autobuild/build
  app-creativity/librecad/autobuild/defines
  app-creativity/librecad/spec
Labels: new-package

#12612 mypaint-brushes+1: fix build with autotools!=1.16
  runtime-creativity/mypaint-brushes+1/autobuild/patches/0001-AOSCOS-turn-autotools-to-unselected-version.patch
  runtime-creativity/mypaint-brushes+1/spec
Labels: has-fix

#12642 cinnamon-settings-daemon: fix build with GCC>=14
  desktop-cinnamon/cinnamon-settings-daemon/autobuild/patches/0001-BAKCPORT-Fix-compile-issue-386.patch
  desktop-cinnamon/cinnamon-settings-daemon/spec
Labels: has-fix

#12644 gnome-keyring: fix build for GCC>=14
  desktop-gnome/gnome-keyring/autobuild/defines
  desktop-gnome/gnome-keyring/autobuild/patches/0001-BACKPORT-Fix-implicit-declaration-of-utimes-and-gett.patch
  desktop-gnome/gnome-keyring/spec
Labels: has-fix

#12645 sdl-mixer: fix build with GCC>=14
  runtime-multimedia/sdl-mixer/autobuild/defines
  runtime-multimedia/sdl-mixer/autobuild/patch
  runtime-multimedia/sdl-mixer/autobuild/patches/0001-BACKPORT-Fixed-1418-crash-on-double-free-if-loading-.patch
  runtime-multimedia/sdl-mixer/autobuild/patches/0002-BACKPORT-Raise-the-maximum-FluidSynth-gain-from-0.8-.patch
  runtime-multimedia/sdl-mixer/autobuild/patches/0003-BACKPORT-Paul-P-Komkoff-Jr-fixed-malloc-free-mismatc.patch
  runtime-multimedia/sdl-mixer/autobuild/patches/0004-BACKPORT-Fixed-normal-linking-with-libmikmod-and-lin.patch
  runtime-multimedia/sdl-mixer/autobuild/patches/0005-FEDORA-C99-compatibility-fix.patch
  runtime-multimedia/sdl-mixer/autobuild/patches/0006-BACKPORT-Fixed-missing-return-value-thanks-to-marius.patch
  runtime-multimedia/sdl-mixer/autobuild/patches/double-free-crash.patch
  runtime-multimedia/sdl-mixer/autobuild/patches/fluidsynth-volume.patch
  runtime-multimedia/sdl-mixer/spec
Labels: has-fix

#12646 marisa: update to 0.2.7
  runtime-common/marisa/autobuild/beyond
  runtime-common/marisa/autobuild/defines
  runtime-common/marisa/spec
Labels: upgrade

#12647 cinnamon-control-center: fix build with GCC>=14
  desktop-cinnamon/cinnamon-control-center/autobuild/defines
  desktop-cinnamon/cinnamon-control-center/autobuild/patches/0001-BACKPORT-network-Fix-warning-about-missing-cast-to-G.patch
  desktop-cinnamon/cinnamon-control-center/spec
Labels: has-fix

#12649 telepathy-logger: fix build with python3 and c89
  runtime-web/telepathy-logger/autobuild/defines
  runtime-web/telepathy-logger/autobuild/patches/0001-BACKPORT-tools-Fix-the-build-with-Python-3.patch
  runtime-web/telepathy-logger/autobuild/patches/0002-BACKPORT-Fix-incompatible-pointer-types.patch
  runtime-web/telepathy-logger/spec
Labels: has-fix

#12670 hmcl: update to 3.6.18
  app-games/hmcl/spec
Labels: upgrade

#12666 telepathy-idle: update to 0.2.2
  runtime-web/telepathy-idle/spec
Labels: upgrade

#12667 bsdiff: fix fuzz patch
  app-utils/bsdiff/autobuild/patches/0001-Fix-bspatch-heap-overflow-vulnerability.patch
  app-utils/bsdiff/spec
Labels: has-fix

#12681 yaru: update to 25.10.2
  desktop-themes/yaru/autobuild/defines
  desktop-themes/yaru/spec
Labels: upgrade

#12671 niri: adjust pkgdep and pkgrecom
  desktop-wm/niri/autobuild/defines
  desktop-wm/niri/spec
Labels: dependencies

#12688 gcc-13: fix defines
  app-devel/gcc-13/autobuild/defines
  app-devel/gcc-13/spec
Labels: has-fix

#12691 tint2: update to 17.0.2
  desktop-wm/tint2/autobuild/build
  desktop-wm/tint2/autobuild/defines
  desktop-wm/tint2/autobuild/patches/0001-fix-tint2conf-undefined-reference-to-symbol-sqrt-GLI.patch
  desktop-wm/tint2/spec
Labels: upgrade

#12693 rmlint: update to 2.10.3
  app-utils/rmlint/spec
Labels: upgrade

#12687 shadowsocks-rust: add network capabilities for binaries
  app-proxy/shadowsocks-rust/autobuild/postinst
  app-proxy/shadowsocks-rust/spec
Labels: enhancement

#12658 meson: update to 1.9.1
  app-devel/meson/spec
Labels: upgrade

#12664 vpl-gpu-rt: update to 25.4.0
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#12705 ciel: update to 3.9.10
  app-devel/ciel/spec
Labels: upgrade

#12706 gearlever: update to 3.4.3
  app-utils/gearlever/spec
Labels: upgrade

#12708 postgresql-18: new, 18.0
  app-database/postgresql-18/01-runtime/beyond
  app-database/postgresql-18/01-runtime/defines
  app-database/postgresql-18/01-runtime/defines.stage2
  app-database/postgresql-18/01-runtime/patches/0001-Fedora-postgresql-var-run-socket.patch
  app-database/postgresql-18/01-runtime/prepare
  app-database/postgresql-18/02-server/beyond
  app-database/postgresql-18/02-server/build
  app-database/postgresql-18/02-server/defines
  app-database/postgresql-18/02-server/defines.stage2
  app-database/postgresql-18/02-server/postgresql-check-db-dir.in
  app-database/postgresql-18/02-server/postgresql.sysusers.in
  app-database/postgresql-18/02-server/postgresqld.service.in
  app-database/postgresql-18/02-server/postgresqld.tmpfiles.in
  app-database/postgresql-18/02-server/postinst.in
  app-database/postgresql-18/spec
Labels: new-package

#12713 oma: update to 1.21.3
  app-admin/oma/spec
Labels: upgrade

#12714 easytier: update to 2.4.5
  app-network/easytier/spec
Labels: upgrade

#12717 vulkan-tools: fix cmake script defects
  app-utils/vulkan-tools/autobuild/patches/0001-build-Remove-pkg-config-provided-library-names.patch
  app-utils/vulkan-tools/spec
Labels: has-fix

#12702 deno: update to 2.5.2
  lang-js/deno/autobuild/defines
  lang-js/deno/autobuild/patches/0001-use-local-patched-rusty_v8.patch
  lang-js/deno/spec
Labels: upgrade

#12723 cherry-studio: update to 1.6.1
  app-utils/cherry-studio/spec
Labels: upgrade

#12728 flclash: update to 0.8.89
  app-proxy/flclash/autobuild/patches/0001-fix-submodules.patch
  app-proxy/flclash/autobuild/patches/0002-use-system-assets.patch
  app-proxy/flclash/autobuild/patches/0003-rm-checkupdate.patch
  app-proxy/flclash/autobuild/patches/0004-better-security.patch
  app-proxy/flclash/autobuild/prepare
  app-proxy/flclash/spec
Labels: upgrade

#12729 asar: update to 4.0.1
  app-utils/asar/autobuild/build
  app-utils/asar/autobuild/prepare
  app-utils/asar/spec
Labels: upgrade

#12750 topics/tum.schema.json: update packages-v2 syntax
  topics/tum.schema.json
Labels: meta

#12739 qt6ct: update to 0.11
  app-utils/qt6ct/spec
Labels: upgrade

#12726 tailscale: update to 1.88.3
  app-network/tailscale/spec
Labels: upgrade

#12674 element-desktop: update to 1.12.0
  app-web/element-desktop/autobuild/patches/0001-Disable-update-check.patch.deferred
  app-web/element-desktop/autobuild/patches/0002-Do-not-build-deb.patch.deferred
  app-web/element-desktop/spec
Labels: upgrade

#12695 zathura: update to 0.5.13
  app-doc/zathura/spec
Labels: upgrade

#12743 gamescope: new, 3.16.17
  desktop-wm/gamescope/autobuild/beyond
  desktop-wm/gamescope/autobuild/defines
  desktop-wm/gamescope/autobuild/patches/0001-FEDORA-Allow-to-use-system-libliftoff.patch
  desktop-wm/gamescope/autobuild/patches/0002-Use-system-glm.patch
  desktop-wm/gamescope/autobuild/prepare
  desktop-wm/gamescope/spec
Labels: new-package

#12757 ab-download-manager: update to 1.6.14
  app-web/ab-download-manager/spec
Labels: upgrade

#12764 libao: fix build with GCC>=14
  runtime-multimedia/libao/autobuild/defines
  runtime-multimedia/libao/autobuild/patches/0001-BACKPORT-pulse-fix-missing-include-warning-for-nanos.patch
  runtime-multimedia/libao/spec
Labels: has-fix

#12735 libexttextcat: fix 'lto-type-mismatch' error during build
  runtime-i18n/libexttextcat/autobuild/patches/0001-Fix-type-mismatch-between-declaration-and-definition.patch
  runtime-i18n/libexttextcat/spec
Labels: has-fix

#12777 bcachefs-tools: drop, orphaned
  app-admin/bcachefs-tools/autobuild/beyond
  app-admin/bcachefs-tools/autobuild/build
  app-admin/bcachefs-tools/autobuild/defines
  app-admin/bcachefs-tools/spec
Labels: drop-package

#12774 btrfs-progs: update to 6.17
  app-admin/btrfs-progs/spec
Labels: upgrade
