Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-06, with the labels that each got.

#11179 osu-lazer: update to 2025.530.0
  app-games/osu-lazer/spec
Labels: upgrade

#11205 swww: update to 0.10.1
  app-utils/swww/spec
Labels: upgrade

#11206 msmtp: update to 1.8.29
  app-web/msmtp/spec
Labels: upgrade

#11203 unifont: update to 16.0.04
  desktop-fonts/unifont/spec
Labels: upgrade

#11208 jq: update to 1.8.0
  app-devel/jq/autobuild/defines
  app-devel/jq/autobuild/patch
  app-devel/jq/spec
Labels: upgrade

#11214 net-snmp: fix build and enhance scripting
  app-network/net-snmp/autobuild/beyond
  app-network/net-snmp/autobuild/defines
  app-network/net-snmp/autobuild/patches/0001-AOSCOS-fix-fix-CVE-2018-1000116.patch
  app-network/net-snmp/autobuild/patches/0002-AOSCOS-fix-fix-CVE-2018-18065.patch
  app-network/net-snmp/autobuild/patches/0003-AOSCOS-fix-fix-build-with-OpenSSL-3.x.patch
  app-network/net-snmp/autobuild/patches/0004-AOSCOS-fix-fix-build-with-Perl-5.24.patch
  app-network/net-snmp/autobuild/patches/0005-BACKPORT-apps-snmpusm-Fix-recently-introduced-compil.patch
  app-network/net-snmp/autobuild/patches/CVE-2018-18065.patch
  app-network/net-snmp/autobuild/prepare
  app-network/net-snmp/spec
Labels: enhancement, has-fix

#11217 libieee1284: fix build with Python 3
  runtime-devices/libieee1284/autobuild/defines
  runtime-devices/libieee1284/autobuild/patches/0001-2009-11-13-Tim-Waugh-twaugh-redhat.com.patch
  runtime-devices/libieee1284/autobuild/patches/0002-2010-06-23-Tim-Waugh-twaugh-redhat.com.patch
  runtime-devices/libieee1284/autobuild/patches/0003-2010-06-23-Tim-Waugh-twaugh-redhat.com.patch
  runtime-devices/libieee1284/autobuild/patches/0004-2011-03-08-Tim-Waugh-twaugh-redhat.com.patch
  runtime-devices/libieee1284/autobuild/patches/0005-Fix-Python-3-compatibility.patch
  runtime-devices/libieee1284/autobuild/patches/0006-Fix-Python-3.12-compatibility.patch
  runtime-devices/libieee1284/prepare
  runtime-devices/libieee1284/spec
Labels: has-fix

#11225 cachy: drop installed tests
  lang-python/cachy/autobuild/beyond
  lang-python/cachy/autobuild/defines
  lang-python/cachy/spec
Labels: drop-package

#11220 aalib: fix build and clean up scripting
  runtime-multimedia/aalib/autobuild/defines
  runtime-multimedia/aalib/autobuild/patch
  runtime-multimedia/aalib/autobuild/patches/0001-DEBIAN-Make-Gimp-produce-better-man-page-output.patch
  runtime-multimedia/aalib/autobuild/patches/0002-DEBIAN-Typo-fix-KEY_MOUDE-KEY_MOUSE.patch
  runtime-multimedia/aalib/autobuild/patches/0003-DEBIAN-Manual-page-for-aalib-config-and-aafire-1-upd.patch
  runtime-multimedia/aalib/autobuild/patches/0004-DEBIAN-Fix-linux_init.patch
  runtime-multimedia/aalib/autobuild/patches/0005-DEBIAN-Fix-the-info-file-s-direntry.patch
  runtime-multimedia/aalib/autobuild/patches/0006-DEBIAN-Fixes-manpage-has-errors-from-man-l-not-defin.patch
  runtime-multimedia/aalib/autobuild/patches/0007-DEBIAN-Better-Dim-support.patch
  runtime-multimedia/aalib/autobuild/patches/0008-DEBIAN-Symbol-versioning.patch
  runtime-multimedia/aalib/autobuild/patches/0009-DEBIAN-Various-build-system-changes.patch
  runtime-multimedia/aalib/autobuild/patches/0010-DEBIAN-Gpm_GetEvent-fix.patch
  runtime-multimedia/aalib/autobuild/patches/0011-DEBIAN-Fix-TexInfo-error.patch
  runtime-multimedia/aalib/autobuild/patches/0012-DEBIAN-aalinuxkbd-Always-return-with-a-value.patch
  runtime-multimedia/aalib/autobuild/patches/0013-FROMLIST-Fix-build-with-GCC-14.patch
  runtime-multimedia/aalib/autobuild/patches/series
  runtime-multimedia/aalib/spec
Labels: has-fix

#11212 php: drop unused enchant, uw-imap deps
  app-devel/php/autobuild/defines
  app-devel/php/spec
Labels: drop-package

#11227 mercurial: update to 7.0.2
  app-vcs/mercurial/autobuild/defines
  app-vcs/mercurial/autobuild/patches/0001-fix-python-3.14.patch
  app-vcs/mercurial/spec
Labels: upgrade

#11239 feishin: update to 0.14.0
  app-multimedia/feishin/autobuild/build
  app-multimedia/feishin/autobuild/patches/0001-mpv-settings-use-usr-bin-mpv-as-default-path.patch
  app-multimedia/feishin/spec
Labels: upgrade

#11233 navidrome: new, 0.56.1
  app-multimedia/navidrome/autobuild/defines
  app-multimedia/navidrome/autobuild/overrides/etc/navidrome/navidrome.toml
  app-multimedia/navidrome/autobuild/overrides/usr/lib/systemd/system/navidrome.service
  app-multimedia/navidrome/autobuild/overrides/usr/lib/sysusers.d/navidrome.conf
  app-multimedia/navidrome/autobuild/overrides/usr/lib/tmpfiles.d/navidrome.conf
  app-multimedia/navidrome/autobuild/patches/0001-disable-anonymous-data-collection-by-default.patch
  app-multimedia/navidrome/autobuild/postinst
  app-multimedia/navidrome/autobuild/prepare
  app-multimedia/navidrome/spec
Labels: new-package

#11246 element-desktop: update to 1.11.102
  app-web/element-desktop/autobuild/patches/0001-Disable-update-check.patch.deferred
  app-web/element-desktop/autobuild/patches/0002-Do-not-build-deb.patch.deferred
  app-web/element-desktop/spec
Labels: upgrade

#11210 qpwgraph: update to 0.9.3
  app-multimedia/qpwgraph/spec
Labels: upgrade

#11245 squashfs-tools: update to 4.7
  app-admin/squashfs-tools/autobuild/build
  app-admin/squashfs-tools/spec
Labels: upgrade

#11256 ttf-vlgothic: update to 20230918
  desktop-fonts/ttf-vlgothic/autobuild/build
  desktop-fonts/ttf-vlgothic/autobuild/defines
  desktop-fonts/ttf-vlgothic/spec
Labels: upgrade

#11260 pipewire: update to 1.4.5
  app-multimedia/pipewire/spec
Labels: upgrade

#11262 zfs: do not build kernel module in containers
  app-admin/zfs/autobuild/postinst
  app-admin/zfs/spec
Labels: has-fix

#11264 sdl2: fix wayland support
  runtime-multimedia/sdl2/autobuild/defines
  runtime-multimedia/sdl2/spec
Labels: has-fix

#11266 zsh: fix build and improve scripting
  app-shells/zsh/autobuild/patches/0001-FROMLIST-C-compatiblity-fixes-for-the-configure-scri.patch
  app-shells/zsh/autobuild/patches/0002-AOSCOS-fix-Completion-fix-paths-in-built-in-completi.patch
  app-shells/zsh/autobuild/patches/0003-AOSCOS-fix-Completion-disable-non-Linux-compatible-c.patch
  app-shells/zsh/autobuild/prepare
  app-shells/zsh/spec
Labels: enhancement, has-fix

#11272 gearlever: update to 3.3.0
  app-utils/gearlever/autobuild/defines
  app-utils/gearlever/spec
Labels: upgrade

#11133 pcl: update to 1.15.0
  runtime-imaging/pcl/autobuild/defines
  runtime-imaging/pcl/spec
Labels: upgrade

#11269 wput: fix build and improve scripting
  app-web/wput/autobuild/build
  app-web/wput/autobuild/defines
  app-web/wput/autobuild/patches/0001-DEBIAN-Enable-POSIX-strdup-and-strptime-definition-v.patch
  app-web/wput/autobuild/patches/0002-DEBIAN-Ensure-variables-are-only-declared-once.patch
  app-web/wput/autobuild/prepare
Labels: enhancement, has-fix

#11263 fwupd: update to 2.0.11
  app-admin/fwupd/spec
Labels: upgrade

#11273 sing-box: update to 1.11.13
  app-network/sing-box/autobuild/beyond
  app-network/sing-box/autobuild/overrides/usr/lib/sysusers.d/sing-box.conf
  app-network/sing-box/autobuild/overrides/usr/lib/tmpfiles.d/sing-box.conf
  app-network/sing-box/autobuild/patches/0001-backport-to-run-systemd-service-with-sing-box-user.patch
  app-network/sing-box/autobuild/postinst
  app-network/sing-box/spec
Labels: upgrade

#11254 uv: update to 0.7.10
  lang-python/uv/spec
Labels: upgrade

#11281 zsh: fix module building
  app-shells/zsh/autobuild/beyond
  app-shells/zsh/autobuild/defines
  app-shells/zsh/autobuild/patches/0001-FROMLIST-C-compatiblity-fixes-for-the-configure-scri.patch
  app-shells/zsh/autobuild/patches/0002-AOSCOS-fix-Completion-fix-paths-in-built-in-completi.patch
  app-shells/zsh/autobuild/patches/0003-AOSCOS-fix-Completion-disable-non-Linux-compatible-c.patch
  app-shells/zsh/autobuild/patches/0004-FROMLIST-51889-fix-module-loading-problem-with-full-.patch
  app-shells/zsh/autobuild/patches/0005-AOSCOS-fix-fixup-pre-C99-syntax-in-m4-modules-and-co.patch
  app-shells/zsh/spec
Labels: enhancement, has-fix

#11286 libuser: drop again, orphaned
  groups/glib-rebuilds
  runtime-admin/libuser/spec
Labels: drop-package

#11284 shh: update to 2025.6.5
  app-utils/shh/autobuild/beyond
  app-utils/shh/spec
Labels: upgrade

#11288 typos: update to 1.33.1
  app-utils/typos/spec
Labels: upgrade

#11291 dnscontrol: update to 4.21.0
  app-network/dnscontrol/spec
Labels: upgrade

#11295 Revert "qownnotes: update to 25.6.0"
  app-web/qownnotes/spec
Labels: rework

#11280 plymouth: add missing libxkbcommon dependency
  app-admin/plymouth/autobuild/beyond
  app-admin/plymouth/autobuild/defines
  app-admin/plymouth/spec
Labels: dependencies

#11282 dovecot: update to 2.4.1
  app-web/dovecot/autobuild/beyond
  app-web/dovecot/autobuild/defines
  app-web/dovecot/autobuild/overrides/usr/lib/sysusers.d/dovecot.conf
  app-web/dovecot/autobuild/patches/0001-global-Drop-support-for-old-iconv.patch
  app-web/dovecot/autobuild/patches/0002-AOSCOS-fix-doc-mkcert.sh-set-default-OPENSSLCONFIG-p.patch
  app-web/dovecot/autobuild/postinst
  app-web/dovecot/autobuild/prepare
  app-web/dovecot/spec
Labels: upgrade

#11299 arcanist: update to 2025.18
  app-devel/arcanist/autobuild/build
  app-devel/arcanist/autobuild/defines
  app-devel/arcanist/autobuild/patches/0001-BACKPORT-arc-browse-add-support-for-Subversion-repos.patch
  app-devel/arcanist/autobuild/patches/0001-Fix-PHP-8-exit-status-cannot-be-null-error.patch
  app-devel/arcanist/autobuild/patches/0002-BACKPORT-Allow-using-PCRE-s-just-in-time-compilation.patch
  app-devel/arcanist/autobuild/patches/0002-Remove-an-outdated-PHP-5.3-check-in-utils.patch
  app-devel/arcanist/autobuild/patches/0003-BACKPORT-Remove-use-of-deprecated-E_STRICT-PHP-const.patch
  app-devel/arcanist/autobuild/patches/0003-Fix-PHP-8.1-strlen-null-exception-in-PHPASTParserTes.patch
  app-devel/arcanist/autobuild/patches/0004-AOSCOS-xhpast-Accept-CXXFLAGS-and-CPPFLAGS-from-the-.patch
  app-devel/arcanist/autobuild/patches/0004-Fix-PHP-8.1-preg_match-null-exception-in-XHPASTNode.patch
  app-devel/arcanist/autobuild/patches/0005-PHPDoc-Replace-return-this-with-return-this.patch
  app-devel/arcanist/autobuild/patches/0006-Fix-PHP-8.1-strlen-null-exception-in-HTTPFutureHTTPR.patch
  app-devel/arcanist/autobuild/patches/0007-Fix-PHP-8.1-strlen-null-exception-in-PhutilOAuth1Fut.patch
  app-devel/arcanist/autobuild/patches/0008-Fix-invalid-constructor-call-for-ArcanistHardpointFu.patch
  app-devel/arcanist/autobuild/patches/0009-Fix-implicitly-nullable-parameter-declarations-for-P.patch
  app-devel/arcanist/autobuild/patches/0010-Fix-implicitly-nullable-parameter-declarations-for-P.patch
  app-devel/arcanist/autobuild/patches/0011-JSON-rendering-Avoid-exception-iterating-on-non-iter.patch
  app-devel/arcanist/autobuild/patches/0012-Skip-writing-symbol-cache-to-non-writable-directorie.patch
  app-devel/arcanist/autobuild/patches/0013-xhpast-Skip-minline-all-stringops-on-non-x86-archite.patch
  app-devel/arcanist/autobuild/patches/0014-AOSCOS-Remove-deprecated-E_STRICT.patch
  app-devel/arcanist/spec
Labels: upgrade

#11304 pcl: add flann dependency
  runtime-imaging/pcl/autobuild/defines
  runtime-imaging/pcl/spec
Labels: dependencies

#11305 osu-lazer: update to 2025.605.3
  app-games/osu-lazer/spec
Labels: upgrade

#11274 repo: update to 2.55.1
  app-devel/repo/spec
Labels: upgrade

#11317 osu-lazer: update to 2025.607.0
  app-games/osu-lazer/spec
Labels: upgrade

#11204 gradle: update to 8.14.2
  lang-java/gradle/autobuild/build
  lang-java/gradle/autobuild/defines
  lang-java/gradle/spec
Labels: upgrade

#11315 ab-download-manager: update to 1.6.3
  app-web/ab-download-manager/spec
Labels: upgrade

#11314 amberol: new, 2025.1
  app-multimedia/amberol/autobuild/defines
  app-multimedia/amberol/spec
Labels: new-package

#11318 swww: update to 0.10.2
  app-utils/swww/spec
Labels: upgrade

#11311 qutebrowser: update to 3.5.1+pdfjs5.3.31
  app-web/qutebrowser/spec
Labels: upgrade

#11320 osu-lazer: update to 2025.607.1
  app-games/osu-lazer/spec
Labels: upgrade

#11323 lazygit: update to 0.52.0
  app-vcs/lazygit/spec
Labels: upgrade

#11321 telegram-desktop: update to 5.15.2
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-fix-current_geo_location_linux-add-missing-QGuiAppli.patch
  app-web/telegram-desktop/autobuild/patches/0010-fix-core_settings.h-enable-video-hardware-accelerati.patch
  app-web/telegram-desktop/autobuild/patches/0011-fix-cmake-disable-CMP0160-to-workaround-KF5-cmake-er.patch
  app-web/telegram-desktop/autobuild/patches/0012-BACKPORT-Add-missing-conditionals-to-the-kimageforma.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#11325 pmbootstrap: update to 3.4.2
  app-utils/pmbootstrap/spec
Labels: upgrade

#11329 ab-download-manager: update to 1.6.4
  app-web/ab-download-manager/spec
Labels: upgrade

#11336 xray: update to 25.6.8
  app-network/xray/autobuild/defines
  app-network/xray/autobuild/prepare
  app-network/xray/spec
Labels: upgrade

#11332 znc: update to 1.10.0
  app-web/znc/spec
Labels: upgrade

#11322 libreoffice: update to 25.2.4.3
  app-productivity/libreoffice/spec
Labels: upgrade

#11338 tailscale: update to 1.84.2
  app-network/tailscale/spec
Labels: upgrade

#11333 telegram-desktop: update to 5.15.3
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-fix-current_geo_location_linux-add-missing-QGuiAppli.patch
  app-web/telegram-desktop/autobuild/patches/0010-fix-core_settings.h-enable-video-hardware-accelerati.patch
  app-web/telegram-desktop/autobuild/patches/0011-fix-cmake-disable-CMP0160-to-workaround-KF5-cmake-er.patch
  app-web/telegram-desktop/autobuild/patches/0012-BACKPORT-Add-missing-conditionals-to-the-kimageforma.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#11339 gnupg: downgrade to 2.4.8
  app-cryptography/gnupg/autobuild/defines
  app-cryptography/gnupg/autobuild/patches/0001-avoid-beta-warning.patch
  app-cryptography/gnupg/autobuild/prepare
  app-cryptography/gnupg/spec
Labels: downgrade

#11340 swww: update to 0.10.3
  app-utils/swww/spec
Labels: upgrade

#11342 fcitx5-pinyin-moegirl: update to 20250610
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#11335 gcc-15: Replace the PR120050 workaround with the upstreamed fix
  app-devel/gcc-15/autobuild/patches/0002-NFU-mips-disable-ext-dce-by-default.patch
  app-devel/gcc-15/autobuild/patches/0002-ext-dce-Don-t-refine-live-width-with-SUBREG-mode-if-.patch
  app-devel/gcc-15/spec
Labels: enhancement

#11344 element-desktop: update to 1.11.103
  app-web/element-desktop/spec
  topics/element-desktop-1.11.103.toml
Labels: upgrade, security

#11350 repo: update to 2.55.2
  app-devel/repo/spec
Labels: upgrade

#11351 z3: update to 4.15.1
  app-devel/z3/spec
Labels: upgrade

#11348 gearlever: update to 3.3.3
  app-utils/gearlever/spec
Labels: upgrade

#11361 nushell: update to 0.105.1
  app-shells/nushell/spec
Labels: upgrade

#11359 scrcpy: update to 3.3
  app-devices/scrcpy/spec
Labels: upgrade

#11365 uv: update to 0.7.13
  lang-python/uv/spec
Labels: upgrade

#11368 eza: update to 0.21.4
  app-utils/eza/spec
Labels: upgrade

#11370 wayland-protocols: update to 1.45
  app-devel/wayland-protocols/spec
Labels: upgrade

#11373 cinnamon: replace py2cairo dep with py3cairo
  desktop-cinnamon/cinnamon/autobuild/defines
  desktop-cinnamon/cinnamon/spec
Labels: dependencies

#11379 chore(github): update pull request template
  .github/PULL_REQUEST_TEMPLATE
Labels: enhancement, workflow

#11377 mtools: update to 4.0.49
  app-admin/mtools/spec
Labels: upgrade

#11372 electron-netease-cloud-music: new, 0.9.40
  app-multimedia/electron-netease-cloud-music/autobuild/build
  app-multimedia/electron-netease-cloud-music/autobuild/defines
  app-multimedia/electron-netease-cloud-music/autobuild/overrides/usr/share/applications/electron-netease-cloud-music.desktop
  app-multimedia/electron-netease-cloud-music/spec
Labels: new-package

#11382 edit: update to 1.2.0
  app-editors/edit/autobuild/patches/0001-Add-other-architecture-support.patch
  app-editors/edit/autobuild/patches/0002-unix-fix-language-match.patch
  app-editors/edit/autobuild/patches/0003-fix-assets-remove-extraneous-Source-and-License-elem.patch
  app-editors/edit/autobuild/patches/0004-feat-assets-add-a-.desktop-entry.patch
  app-editors/edit/autobuild/patches/0005-Add-the-application-icon-to-the-Readme-35.patch
  app-editors/edit/spec
Labels: upgrade

#11374 telegram-desktop: update to 5.15.4
  app-web/telegram-desktop/spec
Labels: upgrade

#11394 qscintilla: update to 2.14.1
  runtime-common/qscintilla/autobuild/build
  runtime-common/qscintilla/autobuild/defines
  runtime-common/qscintilla/spec
Labels: upgrade

#11401 colord-kde: add kirigami-addons dependency
  desktop-kde/colord-kde/autobuild/defines
  desktop-kde/colord-kde/spec
Labels: dependencies

#11396 graphviz: update to 13.0.1
  app-doc/graphviz/spec
Labels: upgrade

#11397 iosevka-fonts: update to 33.2.5
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#11387 freerdp: update to 3.16.0
  app-network/freerdp/spec
Labels: upgrade

#11406 element-desktop: update to 1.11.104
  app-web/element-desktop/spec
Labels: upgrade

#11419 nvidia: update to 575.64
  runtime-display/nvidia/spec
Labels: upgrade

#11404 perl-uri: update to 5.32
  lang-perl/perl-uri/spec
Labels: upgrade

#11432 openblas: update to 0.3.30
  app-scientific/openblas/autobuild/patches/0001-Restore-the-non-vectorized-code-from-before-PR4880-f.patch
  app-scientific/openblas/autobuild/patches/0002-Restore-the-non-vectorized-code-from-before-PR4880-f.patch
  app-scientific/openblas/spec
Labels: upgrade

#11420 nvidia-open: update to 575.64
  runtime-display/nvidia-open/spec
Labels: upgrade

#11439 webkit2gtk: correct WSA numbers in TUM data
  topics/webkit2gtk-2.48.3.toml
Labels: rework

#11444 glab: update to 1.60.2
  app-devel/glab/spec
Labels: upgrade

#11446 tuba: new, 0.9.2
  app-web/tuba/autobuild/defines
  app-web/tuba/spec
Labels: new-package

#11443 difftastic: update to 0.64.0
  app-utils/difftastic/spec
Labels: upgrade

#11442 renpy: fix build
  runtime-games/renpy/autobuild/patches/0001-AOSCOS-Fix-for-Python-3.14.patch
  runtime-games/renpy/autobuild/patches/0002-Replace-deprecated-APIs-when-compiling-against-newer.patch
  runtime-games/renpy/autobuild/patches/0002-system-dir-read-only-bypass.patch
  runtime-games/renpy/autobuild/patches/0003-AOSCOS-Bypass-for-read-only-system-directory.patch
  runtime-games/renpy/spec
Labels: has-fix

#11440 neomutt: update to 20250510
  app-web/neomutt/spec
Labels: upgrade

#11458 qscintilla: remove PKGBREAK
  runtime-common/qscintilla/autobuild/defines
  runtime-common/qscintilla/spec
Labels: dependencies

#10541 qtscrcpy: new, 3.1.3
  app-utils/qtscrcpy/autobuild/beyond
  app-utils/qtscrcpy/autobuild/defines
  app-utils/qtscrcpy/autobuild/overrides/usr/share/applications/qtscrcpy.desktop
  app-utils/qtscrcpy/autobuild/patches/0001-Fix-Use-HTTPS-for-QtScrcpyCore-submodule.patch
  app-utils/qtscrcpy/autobuild/patches/0002-add-install-for-CmakeLists.txt.patch
  app-utils/qtscrcpy/autobuild/patches/0003-Modify-the-hard-coded-paths-to-properly-access-resou.patch
  app-utils/qtscrcpy/autobuild/patches/0004-modify-the-adb-location-in-sndcpy.sh.patch
  app-utils/qtscrcpy/autobuild/patches/0005-modify-the-sndcpy.apk-location-in-sndcpy.sh.patch
  app-utils/qtscrcpy/autobuild/prepare
  app-utils/qtscrcpy/spec
Labels: new-package

#11445 git-extras: update to 7.4.0
  app-devel/git-extras/spec
Labels: upgrade

#11454 catch2: fix cmake build flags
  runtime-common/catch2/autobuild/defines
  runtime-common/catch2/spec
Labels: has-fix

#11465 swig: update to 4.3.1
  app-devel/swig/spec
Labels: upgrade

#11459 scrcpy: update to 3.3.1
  app-devices/scrcpy/spec
Labels: upgrade

#11460 git: update to 2.50.0
  app-vcs/git/spec
Labels: upgrade

#11473 libblockdev: rework TUM for 3.3.1
  topics/libblockdev-3.3.1.toml
Labels: rework

#11481 qbittorrent: update to 5.1.1
  app-web/qbittorrent/spec
Labels: upgrade

#11478 musicfox: update to 4.6.2
  app-multimedia/musicfox/spec
Labels: upgrade

#11470 erofs-utils: update to 1.8.7
  app-admin/erofs-utils/spec
Labels: upgrade

#11482 btrfs-progs: update to 6.15
  app-admin/btrfs-progs/spec
Labels: upgrade

#11485 waybar: update to 0.13.0
  app-utils/waybar/autobuild/patches/0001-fix-support-libcava-0.10.4.patch
  app-utils/waybar/spec
Labels: upgrade

#11491 repo: update to 2.56
  app-devel/repo/spec
Labels: upgrade

#11495 feishin: update to 0.15.1
  app-multimedia/feishin/autobuild/patches/0001-mpv-settings-use-usr-bin-mpv-as-default-path.patch
  app-multimedia/feishin/spec
Labels: upgrade

#11493 frp: update to 0.63.0
  app-proxy/frp/spec
Labels: upgrade

#11480 sunshine: enable cuda
  app-multimedia/sunshine/autobuild/defines
  app-multimedia/sunshine/autobuild/prepare
  app-multimedia/sunshine/spec
Labels: enhancement

#11496 vscode: update to 1.101.1
  app-editors/vscode/spec
Labels: upgrade

#11450 vpl-gpu-rt: update to 25.2.5
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#11449 i2pd: update to 2.57.0
  app-web/i2pd/autobuild/beyond
  app-web/i2pd/spec
Labels: upgrade

#11462 uefitool: rebuild for loongarch
  app-devel/uefitool/autobuild/build
  app-devel/uefitool/autobuild/patches/0001-PE_IMAGE-Add-MultiArch-definitions.patch
  app-devel/uefitool/spec
Labels: enhancement

#11514 opentofu: update to 1.10.1
  app-admin/opentofu/spec
Labels: upgrade

#11513 hugo: update to 0.147.9
  app-web/hugo/spec
Labels: upgrade

#11522 pipewire: update to 1.4.6
  app-multimedia/pipewire/spec
Labels: upgrade

#11523 bitwarden: update to 2025.6.0
  app-utils/bitwarden/spec
Labels: upgrade

#11492 pocl: update to 7.0
  runtime-common/pocl/autobuild/defines
  runtime-common/pocl/spec
Labels: upgrade

#11509 calibre: update to 8.5.0
  app-doc/calibre/autobuild/defines
  app-doc/calibre/spec
Labels: upgrade

#11511 chezmoi: update to 2.62.7
  app-utils/chezmoi/spec
Labels: upgrade

#11515 podman: update to 5.5.2+vsock0.8.4
  app-containers/podman/spec
Labels: upgrade

#11516 glab: update to 1.61.0
  app-devel/glab/spec
Labels: upgrade

#11526 renderdoc: update to 1.39
  app-devel/renderdoc/spec
Labels: upgrade

#11528 stress-ng: update to 0.19.01
  app-benchmarks/stress-ng/spec
Labels: upgrade

#11527 cloudflared: update to 2025.6.1
  app-proxy/cloudflared/autobuild/build
  app-proxy/cloudflared/autobuild/defines
  app-proxy/cloudflared/autobuild/patches/0001-Add-loongarch64-architecture-support.patch
  app-proxy/cloudflared/autobuild/patches/0002-support-build-from-source-on-risc64.patch
  app-proxy/cloudflared/autobuild/patches/0003-add-ppc64le-and-mips64-architecture-support.patch
  app-proxy/cloudflared/spec
Labels: upgrade

#11533 obs-studio: update to 31.0.4
  app-multimedia/obs-studio/autobuild/defines
  app-multimedia/obs-studio/spec
Labels: upgrade

#11534 autobuild4: update to 4.12.1
  app-devel/autobuild4/spec
Labels: upgrade

#11539 iosevka-fonts: update to 33.2.6
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#11540 sarasa-gothic-fonts: update to 1.0.31
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade
