Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-03, with the labels that each got.

#9893 networkmanager: update to 1.52.0
  app-network/networkmanager/autobuild/armv4
  app-network/networkmanager/autobuild/armv6hf
  app-network/networkmanager/autobuild/armv7hf
  app-network/networkmanager/autobuild/beyond
  app-network/networkmanager/autobuild/conffiles
  app-network/networkmanager/autobuild/defines
  app-network/networkmanager/autobuild/defines.stage2
  app-network/networkmanager/autobuild/i486
  app-network/networkmanager/autobuild/loongson2f
  app-network/networkmanager/autobuild/m68k
  app-network/networkmanager/autobuild/networkmanager.png
  app-network/networkmanager/autobuild/powerpc
  app-network/networkmanager/autobuild/ppc64
  app-network/networkmanager/autobuild/retro/overrides/etc/NetworkManager/NetworkManager.conf
  app-network/networkmanager/autobuild/retro/overrides/etc/NetworkManager/conf.d/31-mac-addr-change.conf
  app-network/networkmanager/spec
Labels: upgrade

#9895 r: update to 4.4.3
  app-scientific/r/spec
Labels: upgrade

#9889 libreoffice: update to 25.2.1.2
  app-productivity/libreoffice/spec
Labels: upgrade

#9758 mise: new, 2025.2.8
  app-devel/mise/autobuild/beyond
  app-devel/mise/autobuild/config
  app-devel/mise/autobuild/defines
  app-devel/mise/autobuild/templates
  app-devel/mise/spec
Labels: new-package

#9899 acbs: update to 20250226
  app-devel/acbs/spec
Labels: upgrade

#9900 ciel: update to 3.9.5
  app-devel/ciel/spec
Labels: upgrade

#9901 lfortran: update to 0.46.0
  app-devel/lfortran/spec
Labels: upgrade

#9903 mihomo-party: fix update sub-store feature on linux
  app-network/mihomo-party/autobuild/defines
  app-network/mihomo-party/autobuild/patches/0003-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0004-Remove-upgrade-mihomo-UI.patch
  app-network/mihomo-party/autobuild/patches/0005-Do-not-fetch-Mihomo-Clash-Meta-binaries.patch
  app-network/mihomo-party/autobuild/patches/0006-Do-not-find-Mihomo-Clash-Meta-binary-in-sidecar-dir.patch
  app-network/mihomo-party/autobuild/patches/0007-fix-update-sub-store-on-linux.patch
  app-network/mihomo-party/spec
Labels: upgrade, has-fix

#9906 solaar: add missing dependency to typing-extensions
  app-utils/solaar/autobuild/defines
  app-utils/solaar/spec
Labels: dependencies

#9909 vim: update to 9.1.1164
  app-editors/vim/spec
Labels: upgrade

#9911 yazi: update to 25.3.2
  app-utils/yazi/spec
Labels: upgrade

#9914 terminator: update to 2.1.4
  desktop-gnome/terminator/spec
Labels: upgrade

#9915 blueman: update to 2.4.4
  app-utils/blueman/spec
Labels: upgrade

#9925 abbs-update-checksum: update to 0.4.0
  app-devel/abbs-update-checksum/spec
Labels: upgrade

#9924 sarasa-gothic-fonts: update to 1.0.29
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#9922 iosevka-fonts: update to 33.0.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#9930 deb-installer: update to 0.1.6
  app-admin/deb-installer/spec
Labels: upgrade

#9931 liblol: update to 0.1.9
  runtime-emulation/liblol/autobuild/build
  runtime-emulation/liblol/autobuild/patches/glibc/0001-add-old-world-abi-compatibility.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0002-add-sigset-ops.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0003-add-signal-functions.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0004-add-sigaction-ucontext-compat.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0005-add-stubs-for-signal-related-io-funcs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0006-add-syscall-fallback-for-stat-at.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0007-add-more-pthread-symbols.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0008-remove-clone3-for-compatibility-with-qq.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0009-prepend-trusted-dirs.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0010-Add-___brk_addr-symbol.patch
  runtime-emulation/liblol/autobuild/patches/glibc/0011-siglist-errlist-add-compact-statements.patch
  runtime-emulation/liblol/genspec
  runtime-emulation/liblol/manifest
  runtime-emulation/liblol/spec
  runtime-emulation/liblol/spec.main
Labels: upgrade

#9929 mihomo-party: update to 1.7.2
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0002-Remove-check-update-UI.patch
  app-network/mihomo-party/autobuild/patches/0003-Remove-upgrade-mihomo-UI.patch
  app-network/mihomo-party/autobuild/patches/0004-Do-not-fetch-Mihomo-Clash-Meta-binaries.patch
  app-network/mihomo-party/autobuild/patches/0005-Do-not-find-Mihomo-Clash-Meta-binary-in-sidecar-dir.patch
  app-network/mihomo-party/autobuild/patches/0006-Remove-check-update-feature.patch
  app-network/mihomo-party/autobuild/patches/0007-fix-update-sub-store-on-linux.patch
  app-network/mihomo-party/spec
Labels: upgrade

#9932 synaptic: update to 0.91.5+nmu2
  app-admin/synaptic/spec
Labels: upgrade

#9927 vpl-gpu-rt: update to 25.1.3
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#9923 racket: update to 8.16
  lang-lisp/racket/autobuild/defines
  lang-lisp/racket/spec
Labels: upgrade

#9935 fastfetch: update to 2.38.0
  app-utils/fastfetch/spec
Labels: upgrade

#9936 dust: update to 1.1.2
  app-utils/dust/spec
Labels: upgrade

#9937 tmux: update to 3.5a
  app-utils/tmux/spec
Labels: upgrade

#9938 z3: update to 4.14.0
  app-devel/z3/spec
Labels: upgrade

#9939 zola: update to 0.20.0
  app-web/zola/spec
Labels: upgrade

#9949 ciel: update to 3.9.6
  app-devel/ciel/spec
Labels: upgrade

#9950 ab-download-manager:update to 1.5.3
  app-web/ab-download-manager/autobuild/build
  app-web/ab-download-manager/autobuild/defines
  app-web/ab-download-manager/autobuild/overrides/usr/share/applications/abdownloadmanager.desktop
  app-web/ab-download-manager/spec
Labels: upgrade

#9955 stress-ng: update to 0.18.11
  app-benchmarks/stress-ng/spec
Labels: upgrade

#9956 grub-loongson3: drop, orphaned
  app-admin/grub-loongson3/autobuild/build
  app-admin/grub-loongson3/autobuild/conffiles
  app-admin/grub-loongson3/autobuild/defines
  app-admin/grub-loongson3/autobuild/overrides/etc/default/grub
  app-admin/grub-loongson3/autobuild/overrides/etc/grub.d/10_linux
  app-admin/grub-loongson3/autobuild/overrides/usr/bin/update-grub
  app-admin/grub-loongson3/spec
Labels: drop-package

#9958 deb-installer: update to 0.1.7
  app-admin/deb-installer/spec
Labels: upgrade

#9964 dunst: update to 1.12.2
  app-utils/dunst/spec
Labels: upgrade

#9963 fcft: update to 3.2.0
  runtime-display/fcft/spec
Labels: upgrade

#9968 waydroid: update to 1.5.0
  app-emulation/waydroid/spec
Labels: upgrade

#9971 bash-startup: update to 0.7.0
  runtime-data/bash-startup/spec
Labels: upgrade

#9972 tailscale: update to 1.80.3
  app-network/tailscale/spec
Labels: upgrade

#9943 uv: update to 0.6.4
  lang-python/uv/spec
Labels: upgrade

#9962 llama.cpp: update to 4827
  runtime-creativity/llama.cpp/autobuild/patches/0001-AOSCOS-add-system-backend-path.patch
  runtime-creativity/llama.cpp/spec
Labels: upgrade

#9975 deb-installer: update to 0.1.8
  app-admin/deb-installer/spec
Labels: upgrade

#9976 unifont: update to 16.0.02
  desktop-fonts/unifont/spec
Labels: upgrade

#9982 pipewire: update to 1.4.0
  app-multimedia/pipewire/spec
Labels: upgrade

#9984 winetricks: update to 20250102
  app-emulation/winetricks/spec
Labels: upgrade

#9986 meson: update to 1.7.0
  app-devel/meson/spec
Labels: upgrade

#9989 bitwarden: update to 2025.2.1
  app-utils/bitwarden/spec
Labels: upgrade

#9988 reptyr: update to 0.10.0
  app-utils/reptyr/autobuild/build
  app-utils/reptyr/autobuild/defines
  app-utils/reptyr/autobuild/prepare
  app-utils/reptyr/spec
Labels: upgrade

#9991 zed: update to 0.176.3
  app-editors/zed/spec
Labels: upgrade

#9994 osu-lazer: update to 2025.306.0
  app-games/osu-lazer/spec
Labels: upgrade

#9996 inxi: update to 3.3.37+1
  app-utils/inxi/autobuild/build
  app-utils/inxi/autobuild/defines
  app-utils/inxi/spec
Labels: upgrade

#9998 bluez: update to 5.79
  app-devices/bluez/spec
Labels: upgrade

#9999 vim: update to 9.1.1179
  app-editors/vim/spec
Labels: upgrade

#10002 glib: update to 2.84.0
  runtime-common/glib/spec
Labels: upgrade

#10005 zoxide: update to 0.9.7
  app-utils/zoxide/spec
Labels: upgrade

#10013 autobuild4: update to 4.7.14
  app-devel/autobuild4/spec
Labels: upgrade

#10009 ddcutil: update to 2.2.0
  app-utils/ddcutil/autobuild/defines
  app-utils/ddcutil/autobuild/patches/0001-base-fix-shadow-build.patch
  app-utils/ddcutil/spec
Labels: upgrade

#9992 thunderbird: update to 136.0
  app-web/thunderbird/autobuild/mozconfig
  app-web/thunderbird/autobuild/patches/0001-FEDORA-0001-GLIBCXX-fix-for-GCC-12.patch.patch
  app-web/thunderbird/autobuild/patches/0001-UPSTREAM-Bug-1905842-set-patch-application-order-for.patch
  app-web/thunderbird/autobuild/patches/0002-FEDORA-expat-CVE-2022-25235.patch.patch
  app-web/thunderbird/autobuild/patches/0002-UPSTREAM-Bug-1905842-add-patch-for-NEON64-and-SVE-gy.patch
  app-web/thunderbird/autobuild/patches/0003-FEDORA-expat-CVE-2022-25236.patch.patch
  app-web/thunderbird/autobuild/patches/0003-UPSTREAM-Bug-1905842-add-dotprod-and-SVE-CPU-config-.patch
  app-web/thunderbird/autobuild/patches/0004-FEDORA-expat-CVE-2022-25315.patch.patch
  app-web/thunderbird/autobuild/patches/0004-UPSTREAM-Bug-1905842-non-unified-build-scale_uv.cc-d.patch
  app-web/thunderbird/autobuild/patches/0005-BACKPORT-LOONGARCHLINUX-Add-support-for-LoongArch64.patch
  app-web/thunderbird/autobuild/patches/0005-UPSTREAM-Bug-1905842-update-libyuv-to-616bee5420b-r-.patch
  app-web/thunderbird/autobuild/patches/0006-AOSCOS-comm-botan-add-loongarch64-to-archinfo.patch
  app-web/thunderbird/autobuild/patches/0006-UPSTREAM-Bug-1905842-update-libyuv-to-616bee5420b-ap.patch
  app-web/thunderbird/autobuild/patches/0007-AOSCOS-Build-Loongson-SIMD-EXtension-LSX-and-Loongso.patch
  app-web/thunderbird/autobuild/patches/0007-BACKPORT-Bug-1855960-MIPS64-Make-some-assembler-rout.patch
  app-web/thunderbird/autobuild/patches/0008-WIP-AOSCOS-fix-xptcall-riscv-linker-issue.patch
  app-web/thunderbird/autobuild/patches/0009-BACKPORT-Bug-1948198-Fix-missing-loongarch-subdir-in.patch
  app-web/thunderbird/autobuild/patches/0010-BACKPORT-Bug-1948198-Enable-LSX-for-libpng-on-LoongA.patch
  app-web/thunderbird/autobuild/patches/0013-AOSCOS-Implement-SummarizeTrapInstruction-for-MIPS64.patch
  app-web/thunderbird/autobuild/patches/0018-WIP-AOSCOS-Keep-unsigned-32-bit-parameter-sign-exten.patch
  app-web/thunderbird/autobuild/prepare
  app-web/thunderbird/spec
Labels: upgrade

#9995 oma: update to 1.15.0
  app-admin/oma/spec
Labels: upgrade

#10022 obs-studio: update to 31.0.2
  app-multimedia/obs-studio/spec
Labels: upgrade

#10020 typst: update to 0.13.1
  app-doc/typst/spec
Labels: upgrade

#10018 qpwgraph: update to 0.8.2
  app-multimedia/qpwgraph/spec
Labels: upgrade

#10017 gnupg: update to 2.5.5
  app-cryptography/gnupg/spec
Labels: upgrade

#9979 xray: update to 25.3.6
  app-network/xray/autobuild/beyond
  app-network/xray/autobuild/build
  app-network/xray/autobuild/defines
  app-network/xray/autobuild/prepare
  app-network/xray/spec
Labels: upgrade

#10006 supercollider: new: 3.13.0
  app-creativity/supercollider/autobuild/defines
  app-creativity/supercollider/spec
Labels: new-package

#10019 telegram-desktop: update to 5.12.1
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-fix-current_geo_location_linux-add-missing-QGuiAppli.patch
  app-web/telegram-desktop/autobuild/patches/0010-fix-integration_linux-include-core_settings.h-with-Q.patch
  app-web/telegram-desktop/autobuild/patches/1001-tg_owt_Patch-Fix-build-with-PipeWire-1.4.patch.deferred
  app-web/telegram-desktop/autobuild/prepare
  app-web/telegram-desktop/spec
Labels: upgrade

#10021 wine: update to 10.3+gecko2.47.4+mono9.4.0
  app-emulation/wine/autobuild/build
  app-emulation/wine/autobuild/defines
  app-emulation/wine/spec
Labels: upgrade

#10008 font-manager: update to 0.9.4
  app-utils/font-manager/spec
Labels: upgrade

#10023 libidn2: update to 2.3.8
  runtime-network/libidn2/spec
Labels: upgrade

#10034 texlive: update to 20250308
  app-doc/texlive/spec
Labels: upgrade

#10037 osu-lazer: update to 2025.310.0
  app-games/osu-lazer/spec
Labels: upgrade

#10024 weston: update to 14.0.1
  runtime-display/weston/autobuild/patches/0001-vnc-Allow-neatvnc-in-version-0.9.0.patch
  runtime-display/weston/spec
Labels: upgrade

#10033 fcitx5-pinyin-moegirl: update to 20250309
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#10035 lfortran: update to 0.47.0
  app-devel/lfortran/spec
Labels: upgrade

#10039 cpu-x: update to 5.1.3
  app-utils/cpu-x/spec
Labels: upgrade

#10040 feishin: update to 0.12.3
  app-multimedia/feishin/spec
Labels: upgrade

#10038 bash-startup: Update to 0.7.1
  runtime-data/bash-startup/spec
Labels: upgrade

#10045 telegram-desktop: update to 5.12.3
  app-web/telegram-desktop/autobuild/patches/0010-fix-integration_linux-include-core_settings.h-with-Q.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#10041 htop: update to 3.4.0
  app-admin/htop/autobuild/patches/0001-remove-dev-version.patch
  app-admin/htop/spec
Labels: upgrade

#10003 uv: update to 0.6.5
  lang-python/uv/spec
Labels: upgrade

#10044 pyproject-metadata: update to 0.9.1
  lang-python/pyproject-metadata/spec
Labels: upgrade

#10048 vscode: update to 1.98.1
  app-editors/vscode/spec
Labels: upgrade

#10050 z3: update to 4.14.1
  app-devel/z3/spec
Labels: upgrade

#10011 Hugin 2024.0.1
  app-creativity/hugin/spec
Labels: upgrade, abi-break

#10046 lfortran: fix oom erros when building on loongson3
  app-devel/lfortran/autobuild/defines
  app-devel/lfortran/spec
Labels: has-fix

#10051 lxc: Add Apparmor support
  app-admin/lxc/autobuild/defines
  app-admin/lxc/spec
Labels: enhancement

#10054 sing-box: update to 1.11.5
  app-network/sing-box/spec
Labels: upgrade

#10060 fcft: update to 3.3.0
  runtime-display/fcft/spec
Labels: upgrade

#10059 ab-download-manager: update to 1.5.4
  app-web/ab-download-manager/spec
Labels: upgrade

#10061 vim: update to 9.1.1198
  app-editors/vim/spec
Labels: upgrade

#9961 sbcl: update to 2.5.2
  app-scientific/fricas/spec
  app-scientific/maxima/spec
  lang-lisp/sbcl/autobuild/defines
  lang-lisp/sbcl/autobuild/defines.stage2
  lang-lisp/sbcl/spec
Labels: upgrade

#10063 llama.cpp: update to 4879
  runtime-creativity/llama.cpp/autobuild/patches/0001-AOSCOS-add-system-backend-path.patch
  runtime-creativity/llama.cpp/spec
Labels: upgrade

#9973 keepassxc: update to 2.7.10
  app-utils/keepassxc/spec
Labels: upgrade

#10036 v2raya: update to 2.2.6.6
  app-network/v2raya/spec
Labels: upgrade

#10065 uv: update to 0.6.6
  lang-python/uv/spec
Labels: upgrade

#10064 zed: update to 0.177.7
  app-editors/zed/spec
Labels: upgrade

#10067 dua: update to 2.30.0
  app-utils/dua/spec
Labels: upgrade

#10069 lychee: update to 0.18.1
  app-web/lychee/spec
Labels: upgrade

#10072 fish: update to 4.0.1
  app-shells/fish/spec
Labels: upgrade

#10075 fcft: update to 3.3.1
  runtime-display/fcft/spec
Labels: upgrade

#10078 bottom: update to 0.10.2
  app-admin/bottom/spec
Labels: upgrade

#10079 chafa: update to 1.14.5
  app-utils/chafa/spec
Labels: upgrade

#10080 conky: update to 1.22.0
  app-utils/conky/spec
Labels: upgrade

#10081 debconf: update to 1.5.91
  app-admin/debconf/spec
Labels: upgrade

#10083 eza: update to 0.20.24
  app-utils/eza/spec
Labels: upgrade

#10084 fnm: update to 1.38.1
  lang-js/fnm/spec
Labels: upgrade

#10085 gitui: update to 0.27.0
  app-utils/gitui/spec
Labels: upgrade

#10086 miniserve: update to 0.29.0
  app-web/miniserve/spec
Labels: upgrade

#10087 mold: update to 2.37.1
  app-devel/mold/spec
Labels: upgrade

#10088 mcfly: update to 0.9.3
  app-utils/mcfly/spec
Labels: upgrade

#10091 yq: update to 4.45.1
  app-devel/yq/spec
Labels: upgrade

#10071 rpi-firmware-boot: update to 1.20250305
  runtime-kernel/rpi-firmware-boot/spec
Labels: upgrade

#10098 lazygit: update to 0.48.0
  app-vcs/lazygit/spec
Labels: upgrade

#10107 aoscbootstrap: update to 0.8.3
  app-utils/aoscbootstrap/spec
Labels: upgrade

#10076 zotero: update to 7.0.14
  app-productivity/zotero/spec
Labels: upgrade

#10109 expat: update to 2.7.0
  runtime-common/expat/spec
Labels: upgrade, security, has-fix

#10108 pipewire: update to 1.4.1
  app-multimedia/pipewire/spec
Labels: upgrade

#10096 syncthing: update to 1.29.3
  app-network/syncthing/spec
Labels: upgrade

#10115 wsl-default-settings: fix useradd parameters
  runtime-data/wsl-default-settings/autobuild/overrides/usr/share/wsl/wsl-oobe.sh
  runtime-data/wsl-default-settings/spec
Labels: has-fix

#10092 git-absorb: update to 0.7.0
  app-devel/git-absorb/spec
Labels: upgrade

#10105 dnscontrol: update to 4.17.0
  app-network/dnscontrol/spec
Labels: upgrade

#10101 hugo: update to 0.145.0
  app-web/hugo/spec
Labels: upgrade

#10094 typos: update to 1.30.2
  app-utils/typos/spec
Labels: upgrade

#10093 just: update to 1.40.0
  app-devel/just/spec
Labels: upgrade

#10112 php: update to 8.4.5
  app-devel/php/spec
Labels: upgrade, security

#10089 zed: update to 0.177.8
  app-editors/zed/spec
Labels: upgrade

#10114 ipython: update to 8.32.0
  lang-python/ipython/spec
Labels: upgrade

#10118 libshumate: update to 1.4.0
  desktop-gnome/libshumate/spec
Labels: upgrade

#10117 xiaohuixiangqi: new, 0.1.1
  app-games/xiaohuixiangqi/autobuild/defines
  app-games/xiaohuixiangqi/spec
Labels: new-package

#10104 renderdoc: update to 1.37
  app-devel/renderdoc/spec
Labels: upgrade

#10053 melonds: update to 1.0~rc
  app-games/melonds/autobuild/defines
  app-games/melonds/autobuild/patches/0001-fix-CMakeLists.txt-do-not-strip-during-install-time.patch
  app-games/melonds/spec
Labels: upgrade

#10122 osu-lazer: update to 2025.316.0
  app-games/osu-lazer/spec
Labels: upgrade

#10121 iosevka-fonts: update to 33.1.0
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#10123 zotero: update to 7.0.15
  app-productivity/zotero/spec
Labels: upgrade

#10124 man-pages: update to 6.13+posix2017a
  runtime-data/man-pages/autobuild/build
  runtime-data/man-pages/spec
Labels: upgrade

#10126 mako-notification-daemon: update to 1.10.0
  app-utils/mako-notification-daemon/spec
Labels: upgrade

#9897 llvm-20: new, 20.1.0
  app-devel/llvm-20/01-runtime/build
  app-devel/llvm-20/01-runtime/build.stage2
  app-devel/llvm-20/01-runtime/defines
  app-devel/llvm-20/01-runtime/defines.stage2
  app-devel/llvm-20/01-runtime/patch
  app-devel/llvm-20/01-runtime/patches/0001-Fix-fuzzer-objects-building-when-LTO-is-enabled.patch
  app-devel/llvm-20/01-runtime/patches/0002-Fix-MSVC-detection.patch
  app-devel/llvm-20/01-runtime/patches/0003-Add-stub-for-mips64-LLDB-impl.patch
  app-devel/llvm-20/01-runtime/patches/0004-Add-stub-for-lldb-arch-functions-on-loongson3.patch
  app-devel/llvm-20/01-runtime/patches/0005-HACK-force-enable-cacheflush-function.patch
  app-devel/llvm-20/01-runtime/patches/0006-Fix-build-of-LinuxSignals-on-Mips.patch
  app-devel/llvm-20/01-runtime/patches/0007-Compile-with-MT-on-MSVC.patch
  app-devel/llvm-20/01-runtime/patches/0008-rust-Changes-needed-for-x86_64-fortanix-unknown-sgx-.patch
  app-devel/llvm-20/02-compiler/beyond
  app-devel/llvm-20/02-compiler/build
  app-devel/llvm-20/02-compiler/build.stage2
  app-devel/llvm-20/02-compiler/defines
  app-devel/llvm-20/02-compiler/defines.stage2
  app-devel/llvm-20/spec
Labels: new-package

#9957 zig: update to 0.14.0
  lang-ziglang/zig/autobuild/defines
  lang-ziglang/zig/autobuild/patches/0001-build-allow-overriding-RSS-limit-for-zig-binary-manu.patch
  lang-ziglang/zig/autobuild/patches/0001-enable-build-id-tagging.patch
  lang-ziglang/zig/spec
Labels: upgrade

#10130 intel-gpu-tools: update to 2.0
  app-admin/intel-gpu-tools/spec
Labels: upgrade

#10127 maple-font: update to 7.0
  desktop-fonts/maple-font/autobuild/build
  desktop-fonts/maple-font/autobuild/defines
  desktop-fonts/maple-font/spec
Labels: upgrade

#10116 taskwarrior: update to 3.4.1
  app-productivity/taskwarrior/autobuild/prepare
  app-productivity/taskwarrior/spec
Labels: upgrade, ftbfs

#10134 nvtop: update to 3.1.0+git20250220
  app-admin/nvtop/autobuild/defines
  app-admin/nvtop/spec
Labels: upgrade

#10142 foot: update to 1.21.0
  app-utils/foot/spec
Labels: upgrade

#10143 zellij: update to 0.42.0
  app-utils/zellij/autobuild/beyond
  app-utils/zellij/autobuild/defines
  app-utils/zellij/autobuild/patches/0001-chore-update-wasmtime-to-30.0.2.patch
  app-utils/zellij/autobuild/patches/0002-chore-update-nix-to-0.27-to-support-loongarch64.patch
  app-utils/zellij/spec
Labels: upgrade

#10138 wsl-default-settings: ask the user to set password
  runtime-data/wsl-default-settings/autobuild/overrides/usr/share/wsl/wsl-oobe.sh
  runtime-data/wsl-default-settings/spec
Labels: bug

#10146 libdatachannel: update to 0.22.6
  runtime-multimedia/libdatachannel/spec
Labels: upgrade

#10147 aoscbootstrap: update to 0.8.4
  app-utils/aoscbootstrap/spec
Labels: upgrade

#10152 wsl-default-settings: fix shell script syntax
  runtime-data/wsl-default-settings/autobuild/overrides/usr/share/wsl/wsl-oobe.sh
  runtime-data/wsl-default-settings/spec
Labels: has-fix

#10149 aoscbootstrap: update to 0.8.5
  app-utils/aoscbootstrap/spec
Labels: upgrade

#10155 shadowsocks-rust: update to 1.23.0
  app-network/shadowsocks-rust/spec
Labels: upgrade

#10160 uv: update to 0.6.8
  lang-python/uv/spec
Labels: upgrade

#10141 desktop-base: add recommend dep liberation-fonts
  meta-bases/desktop-base/autobuild/defines
  meta-bases/desktop-base/spec
Labels: dependencies
