Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-10, with the labels that each got.

#12787 fish: update to 4.1.1
  app-shells/fish/spec
Labels: upgrade

#12785 copyq: update to 12.0.1
  app-utils/copyq/autobuild/defines
  app-utils/copyq/spec
Labels: upgrade

#12782 presenterm: update to 0.15.1
  app-productivity/presenterm/autobuild/defines
  app-productivity/presenterm/spec
Labels: upgrade

#12783 shotwell: update to 0.32.13
  desktop-gnome/shotwell/autobuild/defines
  desktop-gnome/shotwell/spec
Labels: upgrade

#12800 autobuild4: update to 4.12.11
  app-devel/autobuild4/spec
Labels: upgrade

#12814 srecord: update to 1.65.0
  app-utils/srecord/autobuild/beyond
  app-utils/srecord/autobuild/defines
  app-utils/srecord/autobuild/patches/0001-Allow-CMAKE_INSTALL_PREFIX-to-be-set-externally.patch
  app-utils/srecord/autobuild/patches/0002-Allow-disable-Doxygen-doc.patch
  app-utils/srecord/autobuild/patches/0003-lib_srecord-build-as-shared-library.patch
  app-utils/srecord/autobuild/patches/0004-Allow-disable-install-runtime-dependancies.patch
  app-utils/srecord/spec
Labels: upgrade

#12775 thunderbird: update to 143.0.1
  app-web/thunderbird/autobuild/patches/0001-AOSCOS-comm-botan-add-loongarch64-to-archinfo.patch
  app-web/thunderbird/autobuild/patches/0002-WIP-AOSCOS-fix-xptcall-riscv-linker-issue.patch
  app-web/thunderbird/autobuild/patches/0003-AOSCOS-rust-allocator-api2-remove-an-autoref-warning.patch
  app-web/thunderbird/autobuild/patches/0004-Bug-1984978-Part-1-Implement-Add-Sub-Mul-Shift-IntPt.patch
  app-web/thunderbird/autobuild/patches/0005-Bug-1984978-Part-2-Implement-Add-Sub-Mul-Shift-IntPt.patch
  app-web/thunderbird/autobuild/patches/0006-Bug-1984978-Part-3-Remove-unnecessary-and-instructio.patch
  app-web/thunderbird/autobuild/patches/0007-Bug-1985581-Update-shift-instruction-codegen-to-use-.patch
  app-web/thunderbird/autobuild/patches/0008-Enable-GLES-on-riscv64.patch
  app-web/thunderbird/spec
Labels: upgrade, has-fix

#12827 vscode: update to 1.104.3
  app-editors/vscode/spec
Labels: upgrade

#12833 dive: rework for PKGDES
  app-utils/dive/autobuild/defines
  app-utils/dive/spec
Labels: rework

#12835 fwupd-efi: update to 1.8
  app-admin/fwupd-efi/autobuild/patches/0001-Fix-build-error-of-LoongArch-in-gnu-efi-3.0.18.patch
  app-admin/fwupd-efi/spec
Labels: upgrade

#12826 scons: update to 4.10.0
  app-devel/scons/spec
Labels: upgrade

#12746 libunistring: update to 1.4
  runtime-common/libunistring/spec
Labels: upgrade

#12857 syslinux: fix build
  app-admin/syslinux/autobuild/beyond
  app-admin/syslinux/autobuild/build
  app-admin/syslinux/autobuild/defines
  app-admin/syslinux/autobuild/patches/0001-Add-install-all-target-to-top-side-of-HAVE_FIRMWARE.patch
  app-admin/syslinux/autobuild/patches/0001-ext4-Fix-64bit-feature.patch
  app-admin/syslinux/autobuild/patches/0002-extlinux-pull-in-sys-sysmacros.h-for-major-minor-mak.patch
  app-admin/syslinux/autobuild/patches/0003-Workaround-multiple-definition-of-symbol-errors.patch
  app-admin/syslinux/autobuild/patches/0004-Add-RPMOPTFLAGS-to-CFLAGS-for-some-stuff.patch
  app-admin/syslinux/autobuild/patches/0004-Replace-builtin-strlen-that-appears-to-get-optimized.patch
  app-admin/syslinux/autobuild/patches/0005-Fix-build-with-GCC-14.patch
  app-admin/syslinux/autobuild/prepare
  app-admin/syslinux/spec
Labels: has-fix

#12852 i7z: fix build errors
  app-utils/i7z/autobuild/patches/0004-Debian-use-stdbool.patch
  app-utils/i7z/autobuild/patches/0006-Debian-fix-cpuid-asm.patch
  app-utils/i7z/autobuild/patches/0007-Debian-nehalem.patch
  app-utils/i7z/autobuild/patches/0009-Debian-gcc-10.patch
  app-utils/i7z/spec
Labels: has-fix

#12848 firefox: update to 143.0.4
  app-web/firefox/spec
Labels: upgrade

#12854 typos: update to 1.37.2
  app-utils/typos/spec
Labels: upgrade

#12844 rosdistro: new 1.0.1
  app-devel/rosdistro/autobuild/defines
  app-devel/rosdistro/spec
Labels: new-package

#12862 v2ray-rules-dat: update to 202510042211
  runtime-data/v2ray-rules-dat/spec
Labels: upgrade

#12661 0ad: update to 0.27.1
  app-games/0ad/autobuild/build
  app-games/0ad/autobuild/defines
  app-games/0ad/autobuild/patches/0001-FROMLIST-Enable-building-on-arbitrary-architectures.patch
  app-games/0ad/autobuild/patches/0001-Fedora-0ad-debug.patch
  app-games/0ad/autobuild/patches/0002-FROMLIST-sysdep-coalesce-ppc64-be-into-generic.patch
  app-games/0ad/autobuild/patches/0005-Fedora-0ad-rust.patch
  app-games/0ad/autobuild/patches/0006-allow-build-with-root.patch
  app-games/0ad/autobuild/patches/0007-fix-altivec-gcc10.patch
  app-games/0ad/autobuild/patches/0008-add-missing-header-gcc-13.patch
  app-games/0ad/autobuild/patches/0009-fix-implicit-conversions-in-libfmt-10.patch
  app-games/0ad/autobuild/patches/1000-remove-broken-patches.patch
  app-games/0ad/autobuild/prepare
  app-games/0ad/spec
Labels: upgrade

#12838 lark-parser: new, 6.5.2
  lang-python/lark-parser/autobuild/defines
  lang-python/lark-parser/spec
Labels: new-package

#12863 numix-icon-theme: update to 25.10.04.2
  desktop-themes/numix-icon-theme/spec
Labels: upgrade

#12867 localsend: rework
  app-network/localsend/autobuild/overrides/usr/share/applications/localsend.desktop
  app-network/localsend/spec
Labels: rework

#12869 ctags: update to 6.2.20251005.0
  app-devel/ctags/autobuild/defines
  app-devel/ctags/spec
Labels: upgrade

#12882 png++: fix build
  runtime-imaging/png++/autobuild/build
  runtime-imaging/png++/autobuild/defines
  runtime-imaging/png++/spec
Labels: has-fix

#12879 sing-box: update to 1.12.9
  app-proxy/sing-box/spec
Labels: upgrade

#12889 dialog: update to 1.3+20251001
  app-utils/dialog/spec
Labels: upgrade

#12865 ast-grep: update to 0.39.6
  app-devel/ast-grep/autobuild/beyond
  app-devel/ast-grep/spec
Labels: upgrade
