Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-04, with the labels that each got.

#10267 kicad: update to 9.0.1
  app-electronics/kicad/spec
Labels: upgrade

#10120 openrazer: update to 3.10.1
  app-devices/openrazer/spec
Labels: upgrade

#10125 digikam: update to 8.6.0
  desktop-kde/digikam/spec
Labels: upgrade

#10265 oma: improve dependency
  app-admin/oma/autobuild/defines
  app-admin/oma/autobuild/prepare
  app-admin/oma/spec
Labels: enhancement, dependencies

#10274 nushell: new, 0.103.0
  app-shells/nushell/autobuild/defines
  app-shells/nushell/autobuild/overrides/usr/share/pixmaps/nushell-logo.png
  app-shells/nushell/spec
Labels: new-package

#10258 containers-common: update to 0.62.3+image5.34.3+shortnames2025.03.19+skopeo1.18.0+storage1.57.2
  runtime-containers/containers-common/autobuild/defines
  runtime-containers/containers-common/spec
Labels: upgrade

#10264 elinks: update to 0.18.0
  app-web/elinks/autobuild/defines
  app-web/elinks/autobuild/patches/0001-Fix-Ruby-not-found-on-AOSC-OS.patch
  app-web/elinks/autobuild/patches/0002-guile.c-do-not-get-version.patch
  app-web/elinks/autobuild/patches/0003-ruby.c-include-ruby.h.patch
  app-web/elinks/autobuild/patches/0004-sixel-comment-out-ormode-as-it-is-not-implemented.patch
  app-web/elinks/autobuild/prepare
  app-web/elinks/spec
Labels: upgrade

#10285 osu-lazer: update to 2025.401.0
  app-games/osu-lazer/spec
Labels: upgrade

#10288 nvtop: update to 3.2.0
  app-admin/nvtop/spec
Labels: upgrade

#10272 scrcpy: update to 3.2
  app-devices/scrcpy/autobuild/defines
  app-devices/scrcpy/spec
Labels: upgrade

#10292 meson: update to 1.7.1
  app-devel/meson/spec
Labels: upgrade

#10286 uv: update to 0.6.11
  lang-python/uv/spec
Labels: upgrade

#10295 gn: update to 0+git20250311
  app-devel/gn/spec
Labels: upgrade

#10296 libvips: update to 8.16.1
  runtime-imaging/libvips/autobuild/defines
  runtime-imaging/libvips/spec
Labels: enhancement, upgrade

#10294 dust: update to 1.2.0
  app-utils/dust/spec
Labels: upgrade

#10307 eza: update to 0.21.0
  app-utils/eza/spec
Labels: upgrade

#10314 tauri-cli: update to 2.4.1
  lang-rust/tauri-cli/spec
Labels: upgrade

#10312 fastfetch: update to 2.40.0
  app-utils/fastfetch/spec
Labels: upgrade

#10311 osu-lazer: update to 2025.403.0
  app-games/osu-lazer/spec
Labels: upgrade

#10321 xz: update to 5.8.1
  app-utils/xz/spec
Labels: upgrade, security

#10318 syncthing: update to 1.29.4
  app-network/syncthing/spec
Labels: upgrade

#10316 dnscontrol: update to 4.18.0
  app-network/dnscontrol/spec
Labels: upgrade

#10317 typos: update to 1.31.1
  app-utils/typos/spec
Labels: upgrade

#10319 llvm-20: update to 20.1.2
  app-devel/llvm-20/spec
Labels: upgrade

#10323 fastfetch: update to 2.40.1
  app-utils/fastfetch/spec
Labels: upgrade

#10324 libevdev: update to 1.13.4
  runtime-devices/libevdev/spec
Labels: upgrade

#10331 vscode: update to 1.99.0
  app-editors/vscode/spec
Labels: upgrade

#10339 fastfetch: update to 2.40.3
  app-utils/fastfetch/spec
Labels: upgrade

#10333 meson: update to 1.7.2
  app-devel/meson/spec
Labels: upgrade

#10326 bitwarden: update to 2025.3.0
  app-utils/bitwarden/autobuild/patches/0001-napi-prefer-glibc-instead-of-musl-libc.patch
  app-utils/bitwarden/autobuild/patches/0002-napi-enable-lto.patch
  app-utils/bitwarden/spec
Labels: upgrade

#10340 linux-kernel: add TUM for 6.14.0-2
  topics/linux-kernel-6.14.toml
Labels: kernel

#10330 zed: update to 0.180.2
  app-editors/zed/spec
Labels: upgrade

#10329 ast-grep: update to 0.36.2
  app-devel/ast-grep/autobuild/patches/0001-Do-not-compile-sg-binary.patch
  app-devel/ast-grep/spec
Labels: upgrade

#10332 uv: update to 0.6.12
  lang-python/uv/spec
Labels: upgrade

#10342 topics: rework linux-kernel-6.14.0.toml
  topics/linux-kernel-6.14.toml
Labels: rework, kernel

#10305 nano: update to 8.4+nanorc2024.1.16
  app-editors/nano/spec
Labels: upgrade

#10328 pyqt5-sip: update to 12.17.0
  lang-python/pyqt5-sip/spec
Labels: upgrade

#10344 spek-x: new, 0.9.4
  app-multimedia/spek-x/autobuild/defines
  app-multimedia/spek-x/spec
Labels: new-package

#10349 gawk: update to 5.3.2
  app-utils/gawk/spec
Labels: upgrade

#10327 gdal: add libavif dependency
  runtime-gis/gdal/autobuild/defines
  runtime-gis/gdal/spec
Labels: dependencies

#10347 wine: update to 10.5+gecko2.47.4+mono10.0.0
  app-emulation/wine/spec
Labels: upgrade

#10354 prismlauncher: update to 9.3
  app-games/prismlauncher/spec
Labels: upgrade

#10356 TUM schema update: add `must_match_all` top-level attribute
  topics/tum.schema.json
Labels: upgrade

#10271 calibre: update to 8.1.1
  app-doc/calibre/autobuild/patches/0001-skip-update-checker.patch
  app-doc/calibre/autobuild/patches/0002-don-t-create-uninstaller-adjust-desktop-file.patch
  app-doc/calibre/spec
Labels: upgrade

#10360 acbs: update to 20250407
  app-devel/acbs/spec
Labels: upgrade

#10350 rustc: update to 1.86.0
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/spec
Labels: upgrade

#10359 inkscape: update to 1.4.1
  app-creativity/inkscape/autobuild/patches/0001-Fix-building-with-poppler-24.12.0.patch
  app-creativity/inkscape/autobuild/patches/0002-Future-proof-against-poppler-24.10-changes.patch
  app-creativity/inkscape/autobuild/patches/0003-Fix-building-with-Poppler-24.11.patch
  app-creativity/inkscape/autobuild/patches/0004-Fix-building-with-poppler-25.02.0.patch
  app-creativity/inkscape/spec
Labels: upgrade

#10361 oma: update to 1.15.2
  app-admin/oma/spec
Labels: upgrade

#10364 breeze-icons: backport to fix telegram-desktop icon names
  desktop-kde/breeze-icons/autobuild/patches/0002-Add-symbolic-links-for-telegram-desktop-new-icon-names.patch
  desktop-kde/breeze-icons/spec
Labels: noarch

#10358 gnuplot: update to 6.0.2
  app-utils/gnuplot/spec
Labels: upgrade

#10366 gperf: update to 3.2
  app-utils/gperf/spec
Labels: upgrade

#10337 vscodium: update to 1.99.02277
  app-editors/vscodium/autobuild/patches/0001-AOSCOS-add-microsoft-vscode-240054.patch
  app-editors/vscodium/spec
Labels: upgrade

#10368 prismlauncher: update to 9.4
  app-games/prismlauncher/spec
Labels: upgrade

#10363 vpl-gpu-rt: update to 25.2.0
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#10365 rclone: update to 1.69.1
  app-web/rclone/autobuild/defines
  app-web/rclone/autobuild/patches/0001-go.mod-update-hanwen-go-fuse-v2-for-fixing-mips64el-.patch.loongson3
  app-web/rclone/autobuild/patches/0001-update-saferith-for-loongarch64.patch
  app-web/rclone/spec
Labels: upgrade

#10373 clash-verge-rev: fix copy geoip data to home dir
  app-network/clash-verge-rev/autobuild/patches/0001-feat-src-assets-add-XDG-.desktop-entry.patch
  app-network/clash-verge-rev/autobuild/patches/0002-fix-tauri.conf.json-disable-bundle-distribution.patch
  app-network/clash-verge-rev/autobuild/patches/0003-fix-scripts-use-ABI2-New-World-Mihomo-binary-for-loo.patch
  app-network/clash-verge-rev/autobuild/patches/0004-feat-drop-clash-meta-alpha-support.patch
  app-network/clash-verge-rev/autobuild/patches/0005-fix-check.mjs-do-not-fetch-Mihomo-Clash-Meta-binarie.patch
  app-network/clash-verge-rev/autobuild/patches/0006-fix-src-tauri-tauri.conf.json-disable-Mihomo-Clash-M.patch
  app-network/clash-verge-rev/autobuild/patches/0007-fix-check.mjs-do-not-check-Mihomo-Clash-Meta-platfor.patch
  app-network/clash-verge-rev/autobuild/patches/0008-Do-not-create-any-bundle-package.patch
  app-network/clash-verge-rev/autobuild/patches/0009-Drop-check-update-feature.patch
  app-network/clash-verge-rev/autobuild/patches/0010-Set-core-binary-name-as-mihomo.patch
  app-network/clash-verge-rev/autobuild/patches/0011-feat-always-not-portable.patch
  app-network/clash-verge-rev/autobuild/patches/0012-find-mihomo-from-PATH.patch
  app-network/clash-verge-rev/autobuild/patches/0013-Set-service-install-uninstall-script-path-to-usr-lib.patch
  app-network/clash-verge-rev/autobuild/patches/0014-Unset-all-release-profile.patch
  app-network/clash-verge-rev/autobuild/patches/0015-Do-not-use-gcc.patch
  app-network/clash-verge-rev/autobuild/patches/0016-Drop-Upgrade-core-button.patch
  app-network/clash-verge-rev/autobuild/patches/0017-ppc64el-Use-rollup-wasm-node-to-fix-build-on-POWER8.patch.ppc64el
  app-network/clash-verge-rev/autobuild/patches/0018-Do-not-sidecar-mihomo-program.patch
  app-network/clash-verge-rev/autobuild/patches/0019-Remove-check-config-step-from-init_config.patch
  app-network/clash-verge-rev/autobuild/patches/0020-Fix-if-mihomo-geoip-file-src_path-is-symlink.patch
  app-network/clash-verge-rev/spec
Labels: has-fix

#10370 firefox: update to 137.0.1
  app-web/firefox/spec
Labels: upgrade

#10372 hdf5: use cmake to build the package
  runtime-scientific/hdf5/autobuild/beyond
  runtime-scientific/hdf5/autobuild/defines
  runtime-scientific/hdf5/spec
Labels: enhancement

#10369 celluloid: update to 0.28
  app-multimedia/celluloid/spec
Labels: upgrade

#10385 adw-gtk3: update to 5.8
  desktop-themes/adw-gtk3/spec
Labels: upgrade

#10387 wayland-protocols: update to 1.43
  app-devel/wayland-protocols/spec
Labels: upgrade

#10386 ostree: move ostree.conf to /usr/lib/dracut/dracut.conf.d/
  app-admin/ostree/autobuild/beyond
  app-admin/ostree/autobuild/conffiles
  app-admin/ostree/spec
Labels: has-fix

#10383 uv: update to 0.6.13
  lang-python/uv/spec
Labels: upgrade

#10384 cups: update to 2.4.12
  app-admin/cups/spec
Labels: upgrade

#10393 yazi: update to 25.4.8
  app-utils/yazi/spec
Labels: upgrade

#10394 gitoxide: update to 0.42.0
  app-vcs/gitoxide/spec
Labels: upgrade

#10396 hdf5: fix path of HDF5_INSTALL_CMAKE_DIR
  runtime-scientific/hdf5/autobuild/defines
  runtime-scientific/hdf5/spec
Labels: has-fix

#10390 picard: update to 2.13.3
  app-multimedia/picard/spec
Labels: upgrade

#10395 zed: update to 0.180.4
  app-editors/zed/spec
Labels: upgrade

#10371 gnuplot: switch off parallel build
  app-utils/gnuplot/autobuild/defines
  app-utils/gnuplot/spec
Labels: has-fix

#10399 swww: new, 0.9.5
  app-utils/swww/autobuild/build
  app-utils/swww/autobuild/defines
  app-utils/swww/spec
Labels: new-package

#10406 fcitx5-pinyin-moegirl: update to 20250409
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#10402 fastfetch: update to 2.40.4
  app-utils/fastfetch/spec
Labels: upgrade

#10404 weechat: update to 4.6.1
  app-web/weechat/spec
Labels: upgrade

#10400 openssh: update to 10.0p1
  app-network/openssh/spec
Labels: upgrade

#10401 neovim: add missing deps (E432)
  app-editors/neovim/autobuild/defines
  app-editors/neovim/spec
Labels: dependencies

#10411 kose-font: update to 3.120
  desktop-fonts/kose-font/spec
Labels: upgrade

#10410 fwupd: update to 2.0.8
  app-admin/fwupd/spec
Labels: upgrade

#10409 coreutils: update to 9.7
  app-utils/coreutils/spec
Labels: upgrade

#10413 uv: update to 0.6.14
  lang-python/uv/spec
Labels: upgrade

#10403 mpd: update to 0.24.3
  app-multimedia/mpd/autobuild/defines
  app-multimedia/mpd/autobuild/patches/0001-Revert-lib-yajl-drop-yajl-prefix-from-include-paths.patch
  app-multimedia/mpd/autobuild/patches/0001-systemd-system-run-service-with-mpd-user.patch
  app-multimedia/mpd/spec
Labels: upgrade

#10421 fuzzel: update to 1.12.0
  app-utils/fuzzel/spec
Labels: upgrade

#10420 bitwarden: update to 2025.3.1
  app-utils/bitwarden/spec
Labels: upgrade

#10419 gzip: update to 1.14
  app-utils/gzip/spec
Labels: upgrade

#10422 grep: update to 3.12
  app-utils/grep/autobuild/defines
  app-utils/grep/spec
Labels: upgrade

#10423 htop: update to 3.4.1
  app-admin/htop/autobuild/patches/0001-remove-dev-version.patch
  app-admin/htop/spec
Labels: upgrade

#10353 u-boot-menu: revert changes for /boot/u-boot
  app-admin/u-boot-menu/autobuild/patches/0001-replace-linux-version-script-with-plain-shell-comman.patch
  app-admin/u-boot-menu/autobuild/patches/0002-fix-dtbs-path.patch
  app-admin/u-boot-menu/autobuild/patches/0003-customize-configuration-files.patch
  app-admin/u-boot-menu/autobuild/patches/0004-make-the-initrd-matching-pattern-suitable-for-AOSC-s.patch
  app-admin/u-boot-menu/autobuild/patches/0005-chore-use-boot-u-boot-as-the-boot-filesystem.patch
  app-admin/u-boot-menu/spec
Labels: hardware-support

#10418 wesnoth: update to 1.18.4
  app-games/wesnoth/autobuild/beyond
  app-games/wesnoth/autobuild/patches/0001-fix-build-with-boost-1.83.patch
  app-games/wesnoth/autobuild/patches/0001_change_wesnothd_file.patch
  app-games/wesnoth/spec
Labels: upgrade

#10397 gdal: update to 3.10.3
  runtime-gis/gdal/autobuild/defines
  runtime-gis/gdal/autobuild/patches/0001-Build-fix-build-against-Poppler-25.02.00.patch
  runtime-gis/gdal/spec
Labels: upgrade

#10427 hugo: update to 0.146.1
  app-web/hugo/spec
Labels: upgrade

#10432 hugo: update to 0.146.2
  app-web/hugo/spec
Labels: upgrade

#10426 qtcreator: update to 16.0.1
  app-devel/qtcreator/spec
Labels: upgrade

#10433 vscode: update to 1.99.2
  app-editors/vscode/spec
Labels: upgrade

#10436 clash-verge-rev: improve packaging for distribution
  app-network/clash-verge-rev/autobuild/patches/0001-feat-src-assets-add-XDG-.desktop-entry.patch
  app-network/clash-verge-rev/autobuild/patches/0002-fix-tauri.conf.json-disable-bundle-distribution.patch
  app-network/clash-verge-rev/autobuild/patches/0003-fix-scripts-use-ABI2-New-World-Mihomo-binary-for-loo.patch
  app-network/clash-verge-rev/autobuild/patches/0004-feat-drop-clash-meta-alpha-support.patch
  app-network/clash-verge-rev/autobuild/patches/0005-fix-check.mjs-do-not-fetch-Mihomo-Clash-Meta-binarie.patch
  app-network/clash-verge-rev/autobuild/patches/0006-fix-src-tauri-tauri.conf.json-disable-Mihomo-Clash-M.patch
  app-network/clash-verge-rev/autobuild/patches/0007-fix-check.mjs-do-not-check-Mihomo-Clash-Meta-platfor.patch
  app-network/clash-verge-rev/autobuild/patches/0008-Do-not-create-any-bundle-package.patch
  app-network/clash-verge-rev/autobuild/patches/0009-Drop-check-update-feature.patch
  app-network/clash-verge-rev/autobuild/patches/0010-Set-core-binary-name-as-mihomo.patch
  app-network/clash-verge-rev/autobuild/patches/0011-feat-always-not-portable.patch
  app-network/clash-verge-rev/autobuild/patches/0012-find-mihomo-from-PATH.patch
  app-network/clash-verge-rev/autobuild/patches/0013-Set-service-install-uninstall-script-path-to-usr-lib.patch
  app-network/clash-verge-rev/autobuild/patches/0014-Unset-all-release-profile.patch
  app-network/clash-verge-rev/autobuild/patches/0015-Do-not-use-gcc.patch
  app-network/clash-verge-rev/autobuild/patches/0016-Drop-Upgrade-core-button.patch
  app-network/clash-verge-rev/autobuild/patches/0017-ppc64el-Use-rollup-wasm-node-to-fix-build-on-POWER8.patch
  app-network/clash-verge-rev/autobuild/patches/0018-Do-not-sidecar-mihomo-program.patch
  app-network/clash-verge-rev/autobuild/patches/0019-Fix-if-mihomo-geoip-file-src_path-is-symlink.patch
  app-network/clash-verge-rev/autobuild/patches/0020-fix-components-drop-update-checker.patch
  app-network/clash-verge-rev/autobuild/patches/0021-fix-drop-Open-Core-Dir-function.patch
  app-network/clash-verge-rev/autobuild/patches/0022-fix-disable-GeoData-update.patch
  app-network/clash-verge-rev/spec
Labels: enhancement

#10435 vscodium: update to 1.99.22418
  app-editors/vscodium/autobuild/build
  app-editors/vscodium/autobuild/defines
  app-editors/vscodium/autobuild/patches/0001-fix-cli-add-an-option-to-use-system-Cargo-rustc.patch
  app-editors/vscodium/autobuild/patches/0002-fix-build_cli.sh-drop-hard-coded-cross-compiler-sett.patch
  app-editors/vscodium/spec
Labels: upgrade

#10429 mihomo-party: add loongarch64 support
  app-network/mihomo-party/autobuild/build
  app-network/mihomo-party/autobuild/defines
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0003-Remove-upgrade-mihomo-UI.patch
  app-network/mihomo-party/autobuild/patches/0004-Do-not-fetch-Mihomo-Clash-Meta-binaries.patch
  app-network/mihomo-party/autobuild/patches/0005-Do-not-find-Mihomo-Clash-Meta-binary-in-sidecar-dir.patch
  app-network/mihomo-party/autobuild/patches/0006-Remove-check-update-feature.patch
  app-network/mihomo-party/autobuild/patches/0007-Add-loong64-support.patch.loongarch64
  app-network/mihomo-party/spec
Labels: hardware-support

#10438 clash-verge-service: fix stop mihomo process
  app-network/clash-verge-service/autobuild/patches/0001-Read-clash-verge-service-path-from-env.patch
  app-network/clash-verge-service/autobuild/patches/0002-Remove-unnecessary-nix-and-libc-dependency.patch
  app-network/clash-verge-service/autobuild/patches/0003-Find-mihomo-process-not-verge-mihomo.patch
  app-network/clash-verge-service/spec
Labels: has-fix

#10144 rime-ice: new, 2024.12.12
  app-i18n/rime-ice/autobuild/build
  app-i18n/rime-ice/autobuild/defines
  app-i18n/rime-ice/spec
Labels: new-package

#10444 mihomo-party: use sidecar mihomo
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Add-loong64-support.patch.loongarch64
  app-network/mihomo-party/autobuild/patches/0002-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0003-Remove-upgrade-mihomo-UI.patch
  app-network/mihomo-party/autobuild/patches/0004-Do-not-fetch-Mihomo-Clash-Meta-binaries.patch
  app-network/mihomo-party/autobuild/patches/0005-Do-not-find-Mihomo-Clash-Meta-binary-in-sidecar-dir.patch
  app-network/mihomo-party/autobuild/patches/0006-Remove-check-update-feature.patch
  app-network/mihomo-party/spec
Labels: enhancement

#10449 syncthing: update to 1.29.5
  app-network/syncthing/spec
Labels: upgrade

#10451 git: fix perl modules install path
  app-vcs/git/01-git-core/beyond
  app-vcs/git/spec
Labels: has-fix

#10448 erofs-utils: new, 1.8.6
  app-admin/erofs-utils/autobuild/defines
  app-admin/erofs-utils/spec
Labels: new-package

#10445 renpy: fix figure and bypass system path writing
  runtime-games/renpy/autobuild/build
  runtime-games/renpy/autobuild/defines
  runtime-games/renpy/autobuild/patches/0002-system-dir-read-only-bypass.patch
  runtime-games/renpy/spec
Labels: has-fix

#10452 niri: fix wrong PKGSUG
  desktop-wm/niri/autobuild/defines
  desktop-wm/niri/spec
Labels: has-fix

#10457 admin-base: add erofs-utils
  meta-bases/admin-base/autobuild/defines
  meta-bases/admin-base/spec
Labels: enhancement

#10455 broadcom-wl: update to 6.30.223.271-7
  runtime-kernel/broadcom-wl/autobuild/dkms.conf.in
  runtime-kernel/broadcom-wl/autobuild/patches/019-linux614.patch
  runtime-kernel/broadcom-wl/spec
Labels: upgrade

#10442 mariadb: improve packaging
  app-database/mariadb/autobuild/defines
  app-database/mariadb/spec
Labels: enhancement

#10456 greetd-regreet: new, 0.2.0
  desktop-displaymanagers/greetd-regreet/autobuild/beyond
  desktop-displaymanagers/greetd-regreet/autobuild/defines
  desktop-displaymanagers/greetd-regreet/autobuild/postinst
  desktop-displaymanagers/greetd-regreet/spec
Labels: new-package

#10454 sarasa-gothic-fonts: update to 1.0.30
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#10453 iosevka-fonts: update to 33.2.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#10458 qutebrowser: update to 3.5.0
  app-web/qutebrowser/spec
Labels: upgrade

#10459 libfishsound: update to 1.0.1
  runtime-multimedia/libfishsound/autobuild/defines
  runtime-multimedia/libfishsound/spec
Labels: upgrade

#10461 mkvtoolnix: update to 91.0
  app-multimedia/mkvtoolnix/autobuild/build
  app-multimedia/mkvtoolnix/autobuild/defines
  app-multimedia/mkvtoolnix/spec
Labels: upgrade

#10464 kernel-base: add broadcom-wl as recommended dependency
  meta-bases/kernel-base/autobuild/build
  meta-bases/kernel-base/autobuild/defines
  meta-bases/kernel-base/spec
Labels: dependencies

#10470 yambar: new, 1.11.0
  app-utils/yambar/autobuild/defines
  app-utils/yambar/spec
Labels: new-package

#10471 fnott: new, 1.7.1
  app-utils/fnott/autobuild/defines
  app-utils/fnott/spec
Labels: new-package

#10477 broadcom-wl: update to 6.30.223.271-8
  runtime-kernel/broadcom-wl/autobuild/dkms.conf.in
  runtime-kernel/broadcom-wl/autobuild/patches/33-wl-Add-explanation-for-IBT-warnings-in-newer-kernels.patch
  runtime-kernel/broadcom-wl/autobuild/patches/37-wl-Fix-memcpy-field-spanning-write-warning.patch
  runtime-kernel/broadcom-wl/spec
Labels: upgrade

#10476 acbs: update to 20250415
  app-devel/acbs/spec
Labels: upgrade

#10473 scummvm: update to 2.9.0
  app-games/scummvm/autobuild/beyond
  app-games/scummvm/autobuild/build
  app-games/scummvm/autobuild/defines
  app-games/scummvm/autobuild/prepare
  app-games/scummvm/spec
Labels: upgrade

#10475 audacity: update to 3.7.3
  app-creativity/audacity/spec
Labels: upgrade

#10437 chromium: update to 135.0.7049.84
  app-web/chromium/autobuild/build
  app-web/chromium/autobuild/defines
  app-web/chromium/autobuild/patches/0001-FEDORA-Set-intial-prefs-path-to-etc-chromium.patch
  app-web/chromium/autobuild/patches/0002-FEDORA-third_party-zlib-Drop-dependency-to-chromecon.patch
  app-web/chromium/autobuild/patches/0003-FEDORA-Hard-code-std-hardware_destructive_interferen.patch
  app-web/chromium/autobuild/patches/0004-AOSCOS-media-enable-VA-API-decoding-encoding-by-defa.patch
  app-web/chromium/autobuild/patches/0004-GENTOO-www-client-chromium-work-around-dead-oauth2-c.patch
  app-web/chromium/autobuild/patches/0005-AOSCOS-build-fix-invalid-flag-substitutions.patch
  app-web/chromium/autobuild/patches/0005-AOSCOS-devtools-frontend-disable-unreliable-terser-p.patch
  app-web/chromium/autobuild/patches/0006-AOSCOS-build-correct-Clang-builtins-path.patch
  app-web/chromium/autobuild/patches/0006-AOSCOS-build-fix-invalid-flag-substitutions.patch
  app-web/chromium/autobuild/patches/0007-AOSCOS-blink-fix-build-with-gperf-3.2.patch
  app-web/chromium/autobuild/patches/0008-AOSCOS-third_party-swiftshader-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0009-AOSCOS-sandbox-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0010-AOSCOS-third_party-crashpad-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0011-AOSCOS-third_party-dav1d-add-LoongArch-architecture-.patch
  app-web/chromium/autobuild/patches/0012-AOSCOS-third_party-ffmpeg-add-LoongArch-support.patch
  app-web/chromium/autobuild/patches/0013-AOSCOS-build-use-medium-code-model-for-LoongArch.patch
  app-web/chromium/autobuild/patches/0014-AOSCOS-feat-introduce-miscellaneous-LoongArch-suppor.patch
  app-web/chromium/autobuild/patches/copy-loongarch64.bash
  app-web/chromium/autobuild/prepare
  app-web/chromium/spec
Labels: upgrade

#10479 pipewire: update to 1.4.2
  app-multimedia/pipewire/spec
Labels: upgrade

#10478 systemd-boot-friend: update to 0.27.4
  app-admin/systemd-boot-friend/spec
Labels: upgrade

#10481 deadbeef: update to 1.10.0
  app-multimedia/deadbeef/autobuild/defines
  app-multimedia/deadbeef/autobuild/patches/0001-ffmpeg-update-API-to-support-FFMPEG-7.patch
  app-multimedia/deadbeef/spec
Labels: upgrade

#8819 giflib: update to 5.2.2
  runtime-imaging/giflib/autobuild/build
  runtime-imaging/giflib/autobuild/defines
  runtime-imaging/giflib/autobuild/patches/0001-FROM-ARCHLINUX-Install-the-actual-man-pages-instead-of-the-sources.patch
  runtime-imaging/giflib/spec
Labels: upgrade

#10482 kcoreaddons: rebuild for gamin dep change
  desktop-kde/kcoreaddons/spec
Labels: dependencies

#10485 ffmpeg: rebuild for samba dep change
  app-multimedia/ffmpeg/spec
Labels: dependencies

#10486 zellij: update to 0.42.2
  app-utils/zellij/autobuild/patches/0001-chore-update-wasmtime-to-30.0.2.patch
  app-utils/zellij/autobuild/patches/0002-chore-update-nix-to-0.27-to-support-loongarch64.patch
  app-utils/zellij/spec
Labels: upgrade

#10498 oma: update to 1.16.1
  app-admin/oma/spec
Labels: upgrade

#10496 virtualbox: update to 7.1.8
  app-virtualization/virtualbox/01-host/patches/0001-FROM-ARCHLINUX-fix-Frontends-VirtualBox-disable-upda.patch
  app-virtualization/virtualbox/01-host/patches/0002-FROM-ARCHLINUX-properly-handle-i3wm.patch
  app-virtualization/virtualbox/01-host/patches/0003-FROM-ARCHLINUX-support-building-from-dkms.patch
  app-virtualization/virtualbox/01-host/patches/0004-FROM-ARCHLINUX-upate-xclient-script.patch
  app-virtualization/virtualbox/01-host/patches/0005-FROM-AOSC-fix-libs-dxvk-fix-build-with-GCC-13.patch
  app-virtualization/virtualbox/01-host/patches/0006-FROM-AOSC-chore-use-the-wheel-group-for-hardware-acc.patch
  app-virtualization/virtualbox/01-host/patches/0007-FROM-ARCHLINUX-fix-python-3.12-compatibility.patch
  app-virtualization/virtualbox/01-host/patches/0008-FROM-AOSC-Link-against-vorbisenc.patch
  app-virtualization/virtualbox/01-host/patches/0009-FROM-AOSC-Add-gitignore.patch
  app-virtualization/virtualbox/01-host/patches/0010-FROM-AOSC-Add-localinst.sh.patch
  app-virtualization/virtualbox/spec
Labels: upgrade

#10489 migrant-demo: new, 0
  app-games/migrant-demo/autobuild/build
  app-games/migrant-demo/autobuild/defines
  app-games/migrant-demo/autobuild/overrides/usr/share/applications/migrant-demo.desktop
  app-games/migrant-demo/autobuild/overrides/usr/share/pixmaps/migrant-demo.png
  app-games/migrant-demo/spec
Labels: new-package

#10499 nexttrace: update to 1.4.0
  app-network/nexttrace/spec
Labels: upgrade

#10466 qbittorrent: update to 5.0.5
  app-web/qbittorrent/spec
Labels: upgrade

#10510 fastfetch: update to 2.41.0
  app-utils/fastfetch/spec
Labels: upgrade

#10511 r: update to 4.5.0
  app-scientific/r/spec
Labels: upgrade

#10514 glmark2: fix visual config matching on IMG blob drivers
  app-benchmarks/glmark2/autobuild/patches/0001-BACKPORT-libmatrix-Add-Log-warning-function.patch
  app-benchmarks/glmark2/autobuild/patches/0002-BACKPORT-GLStateEGL-GLStateGLX-Change-failure-to-get-a-good-v.patch
  app-benchmarks/glmark2/autobuild/patches/0003-BACKPORT-Options-GLStateEGL-GLStateGLX-Add-option-to-require-.patch
  app-benchmarks/glmark2/autobuild/patches/0004-BACKPORT-GLVisualConfig-By-default-don-t-care-about-the-stenc.patch
  app-benchmarks/glmark2/spec
Labels: has-fix

#10441 qt-6: change include directory to /usr/include/qt6
  runtime-desktop/qt-6/01-runtime/defines
  runtime-desktop/qt-6/spec
Labels: has-fix

#10517 fend: update to 1.5.6
  app-utils/fend/spec
Labels: upgrade

#10520 repo: update to 2.54
  app-devel/repo/spec
Labels: upgrade

#10508 atuin: update to 18.5.0
  app-utils/atuin/spec
Labels: upgrade

#10516 oma: update to 1.16.2
  app-admin/oma/spec
Labels: upgrade

#10539 adw-gtk3: update to 5.10
  desktop-themes/adw-gtk3/spec
Labels: upgrade

#10528 tinty: new, 0.27.0
  app-utils/tinty/autobuild/beyond
  app-utils/tinty/autobuild/defines
  app-utils/tinty/spec
Labels: new-package

#10535 waylyrics: update to 0.3.21
  app-multimedia/waylyrics/spec
Labels: upgrade

#10540 osdlyrics: fix Python version used
  app-multimedia/osdlyrics/autobuild/defines
  app-multimedia/osdlyrics/spec
Labels: has-fix

#10559 apache-maven: update to 3.9.9
  lang-java/apache-maven/spec
Labels: upgrade

#10558 gradle: update to 8.13.0
  lang-java/gradle/spec
Labels: upgrade

#10557 stress-ng: update to 0.18.12
  app-benchmarks/stress-ng/spec
Labels: upgrade

#10554 oma: update to 1.16.3
  app-admin/oma/spec
Labels: upgrade

#10552 sing-box: update to 1.11.8
  app-network/sing-box/spec
Labels: upgrade
