Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-07, with the labels that each got.

#11530 intel-oneapi-basekit: update to 2025.2.0
  app-devel/intel-oneapi-basekit/spec
Labels: upgrade

#11541 praat: update to 6.4.37
  app-scientific/praat/spec
Labels: upgrade

#11547 open-vm-tools: update to 13.0.0 and add arm64 architecture support
  app-virtualization/open-vm-tools/autobuild/defines
  app-virtualization/open-vm-tools/spec
Labels: upgrade

#11549 feishin: update to 0.17.0
  app-multimedia/feishin/spec
Labels: upgrade

#11558 discord: update to 0.0.100
  app-web/discord/spec
Labels: upgrade

#11555 lact: update to 0.8.0
  app-admin/lact/autobuild/patches/0001-chore-lact-daemon-make-nvidia-bindgen-feature-as-opt.patch
  app-admin/lact/spec
Labels: upgrade

#11544 iml: fix build error
  runtime-common/iml/autobuild/defines
  runtime-common/iml/spec
Labels: has-fix

#11565 element-desktop: update to 1.11.105
  app-web/element-desktop/spec
Labels: upgrade

#11567 jq: update to 1.8.1
  app-devel/jq/spec
Labels: upgrade

#11575 qbittorrent: update to 5.1.2
  app-web/qbittorrent/spec
Labels: upgrade

#11569 vpl-gpu-rt: update to 25.2.6
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#11574 znc: update to 1.10.1
  app-web/znc/spec
Labels: upgrade

#11535 incus: update to 6.14.0
  app-containers/incus/01-incus/beyond
  app-containers/incus/01-incus/build
  app-containers/incus/01-incus/defines
  app-containers/incus/02-incus-agent/build
  app-containers/incus/02-incus-agent/defines
  app-containers/incus/02-incus-agent/prepare
  app-containers/incus/spec
Labels: upgrade

#11589 fastfetch: update to 2.47.0
  app-utils/fastfetch/spec
Labels: upgrade

#11593 zathura: update to 0.5.12
  app-doc/zathura/autobuild/defines
  app-doc/zathura/spec
Labels: upgrade

#11602 gearlever: update to 3.3.4
  app-utils/gearlever/spec
Labels: upgrade

#11598 just: update to 1.41.0
  app-devel/just/spec
Labels: upgrade

#11599 syncthing: update to 1.30.0
  app-network/syncthing/spec
Labels: upgrade

#11561 anubis: new, 1.20.0
  app-web/anubis/autobuild/build
  app-web/anubis/autobuild/defines
  app-web/anubis/spec
Labels: new-package

#11595 verilator: fix data install path
  app-electronics/verilator/autobuild/patches/0002-Fix-data-install-path.patch
  app-electronics/verilator/spec
Labels: has-fix

#11605 libsigrok: fix wrong `python-2` dep to `python-3`
  runtime-electronics/libsigrok/autobuild/defines
  runtime-electronics/libsigrok/spec
Labels: has-fix, dependencies

#9416 bash-pinyin-completion-rs: new, 0.2.3
  app-shells/bash-pinyin-completion-rs/autobuild/beyond
  app-shells/bash-pinyin-completion-rs/autobuild/conffiles
  app-shells/bash-pinyin-completion-rs/autobuild/defines
  app-shells/bash-pinyin-completion-rs/spec
  runtime-data/bash-startup/autobuild/defines
  runtime-data/bash-startup/spec
Labels: new-package, new-packages

#11625 dust: update to 1.2.2
  app-utils/dust/spec
Labels: upgrade

#11632 opentabletdriver: fix checkupdate
  runtime-devices/opentabletdriver/spec
Labels: has-fix

#11631 surfer: new, 0.3.0
  app-electronics/surfer/autobuild/defines
  app-electronics/surfer/spec
Labels: new-package

#11630 hmcl: update to 3.6.13
  app-games/hmcl/autobuild/overrides/usr/bin/hmcl
  app-games/hmcl/spec
Labels: upgrade

#11640 discord: update to 0.0.101
  app-web/discord/spec
Labels: upgrade

#11648 sing-box: update to 1.11.15
  app-proxy/sing-box/spec
Labels: upgrade

#11641 showmethekey: update to 1.18.4
  app-utils/showmethekey/spec
Labels: upgrade

#11642 listenbrainz-mpd: update to 2.3.9
  app-multimedia/listenbrainz-mpd/spec
Labels: upgrade

#11643 obs-studio: update to 31.1.0
  app-multimedia/obs-studio/autobuild/defines
  app-multimedia/obs-studio/autobuild/patches/0001-cmake-Add-executable-permission-to-CEF-binary-and-li.patch
  app-multimedia/obs-studio/autobuild/patches/0002-obs-ffmpeg-Fix-deprecation-with-FFmpeg-7.1.patch
  app-multimedia/obs-studio/spec
Labels: upgrade

#11653 networkmanager: update to 1.52.1
  app-network/networkmanager/autobuild/patches/0002-BACKPORT-meson-Fix-docs-generation-with-PyGObject-3.52.patch
  app-network/networkmanager/spec
Labels: upgrade

#11665 httplib2: update to 0.22.0
  lang-python/httplib2/autobuild/build
  lang-python/httplib2/autobuild/defines
  lang-python/httplib2/spec
Labels: upgrade

#11659 telegram-desktop: update to 5.16.3
  app-web/telegram-desktop/spec
Labels: upgrade

#11670 zotero: update to 7.0.20
  app-productivity/zotero/spec
Labels: upgrade

#11671 Clp: fix build error with GCC >= 14
  app-scientific/clp/autobuild/patches/0001-FROMEXT-fedora-coin-or-Clp-configure-amd_defaults-c9.patch
  app-scientific/clp/spec
Labels: has-fix

#11654 oma: update to 1.18.1
  app-admin/oma/autobuild/defines
  app-admin/oma/spec
Labels: upgrade

#11677 tig: update to 2.5.12
  app-utils/tig/autobuild/beyond
  app-utils/tig/autobuild/defines
  app-utils/tig/spec
Labels: upgrade

#11698 vscode: update to 1.102.0
  app-editors/vscode/spec
Labels: upgrade

#11702 neovim: update to 0.11.3
  app-editors/neovim/spec
Labels: upgrade

#11699 obs-studio: update to 31.1.1
  app-multimedia/obs-studio/spec
Labels: upgrade

#11704 nwg-look: update to 1.0.6
  app-utils/nwg-look/spec
Labels: upgrade

#11701 eza: update to 0.22.1
  app-utils/eza/spec
Labels: upgrade

#11688 pygments: update to 2.19.1
  lang-python/pygments/autobuild/defines
  lang-python/pygments/spec
Labels: upgrade

#11682 glab: update to 1.62.0
  app-devel/glab/spec
Labels: upgrade

#11681 hugo: update to 0.148.0
  app-web/hugo/spec
Labels: upgrade

#11680 kicad: update to 9.0.3
  app-electronics/kicad/spec
Labels: upgrade

#11585 uv: update to 0.7.19
  lang-python/uv/spec
Labels: upgrade

#11687 jiter: update to 0.10.0
  lang-python/jiter/spec
Labels: upgrade

#11728 oma: update to 1.18.2
  app-admin/oma/autobuild/defines
  app-admin/oma/spec
Labels: upgrade

#11735 element-desktop: update to 1.11.106
  app-web/element-desktop/autobuild/defines
  app-web/element-desktop/spec
Labels: upgrade

#11725 kdepim-apps-libs: drop, orphaned
  desktop-kde/kdepim-apps-libs/autobuild/defines
  desktop-kde/kdepim-apps-libs/spec
Labels: drop-package

#11742 fastfetch: update to 2.48.0
  app-utils/fastfetch/spec
Labels: upgrade

#11748 gyp: Update to 20240207 and use Python 3 (instead of 2) for it
  app-devel/gyp/autobuild/defines
  app-devel/gyp/spec
Labels: upgrade

#11722 git-cinnabar: update to 0.7.3
  app-vcs/git-cinnabar/autobuild/alternatives
  app-vcs/git-cinnabar/autobuild/defines
  app-vcs/git-cinnabar/autobuild/patches/0001-Update-target-to-2.1-to-fix-build-on-LA64.patch
  app-vcs/git-cinnabar/autobuild/prepare
  app-vcs/git-cinnabar/spec
Labels: upgrade

#11750 uv: update to 0.8.0
  lang-python/uv/autobuild/defines
  lang-python/uv/autobuild/prepare
  lang-python/uv/spec
Labels: upgrade

#11720 lego: update to 4.24.0
  app-web/lego/spec
Labels: upgrade

#11739 cinny-desktop: new, 4.8.1
  app-web/cinny-desktop/autobuild/beyond
  app-web/cinny-desktop/autobuild/defines
  app-web/cinny-desktop/autobuild/overrides/usr/share/applications/cinny.desktop
  app-web/cinny-desktop/autobuild/patches/0001-Disable-update-check.patch.cinny-desktop
  app-web/cinny-desktop/autobuild/patches/0001-Update-vite-plugin-top-level-await.patch.cinny
  app-web/cinny-desktop/autobuild/prepare
  app-web/cinny-desktop/spec
Labels: new-package

#11767 cherry-studio: new, 1.5.1
  app-utils/cherry-studio/autobuild/build
  app-utils/cherry-studio/autobuild/defines
  app-utils/cherry-studio/autobuild/overrides/usr/share/applications/cherry-studio.desktop
  app-utils/cherry-studio/spec
Labels: new-package

#11302 corefreq: update to 2.0.7
  app-utils/corefreq/autobuild/Makefile
  app-utils/corefreq/autobuild/build
  app-utils/corefreq/autobuild/defines
  app-utils/corefreq/autobuild/patch
  app-utils/corefreq/autobuild/postinst
  app-utils/corefreq/autobuild/prepare
  app-utils/corefreq/autobuild/prerm
  app-utils/corefreq/spec
Labels: upgrade

#11779 anubis: update to 1.21.0
  app-web/anubis/spec
Labels: upgrade

#11768 weechat: update to 4.7.0
  app-web/weechat/spec
Labels: upgrade

#11770 proton-bridge: new, 3.21.2
  app-web/proton-bridge/autobuild/beyond
  app-web/proton-bridge/autobuild/build
  app-web/proton-bridge/autobuild/defines
  app-web/proton-bridge/autobuild/patches/0001-Override-saferith-v0.33.0-with-v0.33.1-0.20250226174.patch
  app-web/proton-bridge/autobuild/patches/0002-Disable-vcpkg.patch
  app-web/proton-bridge/autobuild/patches/0003-Stop-bundling-Qt6-shared-libraries.patch
  app-web/proton-bridge/autobuild/patches/0004-Make-sentry-an-optional-dependency.patch
  app-web/proton-bridge/autobuild/patches/0005-Set-INSTALL_GTEST-to-OFF.patch
  app-web/proton-bridge/autobuild/prepare
  app-web/proton-bridge/spec
Labels: new-package

#11751 wireshark: update to 4.4.8
  app-network/wireshark/spec
Labels: upgrade

#11729 glab: update to 1.63.0
  app-devel/glab/spec
Labels: upgrade

#11727 just: update to 1.42.2
  app-devel/just/autobuild/defines
  app-devel/just/spec
Labels: upgrade

#11776 motif: fix build error with GCC>=14
  runtime-desktop/motif/autobuild/patches/0001-AOSCOS-fix-build-issue-for-GCC-14.patch
  runtime-desktop/motif/spec
Labels: has-fix

#11783 opentofu: update to 1.10.3
  app-admin/opentofu/spec
Labels: upgrade

#11786 autobuild4: update to 4.12.4
  app-devel/autobuild4/spec
Labels: upgrade

#11756 pixi: new, 0.49.0
  app-devel/pixi/autobuild/beyond
  app-devel/pixi/autobuild/defines
  app-devel/pixi/autobuild/prepare
  app-devel/pixi/spec
Labels: new-package

#11791 lfortran: update to 0.54.0
  app-devel/lfortran/spec
Labels: upgrade

#11794 bear: rebuild for grpc
  app-devel/bear/spec
Labels: upgrade

#11795 man-pages: update to 6.15+posix2017a
  runtime-data/man-pages/spec
Labels: upgrade

#11796 wofi: update to 1.5
  app-utils/wofi/spec
Labels: upgrade

#11803 sarasa-gothic-fonts: update to 1.0.32
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#11802 iosevka-fonts: update to 33.2.7
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#11805 btrfs-assistant: new, 2.2
  app-admin/btrfs-assistant/autobuild/defines
  app-admin/btrfs-assistant/spec
Labels: new-package

#11737 foot: update to 1.23.0
  app-utils/foot/spec
Labels: upgrade

#11694 box64: new,0.3.6
  app-emulation/box64/autobuild/alternatives
  app-emulation/box64/autobuild/beyond
  app-emulation/box64/autobuild/defines
  app-emulation/box64/spec
Labels: new-package

#11812 repo: update to 2.57
  app-devel/repo/spec
Labels: upgrade

#11815 foot: update to 1.23.1
  app-utils/foot/spec
Labels: upgrade

#11830 repo: update to 2.57.1
  app-devel/repo/spec
Labels: upgrade

#11832 nodejs-22: update to 22.17.1
  lang-js/nodejs-22/spec
Labels: upgrade

#11833 osu-lazer: update to 2025.724.0
  app-games/osu-lazer/spec
Labels: upgrade

#11844 vscode: update to 1.102.2
  app-editors/vscode/spec
Labels: upgrade

#11846 less: update to 679
  app-utils/less/spec
Labels: upgrade

#11847 hwinfo: update to 25.0
  app-utils/hwinfo/spec
Labels: upgrade

#11845 cherry-studio: update to 1.5.3
  app-utils/cherry-studio/autobuild/patches/0001-disable-auto-update-feature-by-default.patch
  app-utils/cherry-studio/spec
Labels: upgrade

#11853 qtscrcpy: update to 3.3.1
  app-utils/qtscrcpy/autobuild/defines
  app-utils/qtscrcpy/autobuild/patches/0003-Modify-the-hard-coded-paths-to-properly-access-resou.patch
  app-utils/qtscrcpy/spec
Labels: upgrade

#11854 ncdu: update to 1.22
  app-utils/ncdu/spec
Labels: upgrade

#11843 ninja: update to 1.13.1
  app-devel/ninja/spec
Labels: upgrade

#11850 zotero: update to 7.0.22
  app-productivity/zotero/spec
Labels: upgrade

#11852 telegram-desktop: update to 5.16.6
  app-web/telegram-desktop/spec
Labels: upgrade

#11838 bitwarden: update to 2025.7.0
  app-utils/bitwarden/autobuild/defines
  app-utils/bitwarden/autobuild/patches/0001-napi-prefer-glibc-instead-of-musl-libc.patch
  app-utils/bitwarden/autobuild/patches/0002-napi-enable-lto.patch
  app-utils/bitwarden/spec
Labels: upgrade

#11848 obs-studio: update to 31.1.2
  app-multimedia/obs-studio/spec
Labels: upgrade

#11862 lxgwwenkai-font: update to 1.520
  desktop-fonts/lxgwwenkai-font/spec
Labels: upgrade

#11861 lxgwcleargothic-font: update to 0.503
  desktop-fonts/lxgwcleargothic-font/spec
Labels: upgrade

#11860 lxgwneoxihei-font: update to 1.218.1
  desktop-fonts/lxgwneoxihei-font/spec
Labels: upgrade

#11856 tailscale: update to 1.86.0
  app-network/tailscale/spec
Labels: upgrade

#11842 uv: update to 0.8.3
  lang-python/uv/spec
Labels: upgrade

#11826 v4l2loopback: update to 0.15.1
  app-utils/v4l2loopback/autobuild/patches/0001-added-functionality-for-linux-6.15-626.patch
  app-utils/v4l2loopback/spec
Labels: upgrade

#11774 hmcl: update to 3.6.15
  app-games/hmcl/autobuild/defines
  app-games/hmcl/autobuild/overrides/usr/bin/hmcl
  app-games/hmcl/spec
Labels: upgrade

#11744 helix: update to 25.07
  app-editors/helix/autobuild/defines
  app-editors/helix/spec
Labels: upgrade

#11831 dkcli: update to 0.4.7
  app-admin/dkcli/autobuild/defines
  app-admin/dkcli/spec
Labels: upgrade

#11887 asar: new, 4.0.0
  app-utils/asar/autobuild/build
  app-utils/asar/autobuild/defines
  app-utils/asar/spec
Labels: new-package

#11876 lazygit: update to 0.53.0
  app-vcs/lazygit/spec
Labels: upgrade

#11888 copyq: new, 10.0.0
  app-utils/copyq/autobuild/defines
  app-utils/copyq/spec
Labels: new-package

#11818 gn: update to 0+git20250718
  app-devel/gn/spec
Labels: upgrade

#11891 kernel-build-common: remove merge marker
  app-devel/kernel-build-common/autobuild/ab4/prepare
  app-devel/kernel-build-common/spec
Labels: rework

#11889 pixi: update to 0.50.2
  app-devel/pixi/spec
Labels: upgrade

#11878 telegram-desktop: fix taskbar icon on Wayland
  app-web/telegram-desktop/autobuild/patches/0013-Fix-desktop-file-name-on-Qt-5.patch
  app-web/telegram-desktop/spec
Labels: has-fix

#11893 efibootmgr: backport patch to fix boot reordering
  app-admin/efibootmgr/autobuild/defines
  app-admin/efibootmgr/autobuild/patches/0001-BACKPORT-Fix-boot-reorder.patch
  app-admin/efibootmgr/spec
Labels: has-fix

#11866 nginx: add ngx_brotli module
  app-web/nginx/autobuild/build
  app-web/nginx/autobuild/patches/0002-add-comments-about-compression-in-nginx.conf.patch
  app-web/nginx/spec
Labels: enhancement

#11897 ruri: update to 3.9.0
  app-admin/ruri/autobuild/defines
  app-admin/ruri/autobuild/patches/0001-Add-CMakeLists.txt.patch
  app-admin/ruri/spec
Labels: upgrade

#11817 cli11: new, 2.5.0
  runtime-common/cli11/autobuild/defines
  runtime-common/cli11/spec
Labels: new-package

#11900 gradle: update to 8.14.3
  lang-java/gradle/spec
Labels: upgrade

#11898 glab: update to 1.65.0
  app-devel/glab/spec
Labels: upgrade

#11915 maxima: update to 5.48.0
  app-scientific/maxima/spec
Labels: upgrade

#11913 anubis: update to 1.21.3
  app-web/anubis/autobuild/build
  app-web/anubis/spec
Labels: upgrade

#11914 halloy: new, 2025.7
  app-web/halloy/autobuild/beyond
  app-web/halloy/autobuild/defines
  app-web/halloy/spec
Labels: new-package

#11926 gearlever: update to 3.4.0
  app-utils/gearlever/spec
Labels: upgrade
