Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-01, with the labels that each got.

#8902 binutils+w64: update to 2.43.1
  runtime-optenvw64/binutils+w64/spec
Labels: upgrade

#9130 osu-lazer: update to 2025.101.0
  app-games/osu-lazer/spec
Labels: upgrade

#9134 peazip: update to 10.2.0
  app-utils/peazip/spec
Labels: upgrade

#9136 desktop-file-utils: update to 0.28
  app-admin/desktop-file-utils/spec
Labels: upgrade

#9139 foot: update to 1.20.0
  app-utils/foot/spec
Labels: upgrade

#9137 xorg-server: update to 21.1.15
  runtime-display/xorg-server/spec
Labels: upgrade

#9142 autobuild4: update to 4.7.2
  app-devel/autobuild4/spec
Labels: upgrade

#9118 shadow: update to 4.17.0
  app-admin/shadow/autobuild/defines
  app-admin/shadow/autobuild/overrides/etc/default/useradd
  app-admin/shadow/autobuild/overrides/etc/login.defs
  app-admin/shadow/autobuild/overrides/etc/pam.d/passwd
  app-admin/shadow/autobuild/patches/0001-login.defs-Adapt-to-AOSC-configuration.patch
  app-admin/shadow/spec
Labels: upgrade

#9141 iosevka-fonts: update to 32.3.1
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#9143 sarasa-gothic-fonts: update to 1.0.27
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#9150 autobuild4: update to 4.7.3
  app-devel/autobuild4/spec
Labels: upgrade

#9151 fcft: update to 3.1.10
  runtime-display/fcft/spec
Labels: upgrade

#8805 flat-remix-icon-theme: update to 20240201
  desktop-themes/flat-remix-icon-theme/spec
Labels: upgrade

#9148 debootstrap: update to 1.0.140
  app-utils/debootstrap/spec
Labels: upgrade

#9152 kitty: update to 0.38.1
  app-utils/kitty/autobuild/prepare
  app-utils/kitty/spec
Labels: upgrade

#9146 Telegram Desktop: update to 5.10.0
  app-web/telegram-desktop/autobuild/defines
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#9155 foot: update to 1.20.1
  app-utils/foot/spec
Labels: upgrade

#9160 oma: update to 1.13.3
  app-admin/oma/spec
Labels: upgrade

#9158 zed: update to 0.167.1
  app-editors/zed/spec
Labels: upgrade

#9157 gitoxide: update to 0.40.0
  app-vcs/gitoxide/spec
Labels: upgrade

#9162 sing-box: update to 1.10.6
  app-network/sing-box/spec
Labels: upgrade

#9163 typos: update to 1.29.4
  app-utils/typos/spec
Labels: upgrade

#9164 ciel: update to 3.8.7
  app-devel/ciel/autobuild/beyond
  app-devel/ciel/autobuild/defines
  app-devel/ciel/spec
Labels: upgrade

#9169 ciel: update to 3.8.8
  app-devel/ciel/spec
Labels: upgrade

#9172 autobuild4: update to 4.7.4
  app-devel/autobuild4/spec
Labels: upgrade

#9174 flat-remix-icon-theme: 20240201 Rework
  desktop-themes/flat-remix-icon-theme/spec
Labels: rework

#9135 mixxx: update to 2.5.0
  app-creativity/mixxx/autobuild/defines
  app-creativity/mixxx/spec
Labels: upgrade

#9177 podman: add shadow as a dependency
  app-containers/podman/autobuild/defines
  app-containers/podman/spec
Labels: dependencies

#9180 oma: update to 1.13.4
  app-admin/oma/spec
Labels: upgrade

#9181 autobuild4: update to 4.7.6
  app-devel/autobuild4/spec
Labels: upgrade

#9183 easyeffects: update to 7.2.2
  app-multimedia/easyeffects/spec
Labels: upgrade

#9186 easyeffects: update to 7.2.3
  app-multimedia/easyeffects/spec
Labels: upgrade

#9190 vim: update to 9.1.0993
  app-editors/vim/spec
Labels: upgrade

#9191 deskflow: update to 1.18.0
  app-utils/deskflow/spec
Labels: upgrade

#9198 lmms: update to 1.2.2+git20250101
  app-creativity/lmms/autobuild/defines
  app-creativity/lmms/autobuild/postinst
  app-creativity/lmms/autobuild/prepare
  app-creativity/lmms/spec
Labels: upgrade

#9193 astyle: update to 3.6.6
  app-devel/astyle/spec
Labels: upgrade

#9199 telegram-desktop: update to 5.10.1
  app-web/telegram-desktop/spec
Labels: upgrade

#9170 yaml-cpp-0.7: new, 0.7.0
  runtime-common/yaml-cpp-0.7/autobuild/beyond
  runtime-common/yaml-cpp-0.7/autobuild/defines
  runtime-common/yaml-cpp-0.7/autobuild/overrides/etc/ld.so.conf.d/yaml-cpp-0.7.conf
  runtime-common/yaml-cpp-0.7/autobuild/postinst
  runtime-common/yaml-cpp-0.7/spec
Labels: new-package

#9206 libxkbcommon: rebuild to fix Spiral markers
  runtime-display/libxkbcommon/spec
Labels: has-fix

#9209 oma: update to 1.13.5
  app-admin/oma/spec
Labels: upgrade

#8614 dracut-ng: update to 105
  app-admin/dracut-ng/autobuild/build
  app-admin/dracut-ng/spec
Labels: upgrade

#9223 fastfetch: update to 2.34.0
  app-utils/fastfetch/spec
Labels: upgrade

#9224 flatpak: update to 1.16.0
  app-admin/flatpak/autobuild/defines
  app-admin/flatpak/spec
Labels: upgrade

#9219 libportal: update to 0.9.0
  runtime-desktop/libportal/spec
Labels: upgrade

#9218 vim: update to 9.1.0998
  app-editors/vim/spec
Labels: upgrade

#9217 praat: update to 6.4.26
  app-scientific/praat/autobuild/prepare
  app-scientific/praat/spec
Labels: upgrade

#9216 telegram-desktop: update to 5.10.2
  app-web/telegram-desktop/spec
Labels: upgrade

#9194 timeshift: update to 24.06.6
  app-utils/timeshift/autobuild/patches/0001-Specify-the-environment-variables-named-DISPLAY-and-.patch
  app-utils/timeshift/autobuild/patches/0002-Update-dekstop-entry-translations.patch
  app-utils/timeshift/autobuild/patches/0003-Specify-the-environment-variables-named-DISPLAY-and-.patch
  app-utils/timeshift/spec
Labels: upgrade

#9215 abootimg: new, 0.6+git20120912
  app-devices/abootimg/autobuild/build
  app-devices/abootimg/autobuild/defines
  app-devices/abootimg/spec
Labels: new-packages

#9220 aosc-os-repository-data: update to v20250109
  runtime-data/aosc-os-repository-data/spec
Labels: upgrade

#9210 gradle: update to 8.12.0
  lang-java/gradle/spec
Labels: upgrade

#9208 lfortran: update to 0.43.0
  app-devel/lfortran/autobuild/defines
  app-devel/lfortran/spec
Labels: upgrade

#9227 adaptivecpp: update to 24.10.0
  app-devel/adaptivecpp/autobuild/defines
  app-devel/adaptivecpp/spec
Labels: upgrade

#9236 snapper: update to 0.12.1
  app-admin/snapper/spec
Labels: upgrade

#9237 telegram-desktop: update to 5.10.3
  app-web/telegram-desktop/spec
Labels: upgrade

#9207 chromium: update to 131.0.6778.264
  app-web/chromium/spec
Labels: upgrade

#9229 mgba: update to 0.10.4
  app-games/mgba/spec
Labels: upgrade

#8843 transmission: update to 4.0.6
  app-web/transmission/autobuild/patches/0001-fix-build-error-on-GTKMM-4-6393.patch
  app-web/transmission/spec
Labels: upgrade

#8667 hunspell: update to 1.7.2
  app-i18n/hunspell/spec
Labels: upgrade

#8798 throttled: update to 0.11
  app-utils/throttled/spec
Labels: upgrade

#9187 zed: update to 0.167.2
  app-editors/zed/spec
Labels: upgrade

#9197 atop: update to 2.11.0
  app-utils/atop/spec
Labels: upgrade

#9238 stress-ng: update to 0.18.09
  app-benchmarks/stress-ng/spec
Labels: upgrade

#8700 pstate-frequency: update to 3.15.2
  app-admin/pstate-frequency/spec
Labels: upgrade

#9232 bind: update to 9.20.4
  app-network/bind/spec
Labels: upgrade

#9176 dnscontrol: update to 4.15.3
  app-network/dnscontrol/spec
Labels: upgrade

#8842 fprintd: update to 1.94.4
  app-admin/fprintd/autobuild/beyond
  app-admin/fprintd/spec
Labels: upgrade

#9222 mold: update to 2.36.0
  app-devel/mold/spec
Labels: upgrade

#9126 php: update to 8.4.2
  app-devel/php/autobuild/build
  app-devel/php/autobuild/patches/0001-fix-fpm-define-perferences-for-AOSC-OS.patch
  app-devel/php/autobuild/patches/0002-Arch-php.ini.patch
  app-devel/php/autobuild/patches/0002-fix-php.ini-production-set-default-extensions-direct.patch
  app-devel/php/spec
Labels: upgrade

#9228 tsukimi: update to 0.18.2
  app-multimedia/tsukimi/autobuild/defines
  app-multimedia/tsukimi/spec
Labels: upgrade

#9202 ca-certs: update to 20241119
  runtime-data/ca-certs/spec
Labels: upgrade

#9251 prismlauncher: update to 9.2
  app-games/prismlauncher/spec
Labels: upgrade

#9250 vim: update to 9.1.1006
  app-editors/vim/spec
Labels: upgrade

#9248 starship: update to 1.22.1
  app-utils/starship/autobuild/patches/0001-feat-status-add-success_symbol_rootuser-option.patch
  app-utils/starship/autobuild/patches/0002-refactor-utils-move-is_root_user-function-to-utils-m.patch
  app-utils/starship/spec
Labels: upgrade

#9252 kicad: update to 8.0.8
  app-electronics/kicad/spec
Labels: upgrade

#9247 mihomo-party: update to 1.5.13
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Remove-check-update-UI.patch
  app-network/mihomo-party/autobuild/patches/0003-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0004-Remove-upgrade-mihomo-UI.patch
  app-network/mihomo-party/autobuild/patches/0005-Do-not-fetch-Mihomo-Clash-Meta-binaries.patch
  app-network/mihomo-party/autobuild/patches/0006-Do-not-find-Mihomo-Clash-Meta-binary-in-sidecar-dir.patch
  app-network/mihomo-party/spec
Labels: upgrade

#9244 git-absorb: update to 0.6.17
  app-devel/git-absorb/spec
Labels: upgrade

#9243 syncthing: update to 1.29.1
  app-network/syncthing/spec
Labels: upgrade

#9242 zvm: update to 0.8.4
  lang-ziglang/zvm/spec
Labels: upgrade

#9241 tsukimi: update to 0.18.3
  app-multimedia/tsukimi/spec
Labels: upgrade

#9239 zed: update to 0.168.2
  app-editors/zed/spec
Labels: upgrade

#9231 rustc: update to 1.84.0
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/autobuild/prepare
  lang-rust/rustc/spec
Labels: upgrade

#9261 gnupg: update to 2.4.7
  app-cryptography/gnupg/spec
Labels: upgrade

#9271 oma: update to 1.13.6
  app-admin/oma/spec
Labels: upgrade

#9211 ab-download-manager: new, 1.5.1
  app-web/abdownloadmanager/autobuild/build
  app-web/abdownloadmanager/autobuild/defines
  app-web/abdownloadmanager/autobuild/overrides/usr/share/applications/abdownloadmanager.desktop
  app-web/abdownloadmanager/spec
Labels: new-packages

#9272 tigervnc: fix systemd service, use Arch Linux patches
  app-network/tigervnc/autobuild/patches/0001-Arch-Linux-more-xsessions.patch
  app-network/tigervnc/autobuild/patches/0002-Arch-Linux-remove-selinux.patch
  app-network/tigervnc/spec
Labels: has-fix

#9274 listenbrainz-mpd: new, 2.3.8
  app-multimedia/listenbrainz-mpd/autobuild/beyond
  app-multimedia/listenbrainz-mpd/autobuild/defines
  app-multimedia/listenbrainz-mpd/spec
Labels: new-packages

#9279 ispc: update to 1.25.3
  app-devel/ispc/spec
Labels: upgrade

#9278 r: update to 4.4.2
  app-scientific/r/spec
Labels: upgrade

#9270 libidn2: update to 2.3.7
  runtime-network/libidn2/spec
Labels: upgrade

#9269 libidn: update to 1.42
  runtime-network/libidn/spec
Labels: upgrade

#9268 ocrad: update to 0.29
  app-doc/ocrad/spec
Labels: upgrade

#9265 gdbm: update to 1.24
  app-database/gdbm/spec
Labels: upgrade

#9263 libtool: update to 2.5.4
  app-devel/libtool/spec
Labels: upgrade

#9262 mtools: update to 4.0.46
  app-admin/mtools/spec
Labels: upgrade

#9260 gettext: update to 0.23
  app-devel/gettext/spec
Labels: upgrade

#9259 nettle: update to 3.10.1
  runtime-cryptography/nettle/spec
Labels: upgrade

#9258 texinfo: update to 7.2
  app-utils/texinfo/spec
Labels: upgrade

#9257 bc: update to 1.08.1
  app-utils/bc/spec
Labels: upgrade

#9256 ddrescue: update to 1.29
  app-utils/ddrescue/spec
Labels: upgrade

#9255 ed: update to 1.21
  app-editors/ed/spec
Labels: upgrade

#8984 git: update to 2.48.0
  app-vcs/git/spec
Labels: upgrade, pre-release

#9277 WeeChat: rebuild for PHP, fix BUILDDEP
  app-web/weechat/autobuild/defines
  app-web/weechat/spec
Labels: dependencies

#9283 mihomo-party: update to 1.6.0
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Remove-check-update-UI.patch
  app-network/mihomo-party/autobuild/patches/0003-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0004-Remove-upgrade-mihomo-UI.patch
  app-network/mihomo-party/autobuild/patches/0005-Do-not-fetch-Mihomo-Clash-Meta-binaries.patch
  app-network/mihomo-party/autobuild/patches/0006-Do-not-find-Mihomo-Clash-Meta-binary-in-sidecar-dir.patch
  app-network/mihomo-party/spec
Labels: upgrade

#9286 cmake: update to 3.31.4
  app-devel/cmake/spec
Labels: upgrade

#9289 fastfetch: update to 2.34.1
  app-utils/fastfetch/spec
Labels: upgrade

#9290 iotop: update to 1.27
  app-utils/iotop/spec
Labels: upgrade

#9292 alacritty: update to 0.15.0
  app-utils/alacritty/spec
Labels: upgrade

#9288 linux-firmware: update to 20250113
  runtime-kernel/linux-firmware/spec
Labels: upgrade

#9294 xournalpp: update to 1.2.5
  runtime-productivity/xournalpp/autobuild/defines
  runtime-productivity/xournalpp/spec
Labels: upgrade

#9291 vpl-gpu-rt: update to 25.1.0
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#9298 zfs: update to 2.3.0
  app-admin/zfs/spec
Labels: upgrade

#9285 bat: update to 0.25.0
  app-utils/bat/autobuild/defines
  app-utils/bat/spec
Labels: upgrade

#9295 sing-box: update to 1.10.7
  app-network/sing-box/spec
Labels: upgrade

#9306 rsync: security update to 3.4.0
  app-network/rsync/spec
Labels: upgrade, security

#9312 git: security update to 2.48.1
  app-vcs/git/spec
Labels: upgrade, security

#9309 libdatachannel: update to 0.22.4
  runtime-multimedia/libdatachannel/spec
Labels: upgrade

#9300 mesa: update to 24.3.3+dxheaders1.614.1
  runtime-display/mesa/spec
Labels: upgrade

#9311 vscodium: update to 1.96.3.25013
  app-editors/vscodium/spec
Labels: upgrade

#9296 zed: update to 0.168.3
  app-editors/zed/spec
Labels: upgrade

#9310 vscode: update to 1.96.3
  app-editors/vscode/spec
Labels: upgrade

#9308 osu-lazer: update to 2025.114.0
  app-games/osu-lazer/spec
Labels: upgrade

#9301 gnu-efi: update to 3.0.18
  app-devel/gnu-efi/autobuild/build
  app-devel/gnu-efi/autobuild/defines
  app-devel/gnu-efi/spec
Labels: upgrade

#9319 rsync: update to 3.4.1
  app-network/rsync/spec
Labels: upgrade, has-fix

#9315 bitwarden: update to 2025.1.0
  app-utils/bitwarden/spec
Labels: upgrade

#9326 pam-u2f: update to 1.3.2
  runtime-admin/pam-u2f/spec
Labels: upgrade, security

#9320 lact: update to 0.7.0
  app-admin/lact/spec
Labels: upgrade

#9328 nexttrace: update to 1.3.7
  app-network/nexttrace/spec
Labels: upgrade

#9329 bitwarden: update to 2025.1.1
  app-utils/bitwarden/spec
Labels: upgrade

#9330 ostree: update to 2025.1
  app-admin/ostree/spec
Labels: upgrade

#9338 neovim: update to 0.10.3
  app-editors/neovim/spec
Labels: upgrade

#9339 shadowsocks-rust: update to 1.22.0
  app-network/shadowsocks-rust/autobuild/defines
  app-network/shadowsocks-rust/autobuild/patches/0001-fix-lto-inject.patch
  app-network/shadowsocks-rust/spec
Labels: upgrade

#9333 syncthing: update to 1.29.2
  app-network/syncthing/spec
Labels: upgrade

#9340 containers-common: update to 0.61.1+image5.33.1+shortnames2023.02.20+skopeo1.17.0+storage1.56.1
  runtime-containers/containers-common/spec
Labels: upgrade

#9302 autobuild4: update to 4.7.7
  app-devel/autobuild4/spec
Labels: upgrade

#9341 vscode: update to 1.96.4
  app-editors/vscode/spec
Labels: upgrade

#9316 pandoc: update to 3.6.2
  app-doc/pandoc/spec
Labels: upgrade

#9353 musicfox: new, 4.6.0
  app-multimedia/musicfox/autobuild/build
  app-multimedia/musicfox/autobuild/defines
  app-multimedia/musicfox/spec
Labels: new-packages

#9245 libcap-ng: update to 0.8.5, drop python 2 support
  runtime-common/libcap-ng/autobuild/defines
  runtime-common/libcap-ng/spec
Labels: upgrade

#9354 gdb: update to 16.1
  app-devel/gdb/spec
Labels: upgrade

#9361 osu-lazer: update to 2025.118.0
  app-games/osu-lazer/spec
Labels: upgrade

#9360 foot: update to 1.20.2
  app-utils/foot/spec
Labels: upgrade

#9356 dnscontrol: update to 4.15.5
  app-network/dnscontrol/spec
Labels: upgrade

#9350 difftastic: update to 0.62.0
  app-utils/difftastic/spec
Labels: upgrade

#9372 obs-studio: update to 31.0.1
  app-multimedia/obs-studio/autobuild/patches/0001-cmake-Add-executable-permission-to-CEF-binary-and-li.patch
  app-multimedia/obs-studio/autobuild/patches/0002-obs-ffmpeg-Fix-deprecation-with-FFmpeg-7.1.patch
  app-multimedia/obs-studio/autobuild/patches/0003-libobs-opengl-Avoid-trying-to-allocate-0-byte-on-Lin.patch
  app-multimedia/obs-studio/spec
Labels: upgrade

#9371 dpkg: update to 1.22.14
  app-admin/dpkg/01-update-alternatives/patches/0001-AOSCOS-feat-data-add-AOSC-OS-specific-armv4-architec.patch
  app-admin/dpkg/01-update-alternatives/patches/0002-AOSCOS-ARMV6HF-fix-data-rename-armhf-as-AOSC-OS-spec.patch.armv6hf
  app-admin/dpkg/01-update-alternatives/patches/0002-AOSCOS-ARMV7HF-fix-data-rename-armhf-as-AOSC-OS-spec.patch.armv7hf
  app-admin/dpkg/01-update-alternatives/patches/0003-AOSCOS-fix-data-rename-i-86-as-AOSC-OS-specific-i486.patch
  app-admin/dpkg/01-update-alternatives/patches/0004-AOSCOS-fix-data-rename-loong64-as-AOSC-OS-specific-l.patch
  app-admin/dpkg/01-update-alternatives/patches/0005-AOSCOS-LOONGSON2F-fix-data-rename-mips64el-as-AOSC-O.patch.loongson2f
  app-admin/dpkg/01-update-alternatives/patches/0005-AOSCOS-LOONGSON3-fix-data-rename-mips64el-as-AOSC-O.patch.loongson3
  app-admin/dpkg/01-update-alternatives/patches/0006-AOSCOS-feat-drop-multiarch-features-add-remove-archi.patch
  app-admin/dpkg/01-update-alternatives/patches/0007-AOSCOS-po-update-translation-catalogue.patch
  app-admin/dpkg/01-update-alternatives/patches/0008-AOSCOS-po-add-translation-for-AOSC-OS-add-remove-arc.patch
  app-admin/dpkg/spec
Labels: upgrade

#9373 xdg-desktop-portal-gtk: update to 1.15.2
  app-admin/xdg-desktop-portal-gtk/spec
Labels: upgrade

#9368 mtools: update to 4.0.47
  app-admin/mtools/spec
Labels: upgrade

#9331 json-c: update to 0.18
  runtime-common/json-c/spec
Labels: upgrade

#9343 mesa: add some patches to fix VK_IMG compatiblity
  runtime-display/mesa/autobuild/patches/0003-BACKPORT-zink-emit-consts-as-uint-only-on-IMG-proprietary-dri.patch
  runtime-display/mesa/autobuild/patches/0004-BACKPORT-zink-use-lazy-descriptors-for-IMG-proprietary-driver.patch
  runtime-display/mesa/autobuild/patches/0005-FROMLIST-zink-Do-not-use-demote-on-IMG-blobs.patch
  runtime-display/mesa/spec
Labels: has-fix
