Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-02, with the labels that each got.

#9523 git: add patches chosen by Git for Windows 2.48.x
  app-vcs/git/autobuild/patches/0001-UPSTREAM-show-index-the-short-help-should-say-the-co.patch
  app-vcs/git/autobuild/patches/0002-UPSTREAM-object-file-fix-race-in-object-collision-ch.patch
  app-vcs/git/autobuild/patches/0003-UPSTREAM-object-file-rename-variables-in-check_colli.patch
  app-vcs/git/autobuild/patches/0004-UPSTREAM-object-file-don-t-special-case-missing-sour.patch
  app-vcs/git/autobuild/patches/0005-UPSTREAM-object-file-retry-linking-file-into-place-w.patch
  app-vcs/git/autobuild/patches/0006-UPSTREAM-test-lib-invert-return-value-of-check_test_.patch
  app-vcs/git/autobuild/patches/0007-UPSTREAM-test-lib-simplify-lsan-results-check.patch
  app-vcs/git/autobuild/patches/0008-UPSTREAM-test-lib-add-a-few-comments-to-LSan-log-che.patch
  app-vcs/git/autobuild/patches/0009-UPSTREAM-credential-cache-respect-authtype-capabilit.patch
  app-vcs/git/autobuild/patches/0010-UPSTREAM-object-name-fix-resolution-of-object-names-.patch
  app-vcs/git/autobuild/patches/0011-UPSTREAM-object-name-be-more-strict-in-parsing-descr.patch
  app-vcs/git/autobuild/patches/0012-UPSTREAM-ref-filter-move-ahead-behind-bases-into-use.patch
  app-vcs/git/autobuild/patches/0013-UPSTREAM-ref-filter-move-is-base-tip-to-used_atom.patch
  app-vcs/git/autobuild/patches/0014-UPSTREAM-ref-filter-remove-ref_format_clear.patch
  app-vcs/git/autobuild/patches/0015-UPSTREAM-bswap.h-squelch-potential-sparse-Wcast-trun.patch
  app-vcs/git/autobuild/patches/0016-UPSTREAM-packfile-factor-out-pack_header-argument-pa.patch
  app-vcs/git/autobuild/patches/0017-UPSTREAM-parse_pack_header_option-avoid-unaligned-me.patch
  app-vcs/git/autobuild/patches/0018-UPSTREAM-index-pack-unpack-objects-use-get_be32-for-.patch
  app-vcs/git/autobuild/patches/0019-UPSTREAM-index-pack-unpack-objects-use-skip_prefix-t.patch
  app-vcs/git/autobuild/patches/0020-UPSTREAM-refs-fix-creation-of-reflog-entries-for-sym.patch
  app-vcs/git/autobuild/patches/0021-FROMGIT-reftable-write-correct-max_update_index-to-h.patch
  app-vcs/git/autobuild/patches/0022-FROMGIT-refs-reftable-fix-uninitialized-memory-acces.patch
  app-vcs/git/autobuild/patches/0023-FROMLIST-fetch-set_head-refactor-to-use-remote-direc.patch
  app-vcs/git/autobuild/patches/0024-FROMLIST-fetch-set_head-fix-non-mirror-remotes-in-ba.patch
  app-vcs/git/autobuild/patches/0025-FROMLIST-refs-mark-ref_transaction_update_reflog-as-.patch
  app-vcs/git/autobuild/patches/0026-FROMLIST-refs-use-uint64_t-for-ref_update.index.patch
  app-vcs/git/autobuild/patches/0027-FROMLIST-reftable-prevent-update_index-changes-after.patch
  app-vcs/git/autobuild/patches/0028-WINDOWS-grep-prevent-false-match-at-end-of-file.patch
  app-vcs/git/spec
Labels: bug

#9516 libreoffice: update to 24.8.4.2
  app-productivity/libreoffice/autobuild/build
  app-productivity/libreoffice/autobuild/defines
  app-productivity/libreoffice/autobuild/patches/0001-FROM-AOSC-Make-pyuno-work-with-system-wide-module-install.patch
  app-productivity/libreoffice/autobuild/patches/0002-FROM-AOSC-Allow-building-bundled-Firebird-with-LTO.patch
  app-productivity/libreoffice/autobuild/patches/0002-Make-pyuno-work-with-system-wide-module-install.patch
  app-productivity/libreoffice/autobuild/patches/0003-Allow-building-bundled-firebird-with-LTO.patch
  app-productivity/libreoffice/autobuild/patches/0003-LoongArchLinux-firebird-la64.patch.firebird-deferred.loongarch64
  app-productivity/libreoffice/autobuild/patches/0005-icu-74-compatibility.patch
  app-productivity/libreoffice/spec
Labels: upgrade

#9527 sarasa-gothic-fonts: update to 1.0.28
  desktop-fonts/sarasa-gothic-fonts/spec
Labels: upgrade

#9526 iosevka-fonts: update to 32.5.0
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#9528 font-manager: update to 0.9.2
  app-utils/font-manager/autobuild/defines
  app-utils/font-manager/spec
Labels: upgrade

#9532 papirus-icon-theme: update to 20250201
  desktop-themes/papirus-icon-theme/spec
Labels: upgrade

#9534 telegram-desktop: update to 5.10.7
  app-web/telegram-desktop/spec
Labels: upgrade

#9498 llama.cpp: new package, 4615
  runtime-creativity/llama.cpp/autobuild/beyond
  runtime-creativity/llama.cpp/autobuild/defines
  runtime-creativity/llama.cpp/autobuild/patches/0001-AOSCOS-add-system-backend-path.patch
  runtime-creativity/llama.cpp/spec
Labels: new-packages

#9529 gdb: update to 16.2
  app-devel/gdb/spec
Labels: upgrade

#9542 tsukimi: update to 0.19.3
  app-multimedia/tsukimi/spec
Labels: upgrade

#9548 sing-box: update to 1.11.1
  app-network/sing-box/spec
Labels: upgrade

#9553 curl: update to 8.12.0
  app-web/curl/spec
Labels: upgrade, security

#9551 rustc: update to 1.84.1
  lang-rust/rustc/spec
Labels: upgrade

#9541 rpi-firmware-boot: update to 1.20250127
  runtime-kernel/rpi-firmware-boot/spec
Labels: upgrade

#9509 typos: update to 1.29.5
  app-utils/typos/spec
Labels: upgrade

#9544 hugo: update to 0.143.1
  app-web/hugo/spec
Labels: upgrade

#9538 buildah: update to 1.39.0
  app-containers/buildah/spec
Labels: upgrade

#9554 sof-tools: update to 2.12
  app-multimedia/sof-tools/spec
Labels: upgrade

#9519 deskflow: update to 1.19.0
  app-utils/deskflow/spec
Labels: upgrade

#9403 nodejs-20: update to 20.18.2
  lang-js/nodejs-20/spec
Labels: upgrade

#9558 sof-firmware: update to 2025.01
  runtime-kernel/sof-firmware/spec
Labels: upgrade

#9564 nginx: update to 1.27.4
  app-web/nginx/autobuild/beyond
  app-web/nginx/autobuild/build
  app-web/nginx/autobuild/defines
  app-web/nginx/autobuild/patches/0001-AOSCOS-nginx.conf-adapt-to-AOSC-OS-defaults.patch
  app-web/nginx/autobuild/prepare
  app-web/nginx/spec
Labels: upgrade, security

#9562 thunderbird: update to 128.7.0esr
  app-web/thunderbird/spec
Labels: upgrade, security

#9569 loonggpu-kernel-dkms: add patch to fix building on 6.14
  runtime-kernel/loonggpu-kernel-dkms/autobuild/build
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0001-chore-initialise-a-gitignore-file.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0002-loonggpu-include-use-video-aperture-helpers-for-Linu.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0003-loonggpu-pass-string-literal-parameter-to-MODULE_IMP.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0004-loonggpu-dkms-drop-deprecated-REMAKE_INITRD-yes-opti.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0005-loonggpu-gsgpu_dc_connector-gsgpu-bridge-drop-an-unu.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0006-loonggpu-gsgpu_vm-move-struct-definition-to-include-.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0007-loonggpu-gsgpu-gsgpu-bridge-lint-prototypes.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0008-AOSCOS-loonggpu-remove-driver-date.patch
  runtime-kernel/loonggpu-kernel-dkms/spec
Labels: has-fix

#9563 firefox: update to 135.0
  app-web/firefox/autobuild/patches/0001-feat-netwerk-declare-AOSC-OS-in-user-agent-string.patch
  app-web/firefox/autobuild/patches/0002-Enable-VA-API-support-for-AMD-GPUs.patch
  app-web/firefox/autobuild/patches/0003-Add-support-for-LoongArch64.patch
  app-web/firefox/autobuild/patches/0004-update-gn_processor.py-to-support-linux-on-loong64.patch
  app-web/firefox/autobuild/patches/0005-chore-regenerate-libwebrtc-moz.build-files.patch
  app-web/firefox/autobuild/patches/0006-enable-webrtc-for-loongarch64-in-toolkit-moz.configu.patch
  app-web/firefox/autobuild/patches/0007-Fix-libyuv-unified-source-and-LoongArch-SIMD-build.patch
  app-web/firefox/autobuild/patches/0008-Fix-missing-loongarch-subdir-in-libpng-moz.yaml.patch
  app-web/firefox/autobuild/patches/0009-Vendor-missing-loongarch-files-of-libpng.patch
  app-web/firefox/autobuild/patches/0010-Enable-LoongArch-LSX-optimization-for-libpng.patch
  app-web/firefox/autobuild/patches/0011-Bug-1933368-MIPS-Implement-atomicPause-and-AtomicOpe.patch
  app-web/firefox/autobuild/patches/0011-Bug-1938855-MIPS-Replace-BytecodeOffset-with-TrapSit.patch
  app-web/firefox/autobuild/patches/0012-Bug-1935611-Fix-skia-build-failed-for-loongarch64.-r.patch
  app-web/firefox/autobuild/patches/0013-Bug-1935611-Enable-skia-simd-for-loongarch64.-r-lsal.patch
  app-web/firefox/autobuild/patches/0014-Bug-1935611-Fix-libyuv-libpng-link-failed-for-loonga.patch
  app-web/firefox/spec
Labels: upgrade, security

#9578 libtasn1: update to 4.20.0
  runtime-cryptography/libtasn1/spec
Labels: upgrade

#9577 pycryptodome: update to 3.21.0
  lang-python/pycryptodome/autobuild/defines
  lang-python/pycryptodome/spec
Labels: upgrade

#9575 vpl-gpu-rt: update to 25.1.1
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#9574 osu-lazer: update to 2025.204.0
  app-games/osu-lazer/spec
Labels: upgrade

#9579 zed: update to 0.172.9
  app-editors/zed/spec
Labels: upgrade

#9581 ppsspp: update to 1.18.1
  app-games/ppsspp/spec
Labels: upgrade

#9585 uv: update to 0.5.29
  lang-python/uv/spec
Labels: upgrade

#9582 vscode: update to 1.97.0
  app-editors/vscode/spec
Labels: upgrade

#9590 stress-ng: update to 0.18.10
  app-benchmarks/stress-ng/spec
Labels: upgrade

#9589 libspice: fix USB ACL operation not permitted issue
  runtime-virtualization/libspice-gtk/autobuild/postinst
  runtime-virtualization/libspice-gtk/spec
Labels: has-fix

#9560 dnscontrol: update to 4.16.0
  app-network/dnscontrol/spec
Labels: upgrade

#9499 fricas: new package, 1.3.11
  app-scientific/fricas/autobuild/beyond
  app-scientific/fricas/autobuild/defines
  app-scientific/fricas/autobuild/overrides/usr/share/applications/fricas.desktop
  app-scientific/fricas/spec
Labels: new-package

#9594 pyelftools: update to 0.31
  lang-python/pyelftools/spec
Labels: upgrade

#9593 bitwarden: update to 2025.1.4
  app-utils/bitwarden/spec
Labels: upgrade

#9595 wike: new, 3.1.1
  app-web/wike/autobuild/defines
  app-web/wike/spec
Labels: new-package

#9592 wireplumber: update to 0.5.8
  app-multimedia/wireplumber/spec
Labels: upgrade

#9591 yazi: update to 25.2.7
  app-utils/yazi/spec
Labels: upgrade

#9597 nodejs-22: backport corepack update to 0.31.0
  lang-js/nodejs-22/autobuild/patches/0001-deps-update-corepack-to-0.31.0.patch
  lang-js/nodejs-22/spec
Labels: upgrade, has-fix

#9598 deploykit-backend: update to 0.7.7
  app-admin/deploykit-backend/spec
Labels: upgrade, dependencies

#9588 cloud-init: update to 24.4.1
  app-admin/cloud-init/autobuild/build
  app-admin/cloud-init/autobuild/defines
  app-admin/cloud-init/autobuild/patches/0001-feat-aosc-Add-AOSC-OS-support-5310.patch
  app-admin/cloud-init/autobuild/patches/0002-fix-add-host-template-for-AOSC.patch
  app-admin/cloud-init/spec
Labels: upgrade

#9605 libffi: update to 3.4.7
  runtime-common/libffi/autobuild/patches/0001-BACKPORT-MIPS-add-.note.GNU-stack-section-to-assembly-sources.patch
  runtime-common/libffi/spec
Labels: upgrade

#9599 nodejs-20: backport corepack update to 0.31.0
  lang-js/nodejs-20/autobuild/patches/0001-BACKPORT-deps-update-corepack-to-0.30.0.patch
  lang-js/nodejs-20/autobuild/patches/0002-BACKPORT-deps-update-corepack-to-0.31.0.patch
  lang-js/nodejs-20/spec
Labels: upgrade, has-fix

#9602 oxipng: new, 9.1.3
  app-utils/oxipng/autobuild/defines
  app-utils/oxipng/spec
Labels: new-package

#9610 linux+kernel+rc: fix typo in description
  runtime-kernel/linux+kernel+rc/autobuild/defines
  runtime-kernel/linux+kernel+rc/spec
Labels: has-fix, pre-release

#9609 nvidia: fix building on 6.14
  runtime-display/nvidia/03-kernel/patches/0001-Fix-symbolic-links-for-Linux-kernel-6.13-rc1.patch
  runtime-display/nvidia/03-kernel/patches/0002-FROM-AOSC-Use-linux-aperture.c-for-removing-conflict.patch
  runtime-display/nvidia/03-kernel/patches/0003-FROM-AOSC-TTM-fbdev-emulation-for-Linux-6.13.patch
  runtime-display/nvidia/03-kernel/patches/0004-AOSCOS-nvidia-drm-remove-driver-date.patch
  runtime-display/nvidia/spec
Labels: bug

#9603 forgejo: update to 10.0.1
  app-web/forgejo/autobuild/defines
  app-web/forgejo/spec
Labels: upgrade

#9619 forgejo: fix FAIL_ARCH
  app-web/forgejo/autobuild/defines
  app-web/forgejo/spec
Labels: has-fix

#9617 mihomo: update to 1.19.2
  app-network/mihomo/spec
Labels: upgrade

#9620 ispc: update to 1.26.0
  app-devel/ispc/spec
Labels: upgrade

#9604 aegisub: update to 3.4.2
  app-multimedia/aegisub/autobuild/defines
  app-multimedia/aegisub/autobuild/patches/0001-Backport-to-icu-64.patch
  app-multimedia/aegisub/autobuild/patches/0002-explicitly-set-cpp_eh-to-default.patch
  app-multimedia/aegisub/spec
Labels: upgrade

#9540 virtualbox: update to 7.1.6a
  app-virtualization/virtualbox/01-host/build
  app-virtualization/virtualbox/01-host/patches/0001-FROM-ARCHLINUX-fix-Frontends-VirtualBox-disable-upda.patch
  app-virtualization/virtualbox/01-host/patches/0002-FROM-ARCHLINUX-properly-handle-i3wm.patch
  app-virtualization/virtualbox/01-host/patches/0003-FROM-ARCHLINUX-support-building-from-dkms.patch
  app-virtualization/virtualbox/01-host/patches/0004-FROM-ARCHLINUX-upate-xclient-script.patch
  app-virtualization/virtualbox/01-host/patches/0005-FROM-AOSC-fix-libs-dxvk-fix-build-with-GCC-13.patch
  app-virtualization/virtualbox/01-host/patches/0006-FROM-AOSC-chore-use-the-wheel-group-for-hardware-acc.patch
  app-virtualization/virtualbox/01-host/patches/0007-FROM-ARCHLINUX-fix-python-3.12-compatibility.patch
  app-virtualization/virtualbox/01-host/patches/0008-FROM-AOSC-Link-against-vorbisenc.patch
  app-virtualization/virtualbox/01-host/patches/0009-FROM-AOSC-Add-gitignore.patch
  app-virtualization/virtualbox/01-host/patches/0010-FROM-AOSC-Add-localinst.sh.patch
  app-virtualization/virtualbox/spec
Labels: upgrade

#9625 fastfetch: update to 2.36.0
  app-utils/fastfetch/spec
Labels: upgrade

#9624 fcitx5-pinyin-moegirl: update to 20250209
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#9623 libheif: update to 1.19.5
  runtime-imaging/libheif/spec
Labels: upgrade

#9615 linux-firmware: update to 20250208
  runtime-kernel/linux-firmware/spec
Labels: upgrade

#9630 dracut-ng: improve pre-upstream patches
  app-admin/dracut-ng/autobuild/patches/0004-AOSCOS-dracut-init-decompress-kernel-modules-and-fir.patch
  app-admin/dracut-ng/autobuild/patches/0004-FROMLIST-feat-strip-out-unused-unlikely-AMDGPU-firmw.patch
  app-admin/dracut-ng/autobuild/patches/0005-AOSCOS-dracut-init-strip-out-unused-unlikely-AMDGPU-.patch
  app-admin/dracut-ng/autobuild/patches/0005-FROMLIST-feat-decompress-kernel-modules-and-firmware.patch
  app-admin/dracut-ng/spec
Labels: enhancement

#9573 libreoffice: update to 25.2.0.3
  app-productivity/libreoffice/autobuild/build
  app-productivity/libreoffice/autobuild/patches/0001-AOSCOS-Make-pyuno-work-with-system-wide-module-insta.patch
  app-productivity/libreoffice/autobuild/patches/0002-AOSCOS-Allow-building-bundled-Firebird-with-LTO.patch
  app-productivity/libreoffice/autobuild/patches/0003-sdext-adapt-xpdfwrapper-to-poppler-24.12.patch
  app-productivity/libreoffice/autobuild/patches/0003-skia-enable-LASX-explicitly-to-LASX-binary-compatibl.patch
  app-productivity/libreoffice/autobuild/patches/0004-skia-backport-cherry-pick-fixes-for-LoongArch64-LSX-.patch
  app-productivity/libreoffice/autobuild/patches/1001-LoongArchLinux-firebird-la64.patch.firebird-deferred.loongarch64
  app-productivity/libreoffice/autobuild/patches/1002-ArchRISCV-firebird-riscv64-support.patch.firebird-deferred.riscv64
  app-productivity/libreoffice/spec
Labels: upgrade

#9631 arcanist: new, 2024.35
  app-devel/arcanist/autobuild/build
  app-devel/arcanist/autobuild/defines
  app-devel/arcanist/autobuild/patches/0001-Fix-PHP-8-exit-status-cannot-be-null-error.patch
  app-devel/arcanist/autobuild/patches/0002-Remove-an-outdated-PHP-5.3-check-in-utils.patch
  app-devel/arcanist/autobuild/patches/0003-Fix-PHP-8.1-strlen-null-exception-in-PHPASTParserTes.patch
  app-devel/arcanist/autobuild/patches/0004-Fix-PHP-8.1-preg_match-null-exception-in-XHPASTNode.patch
  app-devel/arcanist/autobuild/patches/0005-PHPDoc-Replace-return-this-with-return-this.patch
  app-devel/arcanist/autobuild/patches/0006-Fix-PHP-8.1-strlen-null-exception-in-HTTPFutureHTTPR.patch
  app-devel/arcanist/autobuild/patches/0007-Fix-PHP-8.1-strlen-null-exception-in-PhutilOAuth1Fut.patch
  app-devel/arcanist/autobuild/patches/0008-Fix-invalid-constructor-call-for-ArcanistHardpointFu.patch
  app-devel/arcanist/autobuild/patches/0009-Fix-implicitly-nullable-parameter-declarations-for-P.patch
  app-devel/arcanist/autobuild/patches/0010-Fix-implicitly-nullable-parameter-declarations-for-P.patch
  app-devel/arcanist/autobuild/patches/0011-JSON-rendering-Avoid-exception-iterating-on-non-iter.patch
  app-devel/arcanist/autobuild/patches/0012-AOSCOS-Remove-deprecated-E_STRICT.patch
  app-devel/arcanist/autobuild/patches/0013-Skip-writing-symbol-cache-to-non-writable-directorie.patch
  app-devel/arcanist/autobuild/patches/0014-xhpast-Skip-minline-all-stringops-on-non-x86-archite.patch
  app-devel/arcanist/spec
Labels: new-package

#9632 sing-box: update to 1.11.2
  app-network/sing-box/spec
Labels: upgrade

#9634 dracut-ng: rework firmware symlink fix-up routine
  app-admin/dracut-ng/autobuild/patches/0004-FROMLIST-feat-strip-out-unused-unlikely-AMDGPU-firmw.patch
  app-admin/dracut-ng/autobuild/patches/0005-FROMLIST-feat-decompress-kernel-modules-and-firmware.patch
  app-admin/dracut-ng/spec
Labels: has-fix, rework

#9638 arcanist: ship symbol cache
  app-devel/arcanist/autobuild/build
  app-devel/arcanist/autobuild/patches/0012-Skip-writing-symbol-cache-to-non-writable-directorie.patch
  app-devel/arcanist/autobuild/patches/0013-xhpast-Skip-minline-all-stringops-on-non-x86-archite.patch
  app-devel/arcanist/autobuild/patches/0014-AOSCOS-Remove-deprecated-E_STRICT.patch
  app-devel/arcanist/spec
Labels: enhancement

#9633 uv: update to 0.5.30
  lang-python/uv/spec
Labels: upgrade

#9639 sing-box: update to 1.11.3
  app-network/sing-box/spec
Labels: upgrade

#9641 remmina: update to 1.4.39
  app-network/remmina/spec
Labels: upgrade

#9636 nodejs-20: update to 20.18.3
  lang-js/nodejs-20/autobuild/patches/0001-BACKPORT-deps-update-corepack-to-0.30.0.patch
  lang-js/nodejs-20/autobuild/patches/0001-UPSTREAM-deps-update-corepack-to-0.31.0.patch
  lang-js/nodejs-20/spec
Labels: upgrade

#9637 vscodium: add patch to fix pwsh detection
  app-editors/vscodium/autobuild/patches/0001-AOSCOS-add-microsoft-vscode-240054.patch
  app-editors/vscodium/spec
Labels: has-fix

#9626 fractal: update to 10.1
  desktop-gnome/fractal/spec
Labels: upgrade

#9596 mihomo-party: update to 1.7.1
  app-network/mihomo-party/autobuild/build
  app-network/mihomo-party/autobuild/overrides/usr/share/applications/mihomo-party.desktop
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Remove-check-update-UI.patch
  app-network/mihomo-party/autobuild/patches/0003-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0003-fix-update-sub-store-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0004-Drop-clash-meta-alpha-support.patch
  app-network/mihomo-party/autobuild/patches/0005-Remove-upgrade-mihomo-UI.patch
  app-network/mihomo-party/autobuild/patches/0006-Do-not-fetch-Mihomo-Clash-Meta-binaries.patch
  app-network/mihomo-party/autobuild/patches/0007-Do-not-find-Mihomo-Clash-Meta-binary-in-sidecar-dir.patch
  app-network/mihomo-party/spec
Labels: upgrade

#9640 zed: update to 0.172.11
  app-editors/zed/spec
Labels: upgrade

#9647 yazi: update to 25.2.11
  app-utils/yazi/spec
Labels: upgrade

#9649 fastfetch: update to 2.36.1
  app-utils/fastfetch/spec
Labels: upgrade

#9653 cava: update to 0.10.4
  app-multimedia/cava/autobuild/patches/0001-bump-hardcoded-version-to-0.10.3.patch
  app-multimedia/cava/spec
Labels: upgrade

#9652 difftastic: update to 0.63.0
  app-utils/difftastic/spec
Labels: upgrade

#9651 podman: update to 5.4.0+vsock0.7.5
  app-containers/podman/spec
Labels: upgrade

#9654 oma: update to 1.13.11
  app-admin/oma/spec
Labels: upgrade

#9643 nnn: update to 5.0
  app-utils/nnn/spec
Labels: upgrade

#9657 intel-ucode: update to 20250211
  runtime-data/intel-ucode/spec
Labels: upgrade, security

#9665 openssl+32: update to 3.4.1
  runtime-optenv32/openssl+32/autobuild/defines
  runtime-optenv32/openssl+32/spec
Labels: upgrade, security

#9658 openssl: update to 3.4.1
  runtime-cryptography/openssl/autobuild/defines
  runtime-cryptography/openssl/autobuild/patches/0001-LoongArch-Fix-output-file-name-detection-for-Perl-scripts.patch
  runtime-cryptography/openssl/spec
Labels: upgrade, security

#9660 pandoc: update to 3.6.3
  app-doc/pandoc/spec
Labels: upgrade

#9668 vim: update to 9.1.1106
  app-editors/vim/spec
Labels: upgrade

#9671 pango: update to 1.56.1
  runtime-desktop/pango/autobuild/defines
  runtime-desktop/pango/spec
Labels: upgrade

#9673 gtk-4: update to 4.17.4
  desktop-gnome/gtk-4/01-main/patches/0002-inspector-Tweak-the-cursor-size-control.patch
  desktop-gnome/gtk-4/01-main/patches/0003-wayland-Redo-cursor-loading.patch
  desktop-gnome/gtk-4/01-main/patches/0004-wayland-Bring-back-the-pointer-viewporter.patch
  desktop-gnome/gtk-4/01-main/patches/0005-wayland-Improve-our-cursor-size-selection.patch
  desktop-gnome/gtk-4/spec
Labels: upgrade

#9680 gtk-4: downgrade to 4.16.12
  desktop-gnome/gtk-4/01-main/defines
  desktop-gnome/gtk-4/01-main/patches/0002-inspector-Tweak-the-cursor-size-control.patch
  desktop-gnome/gtk-4/01-main/patches/0003-wayland-Redo-cursor-loading.patch
  desktop-gnome/gtk-4/01-main/patches/0005-wayland-Improve-our-cursor-size-selection.patch
  desktop-gnome/gtk-4/spec
Labels: downgrade

#9676 pmbootstrap: new, 3.2.0
  app-utils/pmbootstrap/autobuild/build
  app-utils/pmbootstrap/autobuild/defines
  app-utils/pmbootstrap/spec
Labels: new-package

#9677 ydotool: new, 1.0.4
  app-utils/ydotool/autobuild/defines
  app-utils/ydotool/overrides/usr/lib/udev/rules.d/80-ydotool.rules
  app-utils/ydotool/spec
Labels: new-package

#9688 nas: fix lib64 => lib logic
  runtime-multimedia/nas/autobuild/build
  runtime-multimedia/nas/spec
Labels: has-fix

#9678 rofi: update to 1.7.8
  app-utils/rofi/autobuild/defines
  app-utils/rofi/spec
Labels: upgrade

#9686 qutebrowser: new, 3.4.0
  extra-web/qutebrowser/autobuild/build
  extra-web/qutebrowser/autobuild/defines
  extra-web/qutebrowser/spec
Labels: new-package

#9690 lxgwwenkai-font: update to 1.510
  desktop-fonts/lxgwwenkai-font/spec
Labels: upgrade

#9691 libcap: update to 2.73, bump PKGEPOCH_SPIRAL to 1
  runtime-common/libcap/autobuild/defines
  runtime-common/libcap/spec
Labels: upgrade

#9694 ffmpeg: backport patch to support legacy HEVC FLV files
  app-multimedia/ffmpeg/autobuild/patches/0001-UPSTREAM-doc-t2h-Support-texinfo-7.1-and-7.2-pretest.patch
  app-multimedia/ffmpeg/autobuild/patches/0002-UPSTREAM-avformat-flvenc-implement-support-for-multi.patch
  app-multimedia/ffmpeg/autobuild/patches/0003-UPSTREAM-avformat-flvdec-add-support-for-demuxing-mu.patch
  app-multimedia/ffmpeg/autobuild/patches/0004-UPSTREAM-avformat-flvdec-add-enhanced-audio-codecs.patch
  app-multimedia/ffmpeg/autobuild/patches/0005-UPSTREAM-avformat-flvdec-parse-enhanced-rtmp-multich.patch
  app-multimedia/ffmpeg/autobuild/patches/0006-UPSTREAM-avformat-flvdec-add-support-for-reading-mul.patch
  app-multimedia/ffmpeg/autobuild/patches/0007-UPSTREAM-avformat-flvdec-stop-shadowing-local-variab.patch
  app-multimedia/ffmpeg/autobuild/patches/0008-UPSTREAM-avformat-flvdec-support-all-multi-track-mod.patch
  app-multimedia/ffmpeg/autobuild/patches/0009-UPSTREAM-avformat-flvdec-propagate-av_packet_add_sid.patch
  app-multimedia/ffmpeg/autobuild/patches/0010-UPSTREAM-avformat-flvdec-add-missing-track_size-decr.patch
  app-multimedia/ffmpeg/autobuild/patches/0011-UPSTREAM-avformat-flvdec-fix-potential-premature-ret.patch
  app-multimedia/ffmpeg/autobuild/patches/0012-UPSTREAM-avformat-flvdec-clean-up-variable-initializ.patch
  app-multimedia/ffmpeg/autobuild/patches/0013-UPSTREAM-avformat-flvdec-properly-free-mt_extradata.patch
  app-multimedia/ffmpeg/autobuild/patches/0014-UPSTREAM-avformat-flvdec-don-t-leak-extradata-pointe.patch
  app-multimedia/ffmpeg/autobuild/patches/0015-BACKPORT-avformat-flvdec-add-support-for-legacy-HEVC.patch
  app-multimedia/ffmpeg/autobuild/patches/0016-UPSTREAM-avformat-flvdec-implement-support-for-parsi.patch
  app-multimedia/ffmpeg/autobuild/patches/0017-UPSTREAM-avformat-flvdec-correctly-skip-command-fram.patch
  app-multimedia/ffmpeg/autobuild/patches/0018-fix-libavutil-mips-Only-use-cpuinfo-to-read-cpu-ISAs.patch
  app-multimedia/ffmpeg/autobuild/patches/0019-Add-av_stream_get_first_dts-for-Chromium.patch
  app-multimedia/ffmpeg/autobuild/patches/0020-fix-libavcodec-mips-constify-src-for-mmi.patch
  app-multimedia/ffmpeg/autobuild/patches/0021-fix-libavcodec-mips-use-mmi-mnemonics-supported-by-b.patch
  app-multimedia/ffmpeg/spec
Labels: enhancement

#9689 telegram-desktop: update to 5.11.1
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-fix-current_geo_location_linux-add-missing-QGuiAppli.patch
  app-web/telegram-desktop/spec
Labels: upgrade

#9704 vpl-gpu-rt: update to 25.1.2
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#9703 libdatachannel: update to 0.22.5
  runtime-multimedia/libdatachannel/spec
Labels: upgrade

#9702 bitwarden: update to 2025.2.0
  app-utils/bitwarden/spec
Labels: upgrade

#9705 btrfs-progs: update to 6.13
  app-admin/btrfs-progs/spec
Labels: upgrade

#9707 curl: update to 8.12.1
  app-web/curl/spec
Labels: upgrade

#9695 giac: update to 1.9.0+998
  app-scientific/giac/spec
Labels: upgrade

#9687 darktable: update to 5.0.1
  app-creativity/darktable/spec
Labels: upgrade

#9621 loupe: new, 47.4
  desktop-gnome/loupe/autobuild/beyond
  desktop-gnome/loupe/autobuild/defines
  desktop-gnome/loupe/spec
Labels: new-package

#9622 kea: new, kea-2.6.1
  app-network/kea/autobuild/conffiles
  app-network/kea/autobuild/defines
  app-network/kea/autobuild/overrides/usr/lib/systemd/system/kea-ctrl-agent.service
  app-network/kea/autobuild/overrides/usr/lib/systemd/system/kea-dhcp-ddns.service
  app-network/kea/autobuild/overrides/usr/lib/systemd/system/kea-dhcp4-server.service
  app-network/kea/autobuild/overrides/usr/lib/systemd/system/kea-dhcp6-server.service
  app-network/kea/autobuild/overrides/usr/lib/sysusers.d/kea.conf
  app-network/kea/autobuild/overrides/usr/lib/tmpfiles.d/kea.conf
  app-network/kea/autobuild/patches/0001-default-config-log-format-and-ctrl-socket.patch
  app-network/kea/autobuild/postinst
  app-network/kea/spec
  runtime-common/log4cplus/autobuild/defines
  runtime-common/log4cplus/spec
Labels: new-package

#9709 typos: update to 1.29.7
  app-utils/typos/spec
Labels: upgrade

#9708 skopeo: update to 1.18.0
  app-containers/skopeo/spec
Labels: upgrade

#9715 vscode: update to 1.97.2
  app-editors/vscode/spec
Labels: upgrade

#9711 ciel: update to 3.9.2
  app-devel/ciel/spec
Labels: upgrade

#9714 linux-firmware: update to 20250211
  runtime-kernel/linux-firmware/spec
Labels: upgrade

#9718 adobe-source-han-serif: update to 2.003
  desktop-fonts/adobe-source-han-serif/spec
Labels: upgrade

#9710 zed: update to 0.173.10
  app-editors/zed/autobuild/patches/0001-Drop-build-profile.patch
  app-editors/zed/autobuild/patches/0001-cargo-use-default-release-build-settings.patch
  app-editors/zed/spec
Labels: upgrade

#9719 oma: update to 1.14.514
  app-admin/oma/spec
Labels: upgrade

#9717 uv: update to 0.6.0
  lang-python/uv/spec
Labels: upgrade

#9724 vim: update to 9.1.1117
  app-editors/vim/spec
Labels: upgrade, security

#9701 lsp-plugins: update to 1.2.20
  app-multimedia/lsp-plugins/autobuild/defines
  app-multimedia/lsp-plugins/spec
Labels: upgrade

#9730 postgresql: update to 13.19
  app-database/postgresql/spec
Labels: upgrade, security

#9667 thermald: update to 2.5.9
  app-admin/thermald/spec
Labels: upgrade

#9672 sbcl: update to 2.5.1
  app-scientific/fricas/autobuild/defines
  app-scientific/fricas/spec
  app-scientific/maxima/spec
  lang-lisp/sbcl/autobuild/defines
  lang-lisp/sbcl/autobuild/defines.stage2
  lang-lisp/sbcl/spec
Labels: upgrade

#9726 alacritty: update to 0.15.1
  app-utils/alacritty/spec
Labels: upgrade

#9732 nuclei: update to 3.3.9
  app-utils/nuclei/spec
Labels: upgrade

#9727 aoscbootstrap: update to 0.8.2
  app-utils/aoscbootstrap/spec
Labels: upgrade

#9733 wayland-protocols: update to 1.41
  app-devel/wayland-protocols/spec
Labels: upgrade

#9734 ncmpc: update to 0.52
  app-multimedia/ncmpc/spec
Labels: upgrade

#9735 rmpc: new, 0.8.0
  app-multimedia/rmpc/autobuild/beyond
  app-multimedia/rmpc/autobuild/defines
  app-multimedia/rmpc/spec
Labels: new-package

#9737 oxipng: update to 9.1.4
  app-utils/oxipng/spec
Labels: upgrade

#9739 uv: update to 0.6.1
  lang-python/uv/spec
Labels: upgrade

#9520 krita: update to 5.2.9
  app-creativity/krita/autobuild/patches/0001-sip-6.8.patch
  app-creativity/krita/autobuild/patches/0002-xsimd-12.patch
  app-creativity/krita/autobuild/patches/0003-fix-build-with-libjxl-0.9.0.patch
  app-creativity/krita/autobuild/patches/0004-fix-global-menu-on-Plasma-6.patch
  app-creativity/krita/spec
Labels: upgrade

#9742 openssh: update to 9.9p2
  app-network/openssh/spec
Labels: upgrade, security

#9747 lxgwneoxihei-font: update to 1.213
  desktop-fonts/lxgwneoxihei-font/spec
Labels: upgrade

#9740 qbittorrent: update to 5.0.4
  app-web/qbittorrent/spec
Labels: upgrade

#9750 ciel: update to 3.9.3
  app-devel/ciel/spec
Labels: upgrade

#9754 acbs: update to 20250219
  app-devel/acbs/spec
Labels: upgrade

#9746 qemu: update to 9.2.1
  app-virtualization/qemu/spec
Labels: upgrade

#9743 bleachbit: update to 4.6.2
  app-utils/bleachbit/autobuild/overrides/usr/share/applications/bleachbit-root.desktop
  app-utils/bleachbit/autobuild/patches/0001-Remove-localization-cleanup-feature.patch
  app-utils/bleachbit/autobuild/patches/0002-replace-apt-support-with-oma-support.patch
  app-utils/bleachbit/autobuild/patches/0003-add-zh_CN-and-zh_TW-translation-for-oma.patch
  app-utils/bleachbit/autobuild/patches/0004-remove-update-check.patch
  app-utils/bleachbit/spec
Labels: upgrade

#9765 zotero: update to 7.0.12
  app-productivity/zotero/autobuild/patches/0001-Remove-check-for-update-button.patch
  app-productivity/zotero/autobuild/patches/0002-Disable-updater.patch
  app-productivity/zotero/spec
Labels: upgrade

#9770 networkmanager: update to 1.50.2
  app-network/networkmanager/autobuild/defines
  app-network/networkmanager/spec
Labels: upgrade

#9760 strace: update to 6.13
  app-devel/strace/spec
Labels: upgrade

#9761 kbd: update to 2.7.1
  app-utils/kbd/autobuild/defines
  app-utils/kbd/autobuild/prepare
  app-utils/kbd/spec
Labels: upgrade

#9763 setuptools-python3: update to 75.8.0
  lang-python/setuptools-python3/spec
Labels: upgrade

#9768 typst: update to 0.13.0
  app-doc/typst/spec
Labels: upgrade

#9769 fastfetch: update to 2.37.0
  app-utils/fastfetch/spec
Labels: upgrade

#9766 vkd3d: update to 1.15
  runtime-display/vkd3d/spec
Labels: upgrade

#9764 libedit: update to 20250104+3.1
  runtime-common/libedit/autobuild/beyond
  runtime-common/libedit/spec
Labels: upgrade

#9713 memcached: update to 1.6.36
  app-admin/memcached/spec
Labels: upgrade

#9773 uv: update to 0.6.2
  lang-python/uv/spec
Labels: upgrade

#9692 solaar: update to 1.1.14
  app-utils/solaar/spec
Labels: upgrade

#9645 gparted: update to 1.7.0
  app-admin/gparted/autobuild/defines
  app-admin/gparted/spec
Labels: upgrade
