Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-08, with the labels that each got.

#11932 maple-font: update to 7.5
  desktop-fonts/maple-font/spec
Labels: upgrade

#11886 chezmoi: update to 2.63.1
  app-utils/chezmoi/spec
Labels: upgrade

#11885 xray: update to 25.7.26
  app-proxy/xray/spec
Labels: upgrade

#11931 pyside2: fix disappearing libraries
  lang-python/pyside2/autobuild/beyond
  lang-python/pyside2/spec
Labels: has-fix

#11937 ab-download-manager: update to 1.6.8
  app-web/ab-download-manager/autobuild/build
  app-web/ab-download-manager/autobuild/defines
  app-web/ab-download-manager/spec
Labels: upgrade

#11941 halloy: update to 2025.8
  app-web/halloy/spec
Labels: upgrade

#11945 fastfetch: update to 2.49.0
  app-utils/fastfetch/spec
Labels: upgrade

#11948 luanti: update to 5.13.0
  app-games/luanti/spec
Labels: upgrade

#11957 xdg-desktop-portal-termfilechooser: update to 1.2.0
  app-admin/xdg-desktop-portal-termfilechooser/spec
Labels: upgrade

#11954 repo: update to 2.57.2
  app-devel/repo/spec
Labels: upgrade

#11949 meson: update to 1.8.3
  app-devel/meson/spec
Labels: upgrade

#11944 element-desktop: update to 1.11.108
  app-web/element-desktop/spec
Labels: upgrade

#11955 vpl-gpu-rt: update to 25.3.1
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#11946 feishin: update to 0.19.0
  app-multimedia/feishin/spec
Labels: upgrade

#11947 gost: update to 3.2.0
  app-proxy/gost/autobuild/patches/0001-update-cpu-to-0.1.1-to-fix-build-on-loongarch64.patch
  app-proxy/gost/spec
Labels: upgrade

#11940 cyanrip: new, 0.9.3.1
  app-multimedia/cyanrip/autobuild/defines
  app-multimedia/cyanrip/spec
Labels: new-package

#11964 bgpq4: new, 1.15
  app-network/bgpq4/autobuild/defines
  app-network/bgpq4/spec
Labels: new-package

#11966 acbs: update to 20250803
  app-devel/acbs/spec
Labels: upgrade

#11968 yaru: new, 25.10.1
  desktop-themes/yaru/autobuild/defines
  desktop-themes/yaru/spec
Labels: new-package

#11961 wesnoth: update to 1.18.5
  app-games/wesnoth/spec
Labels: upgrade

#11972 telegram-desktop: update to 6.0.2
  app-web/telegram-desktop/spec
Labels: upgrade

#11974 swaylock: update to 1.8.3
  app-utils/swaylock/spec
Labels: upgrade

#11975 oma: update to 1.19.0
  app-admin/oma/spec
Labels: upgrade

#11982 sing-box: update to 1.12.0
  app-proxy/sing-box/autobuild/beyond
  app-proxy/sing-box/autobuild/patches/0001-backport-to-run-systemd-service-with-sing-box-user.patch
  app-proxy/sing-box/autobuild/prepare
  app-proxy/sing-box/spec
Labels: upgrade

#11978 fastfetch: detect cpu name and frequency on loongson3 via /proc/cpuinfo
  app-utils/fastfetch/autobuild/patches/0001-AOSCOS-LOONGSON3-CPU-Linux-detect-cpu-via-proc-cpuin.patch.loongson3
  app-utils/fastfetch/spec
Labels: enhancement

#11990 dunst: update to 1.13.0
  app-utils/dunst/spec
Labels: upgrade

#11991 gost: update to 3.2.1
  app-proxy/gost/spec
Labels: upgrade

#11992 repo: update to 2.57.3
  app-devel/repo/spec
Labels: upgrade

#12003 oma: update to 1.19.1
  app-admin/oma/spec
Labels: upgrade

#12014 llvm-20: update PKGBREAK and PKGREP
  app-devel/llvm-20/01-runtime/defines
  app-devel/llvm-20/01-runtime/defines.stage2
  app-devel/llvm-20/spec
Labels: has-fix

#11977 yukigram: new, 6.0.2
  app-web/yukigram/autobuild/defines
  app-web/yukigram/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/yukigram/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/yukigram/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/yukigram/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/yukigram/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/yukigram/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/yukigram/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/yukigram/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/yukigram/autobuild/patches/0009-fix-current_geo_location_linux-add-missing-QGuiAppli.patch
  app-web/yukigram/autobuild/patches/0010-fix-core_settings.h-enable-video-hardware-accelerati.patch
  app-web/yukigram/autobuild/patches/0011-fix-cmake-disable-CMP0160-to-workaround-KF5-cmake-er.patch
  app-web/yukigram/autobuild/patches/0012-fix-credits_amount.h-include-cmath-for-std-floor.patch
  app-web/yukigram/autobuild/patches/0013-Fix-desktop-file-name-on-Qt-5.patch
  app-web/yukigram/autobuild/prepare
  app-web/yukigram/spec
Labels: new-package

#9439 memtest86plus: Add translations for GRUB menu entry and grub-mkconfig output
  app-benchmarks/memtest86plus/autobuild/beyond
  app-benchmarks/memtest86plus/autobuild/overrides/etc/grub.d/26_memtest86plus
  app-benchmarks/memtest86plus/autobuild/patches/0001-temperature-Add-support-for-AMD-Excavator-440.patch
  app-benchmarks/memtest86plus/autobuild/patches/0002-Add-PCI-ID-for-the-SMBus-controller-behind-the-VT823.patch
  app-benchmarks/memtest86plus/autobuild/patches/0003-hwquirks-Detect-cache-on-VIA-VP3-MVP3-356.patch
  app-benchmarks/memtest86plus/autobuild/patches/0004-Add-a-few-RAM-manufacturers-in-JEDEC-DB.patch
  app-benchmarks/memtest86plus/autobuild/patches/0005-Fix-LD-error-while-linking-LoongArch-EFI-binary-457.patch
  app-benchmarks/memtest86plus/autobuild/patches/0006-system-hwquirks-Optimization-Loongson-7A2000-EHCI-qu.patch
  app-benchmarks/memtest86plus/autobuild/patches/0007-Add-Thermaltake-and-SSTC-Jedec-IDs.patch
  app-benchmarks/memtest86plus/autobuild/patches/0008-Ignore-PS-2-mouse-events-issue-456-484.patch
  app-benchmarks/memtest86plus/autobuild/patches/0009-Fix-DDR5-SPD-parsing-issue-for-XMP-3.0-frequency.patch
  app-benchmarks/memtest86plus/autobuild/patches/0010-loongarch-Supports-2K2000-3B6000M-512.patch
  app-benchmarks/memtest86plus/autobuild/patches/0011-Add-support-for-AMD-Hawk-Point-FP7-Phoenix.patch
  app-benchmarks/memtest86plus/autobuild/patches/0012-imc-Enable-support-for-AMD-Cezanne-Zen-3-APU-525.patch
  app-benchmarks/memtest86plus/autobuild/po/en_US.po
  app-benchmarks/memtest86plus/autobuild/po/memtest-grub.pot
  app-benchmarks/memtest86plus/autobuild/po/zh_CN.po
  app-benchmarks/memtest86plus/autobuild/po/zh_TW.po
  app-benchmarks/memtest86plus/spec
Labels: enhancement, blocked

#12013 clash-verge-rev: (arm64) use total_mem for ENVREQ
  app-proxy/clash-verge-rev/spec
Labels: has-fix

#11986 rime-ice: remove useless file
  app-i18n/rime-ice/autobuild/build
  app-i18n/rime-ice/spec
Labels: has-fix

#12022 bottom: update to 0.11.0
  app-admin/bottom/autobuild/defines
  app-admin/bottom/spec
Labels: upgrade

#11930 nushell: update to 0.106.1
  app-shells/nushell/spec
Labels: upgrade

#12034 gsoap: fix build
  runtime-network/gsoap/autobuild/defines
  runtime-network/gsoap/autobuild/patches/0001-Fedora-gsoap-libtool.patch
  runtime-network/gsoap/spec
Labels: has-fix

#12044 libcamera: update to 0.5.2
  runtime-devices/libcamera/autobuild/beyond
  runtime-devices/libcamera/autobuild/defines
  runtime-devices/libcamera/autobuild/defines.stage2
  runtime-devices/libcamera/spec
Labels: upgrade

#12039 lact: update to 0.8.1
  app-admin/lact/spec
Labels: upgrade

#12029 ed: update to 1.22.1
  app-editors/ed/spec
Labels: upgrade

#12047 melonds: update to 1.0
  app-games/melonds/spec
Labels: upgrade

#12048 wiliwili: update to 1.5.2
  app-multimedia/wiliwili/autobuild/defines
  app-multimedia/wiliwili/spec
Labels: upgrade

#12053 poetry-core: revert to 1.9.0
  lang-python/poetry-core/spec
Labels: downgrade

#12056 uv: update to 0.8.8
  lang-python/uv/spec
Labels: upgrade

#12006 hwdata: do not ship modprobe blacklist
  runtime-data/hwdata/autobuild/build
  runtime-data/hwdata/spec
Labels: has-fix

#12062 svt-av1: update to 3.1.0
  runtime-multimedia/svt-av1/autobuild/defines
  runtime-multimedia/svt-av1/spec
Labels: upgrade

#12064 gearlever: update to 3.4.1
  app-utils/gearlever/spec
Labels: upgrade

#12051 ayano: update to 0.1.4
  app-network/ayano/spec
Labels: upgrade

#12061 gost: update to 3.2.3
  app-proxy/gost/spec
Labels: upgrade

#12082 plog: update to 1.1.11
  runtime-common/plog/spec
Labels: upgrade

#12055 graphviz: update to 13.1.2
  app-doc/graphviz/spec
Labels: upgrade

#12058 dmenu: update to 5.4
  app-utils/dmenu/spec
Labels: upgrade

#12060 handbrake: update to 1.10.0
  app-multimedia/handbrake/spec
Labels: upgrade

#12087 ntfs-3g: fix build
  app-admin/ntfs-3g/autobuild/beyond
  app-admin/ntfs-3g/autobuild/defines
  app-admin/ntfs-3g/autobuild/patches/0003-fix-add-missing-header.patch
  app-admin/ntfs-3g/autobuild/patches/0004-fix-add-missing-header.dedup
  app-admin/ntfs-3g/autobuild/preinst
  app-admin/ntfs-3g/autobuild/prepare
  app-admin/ntfs-3g/spec
Labels: has-fix

#12038 firefox: update to 141.0.3
  app-web/firefox/autobuild/patches/0001-Fix-libyuv-unified-source-and-LoongArch-SIMD-build.patch
  app-web/firefox/autobuild/patches/0002-Bug-1977549-Refine-mlasx-usage-for-LoongArch-r-lsalz.patch
  app-web/firefox/spec
Labels: upgrade

#12103 atop: update to 2.12.0
  app-utils/atop/spec
Labels: upgrade

#12108 lazygit: update to 0.54.2
  app-vcs/lazygit/spec
Labels: upgrade

#12109 libdrm: update to 2.4.125
  runtime-display/libdrm/autobuild/defines
  runtime-display/libdrm/autobuild/patches/0001-Upstream-amdgpu-UAPI-for-AMDGPU-usermode-queues.patch
  runtime-display/libdrm/spec
Labels: upgrade

#12099 musicfox: update to 4.6.6
  app-multimedia/musicfox/spec
Labels: upgrade

#12086 bash-startup: update to 0.8.1
  runtime-data/bash-startup/spec
Labels: upgrade

#12104 nss: update to 3.114
  runtime-cryptography/nss/spec
Labels: upgrade

#12093 element-desktop: update to 1.11.109
  app-web/element-desktop/spec
Labels: upgrade

#12113 loonggpu-kernel-dkms: add patch to fix 4KiB-page kernel oops and hangs
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0001-chore-initialise-a-gitignore-file.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0002-loonggpu-include-use-video-aperture-helpers-for-Linu.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0003-loonggpu-pass-string-literal-parameter-to-MODULE_IMP.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0004-loonggpu-dkms-drop-deprecated-REMAKE_INITRD-yes-opti.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0005-loonggpu-gsgpu_dc_connector-gsgpu-bridge-drop-an-unu.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0006-loonggpu-gsgpu_vm-move-struct-definition-to-include-.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0007-loonggpu-gsgpu-gsgpu-bridge-lint-prototypes.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0008-AOSCOS-loonggpu-remove-driver-date.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0009-loonggpu-Remove-unused-fbdev_list-field-in-gsgpu_fra.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0010-loonggpu-Remove-the-unused-gsgpu_fbdev_total_size-fu.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0011-loonggpu-Improve-fbdev-object-test-helper.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0012-loonggpu-Remove-struct-gsgpu_fbdev-and-add-some-clea.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0013-loonggpu-Move-fbdev-cleanup-code-into-fb_destroy-cal.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0014-loonggpu-Remove-redundant-info-par-assignment.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0015-loonggpu-Remove-test-for-screen_base-in-fbdev-probin.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0016-loonggpu-Correctly-clean-up-failed-display-probing.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0017-loonggpu-Remove-load-callback-from-kms_driver.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0018-loonggpu-Implement-client-based-fbdev-emulation.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0019-loonggpu-Remove-a-redundant-gsgpu_fbdev_client_hotpl.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0020-loonggpu-Disable-outputs-when-releasing-fbdev-client.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0021-loonggpu-Run-DRM-default-client-setup.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0022-AOSCOS-loonggpu-Use-ccflags-y-instead-of-EXTRA_CFLAG.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0023-AOSCOS-loonggpu-Adapt-for-drm_sched_init-struct-para.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0024-AOSCOS-loonggpu-Adapt-for-renaming-of-from_timer-to-.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0025-AOSCOS-loonggpu-Adapt-for-renaming-of-del_timer_sync.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0026-loonggpu-bridge-Adapt-for-recent-kernel-API-changes.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0027-loonggpu-Remove-the-check-against-moving-pinned-BOs.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0028-loonggpu-Remove-dead-code.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0029-loonggpu-NFC-Clean-up-gsgpu_bo_move.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0030-loonggpu-Handle-tt-moves-properly.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0031-loonggpu-Use-multihop.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0032-loonggpu-Drop-the-unused-no_wait_gpu-parameter-of-gs.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0033-loonggpu-Drop-lg_ttm_tt_bind.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0034-loonggpu-Make-the-mode-parameter-of-the-mode_valid-c.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0035-loonggpu-Remove-an-invalid-const-qualifier.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0036-loonggpu-Fix-the-parameter-order-of-a-kmalloc_array-.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0037-loonggpu-Handle-the-different-drm_client_setup.h-loc.patch
  runtime-kernel/loonggpu-kernel-dkms/autobuild/patches.deferred/0038-loonggpu-Handle-the-error-from-gsgpu_driver_load_kms.patch
  runtime-kernel/loonggpu-kernel-dkms/spec
Labels: has-fix

#12112 easytier: update to 2.4.2
  app-network/easytier/autobuild/defines
  app-network/easytier/autobuild/patches/0001-build-remove-linker-configuration-for-aarch64-unknow.patch
  app-network/easytier/autobuild/patches/0001-optimize-easytier-web-features.patch
  app-network/easytier/spec
Labels: upgrade

#12123 crush: new, 0.5.0
  app-utils/crush/autobuild/beyond
  app-utils/crush/autobuild/defines
  app-utils/crush/spec
Labels: new-package

#12140 emacs: update to 30.2
  app-editors/emacs/spec
Labels: upgrade

#12134 skate: new, 1.0.1
  app-utils/skate/autobuild/defines
  app-utils/skate/spec
Labels: new-package

#12132 gum: new, 0.16.2
  app-utils/gum/autobuild/beyond
  app-utils/gum/autobuild/defines
  app-utils/gum/spec
Labels: new-package

#12141 pixi: update to 0.52.0
  app-devel/pixi/spec
Labels: upgrade

#12124 gost: update to 3.2.4
  app-proxy/gost/spec
Labels: upgrade

#12125 btrfs-progs: update to 6.16
  app-admin/btrfs-progs/spec
Labels: upgrade

#12130 cinny-desktop: update to 4.9.0
  app-web/cinny-desktop/autobuild/patches/0001-Disable-update-check.patch.cinny-desktop
  app-web/cinny-desktop/autobuild/patches/0001-Update-vite-plugin-top-level-await.patch.cinny
  app-web/cinny-desktop/autobuild/patches/0002-Use-rollup-wasm-node-to-fix-build-on-POWER8.patch.cinny
  app-web/cinny-desktop/spec
Labels: upgrade

#12137 tauri-cli: update to 2.7.1
  lang-rust/tauri-cli/autobuild/build
  lang-rust/tauri-cli/autobuild/defines
  lang-rust/tauri-cli/spec
Labels: upgrade

#12143 zotero: update to 7.0.23
  app-productivity/zotero/spec
Labels: upgrade

#12146 repo: update to 2.58
  app-devel/repo/spec
Labels: upgrade

#12131 mods: new, 1.8.1
  app-utils/mods/autobuild/beyond
  app-utils/mods/autobuild/defines
  app-utils/mods/spec
Labels: new-package

#12120 libxdg-basedir: fix build
  runtime-desktop/libxdg-basedir/autobuild/defines
  runtime-desktop/libxdg-basedir/autobuild/patches/alloc_buffer.patch
  runtime-desktop/libxdg-basedir/autobuild/patches/series
  runtime-desktop/libxdg-basedir/spec
Labels: has-fix

#12139 uv: update to 0.8.11
  lang-python/uv/spec
Labels: upgrade

#12138 xfsprogs: update to 6.15.0
  app-admin/xfsprogs/spec
Labels: upgrade

#12147 ispc: update to 1.28.0
  app-devel/ispc/spec
Labels: upgrade

#12153 crush: update to 0.6.1
  app-utils/crush/spec
Labels: upgrade

#12151 gnupg: add pinentry dependency
  app-cryptography/gnupg/autobuild/defines
  app-cryptography/gnupg/spec
Labels: dependencies

#12169 vscode: update to 1.103.1
  app-editors/vscode/spec
Labels: upgrade

#12160 typos: update to 1.35.4
  app-utils/typos/spec
Labels: upgrade

#12175 weechat: update to 4.7.1
  app-web/weechat/spec
Labels: upgrade

#12176 fastfetch: update to 2.50.2
  app-utils/fastfetch/spec
Labels: upgrade

#12178 z3: update to 4.15.3
  app-devel/z3/spec
Labels: upgrade

#12179 zotero: update to 7.0.24
  app-productivity/zotero/spec
Labels: upgrade

#12180 bleachbit: update to 5.0.1
  app-utils/bleachbit/autobuild/patches/0001-Remove-localization-cleanup-feature.patch
  app-utils/bleachbit/autobuild/patches/0002-replace-apt-support-with-oma-support.patch
  app-utils/bleachbit/autobuild/patches/0003-add-zh_CN-and-zh_TW-translations-for-oma.patch
  app-utils/bleachbit/autobuild/patches/0004-remove-update-check.patch
  app-utils/bleachbit/spec
Labels: upgrade

#12172 lfortran: update to 0.55.0
  app-devel/lfortran/spec
Labels: upgrade

#12170 openra: update to 20250330
  app-games/openra/autobuild/beyond
  app-games/openra/autobuild/build
  app-games/openra/autobuild/defines
  app-games/openra/autobuild/overrides/usr/share/pixmaps/openra-ts.png
  app-games/openra/autobuild/prepare
  app-games/openra/spec
Labels: upgrade

#12165 vhs: new, 0.10.0
  app-utils/vhs/autobuild/beyond
  app-utils/vhs/autobuild/defines
  app-utils/vhs/spec
Labels: new-package

#12190 asio: update to 1.36.0
  app-devel/asio/autobuild/defines
  app-devel/asio/spec
Labels: upgrade

#12198 intel-graphics-compiler: update to 2.16.0
  app-devel/intel-graphics-compiler/autobuild/beyond
  app-devel/intel-graphics-compiler/autobuild/defines
  app-devel/intel-graphics-compiler/autobuild/prepare
  app-devel/intel-graphics-compiler/spec
Labels: upgrade

#12197 git: update to 2.51.0
  app-vcs/git/spec
Labels: upgrade

#12208 gearlever: update to 3.4.2
  app-utils/gearlever/spec
Labels: upgrade

#12212 lfortran: update to 0.56.0
  app-devel/lfortran/spec
Labels: upgrade

#12211 tailscale: install completions
  app-network/tailscale/autobuild/beyond
  app-network/tailscale/spec
Labels: enhancement

#12216 ed: update to 1.22.2
  app-editors/ed/spec
Labels: upgrade

#12199 ddcutil: update to 2.2.1
  app-utils/ddcutil/spec
Labels: upgrade

#12210 sing-box: update to 1.12.2
  app-proxy/sing-box/spec
Labels: upgrade

#12221 sing-box: update to 1.12.3
  app-proxy/sing-box/spec
Labels: upgrade

#12222 zed: update to 0.200.4
  app-editors/zed/spec
Labels: upgrade

#12254 oma: update to 1.20.1
  app-admin/oma/spec
Labels: upgrade

#12262 pixi: update to 0.53.0
  app-devel/pixi/spec
Labels: upgrade

#12228 kitty: update to 0.42.2
  app-utils/kitty/spec
Labels: upgrade

#12227 msmtp: update to 1.8.30
  app-web/msmtp/spec
Labels: upgrade

#12267 conan: new, 2.19.1
  app-devel/conan/autobuild/defines
  app-devel/conan/spec
Labels: new-package

#12249 partimage: fix build errors
  app-admin/partimage/autobuild/beyond
  app-admin/partimage/autobuild/build
  app-admin/partimage/autobuild/defines
  app-admin/partimage/autobuild/overrides/usr/lib/sysusers.d/partimag.conf
  app-admin/partimage/autobuild/patches/zlib-1.2.6-new.patch
  app-admin/partimage/autobuild/postinst
  app-admin/partimage/autobuild/prepare
  app-admin/partimage/autobuild/usergroup
  app-admin/partimage/spec
Labels: has-fix

#12263 tauri-cli: update to 2.8.3
  lang-rust/tauri-cli/spec
Labels: upgrade

#12272 cherry-studio: update to 1.5.7
  app-utils/cherry-studio/autobuild/patches/0001-disable-auto-update-feature-by-default.patch
  app-utils/cherry-studio/spec
Labels: upgrade

#12264 xviewer: update to 3.4.11
  app-imaging/xviewer/spec
Labels: upgrade

#12269 crush: update to 0.7.1
  app-utils/crush/spec
Labels: upgrade

#12309 which: update to 2.23
  app-utils/which/spec
Labels: upgrade

#12307 xviewer: update to 3.4.12
  app-imaging/xviewer/spec
Labels: upgrade

#12310 wireshark: update to 4.4.9
  app-network/wireshark/spec
Labels: upgrade

#12287 vpl-gpu-rt: update to 25.3.2
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#12280 iosevka-fonts: update to 33.2.8
  desktop-fonts/iosevka-fonts/spec
Labels: upgrade

#12281 meson: update to 1.9.0
  app-devel/meson/spec
Labels: upgrade

#12302 darktable: update to 5.2.1
  app-creativity/darktable/spec
Labels: upgrade

#12276 liquidsfz: fix build error
  app-multimedia/liquidsfz/autobuild/patches/0001-fix-std-sort-undefine.patch
  app-multimedia/liquidsfz/spec
Labels: has-fix

#12306 pcl:update to 1.15.1
  runtime-imaging/pcl/spec
Labels: upgrade

#12322 ispc: update to 1.28.1
  app-devel/ispc/spec
Labels: upgrade

#12289 heimdall: fix build error
  app-devices/heimdall/autobuild/build
  app-devices/heimdall/spec
Labels: has-fix

#12320 wine: update to 10.14+gecko2.47.4+mono10.2.0
  app-emulation/wine/spec
Labels: upgrade

#12245 handbrake: update to 1.10.1
  app-multimedia/handbrake/spec
Labels: upgrade

#12325 graphviz: Add gtk-3, poppler, and devil into PKGDEP
  app-doc/graphviz/autobuild/defines
  app-doc/graphviz/spec
Labels: dependencies

#12323 vkd3d: update to 1.17
  runtime-display/vkd3d/spec
Labels: upgrade

#12308 zed: update to 0.201.6
  app-editors/zed/autobuild/defines
  app-editors/zed/spec
Labels: upgrade

#12328 viddy: new, 1.3.0
  app-utils/viddy/autobuild/defines
  app-utils/viddy/spec
Labels: new-package

#12324 kind: update to 0.30.0
  app-containers/kind/spec
Labels: upgrade

#12288 feh: update to 3.11
  app-imaging/feh/spec
Labels: upgrade

#12331 zed: update to 0.201.8
  app-editors/zed/spec
Labels: upgrade

#12337 aosc-os-repository-data: update to 20250831
  runtime-data/aosc-os-repository-data/spec
Labels: upgrade

#12330 flint: update to 3.3.1
  runtime-scientific/flint/autobuild/build
  runtime-scientific/flint/autobuild/defines
  runtime-scientific/flint/autobuild/patches/flint-pie-hardening-conflict.patch
  runtime-scientific/flint/spec
Labels: upgrade
