Repository AOSC-Dev/aosc-os-abbs, pull requests merged in 2025-05, with the labels that each got.

#10699 wmenu: update to 0.2.0
  app-utils/wmenu/spec
Labels: upgrade

#10700 praat: update to 6.4.30
  app-scientific/praat/spec
Labels: upgrade

#10704 pkgsite-tools: new, 0.3.3
  app-utils/pkgsite-tools/autobuild/beyond
  app-utils/pkgsite-tools/autobuild/defines
  app-utils/pkgsite-tools/spec
Labels: new-package

#10705 libreoffice: update to 25.2.3.2
  app-productivity/libreoffice/spec
Labels: upgrade

#10709 cyrus-sasl: add patch Fix-time.h-check
  app-network/cyrus-sasl/autobuild/patches/0001-Fix-time.h-check.patch
  app-network/cyrus-sasl/autobuild/patches/0002-Fix-build-with-Wl-as-needed.patch
  app-network/cyrus-sasl/autobuild/patches/0003-Make-the-libsasl2-symbols-versioned.patch
  app-network/cyrus-sasl/spec
Labels: has-fix

#10716 octave: rework to remove restricted syntaxes in defines file
  app-scientific/octave/autobuild/defines
  app-scientific/octave/autobuild/patches/0001-AOSCOS-Find-OpenJDK-of-zero-variant.patch
  app-scientific/octave/spec
Labels: rework

#10719 foot: update to 1.22.2
  app-utils/foot/spec
Labels: upgrade

#10720 pkgsite-tools: update to 0.3.4
  app-utils/pkgsite-tools/spec
Labels: upgrade

#10701 rsms-inter-fonts: new, 4.1
  desktop-fonts/rsms-inter-fonts/autobuild/build
  desktop-fonts/rsms-inter-fonts/autobuild/defines
  desktop-fonts/rsms-inter-fonts/spec
Labels: new-package

#10721 pakfixer: new, 0.1.3
  app-utils/pakfixer/autobuild/defines
  app-utils/pakfixer/spec
Labels: new-package

#10693 xcaddy: update to 0.4.4
  app-web/xcaddy/autobuild/beyond
  app-web/xcaddy/autobuild/build
  app-web/xcaddy/autobuild/defines
  app-web/xcaddy/autobuild/patches/0001-enable-specifying-build-version.patch
  app-web/xcaddy/spec
Labels: upgrade

#10722 foot: update to 1.22.3
  app-utils/foot/spec
Labels: upgrade

#10725 hugo: update to 0.147.1
  app-web/hugo/spec
Labels: upgrade

#10728 uv: update to 0.7.2
  lang-python/uv/spec
Labels: upgrade

#10726 papirus-icon-theme: update to 20250501
  desktop-themes/papirus-icon-theme/spec
Labels: upgrade

#10733 forgejo: update to 11.0.0
  app-web/forgejo/spec
Labels: upgrade

#10737 eza: update to 0.21.3
  app-utils/eza/spec
Labels: upgrade

#10731 btop: update to 1.4.2
  app-utils/btop/spec
Labels: upgrade

#10730 bitwarden: update to 2025.4.2
  app-utils/bitwarden/spec
Labels: upgrade

#10740 systemd: add patch basic-linux-update-kernel-headers-from-v6.14-rc1
  app-admin/systemd/autobuild/patches/0001-AOSCOS-sleep.conf-AllowHibernation-no-by-default.patch
  app-admin/systemd/autobuild/patches/0002-AOSCOS-fix-do-not-tint-terminal-by-default.patch
  app-admin/systemd/autobuild/patches/0003-AOSCOS-mount-setup.c-do-not-sleep-during-boot.patch
  app-admin/systemd/autobuild/patches/0004-exec-credential-try-forking-again-without-CLONE_NEWN.patch
  app-admin/systemd/autobuild/patches/0005-basic-linux-update-kernel-headers-from-v6.14-rc1.patch
  app-admin/systemd/spec
Labels: upgrade

#10727 bash-git-status: update to 0.3.1
  app-vcs/bash-git-status/spec
Labels: upgrade

#10756 geary: drop, orphaned
  desktop-gnome/geary/autobuild/defines
  desktop-gnome/geary/spec
  groups/folks-rebuilds
  groups/gnome
  groups/icu-rebuilds
  groups/webkit2gtk-rebuilds
Labels: drop-package

#10746 typos: update to 1.32.0
  app-utils/typos/spec
Labels: upgrade

#10742 chezmoi: new, 2.62.2
  app-utils/chezmoi/autobuild/beyond
  app-utils/chezmoi/autobuild/defines
  app-utils/chezmoi/autobuild/prepare
  app-utils/chezmoi/spec
Labels: new-package

#10751 oma: update to 1.16.6
  app-admin/oma/spec
Labels: upgrade

#10706 llvm-20: update to 20.1.4
  app-devel/llvm-20/01-runtime/patches/0001-Fix-fuzzer-objects-building-when-LTO-is-enabled.patch
  app-devel/llvm-20/01-runtime/patches/0002-Fix-MSVC-detection.patch
  app-devel/llvm-20/01-runtime/patches/0003-Add-stub-for-mips64-LLDB-impl.patch
  app-devel/llvm-20/01-runtime/patches/0004-Add-stub-for-lldb-arch-functions-on-loongson3.patch
  app-devel/llvm-20/01-runtime/patches/0005-HACK-force-enable-cacheflush-function.patch
  app-devel/llvm-20/01-runtime/patches/0006-Fix-build-of-LinuxSignals-on-Mips.patch
  app-devel/llvm-20/01-runtime/patches/0007-Compile-with-MT-on-MSVC.patch
  app-devel/llvm-20/01-runtime/patches/0008-rust-Changes-needed-for-x86_64-fortanix-unknown-sgx-.patch
  app-devel/llvm-20/01-runtime/patches/0009-compiler-rt-Disable-installing-of-custom-libcxx.patch
  app-devel/llvm-20/spec
Labels: upgrade

#10660 mihomo-party: drop, orphaned
  app-network/mihomo-party/autobuild/build
  app-network/mihomo-party/autobuild/defines
  app-network/mihomo-party/autobuild/overrides/usr/share/applications/mihomo-party.desktop
  app-network/mihomo-party/autobuild/patches/0001-Keep-old-productName-on-linux.patch
  app-network/mihomo-party/autobuild/patches/0002-Add-loong64-support.patch.loongarch64
  app-network/mihomo-party/spec
Labels: has-fix

#10628 gcc-15: new, 15.1.0
  app-devel/gcc-15/autobuild/beyond
  app-devel/gcc-15/autobuild/defines
  app-devel/gcc-15/autobuild/patches/0001-libiberty-also-generate-a-PIC-version-of-libiberty.a.patch
  app-devel/gcc-15/autobuild/patches/0002-NFU-mips-disable-ext-dce-by-default.patch
  app-devel/gcc-15/autobuild/prepare
  app-devel/gcc-15/spec
Labels: new-package

#10748 fractal: update to 11
  desktop-gnome/fractal/spec
Labels: upgrade

#10754 quickjs: update to 2025.04.26
  lang-js/quickjs/autobuild/build
  lang-js/quickjs/autobuild/defines
  lang-js/quickjs/autobuild/patches/0001-Disable-strip-for-debug-symbol-in-AOSC.patch
  lang-js/quickjs/spec
Labels: upgrade

#10732 telegram-desktop: update to 5.14.1
  app-web/telegram-desktop/autobuild/defines
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-fix-current_geo_location_linux-add-missing-QGuiAppli.patch
  app-web/telegram-desktop/autobuild/patches/0010-fix-core_settings.h-enable-video-hardware-accelerati.patch
  app-web/telegram-desktop/autobuild/patches/0011-FROM-TERMUX-allow-use-external-libtd.patch
  app-web/telegram-desktop/autobuild/patches/1001-FROM-TERMUX-libtd-install-headers-to-system.patch.td.deferred
  app-web/telegram-desktop/autobuild/patches/1001-tg_owt_Patch-Fix-build-with-PipeWire-1.4.patch.deferred
  app-web/telegram-desktop/autobuild/prepare
  app-web/telegram-desktop/spec
Labels: upgrade

#10760 iotop: update to 1.28
  app-utils/iotop/autobuild/patches/0001-install-binary-to-bin-instead-of-sbin.patch
  app-utils/iotop/autobuild/patches/0002-do-not-strip-during-compilation.patch
  app-utils/iotop/spec
Labels: upgrade

#10762 cargo-audit: update to 0.21.2
  lang-rust/cargo-audit/spec
Labels: upgrade

#10767 sing-box: update to 1.11.10
  app-network/sing-box/autobuild/beyond
  app-network/sing-box/autobuild/defines
  app-network/sing-box/autobuild/prepare
  app-network/sing-box/spec
Labels: upgrade

#10773 libapt-pkg-perl: update to 0.1.42
  lang-perl/libapt-pkg-perl/spec
Labels: upgrade

#10769 pkgsite-tools: update to 0.7.2
  app-utils/pkgsite-tools/autobuild/defines
  app-utils/pkgsite-tools/spec
Labels: upgrade

#10766 libwapcaplet: fix build issue ABTYPE missing
  runtime-web/libwapcaplet/autobuild/build
  runtime-web/libwapcaplet/autobuild/defines
  runtime-web/libwapcaplet/spec
Labels: has-fix

#10785 libglibutil: update to 1.0.80
  runtime-common/libglibutil/spec
Labels: upgrade

#10784 element-desktop: update to 1.11.100
  app-web/element-desktop/spec
Labels: upgrade

#10790 iotop: update to 1.29
  app-utils/iotop/spec
Labels: upgrade

#10778 bleachbit: update to 5.0.0
  app-utils/bleachbit/autobuild/patches/0001-Remove-localization-cleanup-feature.patch
  app-utils/bleachbit/autobuild/patches/0002-replace-apt-support-with-oma-support.patch
  app-utils/bleachbit/autobuild/patches/0003-add-zh_CN-and-zh_TW-translation-for-oma.patch
  app-utils/bleachbit/autobuild/patches/0003-add-zh_CN-and-zh_TW-translations-for-oma.patch
  app-utils/bleachbit/autobuild/patches/0004-remove-update-check.patch
  app-utils/bleachbit/spec
Labels: upgrade

#10791 bash-git-status: update to 0.3.2
  app-vcs/bash-git-status/spec
Labels: upgrade

#10779 expect: fix build with GCC >= 14
  app-utils/expect/autobuild/patches/0001-fix-build-with-GCC-14.patch
  app-utils/expect/spec
Labels: has-fix

#10792 idnkit: fix build with GCC >= 14
  app-network/idnkit/autobuild/patches/0001-AOSCOS-fix-build-with-GCC-14.patch
  app-network/idnkit/spec
Labels: has-fix

#10765 dhcpcd: set ABTYPE to autotools
  app-network/dhcpcd/autobuild/defines
  app-network/dhcpcd/spec
Labels: has-fix

#10793 chezmoi: update to 2.62.3
  app-utils/chezmoi/spec
Labels: upgrade

#10799 hddtemp: fix build with GCC >= 14
  app-utils/hddtemp/autobuild/patches/0001-apply-patch-hddtemp_0.3-beta15-52.diff-from-debian.patch
  app-utils/hddtemp/autobuild/patches/0002-apply-patch-hddtemp-user-context-type.patch-from-fed.patch
  app-utils/hddtemp/autobuild/patches/0003-AOSCOS-fix-build-with-GCC-14.patch
  app-utils/hddtemp/autobuild/patches/hddtemp-user-context-type.patch
  app-utils/hddtemp/spec
Labels: has-fix

#10798 feishin: update to 0.12.5
  app-multimedia/feishin/spec
Labels: upgrade

#10801 fd: remove NOLTO__LOONGARCH64 USECLANG__LOONGARCH64
  app-utils/fd/autobuild/defines
  app-utils/fd/spec
Labels: loongarch64

#10796 smartmontools: update to 7.5
  app-admin/smartmontools/autobuild/defines
  app-admin/smartmontools/spec
Labels: upgrade

#10802 bat: workaround submodule failure
  app-utils/bat/autobuild/patches/0001-remove-LiveScript-submodule.patch.deferred
  app-utils/bat/autobuild/prepare
  app-utils/bat/spec
Labels: has-fix

#10806 udns: update to 0.6
  app-network/udns/autobuild/build
  app-network/udns/autobuild/defines
  app-network/udns/spec
Labels: upgrade

#10805 mdadm: fix patch error
  app-admin/mdadm/autobuild/build
  app-admin/mdadm/autobuild/patches/0001-preserve-mdadm-variant-names-static-tcc-uclibc-klibc.patch
  app-admin/mdadm/autobuild/patches/0002-skip-md-handling-in-favor-of-65-md-incremental.rules.patch
  app-admin/mdadm/autobuild/patches/mdadm-3.3-udev.patch
  app-admin/mdadm/spec
Labels: has-fix

#10808 pv: add a build script
  app-utils/pv/autobuild/build
  app-utils/pv/autobuild/defines
  app-utils/pv/autobuild/prepare
  app-utils/pv/spec
Labels: has-fix

#10807 rfkill: add a build script
  app-utils/rfkill/autobuild/build
  app-utils/rfkill/autobuild/defines
  app-utils/rfkill/spec
Labels: has-fix

#10763 cgdb: fix compilation with GCC >= 14
  app-devel/cgdb/autobuild/defines
  app-devel/cgdb/autobuild/patches/0001-config-fix-compilation-with-GCC14.patch
  app-devel/cgdb/spec
Labels: has-fix

#10812 powertop: fix build and enhance functionalities
  app-utils/powertop/autobuild/defines
  app-utils/powertop/autobuild/patches/0001-tracefs-Use-libtracefs-and-libtraceevent.patch
  app-utils/powertop/autobuild/patches/0002-tracefs-Use-tracefs_event_file_read-to-find-the-even.patch
  app-utils/powertop/autobuild/patches/0003-Fixed-RISCV-T-Head-1520-CPU-identification.patch
  app-utils/powertop/autobuild/patches/0004-on-is-also-good-as-reported-by-Paul-Menzel.patch
  app-utils/powertop/autobuild/patches/0005-Add-Intel-Arrow-Lake-support.patch
  app-utils/powertop/autobuild/patches/0006-Fix-battery-runtime-estimation-with-negative-sysfs-v.patch
  app-utils/powertop/autobuild/patches/0007-Use-AM_GNU_GETTEXT_REQUIRE_VERSION-to-avoid-version-.patch
  app-utils/powertop/autobuild/prepare
  app-utils/powertop/spec
Labels: enhancement, has-fix

#10809 fwupd: update to 2.0.9
  app-admin/fwupd/spec
Labels: upgrade

#10813 guitarix: update to 0.46.0
  app-multimedia/guitarix/autobuild/patches/0001-FEDORA-guitarix-cstdint-include.patch
  app-multimedia/guitarix/autobuild/patches/0002-FEDORA-guitarix-mismatched-delete.patch
  app-multimedia/guitarix/autobuild/patches/0003-FEDORA-guitarix-python-3.11-ftbfs.patch
  app-multimedia/guitarix/spec
Labels: upgrade

#10818 fwupd: add readline to PKGDEP
  app-admin/fwupd/autobuild/defines
  app-admin/fwupd/spec
Labels: dependencies

#10821 libmbim: update to 1.32.0
  runtime-devices/libmbim/spec
Labels: upgrade

#10822 git-branchless: update to 0.10.0
  app-utils/git-branchless/spec
Labels: upgrade

#10825 yq: update to 4.45.2
  app-devel/yq/spec
Labels: upgrade

#10815 firefox: update to 138.0.1
  app-web/firefox/spec
Labels: upgrade

#10823 zed: update to 0.185.12
  app-editors/zed/spec
Labels: upgrade

#10842 libidn2: replace ronn with ronn-ng
  runtime-network/libidn2/autobuild/defines
  runtime-network/libidn2/spec
Labels: dependencies

#10837 ldns: update to 1.8.4
  runtime-network/libidn2/autobuild/defines
  runtime-network/libidn2/spec
Labels: upgrade

#10841 cracklib: fix build with Autobuild4
  runtime-cryptography/cracklib/autobuild/beyond
  runtime-cryptography/cracklib/autobuild/defines
  runtime-cryptography/cracklib/spec
Labels: has-fix

#10830 file: drop Python 2 bindings
  app-utils/file/autobuild/beyond
  app-utils/file/autobuild/defines
  app-utils/file/spec
Labels: dependencies

#10836 qrencode: fix source link
  runtime-imaging/qrencode/spec
Labels: has-fix

#10834 argon2: fix build and improve packaging
  runtime-cryptography/argon2/autobuild/build
  runtime-cryptography/argon2/autobuild/defines
  runtime-cryptography/argon2/spec
Labels: enhancement, has-fix

#10833 snowball: improve patch record
  runtime-common/snowball/autobuild/patches/0001-AOSCOS-feat-build-dynamic-libraries-by-default.patch
  runtime-common/snowball/spec
Labels: enhancement

#10846 uv: update to 0.7.3
  lang-python/uv/spec
Labels: upgrade

#10847 kitty: update to 0.41.1
  app-utils/kitty/spec
Labels: upgrade

#10849 byobu: update to 6.13
  app-utils/byobu/spec
Labels: upgrade

#10826 apt: add support for sub-architectures
  app-admin/apt/autobuild/defines
  app-admin/apt/autobuild/defines.stage2
  app-admin/apt/spec
Labels: new-port

#10853 autobuild4: update to 4.11.0
  app-devel/autobuild4/spec
Labels: upgrade

#10840 wheel: add flit-core dep
  lang-python/wheel/autobuild/defines
  lang-python/wheel/spec
Labels: core, dependencies

#10835 freeglut: (no build) use GitHub source
  runtime-display/freeglut/spec
Labels: has-fix, upstream-issue

#10828 bcache-tools: improve patch record
  app-admin/bcache-tools/autobuild/patches/0001-AOSCOS-fix-bcache.c-do-not-inline-crc64.patch
  app-admin/bcache-tools/autobuild/patches/crc64.patch
  app-admin/bcache-tools/spec
Labels: enhancement

#10832 libatomic-ops: use Git source
  runtime-common/libatomic-ops/spec
Labels: has-fix, upstream-issue

#10854 bup: drop, orphaned
  app-utils/bup/autobuild/build
  app-utils/bup/autobuild/defines
  app-utils/bup/spec
Labels: drop-package

#10851 openrazer: update to 3.10.3
  app-devices/openrazer/spec
Labels: upgrade

#10820 deskflow: update to 1.21.2
  app-utils/deskflow/autobuild/patches/0001-AOSCOS-fix-neuter-version-checking-functionalities.patch
  app-utils/deskflow/spec
Labels: upgrade

#10811 gettext: update to 0.25
  app-devel/gettext/autobuild/beyond
  app-devel/gettext/autobuild/defines
  app-devel/gettext/autobuild/defines.stage2
  app-devel/gettext/autobuild/prepare
  app-devel/gettext/spec
Labels: upgrade

#10857 gdb: disable simulator
  app-devel/gdb/autobuild/defines
  app-devel/gdb/autobuild/defines.stage2
  app-devel/gdb/spec
Labels: enhancement, dependencies

#10858 openblas: rebuild for static library stripping
  app-scientific/openblas/spec
Labels: has-fix

#10860 gnupg: update to 2.5.6
  app-cryptography/gnupg/spec
Labels: upgrade

#10855 qt-6: rebuild for static library stripping
  runtime-desktop/qt-6/spec
Labels: has-fix

#10863 autobuild4: update to 4.11.1
  app-devel/autobuild4/spec
Labels: upgrade

#10868 syncthing: update to 1.29.6
  app-network/syncthing/spec
Labels: upgrade

#10870 kicad: update to 9.0.2
  app-electronics/kicad/spec
Labels: upgrade

#10867 aosc-aaa: fix /var/run to ../run symlink
  core-misc/aosc-aaa/autobuild/build
  core-misc/aosc-aaa/spec
Labels: has-fix

#10865 php: update to 8.4.7
  app-devel/php/spec
Labels: upgrade

#10862 man-pages: update to 6.14+posix2017a
  runtime-data/man-pages/spec
Labels: upgrade

#10859 feishin: update to 0.12.6
  app-multimedia/feishin/spec
Labels: upgrade

#10861 lfortran: update to 0.52.0
  app-devel/lfortran/spec
Labels: upgrade

#10872 Revert "versioneer: drop, orphaned"
  lang-python/versioneer/autobuild/defines
  lang-python/versioneer/spec
Labels: new-package

#10874 vscode: update to 1.100.0
  app-editors/vscode/spec
Labels: upgrade

#10876 adw-gtk3: update to 6.2
  desktop-themes/adw-gtk3/spec
Labels: upgrade

#10873 fcitx5-pinyin-moegirl: update to 20250509
  app-i18n/fcitx5-pinyin-moegirl/spec
Labels: upgrade

#10878 glab: new, 1.57.0
  app-devel/glab/autobuild/beyond
  app-devel/glab/autobuild/defines
  app-devel/glab/spec
Labels: new-package

#10882 bash-startup: update to 0.7.2
  runtime-data/bash-startup/spec
Labels: upgrade

#10880 stress-ng: update to 0.19.00
  app-benchmarks/stress-ng/spec
Labels: upgrade

#10871 vscodium: update to 1.100.03093
  app-editors/vscodium/autobuild/build
  app-editors/vscodium/spec
Labels: upgrade

#10879 adaptivecpp: update to 25.02.0
  app-devel/adaptivecpp/autobuild/defines
  app-devel/adaptivecpp/spec
Labels: upgrade

#10893 systemd: move libxkbcommon to build dependency
  app-admin/systemd/autobuild/defines
  app-admin/systemd/spec
Labels: dependencies

#10897 uboot-tools: add loongarch64 support
  app-utils/uboot-tools/autobuild/patches/0001-lib-fdtdec-Handle-multiple-memory-nodes.patch
  app-utils/uboot-tools/autobuild/patches/0002-linux-io.h-Use-map_physmem-to-implement-ioremap.patch
  app-utils/uboot-tools/autobuild/patches/0003-image-Take-entry-point-as-an-output-of-setup_booti.patch
  app-utils/uboot-tools/autobuild/patches/0004-elf.h-Define-LoongArch-bits.patch
  app-utils/uboot-tools/autobuild/patches/0005-image-Define-IH_ARCH_LOONGARCH.patch
  app-utils/uboot-tools/autobuild/patches/0006-LoongArch-skeleton-and-headers.patch
  app-utils/uboot-tools/autobuild/patches/0007-LoongArch-lib-General-routines.patch
  app-utils/uboot-tools/autobuild/patches/0008-LoongArch-CPU-assembly-routines.patch
  app-utils/uboot-tools/autobuild/patches/0009-LoongArch-Exception-handling.patch
  app-utils/uboot-tools/autobuild/patches/0010-LoongArch-Boot-Image-bits.patch
  app-utils/uboot-tools/autobuild/patches/0011-LoongArch-Generic-CPU-type.patch
  app-utils/uboot-tools/autobuild/patches/0012-cpu-Add-loongarch_cpu-driver.patch
  app-utils/uboot-tools/autobuild/patches/0013-timer-Add-loongarch_timer-driver.patch
  app-utils/uboot-tools/autobuild/patches/0014-board-emulation-Add-qemu-loongarch.patch
  app-utils/uboot-tools/autobuild/patches/0015-efi-LoongArch-Define-LoongArch-bits-everywhere.patch
  app-utils/uboot-tools/autobuild/patches/0016-efi-LoongArch-Implement-everything.patch
  app-utils/uboot-tools/spec
Labels: hardware-support

#10848 tio: update to 3.9
  app-utils/tio/spec
Labels: upgrade

#10898 lxml: update to 5.4.0
  lang-python/lxml/autobuild/defines
  lang-python/lxml/autobuild/patches/0001-Add-missing-import.patch
  lang-python/lxml/autobuild/patches/0002-Build-Switch-to-Cython-3.1.patch
  lang-python/lxml/autobuild/patches/0003-Avoid-custom-tp_new-call-and-add-a-safe-guard-that-e.patch
  lang-python/lxml/spec
Labels: upgrade

#10892 btop: update to 1.4.3
  app-utils/btop/spec
Labels: upgrade

#10890 mpvpaper: update to 1.8
  app-utils/mpvpaper/spec
Labels: upgrade

#10891 z3: update to 4.15.0
  app-devel/z3/spec
Labels: upgrade

#10909 rpi-firmware-boot: update to 1.20250430
  runtime-kernel/rpi-firmware-boot/spec
Labels: upgrade

#10914 flatpak: update to 1.16.1
  app-admin/flatpak/spec
Labels: upgrade

#10918 shadowsocks-rust: update to 1.23.3
  app-network/shadowsocks-rust/spec
Labels: upgrade

#10937 x264: fix build with Autobuild4
  runtime-multimedia/x264/autobuild/build
  runtime-multimedia/x264/autobuild/defines
  runtime-multimedia/x264/spec
Labels: has-fix

#10877 telegram-desktop: update to 5.14.2
  app-web/telegram-desktop/autobuild/patches/0001-fix-window.style-set-default-window-width-to-360px.patch
  app-web/telegram-desktop/autobuild/patches/0002-fix-core_settings.h-use-system-window-decoration-by-.patch
  app-web/telegram-desktop/autobuild/patches/0003-fix-ui-fix-build-with-Qt-5.patch
  app-web/telegram-desktop/autobuild/patches/0004-fix-core-launcher.cpp-revert-to-old-HiDPI-handling-b.patch
  app-web/telegram-desktop/autobuild/patches/0005-fix-settings-use-system-fonts-by-default.patch
  app-web/telegram-desktop/autobuild/patches/0006-Remove-the-confusing-Default-option-from-selectable-.patch
  app-web/telegram-desktop/autobuild/patches/0007-fix-lib_tl-add-missing-cstring-include.patch
  app-web/telegram-desktop/autobuild/patches/0008-fix-lib_webview-add-missing-cstdint-include.patch
  app-web/telegram-desktop/autobuild/patches/0009-fix-current_geo_location_linux-add-missing-QGuiAppli.patch
  app-web/telegram-desktop/autobuild/patches/0010-fix-core_settings.h-enable-video-hardware-accelerati.patch
  app-web/telegram-desktop/autobuild/patches/0011-FROM-TERMUX-allow-use-external-libtd.patch
  app-web/telegram-desktop/autobuild/patches/0011-fix-cmake-disable-CMP0160-to-workaround-KF5-cmake-er.patch
  app-web/telegram-desktop/autobuild/patches/0012-fix-cmake-use-correct-namespace-for-tde2d.patch
  app-web/telegram-desktop/autobuild/patches/0013-fix-codegen-fix-build-with-paths-with-in-them.patch
  app-web/telegram-desktop/autobuild/patches/1001-FROM-TERMUX-libtd-install-headers-to-system.patch.td.deferred
  app-web/telegram-desktop/autobuild/prepare
  app-web/telegram-desktop/spec
Labels: upgrade

#10932 guile-2.2: fix build
  lang-lisp/guile-2.2/autobuild/defines
  lang-lisp/guile-2.2/spec
Labels: has-fix

#10923 [no build] mpg123: (stage2) sync --disable-portable
  app-multimedia/mpg123/autobuild/defines.stage2
Labels: has-fix

#10924 [no build] pulseaudio: (stage2) sync beyond from main script
  app-multimedia/pulseaudio/autobuild/beyond
  app-multimedia/pulseaudio/autobuild/beyond.stage2
Labels: has-fix

#10927 gtk-2: fix build with GCC >= 14
  desktop-gnome/gtk-2/autobuild/patches/0001-FEDORA-Fix-fallout-from-g_object_ref-change.patch
  desktop-gnome/gtk-2/autobuild/patches/0001-icon-padding.patch
  desktop-gnome/gtk-2/autobuild/patches/0002-FEDORA-immodule-fix-a-GCC-warning.patch
  desktop-gnome/gtk-2/autobuild/patches/0002-tooltip-positioning.patch
  desktop-gnome/gtk-2/autobuild/patches/0003-FEDORA-GtkScale-Fix-late-setting-of-marks.patch
  desktop-gnome/gtk-2/autobuild/patches/0003-xid-collision-debug.patch
  desktop-gnome/gtk-2/autobuild/patches/0004-FEDORA-Return-the-expected-GObject-type.patch
  desktop-gnome/gtk-2/autobuild/patches/0005-FEDORA-testsuite-gtk-defaultvalue-Actually-build.-fi.patch
  desktop-gnome/gtk-2/autobuild/patches/0006-FEDORA-Convert-to-the-expected-pointer.patch
  desktop-gnome/gtk-2/autobuild/patches/0007-FEDORA-tests-Too-many-arguments-in-call-to-create_me.patch
  desktop-gnome/gtk-2/spec
Labels: has-fix

#10948 flatseal: new, 2.3.1
  app-utils/flatseal/autobuild/defines
  app-utils/flatseal/spec
Labels: new-package

#10942 ftjam: fix build with GCC >= 14
  app-devel/ftjam/autobuild/build
  app-devel/ftjam/autobuild/patches/0001-AOSCOS-fix-jam.h-fix-build-with-GCC-14.patch
  app-devel/ftjam/autobuild/prepare
  app-devel/ftjam/spec
Labels: has-fix

#10919 m4: update to 1.4.20
  app-utils/m4/spec
Labels: upgrade

#10928 libgee: update to 0.20.8
  desktop-gnome/libgee/spec
Labels: upgrade

#10926 enca: disable RECONF due to re-generation failure
  app-utils/enca/autobuild/defines
  app-utils/enca/spec
Labels: has-fix

#10949 freerdp: update to 3.15.0
  app-network/freerdp/spec
Labels: upgrade

#10925 v4l-utils: fix build
  app-multimedia/v4l-utils/autobuild/defines
  app-multimedia/v4l-utils/spec
Labels: has-fix

#10934 gsm: rebase Makefile patch to fix build
  runtime-multimedia/gsm/autobuild/patches/0001-fix-Makefile-miscellaneous-fix-ups.patch
  runtime-multimedia/gsm/spec
Labels: has-fix

#10921 rtkit: use sysusers.d for user/group creation
  app-admin/rtkit/autobuild/overrides/usr/lib/sysusers.d/rtkit.conf
  app-admin/rtkit/autobuild/postinst
  app-admin/rtkit/autobuild/usergroup
  app-admin/rtkit/spec
Labels: enhancement

#10935 libbluray: specify OpenJDK 17 to fix build
  runtime-multimedia/libbluray/autobuild/defines
  runtime-multimedia/libbluray/autobuild/prepare
  runtime-multimedia/libbluray/spec
Labels: has-fix

#10920 gconf: fix build
  app-admin/gconf/autobuild/defines
  app-admin/gconf/spec
Labels: has-fix

#10967 pfetch: new, 2.11.1
  app-utils/pfetch/autobuild/defines
  app-utils/pfetch/spec
Labels: new-package

#10962 feishin: update to 0.12.7
  app-multimedia/feishin/spec
Labels: upgrade

#10963 fastfetch: update to 2.43.0
  app-utils/fastfetch/spec
Labels: upgrade

#10964 libdecor: update to 0.2.3
  runtime-desktop/libdecor/spec
Labels: upgrade

#10965 shadowsocks-rust: update to 1.23.4
  app-network/shadowsocks-rust/spec
Labels: upgrade

#10966 vpl-gpu-rt: update to 25.2.2
  runtime-multimedia/vpl-gpu-rt/spec
Labels: upgrade

#10973 xdg-desktop-portal: update to 1.20.1
  app-admin/xdg-desktop-portal/spec
Labels: upgrade

#10971 fractal: update to 11.1
  desktop-gnome/fractal/spec
Labels: upgrade

#10975 rustc: update to 1.87.0
  lang-rust/rustc/autobuild/patches/0001-Add-i486-unknown-linux-gnu-compiler-target.patch
  lang-rust/rustc/autobuild/patches/0002-Add-MIPS-definitions-to-vendored-libffi-sys.patch
  lang-rust/rustc/spec
Labels: upgrade

#10978 hugo: update to 0.147.3
  app-web/hugo/spec
Labels: upgrade

#10979 dnscontrol: update to 4.20.0
  app-network/dnscontrol/spec
Labels: upgrade

#10980 podman: update to 5.5.0+vsock0.8.4
  app-containers/podman/spec
Labels: upgrade

#10982 uv: update to 0.7.4
  lang-python/uv/spec
Labels: upgrade

#10958 ab-download-manager: update to 1.6.1
  app-web/ab-download-manager/spec
Labels: upgrade

#10987 epson-inkjet-printer-escpr: new, 1.8.6
  runtime-doc/epson-inkjet-printer-escpr/autobuild/defines
  runtime-doc/epson-inkjet-printer-escpr/spec
Labels: new-package

#10981 llvm-20: update to 20.1.5
  app-devel/llvm-20/spec
Labels: upgrade

#10985 pmbootstrap: update to 3.4.0
  app-utils/pmbootstrap/spec
Labels: upgrade
